### ISSUE TITLE
Adding to inventory of block is broken

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#1]
**The issue:**
Adding stuff to inventory of any block that has an inventory is broken.

**Version:**
Latest Skript (by bensku).
**Spigot version:** 
This server is running CraftBukkit version git-Spigot-3104eb1-daf4514 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Steps to reproduce:**
```
on right click:
  add stone to inventory of event-block

```

**Comment by bensku** [comment]
Fixed in next release.
