### ISSUE TITLE
Biome names need to be updated

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#10]
**Skript version:**
dev4

**The issue:**
```
command /biome:
  trigger:
    send " Biome: %biome at location of player%" to player
```

**Example output:**
"Biome: biomes.taiga_cold" (used to be "cold taiga", now should be: "taiga cold")

**All the biomes need to be updated to these:**
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html

**Comment by bensku** [comment]
I'll try to make Skript automatically "map" old biome names to new, because the new names make no sense. After potion features are ready.

**Comment by bensku** [comment]
Actually, this one was easy. Lots of work, but mainly just writing converter enum.

In next release, Skript will be able to use 1.8 on both 1.8 and 1.9 in scripts and language files. Also, void biome was added :)

**Comment by bensku** [comment]
Fixed in last release.
