### ISSUE TITLE
Latest Spigot 1.8.8 stable release Question About.

### ISSUE THREAD

**Issue by comonier** [bensku/Skript#1005]
Hi, 

I would like to know if you could give me an address for the latest stable release for spigot 1.8.8

Ty.

**Comment by HYPExMon5ter** [comment]
This fork doesn’t support 1.8 but if you were to use it on 1.8 I’d recommend dev25

**Comment by comonier** [comment]
Ty very muth i am using:
[Skript] Loading Skript v2.2-Mineplex-Core-Patch
Its working very well. Ty.

**Comment by Pikachu920** [comment]
That is one of the worst versions you could use. Use dev25 and close this issue
