### ISSUE TITLE
Skript Error

### ISSUE THREAD

**Issue by 3ssej** [bensku/Skript#1006]
I'm getting this error in my console when running a Skript. At first the Skript worked fine, but now it doesn't.
`> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! [Skript] Severe Error:
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Something went horribly wrong with Skript.
> [16:08:47 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [16:08:47 ERROR]: #!#! You should report it at https://github.com/bensku/Skript/issues. Please copy paste this report there (or use paste service).
> [16:08:47 ERROR]: #!#! This ensures that your issue is noticed and will be fixed as soon as possible.
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Stack trace:
> [16:08:47 ERROR]: #!#! ch.njol.skript.SkriptAPIException: Call to getSingle() on a non-single expression
> [16:08:47 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:66)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.effects.EffTeleport.execute(EffTeleport.java:72)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:95)
> [16:08:47 ERROR]: #!#! at ch.njol.skript.events.EvtPeriodical$2.run(EvtPeriodical.java:119)
> [16:08:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [16:08:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
> [16:08:47 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
> [16:08:47 ERROR]: #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
> [16:08:47 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
> [16:08:47 ERROR]: #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
> [16:08:47 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Version Information:
> [16:08:47 ERROR]: #!#! Skript: 2.2-dev32c (latest)
> [16:08:47 ERROR]: #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
> [16:08:47 ERROR]: #!#! Minecraft: 1.12.2
> [16:08:47 ERROR]: #!#! Java: 1.8.0_131 (OpenJDK 64-Bit Server VM 25.131-b11)
> [16:08:47 ERROR]: #!#! OS: Linux amd64 3.10.0-693.2.2.el7.x86_64
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Running CraftBukkit: false
> [16:08:47 ERROR]: #!#! Running Spigot (or compatible): true
> [16:08:47 ERROR]: #!#! Running Paper (or compatible): false
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Current node: null
> [16:08:47 ERROR]: #!#! Current item: teleport {handcuffedplayer::*}(as org.bukkit.entity.Entity) to [[direction:at]] {police::*}(as org.bukkit.Location)
> [16:08:47 ERROR]: #!#! Thread: Server thread
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! Language: english
> [16:08:47 ERROR]: #!#! Link parse mode: DISABLED
> [16:08:47 ERROR]: #!#!
> [16:08:47 ERROR]: #!#! End of Error.
> [16:08:47 ERROR]: #!#!`

Thanks,
Jesse

**Comment by hazycraft** [comment]
@3ssej Can you at least provide the skript you're using that triggers the problem? Thanks Also
It clearly says [16:08:47 ERROR]: #!#! Current item: teleport {handcuffedplayer::}(as org.bukkit.entity.Entity) to [[direction:at]] {police::}(as org.bukkit.Location) is what is causing issue which is not issue with skript plugin it's issue with your code in the skript you're using.

**Comment by 3ssej** [comment]
Yeah, I got it sorted anyway. It said to report it to GitHub so I did.

**Comment by bensku** [comment]
This kind of reports shouldn't be shown to end user.

**Comment by Snow-Pyon** [comment]
Can't reproduce in latest version. Open another issue if you're still experiencing this.
