### ISSUE TITLE
Function arguments can't go to a list var

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#1007]
Example:
```
function potionFrom(item::1: item, item::2: item):
```
cauases a parse error instead of setting {_item::1} and {_item::2}

**Comment by Snow-Pyon** [comment]
Well, Skript has a specific error for that as shown here:
https://github.com/bensku/Skript/blob/e5a184cfd6979396d1b295b2108673e2a077da27/src/main/java/ch/njol/skript/lang/function/Parameter.java#L63

So, it's just vanilla Skript behavior. Although if you ask me, this should be possible.

**Comment by bensku** [comment]
This is intentional. What is the error, exactly? Is it confusing or describing a different problem?

**Comment by Pikachu920** [comment]
It's intentional... why?

**Comment by bensku** [comment]
There is a more sensible way of receiving a list as function parameters.

**Comment by Gemacon** [comment]
one that doesn't fit all cases

**Comment by Pikachu920** [comment]
The issue with how it currently is is a couple things:
  1. currently, to pass a list you sometimes have to define it on a different line then pass it which is annoying
  2. what if you only want to take x values?
  3. sometimes you have params like {_foo1} and {_foo2} which is very ugly compared to e

**Comment by bensku** [comment]
PR coming in next release.

**Comment by Syst3ms** [comment]
@bensku Closing ?
