### ISSUE TITLE
More message customization options

### ISSUE THREAD

**Issue by Nicofisi** [bensku/Skript#101]
Hi, could you add an option to modify this message with the .lang file?
> There is no player online whose name starts with '%1"

If there are more messages like this one, it would be also very nice if you added an option for them.
My suggestion is to place them in this place:

```
 # -- Commands --
 commands:
 	no permission message: You don't have the required permission to use this command
 	executable by players: This command can only be used by players
 	executable by console: This command can only be used by the console
 	usage: Usage:
 	correct usage: Correct usage:
 	invalid argument: Invalid argument <gray>'%s<gray>'<reset>. Allowed are:
 	too many arguments: This command can only accept a single %2$s.
 	internal error: An internal error occurred while attempting to perform this command.
```
Thanks in advance!

**Comment by JKGamerxD** [comment]
You already can modify it with packets and MundoSk but it's a good idea.

**Comment by JKGamerxD** [comment]
Also it's not the issue but @bensku you can remove this debug message?
```
[Skript] Trigger is function ... (simple event)
```
It's really annoying because if you use any function, this is here.
