### ISSUE TITLE
Skript Open chest

### ISSUE THREAD

**Issue by Manyfak** [bensku/Skript#1012]
Open chest doesn't work
my code:
command /backpack:
	description: Use this command for open backpack!
	usage: /backpack
	permission: backpack
	permission message: &cYou don't have permissions for this!
	trigger:
		open chest to player

error message:
chest is not entity type

**Comment by TheBentoBox** [comment]
As far as I can tell you're not using the syntax correctly; looking at [the documentation for this effect](http://bensku.github.io/Skript/effects#EffOpenInventory), you can see that `(view|window|inventory)` is listed as required after the inventory type. Try `open chest inventory to player`.

**Comment by Manyfak** [comment]
Not works
chest inventory is not entity type
