### ISSUE TITLE
Skripd don't understand on jump event.

### ISSUE THREAD

**Issue by MentosPL** [bensku/Skript#1019]
http://prntscr.com/hoh0oh

The same script i have on my 1.8.8 server with Skript 2.2-Fixes-V8b and evrything is working fine.

but Skript 2.2-Fixes-V8b are not working/is not compatible with 1.12.2

**Comment by TheBentoBox** [comment]
That is not a vanilla Skript event, it is being added by one of your add-ons which seems to be incompatible with either this fork or 1.12.2 in general. You'll need to figure out which add-on you are using to get the `on jump` event and start looking there.

**Comment by MentosPL** [comment]
what's addon i need to use?
