### ISSUE TITLE
Skript not working

### ISSUE THREAD

**Issue by HisBoilingPoint** [bensku/Skript#1026]
For the entire day now I have been trying to get Skript to work but it seems to be just problem after problem. Currently, I have just gotten Skript to respond to the /skript command (it wasn't before XD). Now when I try any command like /sk reload all it says "reloading the config and all scripts" and then it says in red "an internal error occurred while trying to perform this command". This happens on all commands I try.
`20.12 21:55:52 [Server] INFO ... 15 more
20.12 21:55:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161) ~[?:?]
20.12 21:55:52 [Server] INFO at ch.njol.skript.Skript.reload(Skript.java:735) ~[?:?]
20.12 21:55:52 [Server] INFO at ch.njol.skript.Skript.reloadMainConfig(Skript.java:753) ~[?:?]
20.12 21:55:52 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.SkriptConfig
20.12 21:55:52 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:371) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:696) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
20.12 21:55:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1198) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1338) [CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:629) ~[CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[CraftBukkit.jar:git-Bukkit-2ee49b4]
20.12 21:55:52 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev32c
20.12 21:55:52 [Server] ERROR null`

**Comment by Syst3ms** [comment]
Skript doesn't support Craftbukkit ; use Spigot.
