### ISSUE TITLE
Problem with Scoreboard

### ISSUE THREAD

**Issue by alugilak** [bensku/Skript#1027]
19:54:30 [ERROR] #!#! [Skript] Severe Error:
19:54:30 [ERROR] #!#!
19:54:30 [ERROR] #!#! Something went horribly wrong with Skript.
19:54:30 [ERROR] #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
19:54:30 [ERROR] #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
19:54:30 [ERROR] #!#! Following plugins are probably related to this error in some way:
19:54:30 [ERROR] #!#! SkQuery
19:54:30 [ERROR] #!#! You should try disabling those plugins one by one, trying to find which one causes it.
19:54:30 [ERROR] #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
19:54:30 [ERROR] #!#! In that case, you will be given instruction on how should you report it.
19:54:30 [ERROR] #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
19:54:30 [ERROR] #!#! Only if the author tells you to do so, report it as Skript issue (url below)
19:54:30 [ERROR] #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
19:54:30 [ERROR] #!#!
19:54:30 [ERROR] #!#! Stack trace:
19:54:30 [ERROR] #!#! java.lang.NullPointerException
19:54:31 [ERROR] #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:47)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
19:54:31 [ERROR] #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
19:54:31 [ERROR] #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
19:54:31 [ERROR] #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19:54:31 [ERROR] #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
19:54:31 [ERROR] #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
19:54:31 [ERROR] #!#!     at com.w00tmast3r.skquery.elements.effects.EffInvoke.execute(EffInvoke.java:29)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
19:54:31 [ERROR] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
19:54:31 [ERROR] #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
19:54:31 [ERROR] #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
19:54:31 [ERROR] #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
19:54:31 [ERROR] #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
19:54:31 [ERROR] #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
19:54:31 [ERROR] #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
19:54:32 [ERROR] #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
19:54:32 [ERROR] #!#!     at java.lang.Thread.run(Thread.java:748)
19:54:32 [ERROR] #!#!
19:54:32 [ERROR] #!#! Version Information:
19:54:32 [ERROR] #!#!   Skript: 2.2-dev32c (latest)
19:54:32 [ERROR] #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
19:54:32 [ERROR] #!#!   Minecraft: 1.12.2
19:54:32 [ERROR] #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
19:54:32 [ERROR] #!#!   OS: Windows 10 amd64 10.0
19:54:32 [ERROR] #!#!
19:54:32 [ERROR] #!#! Running CraftBukkit: false
19:54:32 [ERROR] #!#! Running Spigot (or compatible): true
19:54:32 [ERROR] #!#! Running Paper (or compatible): false
19:54:32 [ERROR] #!#!
19:54:32 [ERROR] #!#! Current node: null
19:54:32 [ERROR] #!#! Current item: null
19:54:32 [ERROR] #!#! Thread: Server thread
19:54:32 [ERROR] #!#!
19:54:32 [ERROR] #!#! Language: english
19:54:32 [ERROR] #!#! Link parse mode: DISABLED
19:54:32 [ERROR] #!#!
19:54:32 [ERROR] #!#! End of Error.
19:54:32 [ERROR] #!#!

**Comment by bensku** [comment]
Addon issue. Contact SkRayfall developer.
