### ISSUE TITLE
Console error when trying to drop items at a location

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1028]
Latest Skript version available + PaperSpigot 1.12.2:

https://hastebin.com/irasetojiy.md

Happens when trying to drop several items at a player's location.

What I am basically doing in the skript:

loop {kits::%{_rkitname}%::items::*}:
set {_amount} to skellett size of item loop-value
drop {_amount} of loop-value at players's location

**Comment by Pikachu920** [comment]
fwiw you don't need to use skellett for this. Skript has `item amount of %itemstack%`

**Comment by bloggy** [comment]
Thanks but this does not resolve the issue.

**Comment by Blueyescat** [comment]
Still an issue, but what is the point of doing that? This should work:
```vb
drop {kits::%{_rkitname}%::items::*} at players
```
or
```vb
loop {kits::%{_rkitname}%::items::*}:
    drop loop-item at players
    #or loop-value
```

**Comment by bloggy** [comment]
Thanks. I just managed to fix the console error with this:

```
loop {kits::%{_rkitname}%::items::*}:
set {_item} to loop-value
drop {_item} at player's location
```
But now I have a new issue. The dropped items appear for half a second and suddenly disappear again. Sometimes I can pick them up, but sometimes they are just gone. Sometimes I only get part of the drops....???

**Comment by TheBentoBox** [comment]
Also not sure why you're setting `loop-value` to some temporary variable and then dropping it from the variable when you could just drop it directly:
```
loop {kits::%{_rkitname}%::items::*}:
    drop loop-value at player
```
Or better yet you could just drop the whole list at once:
```
drop {kits::%{_rkitname}%::items::*} at player
```

**Comment by TheBentoBox** [comment]
No further response about what was causing this or if it was even a legit bug. Lemme know if you find out anything more conclusive and I'd be happy to reopen this.
