### ISSUE TITLE
Logs spam

### ISSUE THREAD

**Issue by RARgames** [bensku/Skript#103]
[05:01:07] [Server thread/INFO]: [SkQuery] WARNING. THIS IS AN UNOFFICIAL BUILD BY GATT TO ALLOW SKQUERY TO WORK WITH 1.9. NO HELP WILL BE GIVEN IF ANYTHING BREAKS.

It's like 20 times, can you remove it and make it show one time?

**Comment by Pilvinen** [comment]
As you can see from the "[SkQuery]" the message doesn't come from Skript. It's coming from SkQuery. Try removing skQuery from your plugins and the problem is solved.

**Comment by RARgames** [comment]
@Pilvinen Really sorry, I was looking on different github, but posted this to other open window.

Sorry again :P
