### ISSUE TITLE
add that you can make folders in the /skripts/ folder that can contain skripts

### ISSUE THREAD

**Issue by Dylan123111** [bensku/Skript#1030]
it would be a big inprovement if you could add folders that contain skripts or folders in the /skripts/ folder. that way you can kind of make classes and if you have a really big skript you can split it so that your server doesn't have such a hard time with reloading and booting up the skript

**Comment by Blueyescat** [comment]
Already you can do that. Even you can use some commands like **``/sk reload folder/``**, **``/sk reload folder/file.sk``** and **``/sk reload folder/folder2/``**.
Also Skript loads scripts in sub folders in the scripts folder on server startup.

**Comment by Pikachu920** [comment]
This is already posisble
