### ISSUE TITLE
Crash My Server

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#1031]
27.12 00:46:25 [Server] ERROR The server has stopped responding!
27.12 00:46:25 [Server] ERROR Please report this to http://www.spigotmc.org/
27.12 00:46:25 [Server] ERROR Be sure to include ALL relevant console errors and Minecraft crash reports
27.12 00:46:25 [Server] ERROR Spigot version: git-Spigot-3d850ec-809c399 (MC: 1.12.2)
27.12 00:46:25 [Server] ERROR ------------------------------
27.12 00:46:25 [Server] ERROR Server thread dump (Look for plugins here before reporting to Spigot!):
27.12 00:46:25 [Server] ERROR ------------------------------
27.12 00:46:25 [Server] ERROR Current Thread: Server thread
27.12 00:46:25 [Server] ERROR PID: 38 | Suspended: false | Native: false | State: RUNNABLE
27.12 00:46:25 [Server] ERROR Stack:
27.12 00:46:25 [Server] ERROR java.util.Collections$UnmodifiableCollection$1.hasNext(Collections.java:1041)
27.12 00:46:25 [Server] ERROR ch.njol.skript.registrations.Classes.toString(Classes.java:597)
27.12 00:46:25 [Server] ERROR ch.njol.skript.registrations.Classes.toString(Classes.java:630)
27.12 00:46:25 [Server] ERROR ch.njol.skript.registrations.Classes.toString(Classes.java:623)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.VariableString.toString(VariableString.java:418)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Variable.getRaw(Variable.java:202)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Variable.get(Variable.java:214)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Variable.getConverted(Variable.java:359)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Variable.getAll(Variable.java:577)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Variable.getArray(Variable.java:569)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.VariableString.toString(VariableString.java:430)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.VariableString.getAll(VariableString.java:599)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.VariableString.check(VariableString.java:609)
27.12 00:46:25 [Server] ERROR ch.njol.skript.conditions.CondContains$1.check(CondContains.java:122)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:175)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:163)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:158)
27.12 00:46:25 [Server] ERROR ch.njol.skript.conditions.CondContains.check(CondContains.java:101)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Condition.run(Condition.java:56)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
27.12 00:46:25 [Server] ERROR ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
27.12 00:46:25 [Server] ERROR ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
27.12 00:46:25 [Server] ERROR ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
27.12 00:46:25 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
27.12 00:46:25 [Server] ERROR org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
27.12 00:46:25 [Server] ERROR org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
27.12 00:46:25 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:895)
27.12 00:46:25 [Server] ERROR net.minecraft.server.v1_12_R1.EntityPlayer.closeInventory(EntityPlayer.java:928)
27.12 00:46:25 [Server] ERROR org.bukkit.craftbukkit.v1_12_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:404)
27.12 00:46:25 [Server] ERROR co.kepler.fastcraftplus.api.gui.GUI.dispose(GUI.java:107)
27.12 00:46:25 [Server] ERROR co.kepler.fastcraftplus.api.gui.GUI.dispose(GUI.java:96)
27.12 00:46:25 [Server] ERROR co.kepler.fastcraftplus.craftgui.GUIFastCraft.dispose(GUIFastCraft.java:84)
27.12 00:46:25 [Server] ERROR co.kepler.fastcraftplus.craftgui.GUIFastCraft$GUIListener.blockRemoved(GUIFastCraft.java:220)
27.12 00:46:25 [Server] ERROR co.kepler.fastcraftplus.craftgui.GUIFastCraft$GUIListener.onBlockBreak(GUIFastCraft.java:199)
27.12 00:46:25 [Server] ERROR sun.reflect.GeneratedMethodAccessor608.invoke(Unknown Source)
27.12 00:46:25 [Server] ERROR sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
27.12 00:46:25 [Server] ERROR java.lang.reflect.Method.invoke(Method.java:498)
27.12 00:46:25 [Server] ERROR org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
27.12 00:46:25 [Server] ERROR org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)

**Comment by hazycraft** [comment]
Clealy says issue is from co.kepler.fastcraftplus you should probably remove that plugin your error is not from skript....

**Comment by bensku** [comment]
Try without FastCraft and also without any Skript addons. This might be Skript issue, but cannot be sure with so little information.

**Comment by Snow-Pyon** [comment]
No response, closing. Reopen if you're still experiencing this.
