### ISSUE TITLE
Play Sound Effect

### ISSUE THREAD

**Issue by Techno3600** [bensku/Skript#1032]
Hello,

Could someone please make an example of how to use the "play sound" effect on the documentation or somewhere where people could see it? It's really annoying because I can't find it anywhere.

Thanks
Techno

**Comment by hazycraft** [comment]
Here's an example from the Skunity.com Documentation page
https://docs.skunity.com/syntax/effects/Play%20Sound
command /sound:
    trigger:
        play sound "AMBIENT_CAVE" to player with volume 1 and pitch 2
        #Uses spigot sound files
command /sound <text>:
    trigger:
        play sound "%arg 1%" to player with volume 1 and pitch 2

**Comment by Blueyescat** [comment]
@hazycraft no, it is not Play Sound effect of Vanilla Skript. Don't use SkUnity for Skript documentation, it is pretty outdated. Even uses Skript 2.1 docs. Use https://bensku.github.io/Skript/ or https://skripthub.net/docs/?addon=Skript.

Example for Skript's [Play Sound](https://bensku.github.io/Skript/effects.html#EffPlaySound) effect:
```vb
play sound "entity.experience_orb.pickup" with volume 1 and pitch 1 at all players for all players
```
It uses Minecraft sound names (/playsound) also supports sounds from resource packs.

**Comment by Techno3600** [comment]
Thanks so much @Blueyescat, I was having a lot of trouble figuring out what the %location% was.

**Comment by Blueyescat** [comment]
You can use ``player`` type on **%location%** expressions, it would take location of player or whatever. In this case you can even use a block location. Think it like the block is a speaker.
Or just a random location like **``location 1, 2, 3 in "world"``**.

**%players%** expression is to determine which players will hear the sound. You can remove it is as it is an optional part, then all player can hear the sound.

**Comment by TheBentoBox** [comment]
This seems resolved (thanks @Blueyescat ) so I'll be closing it. In the future you might have better luck asking on the forums, this issue reports section isn't really for asking general help questions, it's for bugs or feature requests. And as has been said Bensku's documentation found [here](http://bensku.github.io/Skript/) is **always** the most up-to-date and highest quality place to look for **vanilla** Skript syntaxes (not add-ons).
