### ISSUE TITLE
not sure what is this error

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#1038]
01.01 02:39:49 [Server] ERROR The player is not online!
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! [Skript] Severe Error:
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Something went horribly wrong with Skript.
01.01 02:39:49 [Server] ERROR #!#! This issue is NOT your fault! You can't probably fix it yourself, either.
01.01 02:39:49 [Server] ERROR #!#! You're running outdated version of Skript! Please try updating it NOW; it might fix this.
01.01 02:39:49 [Server] ERROR #!#! You may download new version of Skript at https://github.com/bensku/Skript/releases
01.01 02:39:49 [Server] ERROR #!#! You will be given instructions how to report this error if it persists with latest Skript.
01.01 02:39:49 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Stack trace:
01.01 02:39:49 [Server] ERROR #!#! java.lang.NullPointerException
01.01 02:39:49 [Server] ERROR #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:46)
01.01 02:39:49 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
01.01 02:39:49 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
01.01 02:39:49 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
01.01 02:39:49 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
01.01 02:39:49 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
01.01 02:39:49 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
01.01 02:39:49 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
01.01 02:39:49 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
01.01 02:39:49 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
01.01 02:39:49 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
01.01 02:39:49 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Version Information:
01.01 02:39:49 [Server] ERROR #!#!   Skript: 2.2-dev31c (OUTDATED)
01.01 02:39:49 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
01.01 02:39:49 [Server] ERROR #!#!   Minecraft: 1.12.2
01.01 02:39:49 [Server] ERROR #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
01.01 02:39:49 [Server] ERROR #!#!   OS: Linux amd64 3.10.0-514.21.2.el7.x86_64
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Running CraftBukkit: false
01.01 02:39:49 [Server] ERROR #!#! Running Spigot (or compatible): true
01.01 02:39:49 [Server] ERROR #!#! Running Paper (or compatible): false
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Current node: null
01.01 02:39:49 [Server] ERROR #!#! Current item: null
01.01 02:39:49 [Server] ERROR #!#! Thread: Server thread
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! Language: english
01.01 02:39:49 [Server] ERROR #!#! Link parse mode: DISABLED
01.01 02:39:49 [Server] ERROR #!#! 
01.01 02:39:49 [Server] ERROR #!#! End of Error.
01.01 02:39:49 [Server] ERROR #!#!

**Comment by TheBentoBox** [comment]
This is an issue with skRayFall, so you should report it to the add-on developer, not here.
