### ISSUE TITLE
Fly getting dropped when commands are executed

### ISSUE THREAD

**Issue by hazycraft** [bensku/Skript#1039]
I made a fly script. It works great until player types any command then fly get's dropped even though it still returns true? and player's flight mode gets dropped?
I tried on server with only skript for testing. Appears to be issue inside skript?
Test for yourself please.
```
on join:
	set {fly.%player%} to true
command /fly:
	trigger:
		if {fly.%player%} is false:
			set player's flight mode to true
			set {fly.%player%} to true
			message "&a&l(!)&a Fly has been &a&lEnabled"
		else if {fly.%player%} is true:
			set player's flight mode to false
			message "&c&l(!)&c Fly has been &c&lDisabled"
			set {fly.%player%} to false
```

**Comment by Pikachu920** [comment]
The flight mode expression is not from Skript.

**Comment by hazycraft** [comment]
@Pikachu920 Good point I just realized it's from expression from SkQuery.
