### ISSUE TITLE
1.10 is out!

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#104]
When will you plan on update to 1.10 ? :-)

**Comment by bensku** [comment]
It really should work already. 1.10 features will be added later if they're needed.

**Comment by TheBentoBox** [comment]
The only things that will need updating are the entity aliases and the default aliases file. There's the new blocks and the new mob/variants. I'll be testing how it runs on 1.10 soon

**Comment by itismejoey** [comment]
@bloggy You also have to remember that the addons need to updated to 1.10 as well and only a small list ever updated to 1.9.4.

**Comment by bloggy** [comment]
Thanks for the information. I guess that's the reason why umbaska stopped working for me, too.

**Comment by Pilvinen** [comment]
Getting this on start and none of my skripts are loading:

http://pastie.org/private/m7atw7wsrrxsvq5isophq

**Comment by Pilvinen** [comment]
It seems that reverting back to an older version of WorldGuard fixed this issue and the skripts load now.

This build works:
http://builds.enginehub.org/job/worldguard/9122

Newer builds don't seem to.

**Comment by bensku** [comment]
WorldGuard had an API break, it seems. Fixing would be easy, but older versions would probably not work anymore... Low priority issue as long as old WG works.
