### ISSUE TITLE
Skript doesn't load offline player variable after reboot server

### ISSUE THREAD

**Issue by weberlepecheur** [bensku/Skript#1040]
Hi everyone,
I found a bug that bothers me in my skript.

Skript dev32c
Spigot 1.12.2

Before reboot server i put this :
```
command /test:
	trigger:
		set {player} to player
every 30 seconds:
	set {_player} to "WeBer_Le_Pecheur" parsed as offline player
	# set {_player} to "WeBer_Le_Pecheur" parsed as player
	broadcast "%{_player}'s money%"
	broadcast "%{player}'s money%"

```
and it works fine but after a reboot server, I get this value (without the star)
> <*none>

Would you have a solution for this ?

**Comment by Snow-Pyon** [comment]
Just store the UUID instead of the player object, you can use it on the exact same way and it will not get deleted after restart.

**Comment by weberlepecheur** [comment]
I tried this long time ago, but that doesn't work. I still try again but it still does not work :
```
command /test:
	trigger:
		set {player} to uuid of player
		broadcast "§b%{player}%"
		broadcast "§c%{player}'s money%"
every 10 seconds:
	# set {_player} to "WeBer_Le_Pecheur" parsed as offline player
	# broadcast "%{_player}'s money%"
	broadcast "§2%{player}'s money%"

```

![image](https://user-images.githubusercontent.com/18701493/34483957-f33c914e-efc1-11e7-8244-a91c20685fce.png)

**Comment by HYPExMon5ter** [comment]
You need to parse the variable as an offline player before using it

**Comment by Syst3ms** [comment]
Hint hint : `"uuid" parsed as offline player`

**Comment by weberlepecheur** [comment]
Well, after trying all these solutions, it still does not work :(
```
command /test:
	trigger:
		set {player} to "%uuid of player%" parsed as offline player
		broadcast "§b%{player}%"
		broadcast "§c%{player}'s money%"
every 10 seconds:
	broadcast "§2%{player}'s money%"

```
```
command /test:
	trigger:
		set {player} to uuid of player parsed as offline player
		broadcast "§b%{player}%"
		broadcast "§c%{player}'s money%"
every 10 seconds:
	broadcast "§2%{player}'s money%"

```
```
command /test:
	trigger:
		set {player} to uuid of player
		broadcast "§b%{player}%"
		broadcast "§c%{player}'s money%"
every 10 seconds:
	# broadcast "§2%{player}'s money%"
	set {_p} to {player} parsed as offline player
	broadcast "§2%{_p}'s money%"

```

**Comment by bensku** [comment]
It would be better if you looked for advise with your scripts elsewhere. This is most certainly not a Skript bug.

But anyway, the variable must contain the UUID, not player. If you get UUID of player, parse it as offline player and set it to variable, it of course does not work.
