### ISSUE TITLE
QoL Enhancement: '%timespan% ago' expression

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#1041]
Simple suggestion for a `%timespan% ago` expression. Example usage is `set {_previous} to 4 seconds ago`. This would be the shorthand of:
```
set {_previous} to now
subtract 4 seconds from {_previous}
```
Could be useful for the initial setting of variables for cooldowns and stuff and just makes sense to have as an available expression grammatically speaking. Also, sorry if this is already possible in vanilla Skript in one line. I don't think I've ever seen a way but I could just be stupid!

**Comment by Syst3ms** [comment]
By extension, we could also add the opposite, e.g `1 day later`.

**Comment by xXAndrew28Xx** [comment]
I'll work on it.

**Comment by TheLimeGlass** [comment]
Close?

**Comment by TheBentoBox** [comment]
I don't believe this particular PR made it into the newest release (or at least it's not on the release report) and Bensku seems to like to only close stuff once it is properly released; in fact he usually does it (closing resolved issues) himself as he makes the release. I'll wait for confirmation that it's in an properly released build to close.

**Comment by Snow-Pyon** [comment]
I was waiting for the next release to close this as how @TheBentoBox said, bensku usually closes issues after the release with the fix/feature is out.
