### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#1042]
02.01 15:31:14 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to Kingdoms v13.3.44
02.01 15:31:14 [Server] INFO org.bukkit.event.EventException: null
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at ch.njol.skript.Skript.dispatchCommand(Skript.java:1130) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:52) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.effects.Delay$1.run(Delay.java:101) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
02.01 15:31:14 [Server] INFO Caused by: java.lang.NullPointerException
02.01 15:31:14 [Server] INFO at org.kingdoms.constants.player.KingdomPlayer.getLoc(KingdomPlayer.java:87) ~[?:?]
02.01 15:31:14 [Server] INFO at org.kingdoms.manager.game.KingdomManager.onKingdomPlayerCommand(KingdomManager.java:956) ~[?:?]
02.01 15:31:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]

**Comment by Syst3ms** [comment]
Seems like a Kingdoms issue, but yet skript is mentioned. Seems weird

**Comment by TheBentoBox** [comment]
Looks to me like Skript is mentioned because you executed the command using Skript but the issue is still on Kingdoms' side. Do you have any scripts which force players or console to run Kingdoms commands? And if so (shot in the dark), are you perhaps accidentally running a player command from console or something? Looks like there's an NPE occurring which is a bit strange given the context.

**Comment by Syst3ms** [comment]
I'll put the error with proper formatting for the sake of readbility
```
02.01 15:31:14 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to Kingdoms v13.3.44
02.01 15:31:14 [Server] INFO org.bukkit.event.EventException: null
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at ch.njol.skript.Skript.dispatchCommand(Skript.java:1130) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:84) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.Effect.run(Effect.java:52) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at ch.njol.skript.effects.Delay$1.run(Delay.java:101) [Skript.jar:?]
02.01 15:31:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
02.01 15:31:14 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
02.01 15:31:14 [Server] INFO Caused by: java.lang.NullPointerException
02.01 15:31:14 [Server] INFO at org.kingdoms.constants.player.KingdomPlayer.getLoc(KingdomPlayer.java:87) ~[?:?]
02.01 15:31:14 [Server] INFO at org.kingdoms.manager.game.KingdomManager.onKingdomPlayerCommand(KingdomManager.java:956) ~[?:?]
02.01 15:31:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
02.01 15:31:14 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
```

**Comment by bensku** [comment]
Not a Skript issue.
