### ISSUE TITLE
Skript Error Spigot 1.12.2

### ISSUE THREAD

**Issue by jasuogra** [bensku/Skript#1043]
![image](https://user-images.githubusercontent.com/31209154/34569219-64336f74-f168-11e7-8853-788199881d06.png)

When i put this script : 
command /heal [<player>]:
	permission message: &3 ↨ &cNie masz permissji: &6(Tools.Heal)
	permission: Tools.heal
	aliases: ulecz, healing
	trigger:
		if arg 1 is set:
			heal arg 1 by 10 hearts
			send "&7Uleczyles gracza: &2%arg 1%" to player
			send "&7Zostales uleczony!" to arg 1
		else:
			heal player by 10 hearts
			send "&7Zostales uleczony!" to player

**Comment by RiverThrough** [comment]
Disregard the post unless @jasuogra states the issue is still present, helped him on discord and we figured out the issue was that he had an outdated skquery version
