### ISSUE TITLE
On Portal not working

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#105]
the "on portal" event where you should be able to prevent the player from teleporting or call any other action when the player uses a portal isnt working in your release.

http://njol.ch/projects/skript/doc/events/#portal/

**Comment by TheBentoBox** [comment]
Is this now resolved due to the recent WorldGuard hook fixes? I personally haven't received the PlayerPortalEvent errors in my console anymore, but I also don't believe I use that event.

**Comment by TheBentoBox** [comment]
No response and I personally haven't seen these errors in a while as far as I remember. If anyone keeps getting these issues feel free to report it again.
