### ISSUE TITLE
Commands don't work

### ISSUE THREAD

**Issue by 21CoasterGuy** [bensku/Skript#1051]
Hi there!

I've today installed skript on my server, next to skript I've installed skQuerry3, Umbaska and skRayFall.
The plugins works just fine with only one issue, when I try to reload a skript with a command in it I get the following error:

> an internal error occurred while attempting to perform this command

This is what I get in the console after the command:

> 09.01 15:27:40 [Server] INFO 21CoasterGuy issued server command: /skript reload Broadcast
> 09.01 15:27:40 [Server] ERROR null
> 09.01 15:27:40 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'skript' in plugin Skript v2.2-dev32c
> 09.01 15:27:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1354) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1189) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
> 09.01 15:27:40 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot84.jar:git-Spigot-3fb9445-6e3cec8]
> 09.01 15:27:40 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
> 09.01 15:27:40 [Server] INFO Caused by: java.lang.NoSuchMethodError: ch.njol.skript.command.Commands.loadCommand(Lch/njol/skript/config/SectionNode;Z)Lch/njol/skript/command/ScriptCommand;
> 09.01 15:27:40 [Server] INFO at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:571) ~[?:?]
> 09.01 15:27:40 [Server] INFO at ch.njol.skript.ScriptLoader.lambda$1(ScriptLoader.java:347) ~[?:?]
> 09.01 15:27:40 [Server] INFO at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:359) ~[?:?]
> 09.01 15:27:40 [Server] INFO at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:392) ~[?:?]
> 09.01 15:27:40 [Server] INFO at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:188) ~[?:?]
> 09.01 15:27:40 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot84.jar:git-Spigot-3fb9445-6e3cec8]

The code of this skript is:
`command /om <text>:
	trigger:
		broadcast "&3[&9Omroep&3]&7 %arg 1%"`

The server is a 4GB RAM server running on spigot 1.11.2

I hope someone knows more about this issue because I am clueless due to the only error is a null in the console so I don't have a clue what part is wrong (my skripting or the plugin itself or just the server).

I also use the disabled weather.sk skript because I don't like rain in my server xD this skript doesn't have any trouble. Also making a skript where the server says hello to someone who is joining didn't cause any trouble so I came to the conclusion it had something to do with the "command /om <text>" part.

**Comment by bi0qaw** [comment]
This is how your code should look like:
```
command /om <text>:
    trigger:
        broadcast "&3[&9Omroep&3]&7 %arg 1%"
```
Remember that indentation is important for skript.

**Comment by 21CoasterGuy** [comment]
I just tried it, still the same error with reloading, and after a restart the /om command still doesn't work :/

I also right now found something which has to do with skript but I don't believe it has something to do with my issue but I just post the error's in case of xP

> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 235! (aliases-english.sk, line 277: [white(_| )]glazed(_| )terracotta¦s = 235')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 236! (aliases-english.sk, line 278: orange(_| )glazed(_| )terracotta¦s = 236')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 237! (aliases-english.sk, line 279: magenta(_| )glazed(_| )terracotta¦s = 237')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 238! (aliases-english.sk, line 280: light(_| )blue(_| )glazed(_| )terracotta¦s = 238')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 239! (aliases-english.sk, line 281: yellow(_| )glazed(_| )terracotta¦s = 239')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 240! (aliases-english.sk, line 282: (lime|light(_| )green)(_| )glazed(_| )terracotta¦s = 240')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 241! (aliases-english.sk, line 283: pink(_| )glazed(_| )terracotta¦s = 241')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 242! (aliases-english.sk, line 284: gray(_| )glazed(_| )terracotta¦s = 242')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 243! (aliases-english.sk, line 285: light(_| )gray(_| )glazed(_| )terracotta¦s = 243')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 244! (aliases-english.sk, line 286: cyan(_| )glazed(_| )terracotta¦s = 244')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 245! (aliases-english.sk, line 287: purple(_| )glazed(_| )terracotta¦s = 245')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 246! (aliases-english.sk, line 288: blue(_| )glazed(_| )terracotta¦s = 246')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 247! (aliases-english.sk, line 289: brown(_| )glazed(_| )terracotta¦s = 247')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 248! (aliases-english.sk, line 290: green(_| )glazed(_| )terracotta¦s = 248')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 249! (aliases-english.sk, line 291: red(_| )glazed(_| )terracotta¦s = 249')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 250! (aliases-english.sk, line 292: black(_| )glazed(_| )terracotta¦s = 250')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 235! (aliases-english.sk, line 293: [<any>](_| )glazed(_| )terracotta¦s = 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 295: [white(_| )]concrete¦s = 251')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 296: orange(_| )concrete¦s = 251:1')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 297: magenta(_| )concrete¦s = 251:2')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 298: light(_| )blue(_| )concrete¦s = 251:3')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 299: yellow(_| )concrete¦s = 251:4')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 300: (lime|light(_| )green)(_| )concrete¦s = 251:5')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 301: pink(_| )concrete¦s = 251:6')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 302: gray(_| )concrete¦s = 251:7')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 303: light(_| )gray(_| )concrete¦s = 251:8')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 304: cyan(_| )concrete¦s = 251:9')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 305: purple(_| )concrete¦s = 251:10')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 306: blue(_| )concrete¦s = 251:11')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 307: brown(_| )concrete¦s = 251:12')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 308: green(_| )concrete¦s = 251:13')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 309: red(_| )concrete¦s = 251:14')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 310: black(_| )concrete¦s = 251:15')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 251! (aliases-english.sk, line 311: [<any>](_| )concrete¦s = 251, 251:1, 251:2, 251:3, 251:4, 251:5, 251:6, 251:7, 251:8, 251:9, 251:10, 251:11, 251:12, 251:13, 251:14, 251:15')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 313: [white(_| )]concrete(_| )powder¦s = 252')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 314: orange(_| )concrete(_| )powder¦s = 252:1')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 315: magenta(_| )concrete(_| )powder¦s = 252:2')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 316: light(_| )blue(_| )concrete(_| )powder¦s = 252:3')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 317: yellow(_| )concrete(_| )powder¦s = 252:4')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 318: (lime|light(_| )green)(_| )concrete(_| )powder¦s = 252:5')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 319: pink(_| )concrete(_| )powder¦s = 252:6')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 320: gray(_| )concrete(_| )powder¦s = 252:7')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 321: light(_| )gray(_| )concrete(_| )powder¦s = 252:8')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 322: cyan(_| )concrete(_| )powder¦s = 252:9')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 323: purple(_| )concrete(_| )powder¦s = 252:10')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 324: blue(_| )concrete(_| )powder¦s = 252:11')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 325: brown(_| )concrete(_| )powder¦s = 252:12')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 326: green(_| )concrete(_| )powder¦s = 252:13')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 327: red(_| )concrete(_| )powder¦s = 252:14')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 328: black(_| )concrete(_| )powder¦s = 252:15')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 329: [<any>](_| )concrete(_| )powder¦s = 252, 252:1, 252:2, 252:3, 252:4, 252:5, 252:6, 252:7, 252:8, 252:9, 252:10, 252:11, 252:12, 252:13, 252:14, 252:15')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 252! (aliases-english.sk, line 331: [white(_| )]bed(_| )item¦s = 252')
> 09.01 15:49:33 [Server] ERROR There doesn't exist a material with id 453! (aliases-english.sk, line 350: knowledge(_| )book¦s = 453')

**Comment by TheBentoBox** [comment]
This looks to me like an error with your add-ons. There hasn't been a great version of Umbaska for a long time nor any good reason to use it, especially on 1.11, and skQuery 3 is SUPER old and 100% not the version you should be using. Try updating your skQuery to [this version](https://forums.skunity.com/resources/unofficial-skquery-fork-1-6-1-12.68/), and honestly if I were you I'd remove Umbaska entirely. The version you're using is likely way too old given you're using skQuery 3 still. Ya gotta keep better track of your add-on versions.

As for the alias errors, update your aliases; Tim is generally the one who maintains the aliases, his repo can be found [here](https://github.com/tim740/skAliases).

I'm going to close since this definitely doesn't seem like a Skript issue. If you need more help getting it working then you should ask on the forums. Only report here if you get issues that you're sure are caused by Skript and not problems with your setup.
