### ISSUE TITLE
New expression: player's group (from Vault)

### ISSUE THREAD

**Issue by peccator085** [bensku/Skript#1052]
I want to use Expression:% player's group%
Umbaska is not updated or you can not use% player's group%
Other plugins depend on PermissionsEX and should not be available with the LuckPerms plugin.
So I'd like you to get% player's group% from Vault

**Comment by Syst3ms** [comment]
Ask for help like that on forums or appropriate discords, this is for actual skript bugs and *constructive* feature requests.

**Comment by peccator085** [comment]
This is a request
If Vault exists, you can get% player's balance% by default.
already used vault's api, so I thought there was a slight possibility to add that function

**Comment by Syst3ms** [comment]
Oh well.

**Comment by Blueyescat** [comment]
Not that single expression only. Vault API has many methods: http://milkbowl.github.io/VaultAPI/ Which are should be added to Skript.

**Comment by peccator085** [comment]
net.milkbowl.vault.permission/Permission/getPrimaryGroup

getPrimaryGroup
public String getPrimaryGroup(org.bukkit.entity.Player player)
Get players primary group. Defaults to the players current world, so may return only world-specific groups. In most cases getPrimaryGroup(String, OfflinePlayer) is preferable.
Parameters:
player - Player Object
Returns:
Players primary group

**Comment by Snow-Pyon** [comment]
Added in dev35.
