### ISSUE TITLE
Error while enabling skript v2.2-dev29?

### ISSUE THREAD

**Issue by Efnilite** [bensku/Skript#1054]
While enabling my server I get this error:

[ENABLE_ERROR.txt](https://github.com/bensku/Skript/files/1624010/i.txt)

I've tried looking at the error, but I can't seem to figure out why the error pops up.

ALSO, I'm aware of the error when reloading your server, but normally it says what item is causing it.
But here it's 'null'

[RELOAD_ERROR.txt](https://github.com/bensku/Skript/files/1624013/a.txt)

**Comment by TheBentoBox** [comment]
Update your Skript version, we can't accept bug reports for out-of-date versions as the bug you're reporting could already be fixed. If you find you still get this issue with the latest version and have steps to reproduce it, feel free to open a new bug report.
