### ISSUE TITLE
Play Sound Doesn't Work

### ISSUE THREAD

**Issue by Techno3600** [bensku/Skript#1057]
Here is the error:

https://pastebin.com/raw/FSERzV28

I've already checked with Skellet and they have denied the error being their fault.

**Comment by Pikachu920** [comment]
Duplicate of #876

**Comment by Techno3600** [comment]
That looks nothing like a duplicate, I am using the very latest version released a few days ago, it still doesn’t work.

**Comment by Pikachu920** [comment]
look at the stack traces, its probably the same root issue
