### ISSUE TITLE
Color codes within tooltips not working

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1059]
Latest Skript build:

`<tooltip:&4Test>Message<reset>`

This shows "Test" in white color instead of red.

**Comment by Syst3ms** [comment]
Try with §4

**Comment by bloggy** [comment]
This works! Thank you!

**Comment by Snow-Pyon** [comment]
Skript should actually parse colors there.

**Comment by Snow-Pyon** [comment]
Fixed in the latest release.
