### ISSUE TITLE
on world change

### ISSUE THREAD

**Issue by NairasLT** [bensku/Skript#1063]
hello im trying to create a kitpvp server, when a player exits world "PvPArena" and teleports to world "Hub"
thier armor/items teleports to hub any way to clear player's inventory? i tried but it didint work

code:

-
on world change:
	wait 3 ticks
	if player is in "Hub":
		give player glowing compass named "&9&lNavigation"

	else:
	clear player's inventory

-

**Comment by Snow-Pyon** [comment]
Go to the forums or the Discord server for help, the issue tracker isn't for this kind of stuff.
