### ISSUE TITLE
[BUG] All Commands output are double

### ISSUE THREAD

**Issue by Diserix** [bensku/Skript#1066]
Skript Version : Latest
Minecraft Version : 1.12.2 - Spigot - Latest
Java 8
command /test:
	trigger:
		message "Test"
		message "Test1"

When I enter that in Minecraft, the messages come out twice.

Example : 

Normal : /test 

Test
Test1

By me : 

Test
Test1
Test
Test1

I hope someone can help me

Greets,

Diserix

**Comment by Ydda** [comment]
You could attempt adding a 'wait 1 tick' in the end. That has fixed this particular problem for me once before, but I can't guarantee it'll fix it for you.

**Comment by Diserix** [comment]
Not Working for me...

**Comment by Snow-Pyon** [comment]
I'm more than sure this is an issue within your script, I'd have noticed otherwise. If you want help about it you can ask in the forums or in the Skript-chat (a Discord server).
