### ISSUE TITLE
$ sign cannot be used in "options" and "replace all"

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#1072]
Title says it all.

If you do this:
`replace all "!" with "$" in {_msg}`
This happens: https://hastebin.com/lugurasiqi.md
Note: the opposite works.

If you do this:
```
options:
	IWantMoneySign: You have $100
	
command /bug:
	trigger:
		send "{@IWantMoneySign}"
```
This happens: `You have IWantMoneySign00`
* It used to crash in the last version.

Hope this can be fixed.
Thanks!

**Comment by Snow-Pyon** [comment]
Huh, this shouldn't happen, I hope it isn't a parser bug. Just to be sure, can you confirm this happened in dev31? As the replace effect was slightly changed in dev32.

**Comment by Syst3ms** [comment]
It is a regex bug. When replacing something, you can refer to the matched groups using `$<group number>`. In this case, Java thinks that we're trying to refer to a group, yet without specifying any number.
In order to fix this, I think replacing with `\$` should work.

**Comment by Pikachu920** [comment]
yup, its regex. I'll fix this.
