### ISSUE TITLE
I can't use "%" sign in item's name and lore

### ISSUE THREAD

**Issue by Soufreur78** [bensku/Skript#1077]
In the old version of skript you can use "%" in item's name of item's lore only if you use "%%"
Like that : set slot 0 of player with diamond named "3%%" 
In game your item's name is "3%"

But with Bensku version when i put :
set slot 0 of player with diamond named "3%%" 
In game my item's name is "3%%"

Bug ?

**Comment by Snow-Pyon** [comment]
Could you give us the following info?

* Does it happen without addons?
* Which version of Skript are you running?
* Are you using PaperSpigot/Spigot? If so, Which version?

**Comment by Soufreur78** [comment]
Sorry i miss the necessary info :    
- Addons use : SkQuery, Tuske, SkUtilities, SkRayFall
- Skripts's version : 2.2-dev27 (I have some problems with the new version)
- Spigot 1.8.8

**Comment by Pikachu920** [comment]
update your skript and check. if it still happens, include reproduction code

**Comment by Snow-Pyon** [comment]
Is this still an issue?

**Comment by Nicofisi** [comment]
I've just tried this in-game and no, not an issue anymore
