### ISSUE TITLE
All skripts stop working

### ISSUE THREAD

**Issue by jimmybenoit** [bensku/Skript#1080]
I had these command items like fun things like a pig launcher and a wand and now they all stopped worked now is there anything i can do?

**Comment by TheBentoBox** [comment]
We need at least SOME information.

- Skript version?
- Server version?
- Any addons? If so which ones?
- Any errors, both in chat or in console? If so post them.

There's physically no way we can help you if you just say "stuff isn't working".

**Comment by jimmybenoit** [comment]
i just found out how to fix it it had to do with the item names for some reason
