### ISSUE TITLE
Suggestion: Full json text component support

### ISSUE THREAD

**Issue by aeonlamb** [bensku/Skript#1082]
Heya, ever since dev26 added support for json messages, I've been trying to use it more in my scripts as opposed to json.sk api ... however there's still something holding me back from using it full-time. It still doesn't have full support for text components (unless the documentation is lying to me).

Minecraft's json text is really versatile, you can display information about an item or a specific entity using the /json command easily, however the biggest thing missing for me is the insertion text component. You can read all about text components [here](http://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/351959-1-12-json-text-component-for-tellraw-title-books#Textinput). 

I'd really love to see insertions supported by skript, it's actually really useful. I think being able to display entities and items in chat would help a lot of people as well, but it's not as needed imo. Keep up the good work!

**Comment by Pikachu920** [comment]
i don't have much experience with skript's json but i believe insertion is supported

**Comment by Syst3ms** [comment]
No, it isn't supported, as shown [here](http://bensku.github.io/Skript/text.html).
And no, `suggest command` is different.

**Comment by Snow-Pyon** [comment]
Spigot doesn't support it so it may not be possible at the moment, I'll see if there is a way around for it though.

**Comment by Syst3ms** [comment]
https://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/net/md_5/bungee/api/chat/ComponentBuilder.html#insertion-java.lang.String-
