### ISSUE TITLE
Weird effect with many color codes

### ISSUE THREAD

**Issue by Govindass** [bensku/Skript#1083]
I got this weird effect when using:
send "&aYou selected &C&lR&E&la&A&li&B&ln&9&lb&D&lo&C&lw &atrail!"
it sends: https://i.imgur.com/aTSsgRe.png
if I use:
broadcast "&aYou selected &C&lR&E&la&A&li&B&ln&9&lb&D&lo&C&lw &atrail!"
it sends: https://i.imgur.com/fEJYcNv.png

I think this is a bug, they should be same.
Using Skript 2.2-dev32d on Spigot 1.11.2

**Comment by Snow-Pyon** [comment]
what happens if you don't capitalize the color codes? Also, I'm confident this wouldn't be a problem if you use the color tags (`<color>`) instead of the color code, currently, Skript uses a pretty interesting method to allow color codes in the send effect.

**Comment by bensku** [comment]
Whoops. Capitalization is not supported for color codes in JSON chat handling.
