### ISSUE TITLE
Problem with Skript

### ISSUE THREAD

**Issue by Nuppington** [bensku/Skript#1085]
I have server 1.8 spigot and when i upload Skript and start server i get this: https://pastebin.com/9ZH3t7qy

**Comment by bi0qaw** [comment]
You have two different Skript.jar files in your plugins folder. One is named `Skript.jar` and the other `Skript (5).jar`. Try removing one and it should work. As you are using spigot 1.8 you should also download the proper skript version. Have a look at this thread to get more information: https://forums.skunity.com/threads/general-skript-tutorial.5174/

**Comment by xXAndrew28Xx** [comment]
You need Java 8 or above to be able to run Skript.

**Comment by TheBentoBox** [comment]
^ Take advice of both above
