### ISSUE TITLE
Negated comparisons do not take into account Null values

### ISSUE THREAD

**Issue by bi0qaw** [bensku/Skript#1088]
A major issue I encounter frequently is that you cannot use negated comparisons with null values.

Example:
```
command /test:
    trigger:
        if {_v} is not true:
            send "message"
``` 

This command will not send the message even though it should as {_v} is clearly not true. The current workaround for this is:
```
        if {_v} is true:
            exit
        else:
            send "message"
```

**Comment by TheBentoBox** [comment]
I've encountered this as well so I can confirm.

**Comment by HYPExMon5ter** [comment]
I’ve also encountered this

**Comment by Pikachu920** [comment]
I think this is also intended. Skript will pretty much always return false with null values in conditions, barring conds like not set. These things are good for people new to programming (a large part of Skript's users). you could always do
`if {_v} ? false is not true

**Comment by TheBentoBox** [comment]
Genuine question: how is this good for people that are new to programming? Logically speaking, an unset or null variable being `not true` should pass, right? A basic part of programming is understanding booleans and boolean logic, and a null (falsy) value should definitely not pass a comparison check with `true`. It just seems counterintuitive, which is bad for new users, not good.

**Comment by melinstagibson** [comment]
yes, as a noobish user i keep running into this issue and it doesnt make sense to me at all.
if i check a variable thats not set for true the condition isnt met. and not "nothing"  like it is now. 
ive started to use "if var is set / isnt set" instead and use that as true/false checks just to not have to deal with this odd behaviour

**Comment by Syst3ms** [comment]
Pikachu the advocate of Skript weirdness.
