### ISSUE TITLE
Armor stand interact events

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#109]
Hello

Armor stands don't seem to trigger right click events right now, probably because they use a separate event. I suggest implementing a new `on armor stand interact` event using the [PlayerArmorStandManipulateEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerArmorStandManipulateEvent.html). In the context of the event `event-entity` should represent the clicked armor stand retrieved from `PlayerArmorStandManipulateEvent.getRightClicked()`, `event-slot` should represent the slot of the armor stand that was interacted with via `PlayerArmorStandManipulateEvent.getSlot()`, and the `player's tool` and `event-entity's tool` could be retrieved via the normal methods, but if necessary the event includes `PlayerArmorStandManipulateEvent.getPlayerItem()` and `PlayerArmorStandManipulateEvent.getArmorStandItem()`.

**Comment by bensku** [comment]
This is something that I would like to do at some point... It would be great to change equipment of armor stand too.

**Comment by TheBentoBox** [comment]
I've already been able to mess with armor stands in Skript pretty well, they use the same equipment tags as all other entities so something like `set target's tool to iron ingot` works on armor stands. The main issue is just how poorly right click events have handled them for such a long time.

**Comment by bensku** [comment]
I tried to do this now. The problem is that Skript really really dislikes registering subclass of already registered event. Armor stand manipulation event is subclass of entity interact event... But if you register event handler for superclass, wouldn't it work for subclasses too?

[Apparently, no](https://hub.spigotmc.org/jira/browse/SPIGOT-122). Due to that, armor stand events might be impossible to implement for Skript (in Spigot platform).

**Comment by TheBentoBox** [comment]
This was never closed but was added in [dev19](https://github.com/bensku/Skript/releases/tag/dev19) according do the documentation. The commits suggest your events don't work, but either way it seems to be a Spigot/Skript issue that can't be entirely resolved with how it's written. Can re-open it if you'd like in the future.

**Comment by bensku** [comment]
I got it working while testing other stuff for dev20 after Spigot update. It stopped working after server restart, so...

**Comment by TheBentoBox** [comment]
MundoSK's version of the events seems to have the same issue where they sometimes work and then sometimes don't during restarts. I'm not really sure why they're so finnicky.
