### ISSUE TITLE
that was my fault, lol, to remove

### ISSUE THREAD

**Issue by iOshawott** [bensku/Skript#1090]
To remove, on latest version no problem, I had a problem on new version because I changed some things in other plugins ;/

**Comment by bensku** [comment]
Need more information. What errors are shown?

**Comment by iOshawott** [comment]
there's no errors now, only this error on old version. and I can't spawn villagers using "spawn 1 villager at location of {villager%{_a}%} but with zombie it works

**Comment by iOshawott** [comment]
so I can't spawn villagers via skript ? ;x
