### ISSUE TITLE
<tooltip:> does not work in broadcast effect

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#1093]
Skript dev32d

Reproduction:
```
command /test:
    trigger:
        broadcast "<tooltip:test>message" # this will not work
        send "<tooltip:test>message" to command sender # this will work just fine
```

**Comment by Pikachu920** [comment]
You can send to all players instead

**Comment by jaylawl** [comment]
@Pikachu920 i realise that, you mean "loop all players", right?

**Comment by Snow-Pyon** [comment]
There is no direct way to broadcast a JSON message in the Spigot API,  but you can do the following which is pretty much the same:
```
send "<tooltip:test>message" to all players
```
