### ISSUE TITLE
This problems kicks player when join.

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#1094]
03.02 14:56:17 [Server] INFO UUID of player saca is cce4a4ba-8b29-39cf-b1e6-e7dfd35675eb
03.02 14:56:17 [Server] ERROR #!#! 
03.02 14:56:17 [Server] ERROR #!#! [Skript] Severe Error:
03.02 14:56:17 [Server] ERROR #!#! 
03.02 14:56:17 [Server] ERROR #!#! Something went horribly wrong with Skript.
03.02 14:56:17 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
03.02 14:56:17 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
03.02 14:56:17 [Server] ERROR #!#! Here is full list of them:
03.02 14:56:17 [Server] ERROR #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) mmSkriptAddon 
03.02 14:56:17 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
03.02 14:56:17 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
03.02 14:56:17 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
03.02 14:56:17 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
03.02 14:56:17 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
03.02 14:56:17 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
03.02 14:56:17 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
03.02 14:56:17 [Server] ERROR #!#! 
03.02 14:56:17 [Server] ERROR #!#! Stack trace:
03.02 14:56:17 [Server] ERROR #!#! java.lang.IllegalArgumentException: Entry cannot be longer than 40 characters!
03.02 14:56:17 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scoreboard.CraftObjective.getScore(CraftObjective.java:96)
03.02 14:56:17 [Server] ERROR #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:46)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
03.02 14:56:17 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
03.02 14:56:17 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
03.02 14:56:17 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
03.02 14:56:17 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
03.02 14:56:17 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
03.02 14:56:17 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
03.02 14:56:17 [Server] ERROR #!#! 
03.02 14:56:17 [Server] ERROR #!#! Version Information:
03.02 14:56:17 [Server] ERROR #!#!   Skript: 2.2-dev32d (latest)
03.02 14:56:17 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
03.02 14:56:17 [Server] ERROR #!#!   Minecraft: 1.12.2
03.02 14:56:17 [Server] ERROR #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
03.02 14:56:17 [Server] ERROR #!#!   OS: Linux amd64 4.9.78-xxxx-std-ipv6-64
03.02 14:56:17 [Server] ERROR #!#!

**Comment by TheBentoBox** [comment]
This is an skRayFall issue with how you have your scoreboards set up. You're making a scoreboard title or entry too long. Regardless, this isn't a vanilla Skript issue.
