### ISSUE TITLE
[Feature Recommendation] Expressions and Variables in No Permission Message

### ISSUE THREAD

**Issue by CormanYT** [bensku/Skript#1098]
I have a recommendation for Skript. My recommendation is that we add variables, or expressions to no permission messages like this:
`permission message: %{var}%`
Or list variables too like:
`permission message: %{list:var}%`
I also have the idea for expressions like this:
`permission message: &cSorry %player%, but you cannot use this command!`
That's my idea and I hope it'll be added!

**Comment by HYPExMon5ter** [comment]
Duplicate of #652

**Comment by CormanYT** [comment]
Oh. I'll close the issue.
