### ISSUE TITLE
Items with no right click usage don't trigger right click events in offhand with empty mainhand

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#11]
This might be an issue with Minecraft or Spigot itself. How I'm testing it is with:

`on right click with diamond pickaxe on sand:`
`	send "Hello"`

If I have the diamond pick in my main hand, it works. If I have it in my offhand, and have nothing in my mainhand, it doesn't send.

This is a bit of a niche case, but just figured I'd let you know! It's otherwise working exactly as expected in regards to mainhand and offhand stuff. Thanks for these updates!

**Comment by bensku** [comment]
Hmm, interesting. This is probably caused by the code which tries to detect if you can use item - you can't use pickaxes in off hand. I'll see if I can fix this today.

**Comment by bensku** [comment]
See #14
