### ISSUE TITLE
Support for some 1.9+ mobs seems bugged

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#110]
Support for shulkers and polar bears in dev17 [seems to be broken](https://gyazo.com/ed3b6351418741e4022e9663e3941c7e). They both also return "creature" as their entity type when doing something like `send "%player's target%"`. Tested both on my public server ([7 versions behind](https://gyazo.com/0f75a01920712b0b14dc139da3610c80)) and on my test server [with the newest Spigot build](https://gyazo.com/d260b0761e317ee75c9f9c846eaf70fa).

**Comment by xBiscuit** [comment]
Not to mention ShulkerBullets too. Its as if they weren't added to the entity alias list, I cant do simple things like: `Spawn a shulker at the player`, since the shulker is not recognised

**Comment by bensku** [comment]
Hmm. Probably a bug.

**Comment by TheBentoBox** [comment]
I can confirm that the code for strays does generally work (`spawn a stray at the player` spawns one). Looking at one and doing `send "%target%"` still just sends "skeleton", but that's not as important.

**Comment by xBiscuit** [comment]
Also stuff like `push player's target upwards at speed 2` will push polar bears up and other mobs

**Comment by TheBentoBox** [comment]
@bensku Do you expect this to be fixed in the next release? I have a fun script idea that relies on polar bears being supported :blush:

**Comment by bensku** [comment]
I managed to fix shulkers and their bullets, but for some reason Skript refuses to parse polar bear as entity type even after I have verified that it is registered.

Why? Well, due to too much spaghetti code, but I don't know exactly why. For exact same reason why it took me 4 hours to figure out why Skript didn't spawn any entities in certain conditions, it is kinda hard to fix issues like these.

**Comment by TheBentoBox** [comment]
I guess on the bright side that means for now we can check `if "%event-entity%" is "creature"` to see if it's a polar bear. Right now that doesn't work because shulkers also label as creatuer, but it'll work if they're the only broken entity.

Glad shulkers are working at least! Hope you're able to find the rest of the problem eventually.

**Comment by TheBentoBox** [comment]
I'm still having this issue with all 1.9+ mobs and variants (save strays) in dev18b, [am trying here](https://gyazo.com/9f2096eb7e01ec81e559d991adcc5581). Running [this version of Spigot](https://gyazo.com/9f16ac34aa4f62beae250a4f1e62405e).

**Comment by TheBentoBox** [comment]
Scratch my last comment, I had an extra SkQuery API jar lying around that was causing the issue. I have more info now :)

`spawn a shulker` now works. Using `send "%target%"` on a shulker returns "entities.golem.name"

`spawn a polar bear` doesn't work, BUT `spawn a polar bears` *does*. It needs to be plural to work. `send "%target%" on a polar bear returns "polar bear", as expected.

So in summary, the current issues left for full 1.10 entity support are:

1. No husk support.
2. Shulker name returns as entities.golem.name
3. Polar bears need to be spawned with `polar bears` in plural. This applies to all forms of referencing them (e.g. need to do `if clicked entity is a polar bears`)

**Comment by bensku** [comment]
Some of what you meantioned are indeed bugs... But other things do work for me. I need to debug more :)

**Comment by bensku** [comment]
This is finally fixed in next release.

**Comment by TheBentoBox** [comment]
Thank you :)
