### ISSUE TITLE
another new error

### ISSUE THREAD

**Issue by Sodies** [bensku/Skript#1100]
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! [Skript] Severe Error:
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Something went horribly wrong with Skript.
05.02 20:36:09 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
05.02 20:36:09 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
05.02 20:36:09 [Server] ERROR #!#! Here is full list of them:
05.02 20:36:09 [Server] ERROR #!#! skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) mmSkriptAddon 
05.02 20:36:09 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
05.02 20:36:09 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
05.02 20:36:09 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
05.02 20:36:09 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
05.02 20:36:09 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
05.02 20:36:09 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
05.02 20:36:09 [Server] ERROR #!#! Issue tracker: https://github.com/bensku/Skript/issues (only if you know what you're doing!)
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Stack trace:
05.02 20:36:09 [Server] ERROR #!#! java.lang.NullPointerException
05.02 20:36:09 [Server] ERROR #!#!     at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:46)
05.02 20:36:09 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
05.02 20:36:09 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
05.02 20:36:09 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
05.02 20:36:09 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:101)
05.02 20:36:09 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
05.02 20:36:09 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
05.02 20:36:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
05.02 20:36:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
05.02 20:36:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
05.02 20:36:09 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
05.02 20:36:09 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Version Information:
05.02 20:36:09 [Server] ERROR #!#!   Skript: 2.2-dev32d (latest)
05.02 20:36:09 [Server] ERROR #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
05.02 20:36:09 [Server] ERROR #!#!   Minecraft: 1.12.2
05.02 20:36:09 [Server] ERROR #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
05.02 20:36:09 [Server] ERROR #!#!   OS: Linux amd64 4.9.78-xxxx-std-ipv6-64
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Running CraftBukkit: false
05.02 20:36:09 [Server] ERROR #!#! Running Spigot (or compatible): true
05.02 20:36:09 [Server] ERROR #!#! Running Paper (or compatible): false
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Current node: null
05.02 20:36:09 [Server] ERROR #!#! Current item: null
05.02 20:36:09 [Server] ERROR #!#! Thread: Server thread
05.02 20:36:09 [Server] ERROR #!#! 
05.02 20:36:09 [Server] ERROR #!#! Language: english
05.02 20:36:09 [Server] ERROR #!#! Link parse mode: DISABLED
05.02 20:36:13 [Multicraft] Skipped 3 lines due to rate limit (50/s)

**Comment by Syst3ms** [comment]
```
05.02 20:36:09 [Server] ERROR #!#! java.lang.NullPointerException
05.02 20:36:09 [Server] ERROR #!#! at net.rayfall.eyesniper2.skrayfall.scoreboard.EffSetScore.execute(EffSetScore.java:46)
```
skRayFall issue.
