### ISSUE TITLE
Console show "1" every time a mob is killed

### ISSUE THREAD

**Issue by SullyTheUnusual** [bensku/Skript#1101]
I modified an existing script that drops mob heads for players, and now every time a player kills a mob it shows a "1" in the console.  Here's my script:  https://hastebin.com/cejetoyapi.vbs

The top part is what shows up in the console, the bottom part is my script.

**Comment by TheBentoBox** [comment]
Highly doubt this is a Skript issue, but to give it a chance, what Skript/server version are you using?

**Comment by SullyTheUnusual** [comment]
Skript v2.2-dev31c
Skellett v1.9.6b
git-Spigot-596221b-9a1fc1e (MC: 1.12)

The issue did not show up until I implemented the mob head dropping script, and the script is driven by the "on death" event (which is what is triggering the 1's getting written to console), so I'm not sure how it cannot be a Skript issue, unless there's something wrong with my script.

Please let me know if any further information would be useful, and thanks for the reply.

**Comment by TheBentoBox** [comment]
Before we can continue you'd need to update your Skript version to the latest version [found here](https://github.com/bensku/Skript/releases). This may be a debug message that was present in your current version or something, but regardless bug reports are meaningless unless you're on the latest version.

**Comment by SullyTheUnusual** [comment]
I updated the plugin and did some more testing, and it looks like another plugin is causing it.

Sorry for wasting your time.
