### ISSUE TITLE
All /sk commands output "/skript help"

### ISSUE THREAD

**Issue by TheZipCreator** [bensku/Skript#1106]
So when I do /sk [subcommand] with any subcommand, it just outputs "/skript help", even the "/skript help" command. (v2.1.2)

Also I get this in the console

`[17:32:33 ERROR]: Error occurred while enabling Skript v2.1.2 (Is it up to date?) java.lang.NoSuchMethodError: org.bukkit.DyeColor.getData()B at ch.njol.skript.util.Color.<clinit>(Color.java:82) ~[?:?] at ch.njol.skript.SkriptCommand.<clinit>(SkriptCommand.java:60) ~[?:?] at ch.njol.skript.Skript.onEnable(Skript.java:254) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [craftbukkit-1.12.2.jar:git-Bukkit-aa34e9b] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]`

**Comment by Syst3ms** [comment]
2.1.2 is a version for 1.7. Update to dev32d for anything above
