### ISSUE TITLE
Suggestion: variable permissions in commands

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#1109]
Something like this:

```
command /kit <string>:
        permission: mel.kit.%arg-1%
        permission message: &cYou don't have permission to use kit %arg-1%
        trigger:
```
right now the check isnt working (checks for literal mel.kit.%arg-1%) same with the message ("ou don't have permission to use kit %arg-1%" in red)

**Comment by Pikachu920** [comment]
Duplicate of #652
