### ISSUE TITLE
Can't compare player's gamemode to creative in dev17

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#111]
Because of the new and improved inventory click events from dev17, running `player's gamemode is creative` (or isn't creative) now [returns the error](https://gyazo.com/46becdb61560ea99e606b3577a5e69a8) `Can't compare a gamemode with a click actions`.

**Comment by TheBentoBox** [comment]
Forgot to say in case anyone else has issues with this, you're able to get around this by parsing their gamemode as a string and comparing that way (`"%player's gamemode%" is "creative"`).

**Comment by bensku** [comment]
Wait what...

This should _not_ be possible. Apparently the parser contains more spaghetti code than I expected.

**Comment by TheBentoBox** [comment]
I was surprised by it as well. I can confirm other people have mentioned having this issue on the skUnity forums. It's very strange (and only happens with comparing to creative mode because of the creative click action).
