### ISSUE TITLE
Excessive CPU consumption

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#1112]
Spigot 1.12.2
Skript 2.2-dev33

The recent Skript release consumes more CPU than previous versions. It is possibly an interaction effect with other recent plugin updates, but Skript seems to be central. 

I maintain two test servers. At present, there are 92 plugins, all latest dev pulls: Citizens, DeluxeMenus, EssentialsX, ItemJoin, LuckPerms, Multiverse-*, ProtocolLib, Skript, Vault, WorldEdit, WorldGuard, etc. The servers are identical (one is a clone from backups of the other), except for the Skript version. With no players connected:
- Server A: Skript 22-dev33 :: average TPS 19.62
- Server B: Skript 2.2-dev32d :: average TPS 20.00

The reduced TPS on Server A occurs even if all skripts are disabled. So it appears that something in the dev33 Skript engine itself is consuming CPU, or is interacting with other plugin updates, in a way which it did not in dev32d (and previous).

What additional data would be useful to analyze this issue?

**Comment by bensku** [comment]
Full timings report might help.

**Comment by SlimeDog** [comment]
Results of repeated tests are all over the map. Closing until I have definitive results.
