### ISSUE TITLE
While loop not working?

### ISSUE THREAD

**Issue by Wekylend** [bensku/Skript#1113]
**So here is my Skript:**

https://pastebin.com/raw/xh1R8NMk

**And here is the error:**

https://pastebin.com/raw/m4ZzbXSc

I think it's being registered as an event.

**Comment by HYPExMon5ter** [comment]
Is that your full code? If so, of course it’s going to error, you need to put that code in a event or command.

**Comment by Wekylend** [comment]
Ohh! I was so certain you could use it alone.

**Comment by TheBentoBox** [comment]
Yeah, you can't just put a while loop on the top level. It's "being registered as an event" because you're trying to use it as an event, which isn't how that works. You should ask for help on the skUnity forums since it seems like you need to learn more about how & when to use while loops.
