### ISSUE TITLE
Skript scoreboard 1.8

### ISSUE THREAD

**Issue by iLikq** [bensku/Skript#1115]
I have a Minetopia minecraft server for 1.8, ive made a scoreboard plugin with Skript.
I have a little problem, i want that every minute a player executes the command: /mtscoreboard
But i does say: "This is not a boolean"
Can u please help me?

Here is my skript:

command /mtscoreboard:
	trigger:
		display board named "&9&lItzTopia" to player
		make score "&3&lRekening: " in board of player to 15
		make score "  &b€%{rekening.%player%}%" in board of player to 14
		make score "&3&lSpeler: " in board of player to 13
		make score "  &b%player%" in board of player to 12
		make score "&3&lRank: " in board of player to 11
		make score "  &b%coloured {rank.%player%}%" in board of player to 10
		make score "&3&lTemperatuur: " in board of player to 9
		make score "  &b24°C" in board of player to 8
		make score "&3&lTijd: " in board of player to 7
		make score "  &b%time of player%" in board of player to 6
		make score "&3&lLevel: " in board of player to 5
		make score "  &b%{level.%player%}%" in board of player to 4
		move display of player to sidebar

**Comment by TheBentoBox** [comment]
This isn't the right place to ask this, vanilla Skript doesn't support scoreboards so the issue isn't relevant and this also isn't the place to ask for help. Only post here if you have a bug report or feature request relating to the **latest version** of **vanilla** Skript, nothing related to add-ons.

For help with code, especially that involving add-ons, use the skUnity forums instead.
