### ISSUE TITLE
there's no player/console event in the plant growth event?

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#112]
Hey Bensku, when I used this code:
```java
on plant grow of wheat:
	send "Yeah!"
```
And this technically need work but this says there's no player in that event and I'm pretty sure the unique can grow a plant is a player so...

**Comment by TheBentoBox** [comment]
I think this event fires when a plant grows naturally. If you want to detect a player bonemealing a plant, you could use:

```
on right click on wheat:
    player's tool is bonemeal
    data value of clicked block < 7
    send "%player%"
```

Checking the data value makes sure it's not fully grown (wheat:7 is fully grown wheat).

**Comment by Pilvinen** [comment]
The problem is that you are trying to send a message to the player of the event but there is no player in that event because the growth event has nothing to do with players.

If you want to see the debug message you should, for example, send to to the console thus:

```
on plant grow of wheat:
    send "Yeah!" to console
```

**Comment by JKGamerxD** [comment]
Uh, I understand now, thanks for the both responses
