### ISSUE TITLE
/sk reload (name) dont work, error, please help.

### ISSUE THREAD

**Issue by xZod** [bensku/Skript#1121]
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] WARN #!#! 
17.02 20:13:07 [Server] WARN #!#! Skellett v1.9.5LargeSk v1.2-BetaVixio v1.0.5skRayFall v1.8WildSkript v1.8PirateSK v0.4.1skDragon v0.09.0ExertSK v0.1.3bUmbaska v2.0 Beta 5.5.1SkQuery v3.21.4SkExtras v3.9.1ExtrasSK v1.1RandomSK v1.3SkStuff v1.6.2
17.02 20:13:07 [Server] WARN #!#! [Umbaska] List of addons: 
17.02 20:13:07 [Server] WARN #!#! 
17.02 20:13:07 [Server] WARN #!#! CrazyCrates - 1.7.3, LampControl - 3.0, BloodParticles - 0.5.0, GroupManager - Pre2.14.1.3 FINAL (Phoenix), DisableDeathMessage - 1.0, NametagEdit - 4.1.7, Arconix - 1.1.1, ParticleLIB - 2.1.1, ViaVersion - 1.3.0, AsyncWorldEditInjector - 2.3.0, EnderPearlRider - 1.2, WorldEdit - 6.1.7;dd00bb1, TimTheEnchanter - 3.0, Skript - 2.2-dev24b, Essentials - TeamCity, HeadLeaderBoards - 4.0.3, ClearLag - 2.9.7, DisableJoinMessage - 1.0, skDragon - 0.09.0, AdvancedBan - 2.0.6, SkQuery - 3.21.4, BuycraftX - 10.3.0, Votifier - 1.9, SkStuff - 1.6.2, ProtocolLib - 4.3.0, NoCheatPlus - 3.15.1-RC-sMD5NET-b1084, ImageMaps - 0.4.3, AsyncWorldEdit - 2.3.3, CustomServerMessages - 5.2, EssentialsChat - TeamCity, Rename - 1.0, EffectLib - 5.4, AdminShop - 0.4.1, Vault - 1.5.6-b49, ServerListPlus - 3.4.7, MassiveCore - 2.11.0, LargeSk - 1.2-Beta, Vixio - 1.0.5, ExertSK - 0.1.3b, ExtrasSK - 1.1, HolographicDisplays - 2.2.6, SkAction - 2.2, WorldGuard - 6.1, KitCreator - 1.1, PlayerVaults - 3.5.7-b${BUILD_NUMBER}, SkExtras - 3.9.1, StaffList - 3.84, EssentialsSpawn - TeamCity, TitleManager - 2.0.8, Banknotes - 1.8.0, WarpPortals - 5.6.3, Citizens - 2.0.16-SNAPSHOT (build 1267), WildSkript - 1.8, PirateSK - 0.4.1, skRayFall - 1.8, MageSpellsRemastered - 2.0.8.6, RandomSK - 1.3, CombatLogX - 5.2.0 Release, Skellett - 1.9.5, Umbaska - 2.0 Beta 5.5.1
17.02 20:13:07 [Server] WARN #!#! [Umbaska] List of plugins: 
17.02 20:13:07 [Server] WARN #!#! 
17.02 20:13:07 [Server] ERROR #!#! End of Error.
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#! Thread: Server thread
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#! Current item: null
17.02 20:13:07 [Server] ERROR #!#! Current node: null
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#! Running CraftBukkit: false
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
17.02 20:13:07 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
17.02 20:13:07 [Server] ERROR #!#!   Minecraft: 1.8.8
17.02 20:13:07 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
17.02 20:13:07 [Server] ERROR #!#!   Skript: 2.2-dev24b
17.02 20:13:07 [Server] ERROR #!#! Version Information:
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
17.02 20:13:07 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
17.02 20:13:07 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
17.02 20:13:07 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375)
17.02 20:13:07 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:411)
17.02 20:13:07 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627)
17.02 20:13:07 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
17.02 20:13:07 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
17.02 20:13:07 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
17.02 20:13:07 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
17.02 20:13:07 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:706)
17.02 20:13:07 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:713)
17.02 20:13:07 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:255)
17.02 20:13:07 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:264)
17.02 20:13:07 [Server] ERROR #!#! java.lang.NullPointerException
17.02 20:13:07 [Server] ERROR #!#! Stack trace:
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
17.02 20:13:07 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
17.02 20:13:07 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
17.02 20:13:07 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
17.02 20:13:07 [Server] ERROR #!#! and check whether this error has already been reported.
17.02 20:13:07 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
17.02 20:13:07 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] ERROR #!#! Used command: /sk reload report
17.02 20:13:07 [Server] ERROR #!#! Exception occurred in Skript's main command
17.02 20:13:07 [Server] ERROR #!#! [Skript] Severe Error:
17.02 20:13:07 [Server] ERROR #!#! 
17.02 20:13:07 [Server] INFO [Skript] Reloading report.sk...

**Comment by xZod** [comment]
I just use /sk reload (script name) then this happens in the console.

**Comment by xZod** [comment]
All my scripts is doing that

**Comment by xZod** [comment]
[https://gyazo.com/c335c10b28a4a6e987a5f2737f07cce8](url)
This is what happens ingame after i use the command /sk reload report

**Comment by TheBentoBox** [comment]
You're not on the latest version of Skript and we don't even support 1.8. You must at least update to the latest version before filing a bug report, but don't expect much help if you're on a version older than 1.9.
