### ISSUE TITLE
Parsed Item with name and lore

### ISSUE THREAD

**Issue by knugi** [bensku/Skript#1122]
Hello guys, how to parsed text to item with: Enchantments, Name and Lore?
`command /test:
	trigger:
		set {_tool} to "diamond of efficiency 5 named ""Name"" with lore ""lore""" parsed as item type
		send "%{_tool}%"`
This code is broken :/ send <none> 
How parsed it to get my result?

**Comment by Pikachu920** [comment]
this issue tracker is for reporting bugs, not getting help with your script

**Comment by Snow-Pyon** [comment]
Lore isn't part of the item itself, it's an expression from skQuery.

That said, please follow the above advice the next time.
