### ISSUE TITLE
Low Priority - Certain events won't remove potion effects

### ISSUE THREAD

**Issue by diamondpumpkin** [bensku/Skript#1126]
Minecraft: 1.12.2
Spigot: 1.12.2-R0.1-SNAPSHOT
Skript: 2.2-dev33

I'm running a timed loop to attempt to remove slowness from villagers in a world.

```
every 1 second:
    loop all villagers in world "vd":
        remove slowness from the loop-entity
```
Returns when reloaded:
```
[Skript] Reloading vd.sk...
the loop-entity can't have anything removed from it (vd.sk line 3: remove slowness from the loop-entity)
[Skript] Encountered 1 error while reloading vd.sk!
```

I've tried different loop types like 'loop-villager' instead. I've also tried different potions. This seem to only effects villagers. This effect seems to only break in a timed looped like the one above as far as I can tell. There's a very easy work-around this was just very annoying.

Fix:
```
loop all entities in world "vd":
    if loop-entity is a villager:
        remove slowness from the loop-entity
```

**Comment by Pikachu920** [comment]
what events does this happen in?

**Comment by diamondpumpkin** [comment]
The timed one, I also tried an on damage event which worked fine.

**Comment by Blueyescat** [comment]
Can reproduce.

> I also tried an on damage event which worked fine.

Can't reproduce this, it doesn't work at anywhere.

**Comment by diamondpumpkin** [comment]
> Can't reproduce this, it doesn't work at anywhere.

Just retried this with the versions I listed above and works fine.

```
on damage:
    victim is a villager
    remove slowness from the victim
```
Also tried with poison, which after taking damage once it removes it.

**Comment by Nicofisi** [comment]
I did some digging and in SimpleExpression.java in the method [acceptChange](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/lang/util/SimpleExpression.java#L217)

with this code (where it works):
```
every 1 second:
    loop all entities in world "vd":
        if loop-entity is a villager:
            remove slowness from the loop-entity
```
`getReturnType()` returns `interface org.bukkit.entity.Entity`
after the `ClassInfo<?> rti = returnTypeInfo;` line the `rti` is null, 
and inside the if check the variable `returnTypeInfo` is set to a ClassInfo of type `entity`
and `rti.getChanger()` returns an instance of `ch.njol.skript.classes.data.DefaultChangers`

while with:
```
every 1 second:
    loop all villagers in world "vd":
        remove slowness from the loop-entity
```
`getReturnType()` returns `interface org.bukkit.entity.Villager`
`rti` is null again, in the if check it's set to a ClassInfo of type `inventory holder`
and `rti.getChanger()` is null

My best **guess** is that the `inventory holder` type is somehow more specific than an `entity` or simply on some list of registered `ClassInfo`s it's before the `entity` type, and Villagers are both entities and inventory holders.. I have no idea how to solve that though, considering that [InventoryHolders are not only entities but also chests, dispensers etc..](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/InventoryHolder.html)

And I don't think this involves events at all

**Comment by Blueyescat** [comment]
@diamondpumpkin We are talking about removing **something** from the loop-value/villager in a **villagers loop**. Not removing something from a villager. Also it is valid for `add` changer too.

By the way more weird things:
Works: **`loop all villagers and zombies:`**
Doesn't work: **`loop all villagers and 1:`**
Works: **`loop villagers, zombies and players:`**
Doesn't work: **`loop villagers, zombies and (random player of players):`**

(the expression returns the villagers, specifying the world doesn't matter)

**Comment by Blueyescat** [comment]
Ok, lets make this issue critical lol. I gives the same error with any list variable too.

```vb
loop {anyVariable::any::*}:
    remove a stone from loop-value
```
*loop-value can't have anything removed from it*

**Comment by Nicofisi** [comment]
@Blueyescat yeah it's valid for all changers

**Comment by Nicofisi** [comment]
@Blueyescat is this list actually set to anything?

**Comment by Blueyescat** [comment]
@Nicofisi Doesn't matter so i tried it.

**Comment by Blueyescat** [comment]
```vb
loop villagers:
    delete loop-value
```
❌  loop-value can't be deleted/cleared
```vb
loop villagers and zombies:
    delete loop-value
```
```vb
loop zombies:
    delete loop-value
```
```vb
loop {list::*}:
    delete loop-value
```
```vb
loop {list::*} and zombies:
    delete loop-value
```
✅ No error

**Comment by Nicofisi** [comment]
Probably like I said after my digging, I'm on phone now but i suppose in your working examples Skript treats what you're looping as lists of entities or "something else that's default", and in the non working example treats the villagers as "inventory holders" instead of entities. This is weird o.o

**Comment by Blueyescat** [comment]
You are right! It gives the error for llamas and horses. About variables? Because a variable can be an inventory holder? 🤔

**Comment by Nicofisi** [comment]
With the non-existent list:
```vb
loop {anyVariable::any::*}:
    remove a stone from loop-value
    give a stone to loop-value
```
the ClassType is just `object` and it has no default changers, and that's, well.. probably expected? 🤔 

by the way here's just a confirmation that villagers are treated as inventory holders: (I'm not saying that it's a bug that it can't be saved, I get it)
```
[18:26:46 WARN]: an inventory holder cannot be saved, i.e. the contents of the variable {x::*} will be lost when the server stops. (test.sk, line 37: set {x::*} to all villagers')
[18:26:46 WARN]: a living entity cannot be saved, i.e. the contents of the variable {y::*} will be lost when the server stops. (test.sk, line 38: set {y::*} to all zombies')
```
the code which gave me the warnings above is:
```
every 1 second:
        loop {x::*}:
                remove slowness from the loop-value

command /setit:
        trigger:
                set {x::*} to all villagers
                set {y::*} to all zombies
```
in the above code the loop-value is also just treated as an "object" and errors. Pretty expected but doesn't make solving easier at all

**Comment by diamondpumpkin** [comment]
@Blueyescat 

> @diamondpumpkin We are talking about removing something from the loop-value/villager in a villagers loop. Not removing something from a villager. Also it is valid for add changer too.

I'm aware of this, but you stated that you could not reproduce the on damage event. Which I stated otherwise.

> (the expression returns the villagers, specifying the world doesn't matter)

I'm aware the world doesn't matter, I left in some code I copied from my public server scripts.

**Comment by Nicofisi** [comment]
Ok so I managed to fix this by adding the `.after` line to where the pattern is registered
```java
		Classes.registerClass(new ClassInfo<>(InventoryHolder.class, "inventoryholder")
				.name(ClassInfo.NO_DOC)
				.after("entity")
				.defaultExpression(new EventValueExpression<>(InventoryHolder.class)));
```

But I believe the issue is much more deeper as that could probably break looping inventory holders, if there's any good working reason to loop them actually.. someone who knows much about how Skript works would have to share their opinion.

Also what about other inventory holders, ones that are not entities? *Going to sleep now, bye*
