### ISSUE TITLE
Would a general code consistency PR be welcome?

### ISSUE THREAD

**Issue by Nicofisi** [bensku/Skript#1127]
There are minor things in most of the classes that I'd be happy to change:
* Many classes have fields that are both `static` and `final`.
There's no point in making a static method final.
* Many classes have fields with no public/private modifiers, and most of them could simply be private
* In some classes the logical operators could be simplified, just minor changes for example `x != (y != z)` can be changed to `x == (y == z)`
* Many classes that extend the same class have inconsistencies in the way they call static methods in the super class, for example some classes that extend `EntityData<E>` have `EntityData.register(..` in their code while some other have only `register(..`
* Methods in many (all? I checked only three) interfaces have the `public` modifier while according to IntelliJ *Modifier `public` is redundant for interface methods*
* In this one I'm unsure about what reaction to expect about this one but many things could be simplified using Java 8's  syntax, for example
```java
		x = new Converter<Object, Object>() {
			@Override
			public Object convert(Object o) {
				return null;
			}
		};
```
could be changed to
```java
		x = (Converter<Object, Object>) o -> null;
```
When using an IDE or just by looking at the name it still should be pretty easy to follow what's going on in most cases, and we'd save a huge amount of lines that don't actually mean or do anything so developers can focus on parts of code that are significant.
* Other things similar to those mentioned above, that often occur only once in the whole project so I won't mention them here but are simply unneeded (at least in modern versions of Java), for example in a method which's return type is `Long` the `return Long.valueOf(n.longValue())` is not needed, a simple `return n.longValue()` would just work. There's a ton of minor things like that.

I probably wouldn't be touching any annotations at all because I've never really payed attention to `@Nullable`s when dealing with Skript so I'd probably just leave them as they are, untouched 

I also wouldn't be changing any logic, wouldn't be writing or removing any code or making any performance optimizations in this PR, only making things that are already written more.. enjoyable by the IDE and code readers, let's name it this way. After the PR everything will work exactly the way it worked before. The reason is simple, I am aware how annoying and time consuming it would be for repo maintainers to check line by line what is just a meaningless change and what could potentially break half of Skript. So I'll avoid anything like this.

My question is: would a PR of this sort be welcome? I have a lot of free time in the following few days, but I'm asking before doing anything because changing something in 100+ files just to hear that you guys liked how it worked before wouldn't be the best feeling ;)

**Comment by Syst3ms** [comment]
Note Skript's code was mostly made with Java 6, where : 
 * Diamond syntax for generic constructors (e.g `new ArrayList<>()`)
 * Lambdas (of course)
 * `public` being required in interfaces ?
*didn't exist*.

**Comment by Nicofisi** [comment]
Anyways if you don't think any of these changes would be like, just, *bad*, I could practically start.. right now ¯\_(ツ)_/¯

**Comment by Nicofisi** [comment]
See #1132
