### ISSUE TITLE
Bug with OffHand-click

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#1129]
Hey guys,

I've just recognized a bug, which causes, that a click-event isn't being fired.

Scenario:
(1) Player is in survival mode and has a random tool in the off hand (slot 40). 
(2) The player clicks with the right mouse button on a shulker-box.
(3) The rightclick / leftcllick event is not being fired.

I'm not sure, if this is the supposed way to work.

(newest Skript version, Spigot 1.12.2)

**Comment by Nicofisi** [comment]
Was the shulker-box just an example or is this issue specific to shulker boxes?

**Comment by GermanMinerDE** [comment]
Hey!
I tested it with several blocks and the shulker box seems to be an specific issue.
Same is happening with player skulls.

I tested it with rightlick / leftclick / click, result:
(1) When tool in the off-Hand: click or leftclick fired
(2) nothing in off-hand: Rightclick, click or leftclick fired

**Comment by DevilishDante** [comment]
@GermanMinerDE i have the same issue here -> https://github.com/bensku/Skript/issues/1079
it's exacly same for me with the code in my issues, so i think isn't a spécific problem maybe

**Comment by TheLimeGlass** [comment]
https://github.com/bensku/Skript/issues/51

**Comment by khlfkk** [comment]
how can fix it too . really need this function for the skript. @TheLimeGlass
