### ISSUE TITLE
Please post a list of working particle effect names....

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#113]
You once released this list here:
http://hastebin.com/caweracidu.rb
But many of these effect names are wrong and not working. 

Examples of NOT working particles: 
play 200 (potion swirl with speed 0) at {_loc}
play 200 (flame with speed 0) at {_loc}
play 200 (witch magic with speed 0) at {_loc}

Thanks for your help!

**Comment by bensku** [comment]
I updated the (gist)[https://gist.github.com/bensku/834e7bf666eb995e53d456c21ecc1e0e] just in case there was something wrong.

If something still doesn't work, then I guess Skript's particle backend has more bugs.
