### ISSUE TITLE
Variables Bug

### ISSUE THREAD

**Issue by EazyFTW** [bensku/Skript#1134]
When I restart my server some of my variables reset. I was level 17 in what I was making and I went back to level 1.

Server Ver: 1.12.2
Skript Ver: Latest (dev33)

**Comment by Nicofisi** [comment]
Did you stop your server in a normal way? Also I'm not saying it should happen but we have the backup folder for a reason, just restore one of your backups ;)

**Comment by EazyFTW** [comment]
Yes I did.

**Comment by EazyFTW** [comment]
It happens when I just plainly leave...

**Comment by EazyFTW** [comment]
Nvm.. I feel super dumb.. I'm sorry for wasting your time!
