### ISSUE TITLE
 [Warning] Skript loading error on console

### ISSUE THREAD

**Issue by ShaneBolenback** [bensku/Skript#1137]
So I saw this error a few times on my console, later came to realize it only comes up when I run /reload but thought i’d report it anyways 

“
>WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by ch.njol.skript.Skript$4 (file:/Users/Shane/Desktop/Server/plugins/Skript.jar) to field java.lang.reflect.Field.modifiers
WARNING: Please consider reporting this to the maintainers of ch.njol.skript.Skript$4
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
“

**Comment by HYPExMon5ter** [comment]
Simple fix: don’t reload. It’s not good for your server, restart it instead.

**Comment by ShaneBolenback** [comment]
Duly noted, thanks!

**Comment by TheBentoBox** [comment]
Yeah, issues that only come up when using `/reload` aren't relevant. Skript is not made to survive a `/reload` so anything that happens afterwards is unsupported.

**Comment by Syst3ms** [comment]
Not only unsupported, but also totally undefined. C/C++ developers know what that implies.
