### ISSUE TITLE
Toggle %block% don't work with all blocks

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#114]
Hey, I tried to use this effect:
```Java
(close|turn off|de[-]activate) %blocks%
(toggle|switch) [[the] state of] %blocks%
(open|turn on|activate) %blocks%
```
But none of this works with:

New doors and fence doors of 1.8, Iron trapdoor, redstone lamp, sticky and non-sticky piston, TNT, Redtone torch, tripwire hook, gold and iron pressure plate, daylight sensor, redstone comparator and redstone repeater.

*Random suggestion for don't create other issue* :+1:

- Add support to furnace inventory in the open inventory effect

**Comment by bensku** [comment]
Very well, this _should_ be easy to fix now when I have time to work on Skript again.

**Comment by bensku** [comment]
Ok, I fixed the doors. Other things are more complicated; for example, redstone lamp doesn't use block states, but instead has different ids for on/off states.

**Comment by bensku** [comment]
In the end, I had to remove support for redstone lamps, as setting the block changed nothing - if there is no redstone power, lamp will stay dark.
