### ISSUE TITLE
Bring variables into options

### ISSUE THREAD

**Issue by Padlick** [bensku/Skript#1140]
Hey. It would be very nice if something like this

`options:`
`>test.1: 20`
`>test.2: 40`
`command /test <number>:`
`>trigger:`
`>>message "{@test.%arg%}"`

is going to work in the future. Because when I try my code there is this error:
"undefined option {@test.%arg%}"

It should, if I type 1 as a argument, print the data of the option test.1 out..``

**Comment by Nicofisi** [comment]
Hmmm, I wrote this and then realised this issue is about the other thing, variables in option names not options in variable names, just leaving it here in case someone misunderstands too lol
```
>sk reload test
[19:52:31 INFO]: [Skript] Reloading test.sk...
[19:52:31 INFO]: [Skript] Successfully reloaded test.sk.
```
```
options:
  test.1: 20
  test.2: 40
command /test <number>:
  trigger:
    message "{{@test.1}.%arg%}"
```

**Comment by Nicofisi** [comment]
To be fair I don't think it has a big chance of getting implemented, it would be easy to confuse with the syntax above IMO and not very popular probably, but who knows ;)

**Comment by bensku** [comment]
It is intended that options are replaced *before* script is parsed. This allows you to for example
```
options:
    foo: broadcast "Foo"

on right click:
    {@foo} # Executes broadcast "Foo"
```

If you need variables, use variables, not options. In case current variables block in scripts is not good enough, it would be better to improve that instead of touching options.
