### ISSUE TITLE
Some events aren't detected at all

### ISSUE THREAD

**Issue by Eryk1983S** [bensku/Skript#1141]
**Engine:** Spigot 1.12.2.-R.0.1-SNAPSHOT
**Skript-Version:** 2.2. dev33, 2.2. dev34

**Problem:**
The following events don't trigger any effects at all:
- on click (leftclick, rightclick too), when you target a mob
- on tame
- on pick up

**Description of my trials, that confirm the bug:**
Simple script:
_on leftclick:_
     _send "Control-message - LMB"_

_on rightclick:
     send "Control-message - RMB"_

_on tame:
     send "Control-message - taming"
     cancel event_

_on pickup:
     send "Control-message - pickup"
     cancel event_

**Results of the trials:**
1. Left- or rightclick on blocks or even on the air returns the correct control message. When I target a mob, the message don't appear. Even if I hit the mob with the leftclick, the mob gets hurts, but there's no control message. It seems, that the mobs aren't handled like the air, but somehow the click-event doesn't launch the effect.

2. I tamed an ocelot and a horse. I saw the hearts and message, that I made an advance. But there was neighter control-message from the above script nor the event was cancelled.

3. I dropped different items on the ground and picked it up again - without control message and the item wasn't taken from me. The sam was, as I picked up the items, that were dropped (I didn't drop them by myself, but e.g. they dropped after block-breaking).

Please fix it or tell me, what was the latest version, that hasn't that bug and is compatible with 1.12. (or at least with 1.11.). Thanks in advance

**Comment by TheBentoBox** [comment]
1. You shouldn't use `left click` to detect the player clicking on an entity, that's what the damage event is for.
2. The `send` effect can't always detect which entity you want to send stuff to in an event involving multiple entities; I think it defaults to sending to `event-entity`, but that's not always the player. In the tame and pickup events, it's trying to send the message to the tamed entity or picked up item, respectively. Just add `to the player` to the end of your send effects -- this is why it's always good to be explicit :)

Both of these "issues" have been the case for a while IIRC, and while the second one could possibly be considered an enhancement (making the `send` effect better at detecting the player in the event), that's a very debatable point and I believe we have another old issue open addressing that regardless, so I'm going to close this for now. Feel free (this goes for anyone) to reply refuting me or extrapolating on these issues and I'd be happy to reopen.
