### ISSUE TITLE
Skript[dev43] not loading (1.12.2) 

### ISSUE THREAD

**Issue by AROD2003** [bensku/Skript#1143]
Here is the pastebin of the console error: https://pastebin.com/LR5WY6rH
Here is my skript if you are curious. It was just a basic one to make sure everything was working: https://pastebin.com/wkGzVsaq

I have been getting this error for the past few days, and I am not sure why it is not working. I have disabled all of my skript addons (Skellet, skRayfall, and SkQuery). The error still persists.

**Comment by Syst3ms** [comment]
Could you disable all of your addons, restart the server, and send the error log again ?

**Comment by AROD2003** [comment]
There wasn't an error when I did that. Could is possibly be that I'm not using SkQuery-Lime?

**Comment by HYPExMon5ter** [comment]
Yeah, try using limes fork of SkQuery

**Comment by AROD2003** [comment]
Alright. I'll try that and let you know what happens

**Comment by AROD2003** [comment]
Pretty much the same error: https://pastebin.com/fwH1TmB1

**Comment by HYPExMon5ter** [comment]
Contact lime, this isn’t a Skript issue.

**Comment by AROD2003** [comment]
Okay. Thanks for the help.
