### ISSUE TITLE
dev34 causes console errors

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1145]
Lots of console errors that have to do with item stack / items in variables:
https://hastebin.com/axalojiqom.vbs
Had to switch back to the old skript version which works just fine. 
Hope you can find and fix the bugs!

This server is running Paper version git-Paper-1266 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by Snow-Pyon** [comment]
Duplicate of #1138.
