### ISSUE TITLE
[suggestion] collision with projectiles

### ISSUE THREAD

**Issue by UzumakiYT** [bensku/Skript#1146]
will be cool to see an effect that disables/enable player's collision with projectiles

since there is no addon that does that.

**Comment by Pikachu920** [comment]
spigot doesnt have a method that does this (setCollidesWithEntities and setCollidable don't work well for this purpose or at all)

**Comment by bensku** [comment]
Cancelling projectile hit event should do the job. Might even be possible with current Skript features.

**Comment by UzumakiYT** [comment]
`[15:29:03 ERROR]: An on projectile hit event cannot be cancelled (test.sk, line 2: cancel event')`

**Comment by Pikachu920** [comment]
you cant cancel it, the best bet is deleting the arrow, spawning a new one behind the victim and giving it the same velocity

**Comment by UzumakiYT** [comment]
@Pikachu920 can you help me to do that, thank you in advance

**Comment by TheBentoBox** [comment]
I don't believe this to be possible with the Bukkit API so this should be taken off of the issues section since this is not the place for getting help with scripts, that's what the skUnity forums & Discord are for.

**Comment by UzumakiYT** [comment]
ok

**Comment by UzumakiYT** [comment]
p.spigot().setCollidesWithEntities(false); does the job, now it may get added.

**Comment by UzumakiYT** [comment]
also works on 1.8.

**Comment by Nicofisi** [comment]
> spigot doesnt have a method that does this **(*setCollidesWithEntities* and setCollidable don't work well for this purpose or at all)**
