### ISSUE TITLE
Add a warning when a VariableString contains only an expression that is already a String

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#1149]
Take this code:
```
command /fly <text>:
  trigger:
    if "%arg-1%" is "on":
      set player's flight mode to true
```
It's a common beginner mistake to surround arg-1 like this "%arg-1%" even though arg-1 is already a string. My proposal is to add a warning like "arg-1 is already a text, so there is no need to put it in a text" (hopefully someone can come up with something clearer).

**Comment by bensku** [comment]
It is valid syntax, not a mistake. Unnecessary, maybe.

**Comment by Pikachu920** [comment]
Isn't that the point of warnings? I mean, if you look at all the other things Skript has warnings for:

- Starting a variable with an expression

- Missing and/or in a list

- Variable conflict warnings

They are all valid syntaxes.

**Comment by TheBentoBox** [comment]
I agree with your reasoning; one thing I'll note is I've had times where a string comparison with a variable/expression didn't work until I forcibly parsed it as a string like that. Not sure if anyone else has had that problem or if it's even a vanilla Skript comparison issue but if it is then that should be fixed before this would be implemented. Though I guess there would be a config option for this like all other warnings so I guess it doesn't matter too much either way.

**Comment by Pikachu920** [comment]
that happens with a return type of Object, so it doesn't effect this issue

**Comment by bensku** [comment]
@Pikachu920 Thus this is an enhancement, not a bug.

**Comment by Pikachu920** [comment]
nobody ever called it a bug
