### ISSUE TITLE
The walk speed of loop-player can't have anything added to it

### ISSUE THREAD

**Issue by Jonni1** [bensku/Skript#115]
This worked couple of versions ago, but is not working anymore:
```
every second:
        loop all players:
                add 0.02 to walking speed of loop-player
```
The result now:
`the walk speed of loop-player can't have anything added to it`

**Comment by TheBentoBox** [comment]
As a temporary fix:

`set walk speed of player to (walk speed of player + 0.02)`

**Comment by bensku** [comment]
Fixed in next release. I rewrote speed expression, so it should be more reliable when updates are done elsewhere.
