### ISSUE TITLE
on any move

### ISSUE THREAD

**Issue by preterive** [bensku/Skript#1151]
Hello,
since the update, i don't can use "on any move" .
Does anybody have an idea, what i can use?

**Comment by Snow-Pyon** [comment]
That's an event of WildSkript (an addon you shouldn't be using either way), you're better off asking the addon's author about it.

Also, you may prefer use `on any movement` from skQuery or not use the event at all, it's called a ton of times and doing intensive stuff in it may cause a lot of lag to your server. That said, I'm closing this.
