### ISSUE TITLE
Bug When Sending 2 Messages Using Json

### ISSUE THREAD

**Issue by Bartuzen** [bensku/Skript#1153]
This  code works fine:
`send "<tooltip:test1>test1"
send "<tooltip:test2>test2"`
It shows json messages normal. But when I use it like this:
`send "<tooltip:test1>test1" and "<tooltip:test2>test2"`
Json doesn't work. It shows it as a normal message.

**Comment by Snow-Pyon** [comment]
Hopefully fixed for the next patch.
