### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by mat41997** [bensku/Skript#116]
logs
http://pastebin.com/jj41ykqC

**Comment by bensku** [comment]
What you're trying to do with Skript? Please post script source code, and list of all your Skript addons (and other plugins, if you want).

**Comment by mat41997** [comment]
https://www.spigotmc.org/resources/cchat-skript-1-7-1-10.5518/

no other addons

===

ok. i fix this problem, thx ^^

**Comment by bensku** [comment]
So, you got it working? Good. Please open new issue or reply here if something is still not working.
