### ISSUE TITLE
Condition "is not on ground" results with an error

### ISSUE THREAD

**Issue by Eryk1983S** [bensku/Skript#1164]
**Engine:** Spigot 1.12.2.-R.0.1-SNAPSHOT
**Skript-Version:** 2.2. dev34

**Problem:**
The manual (https://bensku.github.io/Skript/conditions.html#CondIsOnGround) suggests, that I can use a condition "player is not on ground", but then I get a message on the console after reloading of scripts:
_Can't compare a player with 'on ground' (SkriptName.sk, line 2: player is not on ground')_

**Possible solution:**
_on place:
	player is on ground:
	else:
		<your event>_

But if the manual suggests something, what doesn't work, I thought, that I'll report it.

**Comment by Snow-Pyon** [comment]
You can't, @bensku forgot to add negation support to that condition and accidentally used that as example. Should be possible for the next patch.

**Comment by Eryk1983S** [comment]
Thank you for - as always - fast answer. As I wrote, before you fix it, we can use conditionals to get the same results.
I wish all the best by your efforts on developing. Keep up the good work

**Comment by Snow-Pyon** [comment]
Fixed in dev35.
