### ISSUE TITLE
High timings

### ISSUE THREAD

**Issue by BBoyJD10** [bensku/Skript#1170]
https://gyazo.com/8714626756ebc804e6471d1927a0daf7

Getting lag coming from skript any chance of improvement?

**Comment by bensku** [comment]
Use Paper and Skript timings, need more information to figure out what is wrong.

Or better, profiling information from server. But I understand that is not as easy to get, especially if you don't run the server locally.

**Comment by BBoyJD10** [comment]
https://timings.aikar.co/?id=28b95fea26fc469eaa35b14962322dce

**Comment by bensku** [comment]
Script timings are still not enabled. And I'm not so sure Skript is the cause of lag. Maybe try without and see if it helps? If it does, I've got something to debug.

**Comment by BBoyJD10** [comment]
Yeah it doesnt occur without it

**Comment by bensku** [comment]
You do not have script timings enabled. Thus, it is not possible to say if your scripts might be causing the problem.

Note that (re)loading scripts is done in server main thread. Server startup with a lot of scripts will take some time. Please make sure you've been running the server for a while, not reloading scripts and take timings for a long period. If Skript is *still* an issue, it is a bug **or** your scripts have something wrong.

**Comment by TheBentoBox** [comment]
No response, invalid up to this point since script timings weren't enabled; all appears to be user error or misunderstanding. Closing.
