### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mikkelius** [bensku/Skript#1174]
Please fix this bug:

Skript version: 2.2
Server Version: 1.8 - 1.12 (Viaversion)
Spigot plugins: Only if requested

03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#! End of Error.
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#! Thread: Server thread
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#! Current item: null
03.04 21:54:04 [Server] ERROR #!#! Current node: null
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#! Running CraftBukkit: false
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
03.04 21:54:04 [Server] ERROR #!#!   Java: 1.8.0_151 (Java HotSpot(TM) 64-Bit Server VM 25.151-b12)
03.04 21:54:04 [Server] ERROR #!#!   Minecraft: 1.8.8
03.04 21:54:04 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT
03.04 21:54:04 [Server] ERROR #!#!   Skript: 2.2-Fixes-V8b
03.04 21:54:04 [Server] ERROR #!#! Version Information:
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
03.04 21:54:04 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03.04 21:54:04 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
03.04 21:54:04 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
03.04 21:54:04 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
03.04 21:54:04 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
03.04 21:54:04 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
03.04 21:54:04 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:154)
03.04 21:54:04 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:603)
03.04 21:54:04 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:609)
03.04 21:54:04 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:237)
03.04 21:54:04 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:193)
03.04 21:54:04 [Server] ERROR #!#! java.lang.NullPointerException
03.04 21:54:04 [Server] ERROR #!#! Stack trace:
03.04 21:54:04 [Server] ERROR #!#! 
03.04 21:54:04 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
03.04 21:54:04 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
03.04 21:54:04 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
03.04 21:54:04 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
03.04 21:54:04 [Server] ERROR #!#! and check whether this error has already been reported.
03.04 21:54:04 [Server] ERROR #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
03.04 21:54:04 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.

**Comment by TheBentoBox** [comment]
Please [upgrade your Skript](https://github.com/bensku/Skript/releases).

**Comment by Mikkelius** [comment]
Download link?

**Comment by Mikkelius** [comment]
I have updated skript but is says

03.04 22:06:22 [Server] WARN [Skript] Also, there are probably bugs. And since 1.8 is not supported, they will not be fixed
03.04 22:06:22 [Server] WARN [Skript] Some features have been disabled; use older Skript to restore them.
03.04 22:06:22 [Server] WARN [Skript] Using this version of Skript on 1.8 is highly discouraged.

And im running an 1.8 server!

**Comment by TheBentoBox** [comment]
Does it work, though? Those are just warnings, I don't see any errors or anything worrisome yet. If you need to downgrade, though, we can't help you. You **must** be using the latest version of Skript from that page I linked if you want to ask for help, otherwise this is not the place to ask. Issues with old versions of Skript (like the one you were using) are completely irrelevant to this fork.

**Comment by Mikkelius** [comment]
Every time i reload a Skript it says Reload Complete. also if there are bugs in it and the commands in the skript, i can't use them!

**Comment by TheBentoBox** [comment]
> Every time i reload a Skript it says Reload Complete. 

Isn't that normal? I fail to see the issue.

> also if there are bugs in it and the commands in the skript, i can't use them!

I'm not sure what you're saying here either. If there are bugs in your scripts then you need to fix them yourself. If there are bugs with Skript itself _while using the latest version_, feel free to report them in a new issue.

**Comment by bensku** [comment]
We do not support 1.8. If it works, that is nice. If it does not, you will have to look elsewhere for help. SkUnity forums and Discord, most likely.

**Comment by Mikkelius** [comment]
Okay bensku thank you!
