### ISSUE TITLE
[Suggestion] Make ability to edit <none> message

### ISSUE THREAD

**Issue by Govindass** [bensku/Skript#1181]
Make ability to edit <none> message, this would help to reduce code for when you are trying to change <none> with local variables xD

**Comment by Snow-Pyon** [comment]
This is already possible. Just change it in the English.lang:
https://github.com/bensku/Skript/blob/62621bc5102102f4ad5102b035f6676991dada59/src/main/resources/lang/english.lang#L18

**Comment by Govindass** [comment]
thanks a lot, didn't know about that, time to rewrite my scripts xD
