### ISSUE TITLE
Urgent help please

### ISSUE THREAD

**Issue by Sitieno14** [bensku/Skript#1191]
Isn't a skript issue, but please help me @bensku, @TheBentoBox 
I accidentally removed a part of code from a skript that actually is actived without the removed part,
Is there a way so that I can get code from actually actived skript that doesn't have the part removed?
Thanks in advance,
Please answer soon
Sitieno14

If it can help I have plugman, spigot 1.12.2 and latest version of skript dev34
I have the following skript addons:
- SkUniversal
- SkQuery
- Skellet
- skUtilities
- SkAction
- SharpSK
- skRayFall
- Tuske
- WildSkript

**Comment by HYPExMon5ter** [comment]
This isn’t the place to ask for help, ask on the forums or in one of the Skript discords

**Comment by Sitieno14** [comment]
Which are skript discords?

**Comment by Nicofisi** [comment]
https://discord.gg/UFHq2X - skUnity
https://discord.gg/V4qFVnh - Skript Chat
