### ISSUE TITLE
Dispenser direction

### ISSUE THREAD

**Issue by Corkick** [bensku/Skript#1192]
Skript version : 2.2 
Server version : 1.8.8 Spigot

Hello, i have a problem with this line :

`set the block south of event-block to dispenser:3`

The dispenser arises, but the direction I want to give it (north), does not work.
I have another line on the bottom orientation, which works:

`set the block above the event-block to dispenser:6`
If anyone has a solution to force the orientation of the dispenser, I am a taker.

Thank you.
(PS : Sorry for my bad english)

**Comment by TheBentoBox** [comment]
Which version of Skript 2.2 are you using? Are you using the latest one from this repository ([found here](https://github.com/bensku/Skript/releases))? You need to be using the latest version from that page to report issues here.

**Comment by Corkick** [comment]
Hi, i don't use dev Skript, I didn't know that dev version is needed for report issues, sorry. 
Do you know where I could get help ?

**Comment by Syst3ms** [comment]
Well, they're called "dev" because they aren't official nor guaranteed to be stable. But these are the most up-to-date versions you can find in general, not some experimental dev-only releases. You need the latest release to report a bug.

**Comment by TheBentoBox** [comment]
Yeah, please make sure to use the dev builds in the future when you want to report a bug! 

Also, you could just be using the wrong data value; on [the wiki](https://minecraft.gamepedia.com/Dispenser#Block_data), it looks like you should be using 2 for north, not 3.

**Comment by Corkick** [comment]
No problem, but i want that dispenser has direction south when he was placed in north so it's 3.
