### ISSUE TITLE
Lists not working in event paramaters

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#1196]
Spigot 1.12.2
Skript 2.2-dev35

> [07:12:00] [Server thread/ERROR]: [Skript] can't understand this event: 'on rightclick on a chest or a trapped chest' ...
> [07:12:00] [Server thread/ERROR]: [Skript] can't understand this event: 'on leftclick on a chest or a trapped chest' ...

did not parse. It did parse (and execute correctly) prior to dev35. What is the correct syntax?

**Comment by bensku** [comment]
If it worked before, it should work now. This sounds like a bug, though not 100% sure.

**Comment by SlimeDog** [comment]
Thanks for quick response. Easy to workaround, for now.

**Comment by UzumakiYT** [comment]
on right click on <block>, on right click with <item> does not work.

**Comment by SlimeDog** [comment]
My testing shows that
> on rightclick on ...
> on right click on ...

both work fine, unless there is an **_or_** involved.

**Comment by melinstagibson** [comment]
broke this stuff for me aswell, what i have:
```
if player's tool is enchanted with unbreaking 10, fortune 10 or efficiency 10:

[09:37:11 ERROR]: Can't compare a slot with ('enchanted with unbreaking 10' and 'fortune 10') (voterstuff.sk, line 89: if player's tool is enchanted with unbreaking 10 and fortune 10:')
```
tried with and aswell, same error, even if i only use one and/or

**Comment by bensku** [comment]
It appears that this bug affects more than just event values. It is a side effect of a fix for another list parsing bug.
