### ISSUE TITLE
Spam messages on skript reload

### ISSUE THREAD

**Issue by Weefle** [bensku/Skript#1198]
Just look at this image.
![image](https://user-images.githubusercontent.com/18496043/39016598-38a2f6fc-4421-11e8-81b2-e2f7cd29c6da.png)

**Comment by Snow-Pyon** [comment]
It isn't spam, it is just the new warning telling you that you're pointlessly converting a string to a string. For example:
```
send "%free space on disk%" to player
```
should be:
```
send free space on disk to player
```
since the `free space on disk` expression returns a string and there is no need to convert it to a something that it already is.
