### ISSUE TITLE
Teleporting between worlds gives an error

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#12]
When teleporting between two separate worlds, a stack trace appears in console saying "cannot measure distance between worlds". I think it's because of the changes in [this commit](https://github.com/bensku/Skript/commit/334555cbb0a87a91f4fd88c76904021f1fedb59c). Particularly this line:

`if (to.equals(from) || to.distanceSquared(from) < 2)`

I don't write plugins, but looking at the Bukkit API, it looks like you'd want to change that whole section to:

```
if (to.equals(from))  
	return;
else if (to.getWorld() == from.getWorld())
	if (to.distanceSquared(from) < 2)
		return;
````

[Stacktrace](http://pastebin.com/SaxiQbwb).

**Comment by bensku** [comment]
Uh... Didn't consider that, but you're right. Sadly I found this issue just after stopping coding for today; fix will come tomorrow.

**Comment by TheBentoBox** [comment]
Nice, sounds ok. Just to let you know, it turns out this bug does have a side effect - it breaks portals, people can't get to the Nether at all. I assume the End portals won't work as well, but I'll chekc and report back here.

**Comment by TheBentoBox** [comment]
Turns out end portals still work, it's just Nether portals that don't. Both send an error to console of course (as any teleport or teleport attempt does), but it's just Nether portals that break entirely.

**Comment by bensku** [comment]
Should be fixed in next release.
