### ISSUE TITLE
Erroneous string form of slot objects in dev35

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#1200]
PaperSpigot 1.12.2
Skript 2.2-dev35

```vb
send "%player's tool%"
```
Returns **`the <item name>`** (eg. the stone), there shoudn't be "the". There isn't already on dev34.

---
```vb
send "%player's helmet%"
```
Returns **`the helmet of <player name>`**, but it returns the item name in dev34, also if there is no helmet returns **`<none>`** in dev34.

Same thing for other armor slots or entities, returns "the leggings of villager" for example.

---
```vb
send "%slot 0 of targeted block%"
#the block is a chest
```
Returns: **``inventory slot 0 of org.bukkit.craftbukkit.v1_12_R1.block.CraftChest@idhere``**

If the inventory holder is an entity, works like armor slots as i explained above ^^ (eg. inventory slot 1 of llama)

---
Someone else encountered the first problem and i confirmed it.
Also an expression to get item in/of a slot should be added.

**Comment by bensku** [comment]
Refer to #1221 for fixing container-to-string. It is not a new issue, and is also not nearly as severe as other issues listed here were.
