### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by TheIntelloBox** [bensku/Skript#1206]
https://hastebin.com/ozukukawac.vbs

**Comment by Snow-Pyon** [comment]
Please be more specific when you have a problem. What version of Skript are you using? Minecraft/Server version? How do you reproduce the error? Which addons are you

**Comment by TheIntelloBox** [comment]
Skript v2.2-dev32d on Paper Spigot 1.12.2.

I have this error when I do /sk reload all.
I have two one skript : https://hastebin.com/gawagadedu.bash

**Comment by Snow-Pyon** [comment]
1. Use the latest version when reporting errors, it'll be invalid otherwise.
2. The problem is (probably) caused by PerWorldPlugins, nothing we can do about it if that's the case.
3. If you loaded Skript or an addon with PWP, it'll surely error, it is the same as using the `/reload` command.
