### ISSUE TITLE
Variable in a function doesn't work

### ISSUE THREAD

**Issue by uiytt** [bensku/Skript#1209]
Skript version: dev35
Addons : SkQuery, Skellett and Tuske
Hi,
I have a very strange problem...
When I try [this](https://pastebin.com/RAEqHDC7)
Everything works without any problem
but when i try [this](https://pastebin.com/0E4rSs32)
Skript sends me that i only gave 1 argument...

I also tried to add `execute functions with missing parameters: false` in the config.sk but it still doesn't work...
Can you help me please ?

**Comment by Snow-Pyon** [comment]
Could you show us the function?

**Comment by uiytt** [comment]
Thank you, it's working ^^
Sorry to have bothered you.

**Comment by TheBentoBox** [comment]
Close, I guess? This is sort of a parsing issue but I'm pretty sure there are multiple issues open related to list parsing so...
