### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#1212]
A config option to disable the "already a string" warnings.

**Comment by Pikachu920** [comment]
i understand it may be annoying, but why not fix the code instead of suppressing it

**Comment by HYPExMon5ter** [comment]
Was already going to, but for people that are to lazy to fix their code, it’d be a good feature

**Comment by Snow-Pyon** [comment]
As Pikachu said, fix your code instead of suppressing it, this is one of the warnings I want people to listen so I won't add an option to disable it, at least not in a while.

**Comment by HYPExMon5ter** [comment]
Fair enough.
