### ISSUE TITLE
Calculation bug

### ISSUE THREAD

**Issue by ThunderGaren** [bensku/Skript#1218]
After the **FIRST** calculation, the next one will ignore the first variable.
For example:
`set {_a} to 50`
`set {_b} to 20`
`set {_c} to {_a} - {_b}`
`set {_d} to {_a} - {_c}`
Normally, {_c} is 30 and {_d} is 20 after the calculation, but it shows {_c} is 30 and {_d} is -30. It ignored the first variable on the second formula.
 
Orignial code:
https://hastebin.com/saloyonete.vbs

**Comment by Snow-Pyon** [comment]
Couldn't reproduce with the code provided above (haven't tested the original code). Are you sure this isn't a bug with your script rather than Skript itself ignoring it?

**Comment by ThunderGaren** [comment]
It said its fine when I reload the skript.
Also I made a better code for you. Try this if it works, thx!!

Original Code (Ver2):
[https://hastebin.com/yukavojida.sql](url)

**Comment by TheBentoBox** [comment]
I think this had to be user error, especially since -30 is a potential result with the two variables provided (`{_b} - {_a}`). If basic math like this wasn't working properly there would be more reports and nothing would be working.
