### ISSUE TITLE
parsing something as an item makes it <none>

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#1227]
Minecraft Version: 1.12.2
Skript Version: dev35b
```
set {defaultKitIcon} to birch wood

command /works:
     trigger:
        set {_icon} to {defaultKitIcon} # broadcasts birch wood
        broadcast "%{_icon}%"

command /bug:
    trigger:
        set {_icon} to ({defaultKitIcon} parsed as an item) # broadcasts <none>
        broadcast "%{_icon}%"
```

**Comment by Snow-Pyon** [comment]
The parse expression isn't meant to be used with items but strings. It works just because Skript can't resolve the type of the variable when parsing it so that result is the expected one.

**Comment by HYPExMon5ter** [comment]
Right, but because of #1138 I have to parse the variable in order to use it in a GUI or something
