### ISSUE TITLE
Request: Name of inventory & more inventory stuff

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#123]
Would like to retrieve the name of a player's current inventory. Would like to see more inventory functions / events. e.g. on inventory open/close, name of inventory etc.

**Comment by bensku** [comment]
Very well... This should be relatively easy. Also setting inventory names of chests is (probably) possible.

This might be something I have time to do myself, but not for next release.

**Comment by bloggy** [comment]
Thanks. Also it would be cool if you could enable to cancel the "on inventory close" event to force players not closing an inventory.

**Comment by JKGamerxD** [comment]
You can't cancel the `o inventory close` event, the [InventoryCloseEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryCloseEvent.html) just the client notifying the server that the inventory is being closed.

**Comment by bensku** [comment]
@JKGamerxD It would require Skript to store data each time player closes inventory, even if no script actually uses data by expression. Probably no.

**Comment by xXAndrew28Xx** [comment]
I would't mind doing a PR to add it. Should I add "player's current inventory" too?

**Comment by xXAndrew28Xx** [comment]
@JKGamerxD :O https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryEvent.html#transaction

**Comment by JKGamerxD** [comment]
What is that @xXAndrew28Xx ?)

**Comment by xXAndrew28Xx** [comment]
InventoryView, might be able to "cancel it" by opening it back to them

**Comment by JKGamerxD** [comment]
Aaah. So with this, maybe you can re-open the inventory? Cool if you can :+1:
