### ISSUE TITLE
parsing text does not seem to work

### ISSUE THREAD

**Issue by Wqrld** [bensku/Skript#1231]
things like
`set {_onlyregion::*} to "%loop-value%" parsed as "%string% in world %string%"`
give the error 
`[15:20:01 ERROR]: {_onlyregion::*} can't be set to '"%loop-value%" parsed as "%string% in world %string%"' because the latter is not an object (mappaster.sk, line 598: set {_onlyregion::*} to "%loop-value%" parsed as "%string% in world %string%"')`
on dev34

**Comment by Blueyescat** [comment]
You can fix it using parentheses: **`("%loop-value%")`**

But still the parse expression needs some rework..

**Comment by Wqrld** [comment]
this was my fault, brackets didn't help but after rewriting the whole thing it worked for some reason.

**Comment by Blueyescat** [comment]
Well it doesn't give that error for me if use brackets, otherwise it does.
