### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by LoXR** [bensku/Skript#1236]
Unsure what has happend but im getting this error when I click on a compass :https://pastebin.com/Mgf4JKP0

All I had changed was to turn off keep spawn in memory in Multiverse, and changed three spigot.yml options, 
stats:
disable-saving: true

advancements:
disable-saving: true

save-structure-info: false

**Comment by TheLimeGlass** [comment]
Can you provide your script code, also try the latest version of Skript which is ` dev35b` https://github.com/bensku/Skript/releases

**Comment by LoXR** [comment]
It had been all fixed, got the hosts to rollback to a 2 day backup.
