### ISSUE TITLE
Does not actually load any scripts

### ISSUE THREAD

**Issue by thejimmyj57** [bensku/Skript#124]
So I added the latest version of your skript to my 1.10 server along with other 1.10 dependencies for Umbaska and SkRayFall. When I reload a script it says it is successful but it does not actually load in the script. The script I wrote is about 5500 lines long so the "initing change" thing on reloading is quite annoying. I am not sure if that part is necessary or what not.

If you can fix this, it will be amazing. Thanks

https://gyazo.com/bcc47858fa0fbff51fedbb3c4b3024d4

**Comment by thejimmyj57** [comment]
**Correction. Some commands do still work. But very few. The others only come up as Unknown Command

**Comment by JKGamerxD** [comment]
Umbaska maybe don't work in the latests versions. Try without Umbaska.

**Comment by thejimmyj57** [comment]
I will try, without Umbaska. But I am using Skript-dev15 currently and it would with the newest version of Umbaska on 1.10 and 1.10.2

**Comment by bensku** [comment]
I need to see console! This "no scripts are loaded" error has happened for me when I have debugged some parser code. It basically appears when parses crashes... Which has not happened for me, ever, when using release Skript build.

It _might_ be caused by addon incompatibility, but there are other possible causes also. Please post console log. If it is indeed caused by some addons, then I'll try to fix it myself or contact addon authors.

**Comment by TheBentoBox** [comment]
Also, you said you were using the newest version, but you just said now you're using dev15, which is not the newest version. We're up to dev18 now, dev15 was the 1.9.4 update. I don't think that's necessarily causing your issue, but you'll want to update to dev18.

**Comment by thejimmyj57** [comment]
Alright I did some more testing, and the latest version of Skript you released seems not to run with the latest version of Umbaska for whatever reason. There are no errors in console, It just either works or doesn't when Umbaska is there or removed. 

http://pastebin.com/FRmWZTeZ

You can see Umbaska through errors here and in the end not load the skript. Any fix that can be made for this would be greatly appreciated. To TheBentoBox's point, I meant that the Version of Umbaska I was using is compatible with Skript-dev15 that I was using previous to downloading the newest update. And that version of Umbaska works on 1.10 and 1.10.2 without issues when paired with Skript-dev15.

Also just as another point, is there a way to get rid of the "initing change," messages spamming console and in-game when skripts are reloaded? Thanks

**Comment by TheLimeGlass** [comment]
I got the same issue, but without any addons.

I tried to load the 1.10 skript edit and nothing works. I was running a 1.9 server which is most likely my case behind why it didn't work, but I gave up and went back to nfell's edt as I couldn't have a server without my scripts.

**Comment by bensku** [comment]
Old stuff here. Fixed months ago.
