### ISSUE TITLE
Skript's "minute/second/hour from date %date%" expression 

### ISSUE THREAD

**Issue by Guarmanda** [bensku/Skript#1245]
I don't speak about skutilities expression. I don't know since when, but skript has its own expression for that, and it's totally broken. 
for example, this code
```
command /test:
	trigger:
		message "seconds from date now: %seconds from date now%"
		message "minutes from date now: %minutes from date now%"
		message "hours from date now: %hours from date now%"
		message "day from date now: %day of week from date now%"
```
returns this
https://image.ibb.co/hPZMdn/Capture.png

**Comment by Pikachu920** [comment]
this expression is not form skript

**Comment by Guarmanda** [comment]
Then how could it loads without any errors?

**Comment by Snow-Pyon** [comment]
As said, this is not from Skript.
