### ISSUE TITLE
Shuffling list not working as it should

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#1249]
`set {_list::*} to shuffled ({test::*})`
Result:
1st list: original
2nd list: shuffled
https://i.imgur.com/9NNXQTN.png

version: v2.2-dev32d

**Comment by Blueyescat** [comment]
Fixed in [dev34](https://github.com/bensku/Skript/releases/tag/dev34), but use [dev35b](https://github.com/bensku/Skript/releases/tag/dev35b).

**Comment by TheBentoBox** [comment]
Cheers @Blueyescat, deleting my first comment since it's not relevant 😂
