### ISSUE TITLE
Parsed as "%integer%%% of Slowing" Not working correctly.

### ISSUE THREAD

**Issue by Klyser8** [bensku/Skript#1255]
Hello everyone, while I was working on a script I noticed while writing a line of code, that something was not working. 

```
on damage:
	if attacker is a player:
		set {_split::*} to lore of attacker's tool split at "||"
		loop {_split::*}:
			if loop-value contains "Damage":
				set {_dmg::*} to uncolored loop-value parsed as "Damage: %integer%-%integer%"
				loop {_dmg::*}:
					#broadcast "&6%random integer between %{_dmg::1}% and %{_dmg::2}%%"
					if loop-value-2 is an integer:
						#broadcast random integer between {_dmg::1} * 0.5 and {_dmg::2} * 0.5
						set damage to random integer between {_dmg::1} *0.5 and {_dmg::2} * 0.5
			
			if loop-value contains "Slowing":
				set {_slow::*} to uncolored loop-value parsed as "%integer%%% of Slowing"
				broadcast "integer%% of Slowing"
				loop {_slow::*}:
					if loop-value-2 is an integer:
						broadcast "eh"
						set victim's walking speed to victim's walking speed * 0.25
```

The line of code which is having issue is this one: `set {_slow::*} to uncolored loop-value parsed as "%integer%%% of Slowing"`

The error that skript gives when reloading the script is as follows: `Invalid pattern: the type " could not be found. Please check your spelling or escape the percent signs if you want to match literal %s: "\%not an expression\%"`

I asked for help on the discord chat, but nobody managed to find a solution to that problem, but people there told me that it's a bug after trying to solve it themselves. No errors were in the console, and the addons I have are as follow: Skript, Skript Mirror, skUtilities, skUniversal, skRPG-LIME, skRayFall, TuSKe, SharpSK and MundoSK.

**Comment by Pikachu920** [comment]
this isn't a bug, the error tells you exactly what to do to fix it

**Comment by Syst3ms** [comment]
Hmm, I asked him to file this report over at skUnity, as it didn't work when I tried it. Oh well.
