### ISSUE TITLE
Potential for MCJukebox support natively?

### ISSUE THREAD

**Issue by oliverdunk** [bensku/Skript#126]
Perhaps https://www.spigotmc.org/resources/mcjukebox.16024/ could be supported? The plugin has an API and I think it'd expand the capabilities greatly.

**Comment by JKGamerxD** [comment]
It's already supported by Umbaska, and I'm pretty sure @bensku don't want more problems with Umbaska.

**Comment by oliverdunk** [comment]
Really, do you have a link to where this is documented? I apologise if it is, I just had no idea :-)

**Comment by JKGamerxD** [comment]
https://umbaska.gatt.space/documentation?searchname=JukeboxAPI

**Comment by oliverdunk** [comment]
Thanks :-)
