### ISSUE TITLE
Offline Permissions bug

### ISSUE THREAD

**Issue by JordyEGNL** [bensku/Skript#1264]
I can't use permissions in my Skript if the player is offline.

**Comment by HYPExMon5ter** [comment]
That’s not a bug. Store the players permission in a list variable on leave and use those list variables to check permission. This can be closed now.

**Comment by JordyEGNL** [comment]
How?

**Comment by HYPExMon5ter** [comment]
This isn’t the place to ask for help, that’s the the forums and various Skript discords are for.
