### ISSUE TITLE
Potions are still a bit buggy

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#13]
**Skript version:**
dev6b

**The Issue:**

1) Take potion of fire resistance in hand

```
on player consuming:
  broadcast " DEBUG: %tool of player%"
```

**The output:**
" DEBUG: bottle of water"

Which it isn't really. This means that there is - for now - no way of detecting whether the player has any (magical) potion in hand or just plain old water bottle.

**Comment by Pilvinen** [comment]
It also seems that lingering and exploding potions are missing from the syntax.

**Comment by Pilvinen** [comment]
Also:
```
on player consuming:
  event-item is potion or milk bucket or melon slice
```

When the event item is a water bottle with nbt tag "**{Potion:"minecraft:water"}**" results in:
http://pastie.org/private/3qkco51k2y7nswdtsuwa

When the event item, water bottle, has no NBT tag there is no error.

**Comment by bensku** [comment]
Actually, this is rather hard to solve... I'm not sure if I can get this fixed today.

**Comment by bensku** [comment]
Partially fixed.

**Comment by Pilvinen** [comment]
Let's try this one more time:
```
on player consuming:
  event-item is potion or milk bucket or water bottle
```

1) potion = should be everything that is in a bottle except xp bottle, ie. all magic potions, water bottles, ...

At the moment potion seems to be equal ONLY to water bottle. So tell me, HOW do I recognize whether or not the event-item or tool of player is in fact any kind of potion or not? Or is this an aliases problem that I'm having? What kind of changes do I need to make to aliases - if any?

2) The water bottle should be equal to potion of water, ie. potion with NBT <none> or {Potion:"minecraft:water"}, both. This part of it seems to be working exactly like that at the moment, right?

3) Recognizing magic potions with the new syntax is now working, right? (You seriously need to start making better, more complete, change logs)

**Comment by TheBentoBox** [comment]
It's not an aliases issue, Pilv. Aliases only work with IDs and damage values. Potions now use NBT tags, as you've said, so it can't be fixed with aliases.

**Comment by Pilvinen** [comment]
I spoke with bensku about it and he told me that for a proper fix it's going to require hauling over the item system (~1 week of coding) but he will probably release a bubble gum patch for it this evening which should get us over this issue until the he starts working on the item system.

**Comment by bensku** [comment]
String representation is still buggy, but otherwise fully fixed in next release.

**Comment by Pilvinen** [comment]
Almost fixed now but it seems the handling of amounts is broken.

Example:
```
remove 1 water bottle from inventory of player
```

**Comment by bensku** [comment]
Allright, this was fixed long ago.
