### ISSUE TITLE
Does not support MC 1.8 r3

### ISSUE THREAD

**Issue by kh498** [bensku/Skript#132]
When enabling:

> [02:31:47 INFO]: [Skript] Enabling Skript v2.2-dev18
> [02:31:47 ERROR]: Error occurred while enabling Skript v2.2-dev18 (Is it up to date?)
> java.lang.NoSuchFieldError: ICE_FLATS
>         at ch.njol.skript.bukkitutil.BiomeMappings$To19Mapping.<clinit>(BiomeMappings.java:55) ~[?:?]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.Class.getEnumConstantsShared(Unknown Source) ~[?:1.8.0_91]
>         at java.lang.Class.getEnumConstants(Unknown Source) ~[?:1.8.0_91]
>         at ch.njol.skript.util.EnumUtils.<init>(EnumUtils.java:50) ~[?:?]
>         at ch.njol.skript.bukkitutil.BiomeMappings.<clinit>(BiomeMappings.java:37) ~[?:?]
>         at ch.njol.skript.util.BiomeUtils.getAllNames(BiomeUtils.java:44) ~[?:?]
>         at ch.njol.skript.classes.data.BukkitClasses.<clinit>(BukkitClasses.java:895) ~[?:?]
>         at ch.njol.skript.Skript.onEnable(Skript.java:277) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by JKGamerxD** [comment]
This version is for 1.9+, if you need use this version on 1.8.8 run an older version or use the Mirreski's fixes. Because the 1.8 on this Skript fork, is unsupported.

**Comment by kh498** [comment]
oh :/
