### ISSUE TITLE
New feature: inherent support for "final damage" expression in damage events

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#135]
The [EntityDamageEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.html) has a getter method to get the final damage after all damage reduction, as `event.getFinalDamage()`. This is supported in RandomSK, but it hasn't been updated and doesn't even run on versions newer than 1.8 without being run through the SpecialSource fix. This is causing issues for a lot of unexperienced players who don't know how to run SpecialSource, and it would be an ideal expression to move straight into vanilla Skript.

**Comment by JKGamerxD** [comment]
You can use:
```Java
last damage cause of %livingentities%
```
It's already from the dev10

Or:
```
last damage %living entity%|
%living entity%'[s] last damage

last damage cause of %living entity%
%living entity%'[s] last damage cause
```
From TuSKe

**Comment by bensku** [comment]
Not bad idea, if it is simple to add.
