### ISSUE TITLE
Missing Mending Enchantment

### ISSUE THREAD

**Issue by googleoblivion** [bensku/Skript#138]
Currently Skript doesn't understand what you're asking it to do for anything about mending enchantment. The english.lang file is also missing the mending: Mending part under enchantments.

**Comment by JKGamerxD** [comment]
Confirmed, but for the moment, you can add this to the english.lang into the Skript.jar

**Comment by bensku** [comment]
Is it just simple "add-to-jar"? Hmm, probably will get to next release, whenever it will come.

**Comment by JKGamerxD** [comment]
Yeah, I added the mending enchantment to the list of enchantments in the .lang and it works flawless.
