### ISSUE TITLE
Console ERROR.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#139]
Exemple code:
```
command /install <number>:
    trigger:
        set {exemple.%player%.%arg-1%.loc}  
command /teleportation:
    trigger:
        teleportation(player, 0)
function teleportation(p: player, n: number):
    teleport {_p} to {exemple.%{_p}%.%{_n}%.loc}
```

> ```
> [15:14:11 INFO]: FUZIK issued server command: /teleportation
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! [Skript] Severe Error:
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
> [15:14:11 ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
> [15:14:11 ERROR]: #!#! and check whether this error has already been reported.
> [15:14:11 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
> [15:14:11 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
> [15:14:11 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
> [15:14:11 ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! Stack trace:
> [15:14:11 ERROR]: #!#! ch.njol.skript.SkriptAPIException: UnparsedLiterals must be converted before use
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.invalidAccessException(UnparsedLiteral.java:275)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.UnparsedLiteral.getArray(UnparsedLiteral.java:295)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:188)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:55)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)
> [15:14:11 ERROR]: #!#!     at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)
> [15:14:11 ERROR]: #!#!     at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
> [15:14:11 ERROR]: #!#!     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> [15:14:11 ERROR]: #!#!     at java.lang.reflect.Method.invoke(Unknown Source)
> [15:14:11 ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
> [15:14:11 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [15:14:11 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [15:14:11 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1343)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [15:14:11 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
> [15:14:11 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
> [15:14:11 ERROR]: #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
> [15:14:11 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! Version Information:
> [15:14:11 ERROR]: #!#!   Skript: 2.2-dev18
> [15:14:11 ERROR]: #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
> [15:14:11 ERROR]: #!#!   Minecraft: 1.10.2
> [15:14:11 ERROR]: #!#!   Java: 1.8.0_91 (Java HotSpot(TM) Client VM 25.91-b14)
> [15:14:11 ERROR]: #!#!   OS: Windows 10 x86 10.0
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! Running CraftBukkit: false
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! Current node: null
> [15:14:11 ERROR]: #!#! Current item: teleportation(the player, '0')
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! Thread: Server thread
> [15:14:11 ERROR]: #!#!
> [15:14:11 ERROR]: #!#! End of Error.
> [15:14:11 ERROR]: #!#!

> ```

**Comment by Nicofisi** [comment]
```
command /install <number>:
    trigger:
        set {exemple.%player%.%arg-1%.loc}  
```
Just set? Without any location or anything?

**Comment by FUZIK** [comment]
set the function above events.
functions need load first...

**Comment by Nicofisi** [comment]
gj
