### ISSUE TITLE
Killing boats & minecarts

### ISSUE THREAD

**Issue by Jonni1** [bensku/Skript#140]
Don't know if this is a bug or enchanment, but when I'm passenger of minecart or boat, I'm unable to kill it by `kill vehicle of me`. I'm able to kill horses and pigs tough.

**Comment by JKGamerxD** [comment]
Other mob you really can't kill is the Armor stand, if @bensku fix it, would be cool.

**Comment by bensku** [comment]
This might do the trick, but I'll need to test more. Probably going for next release.

**Comment by bensku** [comment]
Armor stands should work, but click events on them might be bugged.
