### ISSUE TITLE
PlayerInteractEvent

### ISSUE THREAD

**Issue by RuthlezDev** [bensku/Skript#141]
When interacting with a player it outputs every playerinteractevent in the entire skript instead of just the one specified.

"on right click on player with ice:"
    "code to freeze player"

https://gyazo.com/d32b2ae0ec203f6175e8a8b55cc42677

Freeze - Clicktest & inspect are all bound to different items.
When clicking with either of the items all tool functions run at once.
This issue does not occure in the original Skript version in 1.7-1.8

**Comment by bensku** [comment]
Click events are 100% more "interesting" to code in 1.9+ due to off hand being usable... This might be one of side effects.

**Comment by RuthlezDev** [comment]
You think you will be able to fix it in the near future?

**Comment by bensku** [comment]
No promises since thwre are lots of bugs and I have limited time. As I have said, I would need help with Skript to have guaranteed release dates.

**Comment by bensku** [comment]
Could you post some code for me to debug this?

**Comment by RuthlezDev** [comment]
You mean something like this?

```
on right click on player with stone:
    send "stone" to player
on right click on player with grass:
    send "grass" to player
```

in this case the messages **both** get sent on a click with either grass or stone on a player.

I've also noticed that when triggering a normal on click event (not a playerinteractevent).
It sets off all playerinteractevents when clicked **on a player** with the (on click of "item") item.

If you contact me privatly over skype (IMD.TM) I can send you the full code of my premium spigot skript that has this issue in 1.9-1.10 using your version :)

**Comment by bensku** [comment]
Oh, now I understane what you're trying to do. If it worked before, it should work now. Will take look at this when I have time.

**Comment by TheBentoBox** [comment]
@RuthlezDev Are you still having this issue?

**Comment by bensku** [comment]
No response from OP, closing.
