### ISSUE TITLE
[REQUEST] Clickable chat messages

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#142]
Hey there,
I don't know if it's difficult to achieve but would it be possible to get a new feature so that we can create clickable chat messages which then execute a command? I have seen this in some plugins and it's cool because instead of entering a command the user just clicks on a word within a chat message and a command gets executed.

**Comment by Pilvinen** [comment]
You can already do this with normal Minecraft vanilla functionality.

**Comment by JKGamerxD** [comment]
That's called json. Umbaska and SkQuery support it.
json.sk is an alternative or simply use the vanilla commands.

**Comment by Pilvinen** [comment]
When the vanilla json chat support first came out in vanilla Minecraft I implemented my chat by using Skript + the vanilla commands for the whole thing and I've yet to have any reason to complain about the performance. It's good.

**Comment by bensku** [comment]
JSON chat support would be nice and not-so-trivial to implement.

**Comment by psiber-on-uncovery** [comment]
https://www.minecraftjson.com/

will let you do all of this with no mods / addons using the vanilla /tellraw command

/tellraw @p ["",{"text":"asd","clickEvent":{"action":"run_command","value":"/skriptcommand"}}]

**Comment by bensku** [comment]
That is what you can do already. Click actions can be Skript commands.

It is just a bit clunky to write JSON inside scripts...

**Comment by bensku** [comment]
Did it myself, amount of bugs was even higher than I initially expected. I guess it was worth it.
