### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#144]
```
on mine of sunflower or lilac:
    send "sunflower"
    cancel event
    set block at event-location to stone
    set block above to stone
```

GIF -> vk.com/doc236535795_437735616

**Comment by bensku** [comment]
Private GIF... ? So, please explain what is wrong here.

**Comment by FUZIK** [comment]
Oh, sorry. -> https://drive.google.com/open?id=0BwoHMFwec-qHOVFRcm1VSS0waGM

**Comment by bensku** [comment]
Sunflower top part is different block. I'll have to think if abstracting this away would be good idea...

**Comment by bensku** [comment]
I will not do Skript-level abstraction for this. @tim740 would this be possible using aliases?

**Comment by TheBentoBox** [comment]
This is just an issue with how the data values work; all double tall plants use ID 175 data value 10 to represent their top block, and the way that block renders is determined by the lower block. If you want to do this in the future, you can just detect breaking of long grass, then check `if block 1 meter below event-block is sunflower` or something similar. Annoying, but not really a Skript issue.
