### ISSUE TITLE
Use Gradle instead of Maven

### ISSUE THREAD

**Issue by bensku** [bensku/Skript#145]
I have noticed many people complaining that setting up Skript development environment is too hard. I have also noticed that I'm personally unable to get it compile with my laptop...

So, I have started recreating Skript's build system. Eclipse will no longer be necessary for building, since I'm using ECJ from Gradle directly. Even for Eclipse users, building should be easier and less buggy.

This is work in progress currently. No ETA yet :)

**Comment by wysohn** [comment]
Love it

I tried to compile it yesterday and found that one of the maven repo was dead.

I had to download that dependency manually and set everything manually; what a pain.

I don't know what is Gradle but hopefully easier than maven

**Comment by bensku** [comment]
Apparently ECJ, even with settings loaded from Skript project files, doesn't compile correctly. There are few (2) errorsand thousands of warnings...

But good progress, considering that Gradle dependency loading is way more reliable.

**Comment by bensku** [comment]
[Compiling!](https://xkcd.com/303/)

But yeah, it compiles. Some minor issues with plugin.yml versioning etc, but dependencies are loaded and plugin jar is generated.

**Comment by Namnodorel** [comment]
I'm still unable to build it, but if it works for you thats good ;)

**Comment by bensku** [comment]
Huh... Very interesting.

Did you use Eclipse Gradle (STS) implementation? Other plugins might not be very good and of IDEA I don't know if it works at all (should, but didn't test).

**Comment by Namnodorel** [comment]
No, I use IDEA. Should I use Eclipse instead in order to build Skript? I like IDEA more because it has a way better auto-completion and generally works better than Eclipse.

**Comment by bensku** [comment]
Well, IDEA can screw up by not watching for nullness annotations. It is not dangerous since these are checked when compiling, but you might need to read compiler log to fix errors.

And those errors you see in IDEA are not real either. ECJ (with gradle build) compiles just fine, but javac or IDEA are more strict in mant ways. You can very well develop with IDEA, but you have to ignore errors and make sure your code is valid as you do when writing with text editor.

**Comment by Namnodorel** [comment]
-.- Ok, I'm just gonna get Eclipse...

**Comment by bensku** [comment]
Uh, Eclipse should not show you errors. How exactly did you import project?

(I'm gathering information to write README for Skript)

**Comment by Namnodorel** [comment]
File>Import: Gradle>Gradle Project: Click through dialog, keep existing project
