### ISSUE TITLE
Skript-dev18c Error messages?

### ISSUE THREAD

**Issue by thejimmyj57** [bensku/Skript#148]
Hey, I am not sure if these errors messages are from skript or supposed to be from some of the Dependencies I have. But I get these errors when loading up the bensku skript version from skript-dev15 to skript-dev18c. Same error.

http://pastebin.com/fTNHMkvK

The dependencies I am running are the latest versions of Umbaska, SkRayFall, SkQuery and Wildskript. All running on a 1.10 and 1.10.2 server (I tried both versions)

Any fix would be greatly appreciated. # #

**Comment by JKGamerxD** [comment]
disable the updater (there is an option in the `config.sk`), that solve one of the errors.

**Comment by bensku** [comment]
Duplicate for #146.
