### ISSUE TITLE
Giving a player an item when inventory is full

### ISSUE THREAD

**Issue by RiverThrough** [bensku/Skript#15]
When I run this code with a full inventory:
```
command /giveisbroken:
	trigger:
		give 1 diamond to player
```
it placed the diamond in the leggings armour slot, here's a pic:
http://i.imgur.com/BeeS4RC.png

**Comment by bensku** [comment]
Sanity checks missing... Oops

**Comment by bensku** [comment]
Fixed in next release, hopefully.
