### ISSUE TITLE
Error with latest Skript dev18c

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#150]
http://hastebin.com/apovuliduy.vbs

**Comment by JKGamerxD** [comment]
That is a bug with the updater, simply disable the option `check new version` in the `config.sk`

**Comment by bensku** [comment]
Updater server seems to be down. Will fix by writing my own updater for next release, but for now you can toggle it off.

**Comment by bensku** [comment]
Duplicate of #146.
