### ISSUE TITLE
Missing Glowing and Bad Luck effekt

### ISSUE THREAD

**Issue by DontKillCZ** [bensku/Skript#152]
List of effects: http://minecraft.gamepedia.com/Status_effect
Skirpt don't support Glowing and Bad Luck effect.

**Comment by bensku** [comment]
Glowing is technically also NBT tag, which is indeed supported. Set glowing of entity for that.

But yeah, 2 potion effects missing here.

**Comment by JKGamerxD** [comment]
For the glowing, you can use `glowing of %entities%` expression (you can set it to true or false).

And for the bad luck **EFFECT** try adding the effect to the list  of enchantment in the english.lang (this file is in the Skript.jar/Lang) and view if this works. *I'll test it*

Also @bensku you can add support for glowing colors in the `glowing of %entities%` expression?

**Comment by bensku** [comment]
Coming in next release. Except color stuff, which will come if we get scoreboard support at some point.
