### ISSUE TITLE
1.8.8 PaperSpigot

### ISSUE THREAD

**Issue by xeonentr** [bensku/Skript#154]
http://hastebin.com/cabiyedowu.vbs

**Comment by JKGamerxD** [comment]
Emmm, on the error log you've sent. You're using Skript 2.1.2, not this version.

**Comment by xeonentr** [comment]
not what version ?

**Comment by TheBentoBox** [comment]
The version you're commenting on... this is the repository for NEW versions of Skript, for Minecraft 1.9 - 1.10. The version you're running on your server is 2.1.2, which is not this version. Issues on 1.8 relating to a 1.7 version of Skript aren't relevant here.

**Comment by bensku** [comment]
2.2 dev versions made by be. See this repository's releases
