### ISSUE TITLE
error with "push player forwards with speed 2"

### ISSUE THREAD

**Issue by tuanjr** [bensku/Skript#157]
I have skript like this:
```
on portal enter:
    push player forwards with speed 2
```
and this is error:
http://paste.ubuntu.com/22717951/
if i set speed to low, like 0.1, error does not appear
Skript version dev18c
Paperspigot 1.9.2

**Comment by JKGamerxD** [comment]
I don't have this error on Spigot 1.9.2, maybe it's a PaperSpigot problem.

**Comment by TheBentoBox** [comment]
It's saying the velocity of the entity is being set higher than PaperSpigot wants to allow you to. Go into the config files and see if there's a setting you can modify for excessive velocity thresholds.

**Comment by bensku** [comment]
These are warning rather than errors, and have no relation to Skript. You, as scripter, are setting quite big velocity values and PaperSpigot warns about it.
