### ISSUE TITLE
[REQUEST] Register location event value for HangingEvent

### ISSUE THREAD

**Issue by TlatoaniHJ** [bensku/Skript#158]
This is the first time I have created an issue on GitHub, so I apologize if I have done anything wrong with it.

Currently, in Skript, using the expression `event-location` in an `on break` event where an item frame or a painting is being broken will give you the player's location rather than the location of the item frame/painting. To make this consistent with the other triggers of the `on break` event where the event-location is the location of the block, I am suggesting that Skript registers a location event value for the HangingEvent event. I have included the code so you can see exactly what I am talking about:

```
EventValues.registerEventValue(HangingEvent.class, Location.class, new Getter<Location, HangingEvent>() {
			@Override
			@Nullable
			public Location get(final HangingEvent e) {
				return e.getEntity().getLocation();
			}
		}, 0);
```

**Comment by bensku** [comment]
This is so good thst you could have made a pull request :) Will add to next version.

**Comment by bensku** [comment]
Should be fixed in next release. However, please test it when build is out.
