### ISSUE TITLE
problem with spawn egg

### ISSUE THREAD

**Issue by tuanjr** [bensku/Skript#160]
Example:

```
        set slot 2 of player to creeper spawn egg named "&bGigantic Creeper Egg"
```

but, instead of set creeper spawn egg, it always set "normal spawn egg" (white egg)

**Comment by JKGamerxD** [comment]
You can send your aliases?

**Comment by tuanjr** [comment]
here are alias file:
https://www.dropbox.com/s/r1zpoa5nck1mxtw/aliases-english.sk?dl=1

**Comment by JKGamerxD** [comment]
Try using this aliases:
https://forums.skunity.com/t/latest-aliases-v1-9-4-id-order-full-1-10-support/40

**Comment by bensku** [comment]
Skript's default aliases have been update months ago to support things like these.
