### ISSUE TITLE
[REQUEST] Get current day of week

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#161]
I have been looking for this for so long. I need a way to find out the current time and DAY. As far as I know "now" only gives you the current time (and maybe date) but not the day of the week, e.g. Sunday.

Can this be added?

**Comment by bensku** [comment]
Time stuff in general is not well done with Skript. Needs improvement, but no idea when I have time...

**Comment by Tuke-Nuke** [comment]
Sorry for bumping or something, but I think it isn't solved.
You could just edit the "date format" in your config:
You can use:
date format: EEEEEEEEE, m/d/yy h:mm a
it will return the %now% as: Friday, 9/2/16 2:44 PM

**Comment by bensku** [comment]
This is not solved, you are right. Maybe it will for next release, but as said there are many things to do with little time I have for Skript.

**Comment by Snow-Pyon** [comment]
With the new [formatted time expression](http://bensku.github.io/Skript/expressions.html#ExprFormatTime) shouldn't this be closed?

**Comment by pierrelasse** [comment]
Use:
send now formatted with "mm:hh:ss dd.MM.yyyy"

mm = min
hh = hour
ss = second

dd = day
mm = month
yyyy = year (0000)
yy = year (00)
