### ISSUE TITLE
Tablist stuff.

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#163]
Hey Bensku, if you have used the expression:

``` Java
[the] (player|tab)[ ]list name[s] of %players%
%players%'[s] (player|tab)[ ]list name[s]
```

For set the name of the player in the tablist, if you put a name more longer than 16 characters, the name is shortened to the max character limit.

If you can fix this, because I don't want install other addon like SkRayFall or Skellett only for this fixed feature. 

**Image**
![2016-08-10_12 25 54](https://cloud.githubusercontent.com/assets/16750186/17559791/d1afdde6-5ef5-11e6-99b8-e02d95a660e1.png)

And also, a way for set the header and footer of the tablist ?)

_If any want the the script I'm using in that image, here is it:_
https://www.spigotmc.org/resources/tab-1-3-skquery-skrayfall.27486/

**Comment by bensku** [comment]
Interesting. I'll see if this can be fixed using Spigot API.

**Comment by bensku** [comment]
It is not possible to send tablist _name_ that is longer than 16 characters. See https://www.spigotmc.org/threads/max-tablist-name-length.150818 for explanation.

However, using scoreboards you can skip this limitation. Team name length is unlimited. Sadly Skript has not support for scoreboards and will not get it by me in near future.

If someone wants to hack around this (using no NMS code ofc), help is welcome.

**Comment by JKGamerxD** [comment]
You should check the class of SkRayFall or Skellett:
https://github.com/eyesniper2/skRayFall/blob/master/src/main/java/net/rayfall/eyesniper2/skrayfall/generaleffects/EffSetPlayerListName.java

https://github.com/TheLimeGlass/Skellett/blob/master/src/com/gmail/thelimeglass/Effects/EffSetTabName.java

**Comment by bensku** [comment]
Both use same Bukkit API method as Skript does. At least it looks like this when checking code.

**Comment by JKGamerxD** [comment]
Sorry if I'm wrong (I'm unfamiliar with Java) but comparing the codes:
```
#Skript code
((Player) o).setPlayerListName(s == null ? "" : s.length() > 16 ? s.substring(0, 16) : s);

#Others
player.getSingle(evt).setPlayerListName(name.getSingle(evt).replace("\"", ""));
```
The thing is, In the Skript code is the `substring` method, so, maybe this is the cause why the name is shortened?

**Comment by bensku** [comment]
Oops. Sorry, checked too quickly. Apparently this method is used in more than on places in Skript.

**Comment by JKGamerxD** [comment]
> Oops. Sorry, checked too quickly. Apparently this method is used in more than on places in Skript.

**Comment by JKGamerxD** [comment]
So it's possibly to solve?

Also sorry for close and open the thread, clicked on the wrong button haha.

**Comment by JKGamerxD** [comment]
It's fixed on the dev19, so I close the issue.

**Comment by JKGamerxD** [comment]
I reopen the issue because you can't set the tablist name of a variable, for example:
```Javascript
function animatedTabName(player: player, name: text):
	loop length of {_name} times:
		set {_name::*} to subtext of {_name} from 1 to loop-num
	while {_player} is online:
		loop {_name::*}:
			if loop-value is "&":
				delete {_name::%loop-index%}
			else:
				set tablist name of {_player} to colored loop-value
			wait 3 ticks
```
But it return:
```
the player list name of {_player} can't be set to anything.
```

**Comment by TheLimeGlass** [comment]
MundoSk has this now.

**Comment by JKGamerxD** [comment]
Oh, really? I'll see it (Don't joined to the forums a long time ago u.u)

**Comment by JKGamerxD** [comment]
@bensku the dev20 is out but the bug explained above (can't set the player's tablist name if the player is a variable), if you can fix it...

**Comment by Snow-Pyon** [comment]
This isn't fixed at all yet, as @JKGamerxD reported a _while_ ago, you can't set the tablist name of a player variable. This gets fixed if you parse the variable as a player then set their name like this:
```
set {_test} to first element out of all players
set ({_test} parsed as player)'s tablist name to "testing"
```
But that shouldn't be the case.

**Comment by Snow-Pyon** [comment]
Closing this since the bug explained here isn't related to this expression specifically (it is a parser bug).
