### ISSUE TITLE
[REQ] Particle Effect only to player

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#165]
Can you add a parameter to the particle effect so that I can show these particles only to 1 player.

Example:

play 100 (angry villager with speed 1) at player to player

**Comment by JKGamerxD** [comment]
This is the particles and visual effects syntax:
```java
(play|show) %visualeffects% (on|%directions%) %entities/locations% [(to %-players%|in (radius|range) of %number%)]
(play|show) %number% %visualeffects% (on|%directions%) %locations% [(to %-players%|in (radius|range) of %number%)]
```
So I think it's client side.

**Comment by bensku** [comment]
Looking at those patterns, it seems you can target effects to specific players. Does this not work?

**Comment by TheBentoBox** [comment]
No response, closed.
