### ISSUE TITLE
Bensku edit takes 7mins 32 seconds to load my scripts. Nfell's 3mins and 23seconds

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#166]
Why does the Bensku fork take twice as long to load the scripts on startup?

**Comment by bensku** [comment]
Wow. There is something wrong with the parser.

I guess it is related to function signature pre-parsing... Time to optimize that :)

**Comment by whoshenry** [comment]
Great, thank you!

**Comment by whoshenry** [comment]
Any update on the parsing issue?

**Comment by bensku** [comment]
No idea how long this takes. I basically need to rewrite quite a lot code and test it - meanwhile, there are more or less critical bugs waiting fixes.

**Comment by TrademarkTM** [comment]
Hey Bensku! I'm having the same problem.
And yes, I'm using some addons, but it loads faster with nfell's one.
Here's an example of Skript that takes a long time to load (but others 10x bigger take less time):

`options:
	P: &6&lPla&e&ltoon &b▪
		
on join:
	if player's chestplate is not chain chestplate named "&dJetpack":
		player's gamemode is survival
		set player's fly mode to false
		stop
	set player's fly mode to true
	
on jump:
	if name of player's chestplate is "&dJetpack":
		set player's fly mode to true
		
on quit:
	clear {jetpack.%player%}
	set player's fly mode to false
	
on flight toggle:
	if player's gamemode is creative:
		stop
	if name of player's chestplate is not set:
		set player's fly mode to false
		clear {jetpack.%player%}
		stop
	if name of player's chestplate is not "&dJetpack":
		set player's fly mode to false
		stop
	wait 1 tick
	if player is not flying:
		clear {jetpack.%player%}
		set player's fly mode to false
		wait 3 ticks
		set player's fly mode to true
	player is flying
	if number of coal in player's inventory is smaller than 3:
		set player's fly mode to false
		send "{@P} &cVocê precisa de mais &4carvão&c."
		stop
	remove 3 coal from player's inventory
	if {jetpack.%player%} is not set:
		push player upwards at speed 1.2
		loop blocks in radius 3 around player:
			set {_Y} to rounded player's Y coordinate
			set {_Y2} to rounded Y coordinate of loop-block
			if {_Y} is {_Y2}:
				show 3 "flame" particles at location of player for player offset by 1, 1, 1
				loop entities in radius 5 around player:
					if loop-entity is not item frame or painting or player:
						ignite loop-entity for 4 seconds
		$ thread
		loop 10 times:
			set {_l2} to location 1.2 above player
			set {_l3} to location 1.2 above player
			set {_l2} to location 0.4 behind {_l2}
			set {_l3} to location 0.4 behind {_l3}
			play ghast fireball at block under block under block under player with pitch 10
			play blaze hit at player with pitch 10
			$ thread
			loop 7 times:
				loop all players:
					show 1 "flame" particles at {_l2} for loop-player offset by 0, 0, 0
					show 1 "flame" particles at {_l3} for loop-player offset by 0, 0, 0
					chance of 25%:
						show 1 "flame" particles at {_l2} for loop-player offset by 0, 0, 0
						show 1 "flame" particles at {_l3} for loop-player offset by 0, 0, 0
				set {_l2} to location 0.25 under {_l2}
				set {_l2} to location 0.25 behind {_l2}
				set {_l2} to location 0.15 right {_l2}
				set {_l3} to location 0.25 under {_l3}
				set {_l3} to location 0.25 behind {_l3}
				set {_l3} to location 0.15 left {_l3}
			wait 0.5 tick
		wait 0.2 second
		player is flying
		set {jetpack.%player%} to true
		set player's fly mode to true
		set player's flight speed to 0.08
		$ thread
		while {jetpack.%player%} is set:
			set {_todos::*} to all players
			if player's Y coordinate is more than 256:
				set player's fly mode to false
				send "{@P} &cNão há &4oxigênio &cnesta altura!"
				wait 1.5 seconds
				set player's fly mode to true
				stop
			if number of coal in player's inventory is smaller than 1:
				send "{@P} &cVocê precisa de mais &4carvão&c."
				set player's fly mode to false
				play note bass at player with pitch 10
				clear {jetpack.%player%}
				stop loop
			chance of 2%:
				add 1 to data value of player's chestplate
			chance of 4%:
				remove 1 coal from player's inventory
				play fizz at player with pitch 10
			if player is sprinting:
				set player's flight speed to 0.04
			else:
				set player's flight speed to 0.08
			play ghast fireball at block under block under block under player with pitch 10
			set {_l2} to location 1.2 above player
			set {_l3} to location 1.2 above player
			set {_l2} to location 0.4 behind {_l2}
			set {_l3} to location 0.4 behind {_l3}
			$ thread
			loop 7 times:
				loop all players:
					show 1 "flame" particles at {_l2} for loop-player offset by 0, 0, 0
					show 1 "flame" particles at {_l3} for loop-player offset by 0, 0, 0
					chance of 25%:
						show 1 "flame" particles at {_l2} for loop-player offset by 0, 0, 0
						show 1 "flame" particles at {_l3} for loop-player offset by 0, 0, 0
				set {_l2} to location 0.25 under {_l2}
				set {_l2} to location 0.25 behind {_l2}
				set {_l2} to location 0.15 right {_l2}
				set {_l3} to location 0.25 under {_l3}
				set {_l3} to location 0.25 behind {_l3}
				set {_l3} to location 0.15 left {_l3}
			set {_l3} to location 0.25 right {_l3}
			$ thread
			loop entities in radius 2 around block behind block behind player:
				loop-entity is not player
				ignite loop-entity for 4 seconds
			if name of player's chestplate is not set:
				set player's fly mode to false
				clear {jetpack.%player%}
				stop loop
			if name of player's chestplate is not "&dJetpack":
				set player's fly mode to false
				clear {jetpack.%player%}
				stop loop
			wait 3 ticks

command /jetpack:
	permission: aos.jetpack
	permission message: {@P} &7Você não tem permissão!
	trigger:
		give a chain chestplate named "&dJetpack" to player
		give 64 coal to player
		send "{@P} &7Você recebeu um &fJetpack&7!"`

**Comment by ZeTioZ** [comment]
Hello, I got the same issues and it seem the particles showing make the skript load very slower than other without it

**Comment by bensku** [comment]
Wow, if that is truly the cause... I have really not even idea how to fix it. Particle system is buggy, but slow? It should't be.

**Comment by ZeTioZ** [comment]
If you want I can do a little video to show you when I remove the part of code with the particles how slower it load and when I add them how faster it load.

**Comment by bensku** [comment]
No need, I trust that is the case. I just wonder, how it is so... I fear particle system has some fundamental flaws which would require a rewrite of it - again.

I'll keep you updated when I have new information. No ETA since I have no idea what I'm dealing with.

**Comment by ZeTioZ** [comment]
Ok thanks

**Comment by bensku** [comment]
@ZeTioZ Multithreaded parser coming in next update. I also indeed found one very stupid mistake *I* had made when working with current script loader.

**Comment by ZeTioZ** [comment]
So, @bensku you think you got the solution for this problem ?

**Comment by bensku** [comment]
Probably. And if not, multithreaded parser is so much faster anyway...

**Comment by whoshenry** [comment]
Just an update, the Skript is still taking a long time to load everything. With dev24b.

**Comment by Tristag** [comment]
Hey, I'm also having this issue.  It takes almost twice as long to start up :( 
Not to just whine about it though, awesome job you've been doing so far! I'm just salty I can't get your awesome built in json!

I know its probably not this simple, however what if you were to look at nfell's fork and see how the parser works there?

Thanks again for your work!

**Comment by bensku** [comment]
I might have a hunch what causes this, but no promises.

**Comment by Tristag** [comment]
No problem, it seems like its particle/sound related, if that helps?

**Comment by TheBentoBox** [comment]
There are far newer issues related to slow script load times.
