### ISSUE TITLE
Docs: Duplications and Unknown names.

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#167]
Hey, there are duplications and syntaxes without names I've founded on the new docs:

**Duplications**
![docs_1](https://cloud.githubusercontent.com/assets/16750186/17704873/c641053c-63ac-11e6-98b7-0a1b06dff5e2.jpg)
![docs_7](https://cloud.githubusercontent.com/assets/16750186/17704913/e2e5c344-63ac-11e6-9236-2a7d5118b3ea.jpg)

**Unknown names**
![docs_2](https://cloud.githubusercontent.com/assets/16750186/17704890/cf6ca800-63ac-11e6-9b2c-c193df40fb10.jpg)
![docs_3](https://cloud.githubusercontent.com/assets/16750186/17704897/d569d610-63ac-11e6-8e1a-7ba27928e144.jpg)
![docs_4](https://cloud.githubusercontent.com/assets/16750186/17704901/d9704d34-63ac-11e6-8fad-439020f8d627.jpg)
![docs_5](https://cloud.githubusercontent.com/assets/16750186/17704903/dc61f506-63ac-11e6-8035-42bdae3e13c2.jpg)
![docs_6](https://cloud.githubusercontent.com/assets/16750186/17704908/df57d7da-63ac-11e6-83a2-4cdc3d179064.jpg)

And the `structuretype` type isn't defined on the `type` section of the docs.

**Comment by bensku** [comment]
Unknown name means that something is wrong with documentation inside Skript's source. It is something that I need to fix on Java side.

Duplicate entries are just what you would think - they are registered multiple times using same class. Due to Skript's documentation being tied to classes, not instances, it will output incorrectly. However, this is something that is probably fixable.

**Comment by JKGamerxD** [comment]
The `use[s] (1¦old|2¦new|1¦2.1.2|2¦2.2) loops` is an effect by Mirreski, this makes what the effect says on the syntax, use the loops of the 2.2 or 2.1.2 on the event. I don't know why he add it, but for the people who the loops of the 2.2 don't work (e.x: `loop players`), if you use this effect, it make the loops works other time. Example:
```
on script load:
	use 2.1.2 loops
	loop players:
		send "You're receiving this with the 2.1.2 loops" to loop-player
```

And the `[chat][( |-)]recipients` is an expression that contains all the players who are sent the message, you can add, remove, set and delete it. Example:
```
on chat:
	if player don't have permission "message.see":
		remove player from chat recipients #This makes the player don't receive the message but the others would receive it.
```

**Comment by bensku** [comment]
Uhh, I fixed looping players anyway a long ago... But I can see the use there :)

**Comment by bensku** [comment]
I fixed missing information, since it was kinda more urgent. Other fixes will have to wait, I'm very busy with another project until end of the month.

**Comment by bensku** [comment]
This has been since fixed.
