### ISSUE TITLE
New feature: event-tool/hand/etc of player/entity

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#17]
Let's consider this scenario:

```
on player consuming:                                 
  if name of event-item is "&fWhiskey":       # Player is drinking whiskey.
    cancel event                                            # We are using magic potions for nice color, cancel effects.
    if name of tool of player is "&fWhiskey":  # Now we have to find out where the whiskey is.
      remove 1 of tool from tool of player       # This wasn't a problem before 1.9 added two hands.
      give glass bottle to player                      # Now it bring a new screnario where there is amount of
    else if name of off-tool of player is "&fWhiskey":  # uncertainty where the event-item is
      remove 1 of off-tool from tool of player   # and a possibility to choose the wrong hand
      give glass bottle to player         # accidentally if we are comparing same base items for example.
```

So how to fix this? Best way to fix it would be letting Skript decide. That way we wouldn't have to clutter our code with extra checks.

My suggestion:

```
on player consuming:                                 
  if event-tool of player is "&fWhiskey": 
    cancel event                                            
    remove 1 of event-tool from event-tool of player
    give glass bottle to player
```

Event-tool would be something that exists in events, for example:
- on damage -> %weapon/event-tool of entity%
- on left/right click -> %event-tool of entity%
- on projectile hit -> %weapon/event-tool of shooter%

Etc. 

Skript would basically check what the player/entity is doing in the event and if he is doing it with his main tool of off-tool and Skript would store the information which one it is in %event-tool of entity%.

Does this make sense?

**Comment by bensku** [comment]
Coming in next version as <code>item</code> syntax support for click events.
