### ISSUE TITLE
[Question] What's wrong with NMS?

### ISSUE THREAD

**Issue by xXAndrew28Xx** [bensku/Skript#170]
What is wrong with using NMS? Is it OK to use if I use reflection and test it on multiple versions? There are some things only possible via NMS.

**Comment by bensku** [comment]
NMS tends to break between versions. Wirhout reflection, plugin needs update to work with newer Minecraft versions. If you hack around this, you are essentially bypassing safety feature or CraftBukkit.

What fearure you'd need NMS for?

**Comment by xXAndrew28Xx** [comment]
Nothing atm.
