### ISSUE TITLE
Add Hide Potion particles

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#175]
Could you add a option to hide potion particles with the effect apply?
Thanks

**Comment by Isabaella** [comment]
Bump! In need of it, too. Got sick of executing a console command the whole time as I'm using it quite often.

If you don't know what he was talking about:
When you apply a potion effect to a player, there's an option to do it without particles.
Here's a simple example of the vanilla command: `/effect @p strength 30 2 true`

The 'true' is the parameter to hide particles. In Java, it's the `hasParticles()` method.

Additionally, translucent particles would be fine, too: `isAmbient()`
