### ISSUE TITLE
On teleport event doesn't work as well.

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#178]
Hello, I'm in 1.8.8 and I use the dev19, all work but sometime when I restart the server, the teleport event doesn't work, how can I fix it ?

Thanks in advance.

**Comment by bensku** [comment]
I haven't run 1.8 server for ages, but will debug this when I do that again - maybe for next release.

**Comment by ZeTioZ** [comment]
Ok thank you for your work

**Comment by TheBentoBox** [comment]
@ZeTioZ Are you still experiencing this issue?

**Comment by ZeTioZ** [comment]
Yes there is still this issue :/

**Comment by TheBentoBox** [comment]
What exact version of Skript & Spigot are you using, and what addons/plugins? It's up to Bensku if he'd still like to address this, as this version of Skript technically doesn't support below 1.9.

**Comment by ZeTioZ** [comment]
Skript-dev20b

**Comment by bensku** [comment]
Teleport event is registered in really simple way and works for new Spigot versions. I assume it is bugged on certain Spigot/PaperSpigot versions. Here are some (resolved) issues:

https://hub.spigotmc.org/jira/browse/SPIGOT-264
