### ISSUE TITLE
Loop All Players broken!

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#18]
For me the "loop all players" effect is broken:

console error when trying to do it:
http://pastebin.com/2Sg3mrZC

Using latest Paper-Spigot 1.9 Dev Build, Umbaska, skrayfall, ExertSK

**Comment by Pilvinen** [comment]
Strange. For me "loop players" works just fine.

Have you tried if you get the same error with regular Spigot 1.9? Something seems to be trying to use the old depreached getonlineplayers method.

**Comment by bloggy** [comment]
For me it does not work. I just tried it again (downloaded your latest Skript version).

My script:
```
command /loop:
	trigger:
		loop all players:
			send "test" to loop-player
```

The result (console error):
http://pastebin.com/bPguMu36

**Comment by bloggy** [comment]
I think the problem was SkQuery4 which I forgot to mention. I deleted it from plugins folder and it seems to work now!
