### ISSUE TITLE
Internal error? Skript doesnt recognize or load my skripts

### ISSUE THREAD

**Issue by CriticalMagics** [bensku/Skript#180]
28.08 18:32:02 [Server] ERROR #!#! Version Information:
28.08 18:32:02 [Server] ERROR #!#! 
28.08 18:32:02 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
28.08 18:32:02 [Server] ERROR #!#!     at ch.njol.skript.Updater$2.run(Updater.java:210)
28.08 18:32:02 [Server] ERROR #!#!     at ch.njol.skript.Updater.getChangelogs(Updater.java:286)
28.08 18:32:02 [Server] ERROR #!#!     at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83)
28.08 18:32:02 [Server] ERROR #!#!     at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:601)
28.08 18:32:02 [Server] INFO Message: Premature end of file.
28.08 18:32:02 [Server] ERROR #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
28.08 18:32:02 [Server] ERROR #!#! Stack trace:
28.08 18:32:02 [Server] ERROR #!#! 
28.08 18:32:02 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
28.08 18:32:02 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
28.08 18:32:02 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
28.08 18:32:02 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it,
28.08 18:32:02 [Server] ERROR #!#! and check whether this error has already been reported.
28.08 18:32:02 [Server] ERROR #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/
28.08 18:32:02 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
28.08 18:32:02 [Server] ERROR #!#! 
28.08 18:32:02 [Server] ERROR #!#! Unexpected error while checking for a new version of Skript
28.08 18:32:02 [Server] ERROR #!#! [Skript] Severe Error:
28.08 18:32:02 [Server] ERROR #!#!

**Comment by CriticalMagics** [comment]
This reads from bottom to top

**Comment by itismejoey** [comment]
https://forums.skunity.com/t/psa-non-fatal-skript-bug/8857

**Comment by bensku** [comment]
Old version of Skript...
