### ISSUE TITLE
Particles doesn't work correctly.

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#182]
Well for first, the offsetting of the colored dust particles doesn't work, it only offset the particle to red. And when you try to use the speed and offset expression on other particles that aren't the `sprinting dust` returns a `can't understand this condition/effect` error.

**Comment by bensku** [comment]
Please verify that you're using correct syntax at documentation. If so, please provide example code so I can debug this.

If you do that soon enough, I'm probably able to fix this for next version.

**Comment by JKGamerxD** [comment]
``` YAML
command /debug [<num>]:
	trigger:
		set {_effect} to colored dust with offset of 30, 120, 85 and speed 1
		show arg-1 {_effect} on player
```
It need to work, but if I add the `offset` or `speed` to the visual effect, it retuns `can't understand this expression` and if you use `%color% dust` (`green dust` for example) it only makes the particle red.

The speed should work with the most part of the particles, but the offset seems only work with the sprinting dust.

**Comment by bensku** [comment]
Colors are bugged indeed. I gave up last time I tried to fix them due to general bugginess pf Spigot particle backend.

**Comment by bensku** [comment]
This was fixed in latest release few months ago - I think.
