### ISSUE TITLE
Detect shulker events

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#183]
The event: on death of shulker is not detected. Other mobs are detected but it seems that shulkers are not added yet.

**Comment by TheBentoBox** [comment]
I believe it's because shulkers aren't properly named by Skript, as discussed in [this issue](https://github.com/bensku/Skript/issues/110). Looking at a shulker and doing `send "%target%"` returns "entities.golem.name" last I checked. Kinda weird.

**Comment by bensku** [comment]
Next release will fix this.
