### ISSUE TITLE
painting place and break

### ISSUE THREAD

**Issue by yyeerai** [bensku/Skript#185]
painting place and break is not work，
exp：
on break of painting:
	If player's gamemode is not creative:
		cancel event

is not work

**Comment by TheBentoBox** [comment]
Paintings are entities, not blocks, so they won't trigger break events. You can use MundoSK's `on hang` event to detect when a player hangs a painting or anything similar (item frame, and I believe leash knots). Then `on unhang` triggers when a player destroys a painting/item frame/whatever. The `hanged entity` expression is the painting in both of these events.

While inherent support for more things in vanilla Skript isn't really ever bad, this isn't a bug.
