### ISSUE TITLE
A bug with leaf type

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#186]
I found that my aliases part for leaf types gets ignored by Skript. Because ingame it always says "18" instead of "oak leave" when holding oak leave block and message me the result of "%player's tool%".
See my thread @ skunity: https://forums.skunity.com/t/how-to-find-out-which-kind-of-leaves-the-user-breaks/9632/7

That's the part of my aliases file for the leaves:

	{tree type}(_| )leaves @x = 18
	oak(_| )leaves = 18, 18:4, 18:8, 18:12
	spruce(_| )leaves = 18:1, 18:5, 18:9, 18:13
	birch(_| )leaves = 18:2, 18:6, 18:10, 18:14
	jungle(_| )leaves = 18:3, 18:7, 18:11, 18:15
	{tree type}(_| )permanent(_| )leaves @x = 18:4-7, 18:12-15

**Comment by bensku** [comment]
@tim740 Any idea what might be causing this? You're the aliases expert here :)

**Comment by tim740** [comment]
i was reported this error about a week ago, ill look into it, im really busy and don't have much time to work on these things

**Comment by tim740** [comment]
![casfjbgblsdagjgaspture](https://cloud.githubusercontent.com/assets/13081972/18288818/d71aba6e-7474-11e6-8d6f-7e2a8d255019.PNG)

fixed in the next version of the aliases ill get bensku to add them as default

**Comment by tim740** [comment]
ill release the next version soon

**Comment by tim740** [comment]
v1.9.5 has been release

https://forums.skunity.com/t/latest-aliases-v1-9-5-id-order-full-1-10-support/40/111?u=tim740

**Comment by tim740** [comment]
@bensku please grab https://github.com/tim740/skAliases/blob/master/aliases-english.sk
and put it in your skript fork then close this issue

**Comment by bensku** [comment]
Yes, will do so for nexr version. Hopefully with updater, but that I don't know for sure.

**Comment by tim740** [comment]
I've Updated the aliases within this repo to v1.9.8 you can get the latest version from
https://github.com/tim740/skAliases/releases/latest

**Comment by NurdTurd** [comment]
Thanks Tim! :+1:

**Comment by bloggy** [comment]
Thank you Tim for your work!!!
