### ISSUE TITLE
Issue with UTF-8

### ISSUE THREAD

**Issue by Nicofisi** [bensku/Skript#189]
Hi, can you please add those 3 lines to your build.gradle? I'm not creating a pull request because you may want to place it somewhere else, so too much effort.
https://github.com/Nicofisi/Skript/blob/master/build.gradle#L6-L8
It fixes an issue for me (utf-8 encoding in compiler arguments is not enough in my case).
Thanks in advance!

**Comment by bensku** [comment]
ECJ uses UTF-8 as of today's build. Please try again and report if that does it.

I very mich doubt option you provided would help anything for non-javac compiler.

**Comment by bensku** [comment]
Done, I hope it helps.
