### ISSUE TITLE
On command

### ISSUE THREAD

**Issue by itismejoey** [bensku/Skript#19]
On my server a lot of command permissions are used with variables (ie: `{rank::staff::%player%}`). I like to use custom permission messages for some commands (such as /op). 

Previously, I would be able to use the following just fine:

```
on command "/op":
	if {rank::staff::%player%} is not "admin" or "owner":
		cancel event
		message "{@noperms}"
```

Now, with both this version and nfell's, I can only use `if {rank::staff::%player%}` is not set to actually catch and cancel the event.

Also, it seems like having a multiple options in `if command contains ....` doesn't work either.
```
on command:
	if command contains "spigot" or "bukkit" or "bukkit:" or "minecraft":
		if player is not op:
			cancel event
			message "&4* &cUnknown command. &7Type &f/help [topic] &7for help."
```

**Comment by Pilvinen** [comment]
As a quick fix you might try comparing agains text and see if that works, ie:

```
if "%{rank::staff::%player%}%" is not "admin" or "owner":
...
if "%command%" contains "spigot" or "bukkit" or "bukkit:" or "minecraft":
```

**Comment by bensku** [comment]
```
on command:
    if command contains "spigot" or "bukkit" or "bukkit:" or "minecraft":
        message "Command contains."
```

**Comment by bensku** [comment]
No response -> closed.

**Comment by itismejoey** [comment]
Have a life outside of Minecraft...

I figured out my own workarounds though. Just don't understand why it all of a sudden changed.
