### ISSUE TITLE
Random [lowest priority ever] bug

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#192]
Hey!
I'm using cooldown for my warps script, but this occours when I use this:

```
command /asd:
	trigger:
		set {_number} to 1
		send "Whatever lol %{_number}%s"
```

Using "s":
> Whatever lol 1

Any other character:
> Whatever lol 1[character]

The "s" after {_number} dissapears, I have no idea why.
Tested with any other character and works.

I don't know if it occours in other versions and whatever, I'm using dev19.
And yeah, it's priority is really low, nothing special.

I'm using: skMorkaz, skQuery, skRayFall.

**Comment by tim740** [comment]
I've seen this bug before, long time ago in 2.1.2

**Comment by RezzedUp** [comment]
This isn't a bug, it's actually a feature believe it or not. See the "Advanced Syntax" section on this page: http://njol.ch/projects/skript/doc/strings/

**Comment by bensku** [comment]
I don't know if that is for good, but it is feature.
