### ISSUE TITLE
Enhancement: entity UUID

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#193]
The parent `Entity` class in Bukkit has a `getUniqueId()` function that returns a UUID object for that entity's persistent ID, which is persistent. This would be very useful for keeping references/comparisons for an entity which works across server restarts, as entity objects in variables don't save on server reload. It's also (I imagine) a smaller object, since the UUID would just be a string. It would be nice if the `[the] UUID of %offlineplayers/worlds%` expression could be extrapolated to work with entities as well, to instead be `[the] UUID of %entity/worlds%`. 

Note that this expression does exist in Umbaska. However, I believe it makes sense to include it in vanilla Skript given how useful it'd be, and given the issues Umbaska has had with working with this fork.

Cheers!

**Comment by JKGamerxD** [comment]
That expression is on RandomSK too, but the `entity from uuid %string%` doesn't work. You can still get the uuid of an entity with `uuid from %entity%`.

**Comment by TheBentoBox** [comment]
RandomSK is also pretty broken though, and is getting more broken with time since it's not getting updated anymore. It doesn't even run on 1.9+ without the SpecialSource fix :-1:

**Comment by bensku** [comment]
This is something that sounds quite possible and useful. Note that it still might not be best idea to save entity UUIDs anywhere, just in case they are not really unique.

**Comment by TheBentoBox** [comment]
Yeah, there's no true 100% guarantee, but it's a pretty safe bet and the odds of coming across two with the same UUID is very rare, if at all possible. The UU does stand for Universally Unique, so hopefully they're true to their name!

**Comment by JKGamerxD** [comment]
Yeah, I know RandomSK is pretty broken, but it works using the SpecialSource fix _yet_

And talking about entities, you can make an expression for get an entity from a variable/uuid? Something like:
```
entity from %objects%
```
So, that close the bugs when you use an entity that is saved on a variable and makes you could use the entity from an entity UUID.

**Comment by Tuke-Nuke** [comment]
@TheBentoBox I think it might be closed due to already added in newest versions? Also, the expression to get an entity from a uuid would be the same as:
```
loop all entities:
    if uuid of loop-entity is {_uuid}:
```
So it's worth to create a function for that simple code instead.

**Comment by TheBentoBox** [comment]
Right! Forgot to close this after your PR @Tuke-Nuke . Cheers.
