### ISSUE TITLE
uuid of victim

### ISSUE THREAD

**Issue by epicskymi** [bensku/Skript#195]
Im using 

%uuid of victim% and this returns none 

tried

set {_uuid} to uuid of victim

also returns none

trying to get uuid of a zombie

**Comment by TheBentoBox** [comment]
The UUID expression in vanilla Skript doesn't work on non-player entities, just players and world. There is already an issue request [here](https://github.com/bensku/Skript/issues/193) requesting entity UUID support, so this is technically a duplicate ticket.
