### ISSUE TITLE
Entity target and untarget

### ISSUE THREAD

**Issue by epicskymi** [bensku/Skript#196]
so im broadcasting target when an entity targets a player 

if it targets you before you hit it untargets then re-targets you again when you hit the entity

idono if this is a bug

**Comment by epicskymi** [comment]
to fix this I just waited a couple ticks and checked again for entitys target just seems weird so Ill leave this here

**Comment by JKGamerxD** [comment]
It's because when you hit to a player it going out of the range of your hand, that is how Minecraft works, not a bug.

**Comment by epicskymi** [comment]
what? o-0

**Comment by JKGamerxD** [comment]
When you hit, you can saw the hanging animation, that animation makes you untarget the entity, because the target is on the hand, not on the cursor.

**Comment by epicskymi** [comment]
I have no idea what your saying

**Comment by JKGamerxD** [comment]
Seems you don't understand me, but the point is, it's how Minecraft works really.

**Comment by bensku** [comment]
This is "feature" of Vanilla, I think. When you hit mob, it retargets no matter what, to go for *you*. At least that is what I have understood.
