### ISSUE TITLE
Can not get name of item from a list variable (<none>)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#198]
Using the latest Skript: dev20b

I am unable to get the name of an item from a list variable.
Example command:

```
command /testlist:
    trigger:
        set {_item} to player's tool
        add {_item} to {_itemlist::*}
        set {_getitem} to {_itemlist::1}
        set {_getitemname} to name of {_getitem}
        broadcast "%{_getitem}% -> %{_getitemname}%"
```

`Result is: paper -> <none>`
But the item I am holding has a name.

**Comment by TrademarkTM** [comment]
http://prntscr.com/cmmm3f
It actually worked to me...

**Comment by TheBentoBox** [comment]
No response from reporter, response of it working from others, 3 month old issue, so closing.
