### ISSUE TITLE
world is "world" does not seem to work

### ISSUE THREAD

**Issue by MinecraftAdmin** [bensku/Skript#200]
For example when setting

```
on damage:
    world is "world"
    broadcast "%victim%"
```

The above example does not work but the below one works. AFAIK the above example is functional in the pre-1.9 versions of Skript

```
on damage:
    victim is in "world"
    broadcast "%victim%"
```

**Comment by JKGamerxD** [comment]
Maybe because you're comparing a world with a string, try parse it as a world or use the `world(world: text)` function for it:
```actionscript
on damage:
	world = world("world")
#Or
	world = "world" parsed as world
```
And the `world` expression is really the `[event-]world` expression.

**Comment by TheBentoBox** [comment]
I believe this is what JKGamer said; you can't compare a world with a text. You'd need to do something like `event-world is world "world"`, or `event-world is world("world")`, or event `"%event-world%" is "world"`.
