### ISSUE TITLE
Arrow shoot event

### ISSUE THREAD

**Issue by CriticalMagics** [bensku/Skript#204]
Syntax either doesn't work or is broken on events such as shoot %entity% at speed %integer% from %entity% (shoot arrow at speed X from player, etc). Delivers a "can't understand condition/effect" error

**Comment by JKGamerxD** [comment]
It works fine for me.

Please send the code that you have tried and the version of Skript that you're using.

**Comment by CriticalMagics** [comment]
@JKGamerxD 
Skript: 2.2-dev20
Server: 1.10-R0.1-SNAPSHOT
Test command that doesn't work:
```command /test:
  trigger:
    shoot arrow at speed 5 from player```

**Comment by TheBentoBox** [comment]
You have it wrong. This is the syntax for the event from Bensku's documentation:

```
shoot %entitydatas% [from %livingentities/locations%] [(at|with) (speed|velocity) %-number%] [%-direction%]
```

You'll notice the option entity to shoot it from comes BEFORE the speed. The order matters, you can't just rearrange them however you want. It should be `shoot arrow from player at speed 5` (it makes more sense in that order too, IMO).

**Comment by bensku** [comment]
Skript does have English-like syntax, but it is **not** natural language. While your way to write this effect is grammatically correct English, it is not valid Skript effect.
