### ISSUE TITLE
= != < >

### ISSUE THREAD

**Issue by Isabaella** [bensku/Skript#205]
Hi there.

There's this feature to shorten "is", "is not" etc. in skQuery (using =, !=, <, > etc).

If this is not already in the fork, I'd appreciate it.

~ Bella

(long post i know)

**Comment by TheBentoBox** [comment]
Looking at the Comparison condition on [the fork's documentation](http://bensku.github.io/Skript/conditions.html), it looks like those are already implemented in Skript. It actually says they've been in since 1.0 (but I've never tried it without SkQuery).

**Comment by JKGamerxD** [comment]
SkQuery's comparison shorten methods:
```
%object% == %object%
%object% === %object%
%object% > %object%
%object% < %object%
%object% >= %object%
%object% <= %object%
```

Skript's comparison shorten methods:
```
%objects% > %objects%
%objects% >= %objects%
%objects% < %objects%
%objects% <= %objects%
%objects% != %objects%
%objects% = %objects%
%objects% < %objects%
```

**Comment by Isabaella** [comment]
Documentation's quite hard to read.
https://gyazo.com/72a17ef3545cbba5c25a0dcd0f15776b

**Comment by bensku** [comment]
Whelp, I guess Github Pages does not send UTF-8 HTTP header after all... Oops

Will be fixed when I get script running well enough to re-generate documentation (then I need only add single line in template).

**Comment by GoodmanSIG** [comment]
`if {sk.generator.%player%} >= "1":`
Can not distinguish :( How to treat it differently?

**Comment by TheBentoBox** [comment]
This is definitely not the place to ask that @GoodmanSIG , ask on the skUnity forums.
