### ISSUE TITLE
No message when clicking a villager

### ISSUE THREAD

**Issue by FightingDEV** [bensku/Skript#207]
```
on right click on villager:
    message "1" to player

on right click on living entity:
    message "1" to player

on right click on entity:
    message "1" to player
```

Also tried "to the player", "rightclick/right click", "broadcast"

**Comment by Weefle** [comment]
try removing "to player"

**Comment by TheBentoBox** [comment]
No @Weefle, you need to specify `to player` in most events involving extra entities, otherwise it often sends it to the `event-entity`, which is not the player. That is most certainly not the issue -- it's never going to hurt to have been MORE specific.

**Comment by Weefle** [comment]
It works fine with Skript 2.2 V8b

**Comment by bensku** [comment]
Uh. Villager click event itself is probably broken, not the message.

**Comment by TheBentoBox** [comment]
Please see #311, which is more updated and represents more issues.
