### ISSUE TITLE
Timings dont Work on Windows

### ISSUE THREAD

**Issue by sapphyrus** [bensku/Skript#211]
**Console Error:**
http://hastebin.com/poqojunoxa.sql

**Version:**
[Newest Version from GitHub relases](https://github.com/bensku/Skript/releases/tag/dev20b)

**Comment by bensku** [comment]
Wait what. I'll need to test this on Windows at some point.

Anyway, I strongly advise running any server applications on Linux/anything that is not Windows. At least unless you have expensive Windows Server license.

**Comment by sapphyrus** [comment]
Yeah, we have a license and the manager wanted to use windows. Can you change the log message to something like `[Skript] Timings stopped and results written to "Server/plugins/Skript/timings/..."`?

**Comment by bensku** [comment]
Ok, figured out what was wrong. Apparently Windows can't handle <code>:</code> in file names.

Meanwhile, on Unix/Linux you can even have ASCII beep...
