### ISSUE TITLE
why isn't this working??!

### ISSUE THREAD

**Issue by Isabaella** [bensku/Skript#212]
I'm not sure why this is not working. 

What's not working? Look: Everybody wants you doing stuff for them. The not working part is their gratitude. Most people don't even think about thanking you! 

This one's for you, Bensku! Thank you :heart: for publishing your versions of Skript, keeping it up to date and looking into every reported issue, request or suggestion! You probably don't know how many people are using it the whole time (without taking a look at metrics of course). I'm glad good people like you exist and keep it going. 

I would make a :cake: for you, but as we all know, the :cake: is a ~~lie~~ pie.

:two_hearts:

**Comment by bensku** [comment]
Thanks! But since this is issue tracker after all, I'll close this.. at some point :)

**Comment by Isabaella** [comment]
:(

**Comment by Pilvinen** [comment]
For future reference you can post any thanks/discussion/feedback about Bensku's Skript fork here in the appropriate forums:

https://forums.skunity.com/t/benskus-fork-skript-for-minecraft-1-9-1-10/4588

Thank you.
