### ISSUE TITLE
Sorting by numbers + alphabetically

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#213]
Asking for a simple solution to sorting / ordering a list by numbers from highest to lowest (and from lowest to highest) AND alphabetically.
See my thread: https://forums.skunity.com/t/sort-a-list-by-numbers-and-alphabetically/10584

**Comment by JKGamerxD** [comment]
It's already possible as I can see on the thread, also there is the `sorted %objects%` expression, that @bensku may add index support for list variables

**Comment by bloggy** [comment]
As mentioned in the thread there is only 1 option to sort numbers in a list and this method is pretty old and inefficient and sometimes even causes lags. The other solutions are inacceptable because they are way to circuitous. I really hope that bensku can add a simple, efficient sorting method for list variables.

Something like:

set {_sortedlist::*} to sort ascending {_unsortedlist::*}
set {_sortedlist::*} to sort descending {_unsortedlist::*}

**Comment by bensku** [comment]
Using object sorting, you will recieve objects back in natural order. What that is depends on type of objects... For numbers, from smallest to biggest. For strings, from A to Z.

**Comment by bloggy** [comment]
It would be great if you'd find a solution because without number sorting I am unable to create toplists.

**Comment by TheLimeGlass** [comment]
@bensku This was added right?

**Comment by bensku** [comment]
Yeah, this was kinda added. Sorting by values destroys keys (sorted expression), and every list is sorted by keys currently.

**Comment by bloggy** [comment]
Any example for a simple toplist with list variables?
