### ISSUE TITLE
GUIs (open chest) are very buggy / unrelieable

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#214]
```
command /sktest:
trigger:
  wait 1 tick
  open chest with 3 row named "<gold>Menge wählen" to player
  format slot 1 of player with black stained glass to close and run "sktest"
```

Now when you do this and click on the black stained glass a few times, you will notice that you can take out the item from the gui and put it into your inventory.
This is because of the "wait 1 tick". Now if you change it to "wait 5 ticks" it works like a charm.
But for some GUIs I need them to open instantly (1 tick is ok, but not more).

Could you please fix this issue which is around since ... years?

Thanks a lot in advance :)

**Comment by Isabaella** [comment]
That's not a Skript issue (it's skQuery). Additionally, the delay needs to be between `open chest` and `format slot` and at least on 3 ticks. TIP: TuSke has a great GUI manager.

**Comment by bensku** [comment]
Yep, Skript has no support for creating inventory GUIs, nor do I consider this something that should be added in near future.
