### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by ProgrammingWizzard** [bensku/Skript#215]
This error occurs when the issue of "loop all players." Without this line everything works without any problems.
Error: http://pastebin.com/7tdmLX1b

**Comment by bensku** [comment]
What Skript version and what server version? This is something that should never ever happen with recent Spigot+Skript.

**Comment by ProgrammingWizzard** [comment]
Skript v2.2-dev20
Spigot 1.10

**Comment by TheBentoBox** [comment]
@ProgrammingWizzard Are you still experiencing this?
