### ISSUE TITLE
Inventory.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#217]
Add events:
On inventory [open or close]
On jump

P.S You planed to add the format slot?

**Comment by JKGamerxD** [comment]
1. The format slot is of SkQuery and it's not really efficient.
2. The `inventory open` and `close` event was suggested before.
3. It maybe can be a good idea but not at all.

**Comment by FUZIK** [comment]
If used a WildSkript:
```
on inventory close: 
    send "Close"
```
------------------
[OPEN INVENTORY]
[CLOSE INVENTORY]
[MESSAGE: Close]

**Comment by FUZIK** [comment]
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryOpenEvent.html

**Comment by bensku** [comment]
Enhancement - adding inventory open event for next release.
