### ISSUE TITLE
Request: Get amount of crafted items from "On Craft" event.

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#218]
It would be great if we could get the total amount of crafted items from an "on craft" event. At the moment it only counts 1 even if the player produces 64x of an item.

**Comment by JKGamerxD** [comment]
Have you tried using the `amount of` expression?

**Comment by bensku** [comment]
@bloggy Have you tried <code>amount of</code>?

**Comment by bensku** [comment]
@bloggy Asking again. Doesn't the expression work?

**Comment by Snow-Pyon** [comment]
Now you could just use:
```
item amount of event-item
```

**Comment by Snow-Pyon** [comment]
Sorry for bumping this again but as said above, there is an item amount expression now so this can be closed.
