### ISSUE TITLE
Inventory click

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#219]
Hello I was trying to deny the player to change the place of some special item of a kit in the player's inventory with this line of code

if clicked item is any helmet:

But it return this error in the console

[Skript] Can't compare 'clicked item' with an item type (PvPBoxN.sk, line 719: if clicked item is any helmet:')

Can you help me (I'm in 1.10) ?

Thanks in advance :)

**Comment by JKGamerxD** [comment]
The `clicked item` expression is of Umbaska, the `clicked item` in this Skript version is the `event-slot`

**Comment by ZeTioZ** [comment]
So can I do

if event-slot is named "name":
    *stuff*

?

**Comment by bensku** [comment]
No of that. Instead: <code>if event-slot is <insert slot name, for example helmet> of player:</code>

**Comment by KroterPvP** [comment]
I need to check if clicked slot is 11.
using "if clicked slot is 11" doesn't run without addon.
using "if event-slot is 11:" doesn't run
...

**Comment by Snow-Pyon** [comment]
why don't you just check for the item type and/or name? You should ask that on the forums or the #skript-help discord channel anyways.
