### ISSUE TITLE
Inventory items counting: MANY items concerned

### ISSUE THREAD

**Issue by Guarmanda** [bensku/Skript#223]
When typing
"set {_amountair} to number of air in event-inventory"
"set {_number} to number of items in event-inventory - {_amountair}",
 many blocks won't be set in the {_number} variable. BUT: we can still counting an uncounted block by doing that:
"add number of 159 in event-inventory to {_number}" (159 is stained clay)
Many items are concerned: all coloured glass and wool, stained clay, all types of wood, planks, saplings, leaves, eccept oak items, red sand, wet sponge, all 1.8 stones, (granite, diorite ect), all sandstone eccept basic one, all flowers eccept the two first flowers, any monster egg blocks, any special stone (stonebrick, mossi stone brick, cobblestone, some quartz blocks, banners, heads, notch apples, and so much thing I didn't try...

This problem can be solved by counting 1.8 items 1 by 1, but it's LOOOOOOOONG!:
"set {_amountair} to number of air in event-inventory"
"set {_amountstone} to number of stone in event-inventory"
"set {_amountwool} to number of stone in event-inventory"
"set {_number} to (number of items in event-inventory - {_amountair})- ({_amountstone} + {_amountwool})",
"add number of 1 in event-inventory to {_number}"
"add number of 159 in event-inventory to {_number}"
"add number of 35 in event-inventory to {_number}"
and so one...

**Comment by F8te** [comment]
Maybe it's because your aliases, check if you have the latest aliases.

**Comment by Guarmanda** [comment]
Mmm I installed that plugin two days ago, should I find aliases manually then relace my folder?

**Comment by Guarmanda** [comment]
Oh and that's strange since skript knows the names of these items. when I put all items in a variable, or all id of items, and then put that variable in a message, all their name/id shows correctly. But I cant count items by using a variable :/ or I didn't find how^^

**Comment by bensku** [comment]
@tim740 Could this be related to aliases?

**Comment by Guarmanda** [comment]
I just checked aliases and found that (see below). I think if it was related to aliases, skript would correctly count special stones, and he doesn't...	
        stone¦s = 1
	granite = 1:1
	polished(_| )granite = 1:2
	diorite = 1:3
	polished(_| )diorite = 1:4
	andesite = 1:5
	polished(_| )andesite = 1:6

**Comment by Guarmanda** [comment]
MOUAHAHA I FINALLY GET IT WORKS:
		set {_number.of.items} to 0
		set {id} to 0
		set {id} to {id} parsed as integer
		while {id} is less than 54:
			set {_item} to "%slot {id} of event-inventory%" parsed as item
			add number of {_item} in event-inventory to {_number.of.items}
		set {_items} to {_number.of.items}/54 #54= number of slots in the chest
		message "There is %{_items}% in the chest"
That code is really weird for me, I did random tests to find it, but he gives the REAL amount of items in the chest with ALL items, and without counting air.

**Comment by TheBentoBox** [comment]
I can't even reproduce this, but it seems resolved anyways.
