### ISSUE TITLE
effect.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#225]
add effect -
```
on skript start:
  run script at "reboot-server.sh"
```

**Comment by F8te** [comment]
It's already on SkUtilities and I don't think it would be a really useful feature for vanilla Skript.

**Comment by bensku** [comment]
Closed, I know, but still commenting.

This is nothing that would be good for Vanilla script. Can do too evil stuff if script is malicious. Far worse that just ruin your worlds...
