### ISSUE TITLE
Request: `on ground` expression

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#226]
```
please add expressions:
    player is on ground and player is not on ground
```

hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Entity.html#isOnGround()

**Comment by bensku** [comment]
Good idea. I'm drowning in work, though...

**Comment by FUZIK** [comment]
> Good idea. I'm drowning in work, though...
;D

**Comment by FUZIK** [comment]
Как я вас понимаю... И как вы умудряетесь держать это в голове?

**Comment by itismejoey** [comment]
@FUZIK - You might get faster support with this by asking an addon dev to add this. Head on over to [skUnity](http://forums.skunity.com) and ask a developer (i would suggest Skellett or TuSKe).

**Comment by FUZIK** [comment]
I think that this garbage and addons I use only MundoSk.

**Comment by itismejoey** [comment]
Maybe you're new to this community (or not even in it at all), but Skript isn't all about cramming everything into the core plugin. It's about allowing other developers to create features using addons. 

So, you can either wait for a long period of time for Bensku to create the expression, or a few days for another dev. Your call.

**Comment by FUZIK** [comment]
I realize a lot with the help of MundoSk and packages. But you're right!
And what addon advise to create a GUI?

**Comment by itismejoey** [comment]
I personally haven't used it yet, but TuSKe recreated the format slot that we all know and love.

**Comment by bensku** [comment]
Well, originally Skript was about throwing most stuff to core plugin. But I just don't have enough time to do that :)
