### ISSUE TITLE
bug on using sign.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#229]
```
on click on sign:
    send "click sign"
    line 1 of event-block is ""
    send "line 1: true"
    line 2 of event-block is ""
    send "line 2: true"
    line 3 of event-block is ""
    send "line 3: true"
    line 4 of event-block is not set
    send "line 4: true"
```

![image](https://cloud.githubusercontent.com/assets/15977008/19933874/e7207ca4-a125-11e6-9cab-791e7a1649f1.png)

**Comment by bensku** [comment]
This is not bug. Line of sign is never "not set", it just contains nothing when you didn't type anything on placing it.
