### ISSUE TITLE
on right click holding player head - broken!

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#23]
```
on right click holding player head:
   broadcast "Test"
```

It does not work for me anymore! Worked in 1.8 without problems!
No console errors at all.

And it works with nfells' 1.9 Skript (just tried)

**Comment by bensku** [comment]
Hmm... Do you get any errors? Or is it just that it doesn't work?
And does "on right click with player head" work?

**Comment by bloggy** [comment]
No errors at all. 
Nothing with "on right click" works.

**Comment by Pilvinen** [comment]
I tested this on dev9.

1) /give YourNameHere playerhead 1 player:Pilvinen
2) Hold the head
3) Run this code:

```
on right click:
  tool of player is player head         
  broadcast " DEBUG: 1"

on right click holding player head:
 broadcast " DEBUG: 2"       
```

I get BOTH debug messages. It seems to be working fine.

Are you sure you have tried the latest version of bensku's fixes, dev9? I'm unable to reproduce this bug.

**Comment by bensku** [comment]
Yeah, dev9 is currently most stable version. There are some bugs, sure, but way less than in other versions. I do not and will not support old pre-releases.

**Comment by bensku** [comment]
It seems this is not issue since you @bloggy didn't comment. Please open new issue if it happens again.
