### ISSUE TITLE
The latest release of Skript breaks a lot of things (log attached)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#232]
Just tried updating to your latest available Skript version and this is what the console says:

http://hastebin.com/funurevato.coffeescript

Wow :-)

Hope it helps you to fix the issues. Let me know if you need any more information!
Thanks for your hard work!

**Comment by F8te** [comment]
Please read the issue #227 and the update notes of that update. It's a beta update for the parser, so, there are some bugs that hope bensku could fix in a future release.

**Comment by bensku** [comment]
Wow, there is a race conditions. Note to self, ise ConcurrentHashMap.

And then it looks like that some addon also broke. Will see that too

**Comment by bensku** [comment]
Most of this, apart from log spam (did it happen with older versions?) should be fixed. But I'm fixing some more stuff before next build.

After all, Spigot 1.11 is not there, yet. Final release will come a bit after that regardless of anything else.

**Comment by bloggy** [comment]
So I checked your latest 1.11 rdy version and still skript is spamming errors in my console which I never had before. Here is only a very small part from my logs:

http://hastebin.com/yeceveyuvo.sql

http://hastebin.com/mujofijaxe.coffeescript

Hope it helps you to fix these issues.

**Comment by bensku** [comment]
What addons do you have installed? Lines giving errors are apparently not of Skript syntax.

**Comment by F8te** [comment]
@bensku Apparently he is using Skellett and SkQuery as I can see on that logs.

**Comment by bensku** [comment]
Oops, should have found out that myself. Anyway.

**Comment by bloggy** [comment]
My issue still exist, I don't know what to do.
Latest log:
https://hastebin.com/oyayevoqot.coffeescript

I am using all latest available versions of every skript addon that I found.

My current addon list:
- Skellett
- skQuery 1.11 LimeGlass Version
- TuSKe
- SkStuff
- skRayFall

**Comment by TheBentoBox** [comment]
You have a lot of issues with "can't understand condition/effect", which would imply that the addons which those effects are from are possibly not loading properly. Have you tried checking higher up in your startup log to see if those addons are starting up properly?

**Comment by bloggy** [comment]
Thankyou @TheBentoBox you are leading me in the right direction - appreciate your help!
Now I found that in the logs:

https://hastebin.com/ocasuqipiy.vbs

But what now?

**Comment by bloggy** [comment]
Update: Have this error fixed. But still many errors that I have to sort out now. Will report back soon!

**Comment by bloggy** [comment]
Ok, I think I have this fixed, not skript's fault!
