### ISSUE TITLE
Very strange bug: Storing an item into a variable, skript sometimes losing the "amount" information

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#235]
I have described the bug here (with screenshots) and example script:
https://forums.skunity.com/t/help-me-with-a-very-strange-bug/10980

Please take a look at it.

**Comment by bensku** [comment]
Hmm, I guess <code>ItemType</code> is not storing data that accurately after all.

**Comment by bensku** [comment]
Still happens?

**Comment by Snow-Pyon** [comment]
No response, closing.
