### ISSUE TITLE
Problem at first launch of skript

### ISSUE THREAD

**Issue by Weefle** [bensku/Skript#245]
So I do not know if this has ever been reported but at the first launch of skript 2.2-dev21c, if I add a skript to the list and I reload them all with skript, it does not work.
Then I have to do a reload (= NullPointerException) or a restart for it to work!
Please solve this problem.
I love your work!

**Comment by F8te** [comment]
the releases up to the dev20b are marked as unstable, don't use it if it's not for your test server.

Also, please provide which errors you had exactly, so, that maybe can help to bensku for fix the issue.

**Comment by Weefle** [comment]
But there is no error, the skripts not working at the first launch!

**Comment by bensku** [comment]
I would still like to see your server log, even if you think there are no errors.

**Comment by Weefle** [comment]
Look here: http://hastebin.com/migavicacu.md

**Comment by F8te** [comment]
@Weefle it's not the whole log, please show us the whole log.

**Comment by Weefle** [comment]
Lol now there are new errors when I enable all: http://hastebin.com/luvafolula.md

**Comment by Weefle** [comment]
The latest update has broken the bug

**Comment by bensku** [comment]
It is another way to say it fixes the bug, I hope? Very good.
