### ISSUE TITLE
Issue reloading scripts

### ISSUE THREAD

**Issue by Defterdar** [bensku/Skript#247]
Just a 'fyi'

Adding a "non working script" to Skript will cause it to not reload scripts properly.
Removing all scripts dosen't fix the problem - only restarting the server will fix it.
I guess that something is hanging in the background and thats why Skript isn't able to reload.

**Comment by bensku** [comment]
Hmm... That seems likely. I'll take look once the big issue is out of the way.

**Comment by bensku** [comment]
Need more information. What is non-working script?

**Comment by Defterdar** [comment]
i happend when a added a script, which needed another addon to function, which was not updated yet so therefore not in my pluginlist (some function from skrayfall i guess).

**Comment by bensku** [comment]
Ah. If you have incompatible addon installed, it causes weird stuff. And it is hard to prevent everything, so...
