### ISSUE TITLE
Scripts fail to load, multiple errors reported

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#248]
I have a small collection of scripts. In general, those with commands do not load. The error messages refer to lines that make little sense, and refer to constructs that look correct. All of them load and run correctly on Spigot 1.10.2 and Njol's Skript 2.1.2. For example:

[dump-garbage.sk.txt](https://github.com/bensku/Skript/files/601651/dump-garbage.sk.txt)

[dump-garbage.errors.txt](https://github.com/bensku/Skript/files/601652/dump-garbage.errors.txt)

**Comment by bensku** [comment]
This is due to lists being buggy. Please fall back to dev20b or if running 1.11, just wait.

**Comment by SlimeDog** [comment]
I just noticed that the errors are because skript is delving into the ./plugins/Skript/scripts/RCS/ directory. I will (re)move that, and keep testing. Apologies.

**Comment by bensku** [comment]
Yep, you can throw your scripts into subfolders :) Might be useful.
