### ISSUE TITLE
The expression 'argument' can only be used within a command

### ISSUE THREAD

**Issue by cyanide43** [bensku/Skript#250]
This works on old Skript 2.2 but fails on your build. How do I get this to work on your version?

```
on chat:
	set {_waited} to difference between {spam.%player%.lastused} and now
	if player doesn't have permission "skript.spam":
		if {_waited} is less than 1 second:
			cancel event
			message "&2> &aChat: &7Don't spam! Wait 1 second to chat again."
			stop
		set {spam.%player%.lastused} to now
```

EDIT: The skript works, but I'm having tons of issues with errors even though all the skripts work as intended.

**Comment by Pilvinen** [comment]
The code you pasted doesn't have an "argument". Did you paste wrong part of the skript? It would help to see the whole actual error in figuring out the problem. Also if you're using Skript for 1.11, don't. It's only for testing - for now.

**Comment by cyanide43** [comment]
The issue I have seems to be something totally different from what I initially thought--but there were still errors coming from this skript bizarrely.

The issues I'm having all have to do with using <offline player> and join and leave events. Here is the message I am receiving that crashes skript: "An error happened when trying to enably resolving offline players, so the feature has been turned off."

**Comment by bensku** [comment]
Ah. Something is broken with offline player resolver, I fear.

**Comment by Snow-Pyon** [comment]
Is this fixed now or should this be closed? Not too sure what was the issue here.
