### ISSUE TITLE
On Command Don't Catch Command From Skript

### ISSUE THREAD

**Issue by onenrico** [bensku/Skript#251]

**Comment by F8te** [comment]
That is obvious and it's explained on every Skript docs, it's because you could just edit the command from the file instead of use the `on command` event for it.

**Comment by bensku** [comment]
As said above.

**Comment by onenrico** [comment]
ups sorry i just solved the problem , that because i setting plugin priority to highest , 
i use [on command] to make commandwatcher.sk :D
