### ISSUE TITLE
Prepare two different builds

### ISSUE THREAD

**Issue by bensku** [bensku/Skript#252]
Due to amount of changes in new parser, especially with addons, I have decided to modularize Skript build system. This will allow me to easily add new expression, effects etc. and release "legacy" and new versions. This would have been done anyway, but I decided to do it *right now* for 1.11 update.

- [ ] Modularize Skript components using Gradle
- [x] Do few little changes to old parser
- [x] Do few changes in new parser
- [x] Add 1.11 features
- [ ] Release

Note that 1.11 functionality is still mostly WIP, so this won't be here in few days.

**Comment by TheBentoBox** [comment]
I will add links on [my 1.11 checklist issue](https://github.com/bensku/Skript/issues/203) to relevant API release/change commits from the Spigot repo so you can do the `Add 1.11 features` stage more quickly.

**Comment by bensku** [comment]
Well, oops. Instead of using Gradle, I "modularized" Skript using bash scripts.
