### ISSUE TITLE
if {total} is 1000: [Checks for item id of 1000 not numeral value]

### ISSUE THREAD

**Issue by Jduffygames** [bensku/Skript#254]
**There doesn't exist a material with id 100000**! (-Achieve.sk, line 244: if **{{@databasePrefix}Achieveinfo.stats.player.%player's uuid%.place} is 100000:**')

Every time someone places a block, it adds one to {{@databasePrefix}Achieveinfo.stats.player.%player's uuid%.place}

**Comment by bensku** [comment]
I have been trying to track down these issues. Well, they do not appear anymote for *me*. And that means, thry do bot appear if I do not use any addons.

So, are you running some addons?

**Comment by Jduffygames** [comment]
Yes. 

- Skquery
- SkRayFall
- SkUtilities
- SkExtras
- RandomSK
