### ISSUE TITLE
Loop-player not working

### ISSUE THREAD

**Issue by Jduffygames** [bensku/Skript#255]
There's no loop that matches 'loop-player's balance' (-Achieve.sk, line 253: if loop-player's balance is more than 999999:

Code:
every 30 seconds:
	loop all players:
		if loop-player's balance is more than 999999:
			if {{@databasePrefix}Achieveinfo.%loop-player's uuid%.achieve.millionaire} is not set:
				execute console command "/giveachieve %loop-player% millionaire Millionaire"

**Comment by FUZIK** [comment]
```
every 1 seconds:
    loop all players:
        loop-player's balance > 999999
        {var.%loop-player%} is not set
        execute console command "/giveachieve %loop-player% millionaire Millionaire"
```
console:
There's no loop that matches 'loop-player balance' (test.sk, line 3: loop-player balance > 999999')

**Comment by F8te** [comment]
If you don't have Vault and a plugin for the economy (like Fe or Essentials) that expression wouldn't work.

**Comment by bensku** [comment]
Yep. @Jduffygames do you have Vault installed **in addition** to some random economy plugin.

**Comment by bensku** [comment]
No response -> closing.
