### ISSUE TITLE
!message, !give, !teleport, etc...

### ISSUE THREAD

**Issue by Jduffygames** [bensku/Skript#256]
Picture:
- https://gyazo.com/7ba0c7b8b3c6470f4998054f9d4483c0

Some things do work like !broadcast

**Comment by bensku** [comment]
I would like to see what is on console.

**Comment by Jduffygames** [comment]
Nothing appears in cobble.

**Comment by F8te** [comment]
In the console is the specific error, if you can provide your log could be useful.

**Comment by Jduffygames** [comment]
@F8te I looked at the console while typing it. Nothing appeared.

**Comment by GermanMinerDE** [comment]
@Jduffygames Possible, that you don't have the "skript.effectcommands"-Permission? OP doesn't make sense here.

**Comment by TheLimeGlass** [comment]
This is the same issue as https://github.com/bensku/Skript/issues/240

**Comment by bensku** [comment]
@TheLimeGlass Your issue is different, since you used effect from Skellett there.

@Jduffygames Make sure you have configured you to have permission to execute effect commands. Disabled by default even for OPs (for security reasons).

**Comment by Jduffygames** [comment]
@bensku I've never had it permission based, it's based on ops. It's always worked and now it does not.

**Comment by Jduffygames** [comment]
@bensku When will the next update be released?

**Comment by TheBentoBox** [comment]
This is now working for me.

**Comment by bensku** [comment]
Very good. @Jduffygames does it work for you?

**Comment by Jduffygames** [comment]
@bensku I use addons, so I can't test.
