### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Grimmy347** [bensku/Skript#258]
While you are fixing skript and updating/upgrading it, can you add the ability to specify a table to use for mysql databases along with the database so that you can keep your skripts separated?  Many server host only allow 1 mysql database but as many tables as you want.  This would be much cleaner than everything being added into variables21.  Thanks!!

**Comment by bensku** [comment]
Skript's MySQL support is not reliable anyway. At some point, rewrite of it is required anyway.

**Comment by Grimmy347** [comment]
SQLight will still have full support though right?  I am just trying to figure out the safest way to go with my variables for now until MySQL support is restored.

**Comment by bensku** [comment]
I personally haven't tested storate types much. On production CSV has been quite good, never losing any data. But as I said, I have not really touched that code (yet).

**Comment by Snow-Pyon** [comment]
The table specification has been added in one of the pull requests by Andrew so I think this can be closed now.

**Comment by TheBentoBox** [comment]
Yeah probably safe to close, since this is a very old issue and the support Andrew added is probably the best improvements we'll get anytime soon.
