### ISSUE TITLE
Maven error or just me?

### ISSUE THREAD

**Issue by Cla6** [bensku/Skript#260]
Hello folks, I tried compiling this plugin using Maven, and came to find that I couldn't.
This is what I got:
![image](https://cloud.githubusercontent.com/assets/23744347/20633140/b6539ca2-b343-11e6-8d3f-07de6f71679f.png)

Since I am rather new to GitHub, can anyone else tell me how to do it properly? Perhaps with another program? Or is there a download somewhere? I didn't seem to find the download for the latest version of this fork. Halp?

**Comment by F8te** [comment]
Here are all releases:
https://github.com/bensku/Skript/releases

Just click at the Skript.jar of the version that you want.

**Comment by Cla6** [comment]
Thankies <3
Appreciated (:

**Comment by bensku** [comment]
Skript is compiled with Gradle so no wonder wht this didn't work...
