### ISSUE TITLE
Various issues with new parser

### ISSUE THREAD

**Issue by RoyCurtis** [bensku/Skript#263]
I realize there are multiple issues on this and the title is vague, however I wasn't sure on how to report my experience with the new parser. Maybe it'd help if I recorded them in my own issue, such as this one.

These are the results of attempting to load and use [our collection of skripts for our Survival server](https://github.com/Gamealition/Survival-Skripts), with the new Skript parser. I do not use any Skript addons.

If you need a list of features this Skript collection provides, for testing purposes, [see this checklist.](https://github.com/Gamealition/Survival-Skripts/issues/2)

# Working setup

This is just the details of our currently working setup, wherein there are no Skript errors, for comparison.

* Skripts in use: [Survival-Skripts repository](https://github.com/Gamealition/Survival-Skripts)
    * No errors
    * `Loaded 20 scripts with a total of 59 triggers and 61 commands in 2.29 seconds`
* Live multiplayer PaperSpigot server for 1.10.2
    * Ubuntu 16.04.1 LTS server, 32GB RAM, 8 cores, no X11 server
    * `git-Paper-916.1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)`
    * `Plugins (31): CleanroomGenerator, CoreProtect, dynmap, WorldEdit, Skript, Titanic, zPermissions, Chairs, WorldBorder, ProtocolLib, Multiverse-Core, WorldGuard, NoCheatPlus, WoodCutter, Stables, Multiverse-SignPortals, HappyPet, SQLibrary, Multiverse-Portals, Vault, Prism, GTicketMaster, Essentials, PerWorldInventory, LWC, SignShop, VanishNoPacket, SignShopExport, CraftBook, Multiverse-NetherPortals, PurpleIRC`
* Skript version `2.2-dev20`
    * No Skript addons
    * MySQL database
    * [Skript `config.sk`](https://gist.github.com/RoyCurtis/517f878ba67e536e72b711045f2419ba)
    * [Custom `aliases-english.sk` file](https://gist.github.com/RoyCurtis/dff02abecaf7602624075e5fa514a85e)

# BETA server

This is our public BETA 1.11 server, which is a nightly copy of our stable 1.10.2 server.

* Skripts in use: [Survival-Skripts repository](https://github.com/Gamealition/Survival-Skripts)
    * Git repository and markdown files removed due to issue #257
    * [**Parser error log**](https://gist.github.com/RoyCurtis/2749ff7db69d5c233d27c24b6e65e6f2)
* Live testing PaperSpigot server for 1.11
    * Ubuntu 16.04.1 LTS server, 32GB RAM, 8 cores, no X11 server
    * `git-Paper-943 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
    * `Plugins (31): CoreProtect, CleanroomGenerator, dynmap, WorldEdit, Skript, Titanic, zPermissions, Chairs, WorldBorder, ProtocolLib, Multiverse-Core, WorldGuard, NoCheatPlus, WoodCutter, Stables, Multiverse-SignPortals, HappyPet, SQLibrary, Multiverse-Portals, Vault, Prism, GTicketMaster, Essentials, PerWorldInventory, LWC, SignShop, VanishNoPacket, SignShopExport, CraftBook, Multiverse-NetherPortals, PurpleIRC`
* Skript version `dev22b`
    * No Skript addons
    * MySQL database
    * [Skript `config.sk`](https://gist.github.com/RoyCurtis/517f878ba67e536e72b711045f2419ba)
    * [Custom `aliases-english.sk` file](https://gist.github.com/RoyCurtis/dff02abecaf7602624075e5fa514a85e)

# Local testing server

This is my local testing server. Mostly uses defaults.

* Skripts in use: [Survival-Skripts repository](https://github.com/Gamealition/Survival-Skripts)
    * Git repository and markdown files removed due to issue #257
    * [**Parser error log**](https://gist.github.com/RoyCurtis/1fefb4a40c578a8194545d31b97dbcf6)
* Local Spigot server for 1.11
    * Windows 10, 16GB RAM, 8 cores, command line
    * `CraftBukkit version git-Spigot-f950f8e-1c07d5c (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
    * `Plugins (3): Skript, Vault, Essentials`
* Skript version `dev22b`
    * No Skript addons
    * CSV database
    * Default Skript `config.sk`
    * Default Skript `aliases-english.sk`

-----

If there's anything specific to these logs that you'd like tested, debugged or more info on, please ask!

**Comment by SlimeDog** [comment]
After adding 1.11 blocks and entities the _aliases-english.sk_:

`...
	acacia door = 431
	splash potion = 438
	lingering potion = 441
	dark oak boat = 448`
most materials are recognized, but console/log reports:
`[07:47:24] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441`

**Comment by bensku** [comment]
New parser has probably nothing to do with aliases weirdness. It has always been quite... interesting code.

@RoyCurtis I have invited you as collaborator. You should see experimental release using old parser (from branch oldparser) there. For everyone else, it can be found on #random at Skript Discord.

**Comment by RoyCurtis** [comment]
Thanks! I appreciate the invite. I can give the old parser a try for 1.11 testing.

**Comment by RoyCurtis** [comment]
With the old parser, all the scripts appear to load fine without error. But I need to make a new checklist of 1.11 features and make sure they all work. If any bugs are found, I will create new issues.

If curious, here is the debug log: https://gist.github.com/RoyCurtis/cb04289d2005dbfd72cfad3e11388a45

**Comment by SlimeDog** [comment]
(New) old parser in dev22c works fine. All scripts load without error, and execute correctly.

On startup, I still get:
`[07:47:24] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441`
These are defined in _aliases-english.sk_. But small price to pay for working scripts. Yay!

**Comment by melinstagibson** [comment]
Can i use dev22c with the new parser? I dont like sticking to outdated
things now that i squashed all bugs besides the annoying "WARNS"

Am 30.11.2016 4:59 nachm. schrieb "SlimeDog" <notifications@github.com>:

**Comment by bensku** [comment]
I will build and release new parser version after squashing few more bugs. In meantime, you can compile it yourself quite easily.
