### ISSUE TITLE
No longer able to use the GUI window

### ISSUE THREAD

**Issue by Legoman99573** [bensku/Skript#264]
It seems that when i use `to close then run` it just wont register that item anymore and works when i take the `then run` out, it works in the GUI Window. Is there a new format to do this or is it broken in general?

**Comment by TheBentoBox** [comment]
That effect is not from vanilla Skript, it's added by an addon (either SkQuery or TuSKe depending on if you're using the old `format slot` or the newer `format gui slot`, respectively). This isn't the place to report issues with non-vanilla Skript syntaxes.

**Comment by Legoman99573** [comment]
thought it was a part of the main skript plugin
ill close it
