### ISSUE TITLE
Skript Mysql Issue

### ISSUE THREAD

**Issue by paxoboy** [bensku/Skript#267]
hi i have been haveing issues of skript not saveing variables into my mysql database it creates the table just fine but it dosssent inport them into the database any ideas?

**Comment by Weefle** [comment]
Details please!
Screen, hastebin link, versions?

**Comment by bensku** [comment]
It sounds quige likely that MySQL doesn't work very well. But I have database experience so...

**Comment by TheBentoBox** [comment]
@paxoboy Can you please provide more details as Weefle suggested? We can't help with vague information about versions.

**Comment by TheBentoBox** [comment]
No reporter response over 2 weeks after asking for clarification.
