### ISSUE TITLE
on breaking tool, break)

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#269]
my english speaking is 0,0001 level and i upload a gif file.
GIF: i.yapx.ru/FNo4.gif
```
on breaking tool:
    send "tool: %event-item%"
    send "item: %event-item%"
    wait a tick
    send "%event-item%"
    send "%event-item%"
```

**Comment by FUZIK** [comment]
MC: 1.11 SK: dev22c

**Comment by bensku** [comment]
Working as intended. Event-item refers to slot where item is during the event. After event has passed, tool has broken so it is no longer there. You might want to save event-item to local variable like
<code>set {_item} to event-item</code>
before using wait.
