### ISSUE TITLE
Error referencing clicked entity in click events

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#273]
Hey

I'm not really sure what's going on, nobody else has complained about having this issue as far as I can see, but I can't use the `clicked entity` expression in click events anymore. [This screenshot should show all of the important info](https://gyazo.com/64649009f53481f8e8901aef164dd734). This is the script I'm testing with:

```
on right click on living entity:
	send "%clicked entity%"
```

As you can see, my Spigot jar is recent, I'm using 22d, and this is happening with no other plugins ([or scripts](https://gyazo.com/37c121b66b7925f34ee8233ca6cacf1b)) running. I'm pretty stumped as to why, I feel like it might be something with the hacky compilation method for the old parser in conjunction with the large changes to entities in 1.11. But I still imagine other people would be complaining about this issue if it wasn't just me.

Cheers.

**Comment by Weefle** [comment]
Yep, I confirm

**Comment by bensku** [comment]
Tested and doesn't work. Won't be fixed for today's release, but hopefully soon.

**Comment by TheBentoBox** [comment]
Thanks Bensku, think this is the last thing I need fixed before being able to update to 1.11 (it breaks a lot of events!) so I'll be excited to see it. Cheers!

**Comment by bensku** [comment]
Fixed. 1.11 changed the event that was used from PlayerInteractEvent to PlayerInteract**At**Event.
