### ISSUE TITLE
on weather change event doesn't work

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#276]
On older versions, the weather change event used to work with: on weather change to rain, to sun, to thunder...
Now it only works with "to sun".
I'm using 2.2-dev21c (the latest builds don't work anything for me)

**Comment by DontKillCZ** [comment]
That's right.

**Comment by bensku** [comment]
I do not provide support for build that I have warned to be unstable. Why cannot you use latest builds?

**Comment by bensku** [comment]
I have verified this works with latest Skript. Please open new issue for your problem with latest Skript.
