### ISSUE TITLE
Skripts not reloading

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#279]
Hi,

don't know, if this is a bug related to the new update. We used dev20b before and since yesterday Skripts aren't reloading, but when starting the server every Skript loads fine.

Here's the error, that occurs:

`‎23‎:‎17‎:‎48 CONSOLE: [INFO] SchmidtMax issued server command: /skript reload 03chat_check
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! [Skript] Severe Error:
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! Exception occurred in Skript's main command
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! Used command: /skript reload 03chat_check
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! and check whether this error has already been reported.
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! By following this guide fixing the error should be easy and done fast.
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! Stack trace:
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! java.lang.NullPointerException
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at ch.njol.skript.lang.function.Functions.clearFunctions(Functions.java:264)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.removeTriggers(SkriptEventHandler.java:255)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at ch.njol.skript.ScriptLoader.unloadScript_(ScriptLoader.java:713)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at ch.njol.skript.ScriptLoader.unloadScript(ScriptLoader.java:706)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:165)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
‎23‎:‎17‎:‎48 CONSOLE: ERROR]: #!#! at java.lang.Thread.run(Thread.java:745)
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Version Information:
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Skript: 2.2-dev22e
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Bukkit: 1.10.2-R0.1-SNAPSHOT
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Minecraft: 1.10.2
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13)
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! OS: Windows Server 2012 R2 amd64 6.3
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Running CraftBukkit: false
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Current node: null
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Current item: null
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Thread: Server thread
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! End of Error.
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#!
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! List of plugins: 
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Projangtile - 0.05, HelicoptersFlag - 1.0, iConomy_Recreation - 8.0, GroupManager - 2.0.1-b332, PlaceholderAPI - 2.6.0, Vehicles - 7.6, PlugMan - 2.1.1, BookSuite - 4.0.2, NametagEdit - 4.1.2, AdminMode_Advanced - 1.2, NoPlayerPushing - BETA-1.3, ViaVersion - 1.0.1, ViaBackwards - 2.0, dynmap - 2.3-1142, WorldEdit - 6.1.3;7a097ca, BukkitCompat - R22A, CrackShot - 0.98.5, WorldBorder - 1.8.5, BuycraftX - 10.1.3, Votifier - 1.9, Multiverse-Core - 2.5.0-SNAPSHOT-b722, ProtocolLib - 4.0.1, ResourcePackApi - 2.2.1, CrackShotPlus - 1.12, eZProtector - 4.1.3, MVdWPlaceholderAPI - 1.0.0, CloudBot - 2.1.4, FeatherBoard - 3.15.0, SQLibrary - 7.1, UltraCommand - 0.4.6, Vault - 1.5.6-b49, BGUILib - 1.0.1, UltraCosmetics - 2.3.9, LogBlock - 1.94, ForceResourcePack - 1.1.2, HolographicDisplays - 2.2.1, LWC - 4.5.0-SNAPSHOT, WorldGuard - 6.1.3-SNAPSHOT;1685-9cafb07, ChestCommands - 3.1.4, afkTerminator - 3.0.8, AreaShop - 2.4.0, DynamicStands - 1.5.2, Essentials - 2.0.1-b434, ArmorStandEditor - 1.9-0.1.7BETA, Jobs - 3.6.2, HeadDatabase - 2.3.2, LWC_Tools - 1.5.1.1, BannerMaker - 1.4.3, Citizens - 2.0.20-SNAPSHOT (build 1420), BlockBall - 3.4.0, Magic - 6.2.3, OnTime - 4.1.4, EssentialsChat - 2.0.1-b434, CraftBook - 3.9-SNAPSHOT, CS-CoreLib - 1.5.12, Quests - 2.7.3-b117, EssentialsProtect - 2.0.1-b434, EssentialsGeoIP - 2.0.1-b434, EssentialsSpawn - 2.0.1-b434, PremiumVanish - 1.7.0, TuSKe - 1.5.9, Skript - 2.2-dev22e, LargeSk - 1.2-Beta, ExertSK - 0.1.3b, ExtrasSK - 1.1, SkAction - 1.0, skRayFall - 1.9.5, Umbaska - 2.0 Beta 5.5.1 for Minecraft 1.10, skDragon - 0.12.1, SkQuery - 3.5.1, SkStuff - 1.6.3.6, Skellett - 1.6.0, MundoSK - 1.7.2, WildSkript - 1.9, skUtilities - 0.7.8, SharpSK - 1.5.3, RandomSK - 2.7.1
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#!
‎23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! List of addons: 
23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! Skellett v1.6.0skRayFall v1.9.5SharpSK v1.5.3MundoSK v1.7.2WildSkript v1.9ExertSK v0.1.3bskDragon v0.12.1skUtilities v0.7.8Umbaska v2.0 Beta 5.5.1 for Minecraft 1.10SkQuery v3.5.1ExtrasSK v1.1TuSKe v1.5.9RandomSK v2.7.1SkAction v1.0SkStuff v1.6.3.6
23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! 
23‎:‎17‎:‎49 CONSOLE: ERROR]: #!#! `

**Comment by GermanMinerDE** [comment]
Edit: Is only with the new version of Skript.

**Comment by bensku** [comment]
Does this happen with dev22d?

**Comment by GermanMinerDE** [comment]
Happened on dev22e yesterday.

Von meinem iPhone gesendet

Am 06.12.2016 um 17:37 schrieb bensku <notifications@github.com<mailto:notifications@github.com>>:


Does this happen with dev22d?

-

**Comment by bensku** [comment]
I know this happends with dev22e. I mean, I want to know if this is a new bug in dev22e, or older bug.

**Comment by GermanMinerDE** [comment]
We Tested 22d few days ago. I think, it was the same there + spamming PlayerMoveEvent into the console.

Von meinem iPhone gesendet

Am 06.12.2016 um 17:50 schrieb bensku <notifications@github.com<mailto:notifications@github.com>>:


I know this happends with dev22e. I mean, I want to know if this is a new bug in dev22e, or older bug.

-

**Comment by bensku** [comment]
Good to know.

**Comment by bensku** [comment]
I have found out where this bug technically occurs, but unable to reproduce. I need to see your script which is causing it.

**Comment by GermanMinerDE** [comment]
Doesn't matter which Script is it (I think), tested with 10 unique scripts, same error. However, I will send you one of them in a separate message!

Von meinem iPhone gesendet

Am 06.12.2016 um 19:09 schrieb bensku <notifications@github.com<mailto:notifications@github.com>>:


I have found out where this bug technically occurs, but unable to reproduce. I need to see your script which is causing it.

**Comment by GermanMinerDE** [comment]
[03chat_check.txt](https://github.com/bensku/Skript/files/634728/03chat_check.txt)
[medic.txt](https://github.com/bensku/Skript/files/634727/medic.txt)

**Comment by TheBentoBox** [comment]
Are you still having this issue @GermanMinerDE ?

**Comment by GermanMinerDE** [comment]
No

Von meinem iPhone gesendet

Am 10.01.2017 um 02:10 schrieb Jake Ben-Tovim <notifications@github.com<mailto:notifications@github.com>>:


Are you still having this issue @GermanMinerDE<https://github.com/GermanMinerDE> ?

-
