### ISSUE TITLE
"doesn't have" Condition

### ISSUE THREAD

**Issue by ulufulufu** [bensku/Skript#28]
> command /addammo <player> <text>:
>   trigger:
> 
>     argument 2 is "0":
> 
>       argument 1 doesn't have 1 Iron Ingot:
>         send "&cNot Iron Ingot!!" to argument 1
>         stop
>       send "&aOK!"

Iron Ingot is having in the inventory become "No Iron Ingot !!".

ERROR code
Maybe there is no relationship........

> [00:02:30 ERROR]: Could not pass event PlayerInteractEvent to Skript v2.2-Fixes-
> V10
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
> va:310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
> a:62) ~[spigot.jar:git-Spigot-d97e08b-880a532]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
> ava:502) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
> ava:487) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInte
> ractEvent(CraftEventFactory.java:227) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInt
> eractManager.java:463) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
> :759) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
> ckPlace.java:52) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlo
> ckPlace.java:1) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
> 3) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
> ?:1.8.0_73]
>         at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
>         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar
> :git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
> 14) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
> 74) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
> 53) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
> :556) [spigot.jar:git-Spigot-d97e08b-880a532]
>         at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
> Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.PlayerInventory.get
> ItemInMainHand()Lorg/bukkit/inventory/ItemStack;
>         at ch.njol.skript.bukkitutil.Workarounds$1.onInteract(Workarounds.java:5
> 0) ~[?:?]
>         at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source) ~[?:?]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
> .8.0_73]
>         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
> va:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
>         ... 17 more

**Comment by Pilvinen** [comment]
Your code doesn't make any sense that's why it doesn't work.

**Comment by ulufulufu** [comment]
Sorry.I can't completely works.

> on rightclick on Crafting Table:
>   show "s;1;i;iron ingot;n;&6test;c;gun %player% 0;" with 3 rows named "menu" to player
> 
> command /gun <player> <text> :
>  trigger:
>   argument 2 is "0":
>     argument 1 doesn't have 1 Iron Ingot:
>       send "&cNot Iron Ingot!!" to argument 1
>       stop
>     send "&aOK!"
>

**Comment by bensku** [comment]
Which version of Minecraft are you running? It seems your server doesn't support main/off hand separation, i.e. it is not running Minecraft 1.9+.
