### ISSUE TITLE
Player put in fly mode

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#285]
Spigot 1.11, Skript dev22f, plus MV, PEX, PWI, ProtocolLib, Vault and a host of other plugins (all latest pulls).

On join, the player is placed in fly mode.

If I remove only Skript JAR, I am not placed in fly mode.

This does not occur with the same scripts in Spigot 1.10.2, Skript 2.1.2.

**Comment by bensku** [comment]
Are you sure that some of your scripts is not making player fly? And do you use addons?

**Comment by SlimeDog** [comment]
1. None of my scripts touch fly mode.
2. No addons.
3. Behavior does not occur with the same scripts in Spigot 1.10.2, Skript 2.1.2.

**Comment by bensku** [comment]
You'll have to try removing other plugins until you find the one which is conflicting with Skript. Then post name of it, so I can take look at possible incompatibility.

**Comment by TheBentoBox** [comment]
Cannot reproduce on 1.11 using 2.2-dev22g, [here are my plugins](https://gyazo.com/072d22de51a70a3028a0ab9e6340caca). I actually event have a script running that messes with fly mode and it's not causing any issues. Can you confirm of you're still experiencing this in 22g @SlimeDog ?

**Comment by SlimeDog** [comment]
With 22-dev22g, the issue appears to be resolved. When I enter a creative world, fly mode is enabled; when I enter a survival world, fly mode is disabled. I suppose that is the intended behavior.

**Comment by TheBentoBox** [comment]
Sounds good, glad it's working.
