### ISSUE TITLE
Console Error: java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R1.WorldServer.makeSound(double, double, double, java.lang.String, float, float)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#29]
Every now and then I get this error in the console:
http://pastebin.com/4xCWtzsP

java.lang.NoSuchMethodException: net.minecraft.server.v1_9_R1.WorldServer.makeSound(double, double, double, java.lang.String, float, float)

Any idea why? Is this something to be fixed?

**Comment by TheBentoBox** [comment]
Are you using the "play raw sound" effect from SkQuery? If so, that's what's causing this issue, not Skript itself. SkQuery doesn't work fully properly on 1.9.

**Comment by Pilvinen** [comment]
Remove SkQuery -> problem solved.

**Comment by bloggy** [comment]
Can't remove it completely, because I need some stuff from it (like mysql etc.). But I have removed all "play raw sound" effects. THank you for the help, appreciate it!
