### ISSUE TITLE
Aliases ids 438, 441

### ISSUE THREAD

**Issue by Soony37CZE** [bensku/Skript#291]
my server version are 1.10.2 I have latest version of your skript still getting me error: There are no aliases defined for the following ids: 438, 441 thanks for help

**Comment by Syst3ms** [comment]
This isn't an error. It only tells that some ids aren't defined in the aliases file. Change your title, cause your aliases will still work.

**Comment by Pyon-Pyon** [comment]
that are the IDs of the `splash potion` and the `lingering potion`, maybe your aliases file wasn't generated correctly, try delete your aliases file and start the server so it'll be regenerated with the new aliases.

**Comment by bensku** [comment]
This has been reported before.
