### ISSUE TITLE
Husk zombie variant isn't properly supported

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#292]
Hey

Creating an `on death of elder guardian` event loads correctly, but the event will never be fired. You can only check for elder guardian deaths by checking for ALL guardian deaths, and as there is no NBT tag to differentiate between elders and normal guardians anymore, this makes it more difficult to detect elder guardian deaths.

Code I'm using (with my server-specific stuff cut out):
```
on death of guardian:
	send "killed %victim%" to the attacker
```

This also sends "killed guardian", even though it should send "killed elder guardian", as they're a different entity type.

**Comment by TheBentoBox** [comment]
This also extends to other entity variants, it turns out. Strays throw skeleton death events and return "skeleton" when using `send "%target%"` on one, same with husks except they map to zombies.

In general, it seems as if Skript was updated to support the new entity format, but none of its behaviors actually respect the fact that these variants are now separate entities, which it should. It should be possible to use `on death of elder guardian`, or `on death of husk` and have it fire for only those variants (and they should return their own entity name when stringifying them).

**Comment by bensku** [comment]
Fixed in next release, probably.

**Comment by TheBentoBox** [comment]
I'm using 22g now and it's better. Elder guardians are fixed, as are strays, horse variants seem good too. Husks still have this issue; not sure why. But they don't throw their own death events, return "zombie" from `send "%target%"`, etc.

There's also now debug messages sent for each entity event as a script is loaded (you left in a Skript.info call in [this commit](https://github.com/bensku/Skript/commit/118897c406acaa8d77669650b8c9f2ff6aa739de) on line 79 of EvtEntity.java).

Overall very close to working, pretty sure it's just husks that are an issue now.

**Comment by JeepSmash** [comment]
When stringifying villagers such as with "%victim%" or "%loop-entity%" it no longer returns the appropriate "villager" but the text returned is "entities.name.normal" #311

**Comment by TheBentoBox** [comment]
I've updated the title to more accurately reflect the current state of the bug; the only issue really left is Husks still returning "zombie" when stringified and not firing their own death events. They should get the same treatment that other mobs got in [dev22g](https://github.com/bensku/Skript/releases/tag/dev22g), by having a "normal zombie" and "husk", with "zombie" as the supertype.
