### ISSUE TITLE
Bad Storage error

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#293]
Hi,

this is occurring since yesterday on our server, if you want to set or want to load variables.

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

‎14‎:‎16‎:‎01 CONSOLE: 
ERROR]: [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.expressions.ExprParse.get(ExprParse.java:171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

**Comment by GermanMinerDE** [comment]
And when restarting the server, Skript is not disabling and all not saved variables are away.
(dev20b)

**Comment by TheGlitch76** [comment]
ch.njol.skript.expressions.ExprParse.get
Wait.... This is the _latest_ version of **THIS** branch of Skript, correct?

**Comment by GermanMinerDE** [comment]
Hi @TheGlitch76 ,

no, it isn't. In the newest version I am not able to reload any of our Skripts, so I use dev22b now (sorry, earlier I wrote, that I use 20b)

**Comment by GermanMinerDE** [comment]
I fixed it for me. I used a variable containing "||" in the loop-index. So there were variables named "{loop::%player%||%day%}

**Comment by bensku** [comment]
I do not support old versions. Great that you got it fixed, anyway...
