### ISSUE TITLE
Integer/Number not working

### ISSUE THREAD

**Issue by Andalmere** [bensku/Skript#294]
I am currently using number on my skript but when i test it, it doesn't work. Im gonna make an example but i won't paste my whole skript for private reasons. Here is the example one.
```
command /numberpleasework [<text>]:
    trigger:
        if arg-1 is number:
            set {test.test} to arg-1
            send "%{test.test}%"
```

When i reload there are no errors.  And also, when I execute the command "/numberpleasework 23", it sends me "< none >". 

INFO:
Skript: Latest version
Spigot Version: 1.8.8
Java: 8

**Comment by Pyon-Pyon** [comment]
please use [the forums](https://forums.skunity.com) before create issues like this... what you are trying to do wouldn't work because the argument is a text, not a number, it always will return null then. If you want to check if a string is a number you need do:
```
command /numberpleasework [<text>]:
	trigger:
		if (arg parsed as num) is set:
			send "%arg% is a number"
		else:
			send "%arg% isn't a number"
```

**Comment by karingijs272** [comment]
command numberplasework [<integer>]:
    trigger:
        #OR use this when you use [<text>]
        set {_arg} to arg 1 parsed as integer

**Comment by Pyon-Pyon** [comment]
@karingijs272 my solution was correct, there isn't a reason for continue commenting at the issue and you're parsing an integer as an integer :neutral_face:

**Comment by Andalmere** [comment]
Sorry for not replying, i think i saw the problem now. @bensku can you please check the "{variable} is a number" in the skript plugin if it is working.

`
if arg-2 is a number:
                set {signedit.amount.%player%} to arg-2
            else:
                send "&cThat is not a number."
`
When i put any number (like 3) at arg-2 it will send me "That is not a number".

**Comment by bensku** [comment]
This is not PHP (horror). Types are not automatically converted, so here arg-2 is *always* string. You could try something like http://bensku.github.io/Skript/expressions.html#Parse%20Error
