### ISSUE TITLE
No Skripts Working.

### ISSUE THREAD

**Issue by TheMGRF** [bensku/Skript#295]
So I've been developing with skript for many months. However, this development was done on 1.8. I have recently just tried to update to 1.11. This meant using bensku's 1.11 version of skript.

I have tried to load up my old skripts and unsurprisingly none of them are working. So I was wanting to know if the syntax or something has changed for this update? Like even reloading a simple help skript it tells me "Unknown type 'text' (help.sk, line 16: command /help []:')".

(I tried posting this on the forums at SkUnity and they told me to come here.)

I also have this from my servers log file if it is of any use.
http://pastebin.com/eiGjunhd

So any help would be greatly appreciated!

**Comment by Pyon-Pyon** [comment]
Wait, are you using commands without specifying the argument? You can't do that, it will throw an error as it did if you do it in that way.

**Comment by TheMGRF** [comment]
Specifically for the server im developing for the /help command opens a GUI. However it also allows for arguments that can be used from within that GUI. (This uses "command /help [<text>]")So clicking the plots help icon would run "/help plots". It was throwing that unknown type "text" error before, however I after Isabella told me to remove Umbaska I did so and I have began to use an older version that what I had and it now seems to work. Again, however this throws out a large error of: http://pastebin.com/p1W8fQFK

**Comment by TheMGRF** [comment]
Oh ok, sorry my bad. I just actually read that error and realised it was the "play raw sound" code I was using. On removing that it seems to no longer throw an error at that point.

**Comment by Pyon-Pyon** [comment]
If you need a play raw sound equally, you could try [SkStuff](https://forums.skunity.com/topic/1081/1-11-ready-skstuff-v1-6-4-1-nbt-worldedit-pathfinders-more)'s play raw sound effect which is:
```
play [raw] [([resource[ ]]pack)] sound %string% (for|to) %players% at %location% [[with] volume %number%[[(,| and)] pitch %number%]]

play [raw] [([resource[ ]]pack)] sound %string% for %players% at %location% [[with] pitch %number%[[(,| and)] volume %number%]].
```
Example:
```
play sound "entity.player.levelup" to player at player's location volume 1 and pitch .1
```

**Comment by TheMGRF** [comment]
Wow! Thanks a lot! That's all really useful information that I'm definitely going to put to immediate use! Yeah my sounds are still from 1.8 development and need updating but I didn't know about SkStuff's play raw sound so thanks.

**Comment by Pyon-Pyon** [comment]
No problem, and if you still have issues I always answer to the help threads in the skU forums (I'm Pyon-Pyon on the forums too, but with a different profile picture).

**Comment by bensku** [comment]
I finally had time to check your log, and found out that there are some outdated addons on your server. They may cause Skript to not load properly.

You can set "addon safety checks: true" if config to get Skript start. However, that won't fix the addons; it merely makes Skript reject some invalid data that could prevent plugin from starting at all.
