### ISSUE TITLE
please update particles list.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#297]
please add "WATER_BUBBLE" particle)
p.s. hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
current particles list: gist.github.com/bensku/834e7bf666eb995e53d456c21ecc1e0e

**Comment by Pyon-Pyon** [comment]
that isn't the current particles list, it's the current visual effects list which is different of the particles, if you need particle just use skDragon for it.

**Comment by bensku** [comment]
Skript's particle backend relies on old Spigot-only API, which has not got the new 1.11 particles... That means I'd need to do quite large update for it.

**Comment by TheBentoBox** [comment]
@bensku Looking at the [particle enum](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html) and it does appear to now contain `totem` and `spit`, which are the new 1.11 particles. The `water_bubble` particle  as per this suggestion is also in the enum.

**Comment by bensku** [comment]
Skript does not use Particle enum, it uses Effect instead. This needs to change.

**Comment by bensku** [comment]
This has been done, forgot to close this for some reason.
