### ISSUE TITLE
Many errors in my console (1.11)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#298]
Did something change in the syntax there or what?
http://hastebin.com/efeyukames.md
Particle effects seem to cause exceptions?

**Comment by bensku** [comment]
That expression has never been part of Skript. From what addon does it come?

**Comment by TheBentoBox** [comment]
This particle syntax, while similar to the vanilla Skript visual effect syntax, is from [skRayFall](http://skunity.com/effects#CreateParticles). You should check with eyesniper on [the forum post for skRayFall](https://forums.skunity.com/topic/116/skrayfall-v1-9-7-make-your-server-come-alive/) or in Discord.
