### ISSUE TITLE
on block fade event console error

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#3]
**The issue:**
"on place" and "on break" events don't fire at all when placing/breaking blocks.

**Version:**
Latest Skript (by bensku).

**Spigot version:**
This server is running CraftBukkit version git-Spigot-3104eb1-daf4514 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Error log:**
http://pastie.org/private/olslyxouuzugsyssccxg

**Comment by bensku** [comment]
Same cause with issue #2 (fix one, both solved).

**Comment by bensku** [comment]
Should be fixed now. Please test it to be sure.
