### ISSUE TITLE
"can hold/give" doesn't handle space calculations correctly

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#30]
Version: dev9b

1) /give player stone 100000 - to fill up inventory
2) Wear armor, boots, helmet, leggings and shield
2) Run this code:

```
command /debugtest:
  trigger:
    if player can hold 64 bread:
      give 64 bread to player
    else:
      drop 64 bread at location of player
```

It drops 64 bread on the ground.

3) Drop the shield - you now have all slots filled except for the off-hand.
4) Run the command again.

No bread on the ground + no bread in off-hand. It tries to give you the bread but thinks all slots are filled. So this is either an error in give logic (should you be able to fill off-hand with give?) or error in "can hold" calculations (if you can't fill off-hand, then you should ignore it).

IMO, there's no reason why give shouldn't put the items in off-hand since it's empty and perfectly capable of holding the items.

**Comment by bensku** [comment]
Fixed in dev10.
