### ISSUE TITLE
Can't get the time difference between two timespan variables

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#301]
Can't get the time difference between two timespan variables

see:
https://forums.skunity.com/topic/7846/difference-between-does-not-work/8

Example:

```

                set {_start} to now
                wait 1 second
                set {_stop} to now
                set {_diff} to difference between {_start} and {_stop}
                message "%{_diff}%"
```

result is NONE

**Comment by bensku** [comment]
Difference expressions doesn't like variables, apparently. Especially if both first and second argument are variables, not just either of them

**Comment by bensku** [comment]
Could someone check if this is still the case? @bloggy

**Comment by Snow-Pyon** [comment]
This isn't an issue anymore as far I can tell.
