### ISSUE TITLE
Checking list-variables sometimes give errors

### ISSUE THREAD

**Issue by Ydda** [bensku/Skript#302]
Am I doing something wrong, or is this something?
This does not occur with every player executing the command in question. Just some. I have tried with and without the Skript-addons RandomSK and SharpSK, but the error persists.

19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! [Skript] Severe Error:
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
19.12 14:32:04 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
19.12 14:32:04 [Server] ERROR #!#! and check whether this error has already been reported.
19.12 14:32:04 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
19.12 14:32:04 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
19.12 14:32:04 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
19.12 14:32:04 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! Stack trace:
19.12 14:32:04 [Server] ERROR #!#! java.lang.NullPointerException
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.classes.data.DefaultComparators$12.compare(DefaultComparators.java:298)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.classes.data.DefaultComparators$12.compare(DefaultComparators.java:1)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.registrations.Comparators.compare(Comparators.java:71)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare$1$1.check(CondCompare.java:267)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:176)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.check(VariableString.java:503)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare$1.check(CondCompare.java:263)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:176)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.Variable.check(Variable.java:591)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:260)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:58)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:53)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)
19.12 14:32:04 [Server] ERROR #!#!     at ch.njol.skript.command.ScriptCommand.onCommand(ScriptCommand.java:161)
19.12 14:32:04 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
19.12 14:32:04 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
19.12 14:32:04 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646)
19.12 14:32:04 [Server] ERROR #!#!     at com.earth2me.essentials.commands.Commandsudo$1SudoCommandTask.run(Commandsudo.java:59)
19.12 14:32:04 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.12 14:32:04 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.12 14:32:04 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723)
19.12 14:32:04 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
19.12 14:32:04 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
19.12 14:32:04 [Server] ERROR #!#!     at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
19.12 14:32:04 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! Version Information:
19.12 14:32:04 [Server] ERROR #!#!   Skript: 2.2-dev22f
19.12 14:32:04 [Server] ERROR #!#!   Bukkit: 1.10.2-R0.1-SNAPSHOT
19.12 14:32:04 [Server] ERROR #!#!   Minecraft: 1.10.2
19.12 14:32:04 [Server] ERROR #!#!   Java: 1.8.0_72 (Java HotSpot(TM) 64-Bit Server VM 25.72-b15)
19.12 14:32:04 [Server] ERROR #!#!   OS: Linux amd64 4.4.0-47-generic
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! Running CraftBukkit: false
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! Current node: null
19.12 14:32:04 [Server] ERROR #!#! Current item: {pelaajat.klaani.%{klaani.%the player%}(as java.lang.Object)%::%loop-index%}(as java.lang.Object) is equal to "%the player%" (comparator: null)
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! Thread: Server thread
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! End of Error.
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! List of plugins: 
19.12 14:32:04 [Server] ERROR #!#! CoreProtect - 2.13.1, dynmap - 2.3-SNAPSHOT-1137, WorldEdit - 6.1.3;7a097ca, ColoredSigns - 4.25 Release, HealthBar - 1.8.3, Skript - 2.2-dev22f, OnlyProxyJoin - 1.1.2, NamelessMC - 1.1, Pl3xMOTD - 2.5.1, WorldGuard - 6.1.2;e38d98d, ProtocolLib - 3.6.5, iDisguise - 5.5.1, PermissionsEx - 1.23.4, Vault - 1.5.6-b49, ChairStairs - 1.1, RandomSK - 1.3, SharpSK - 1.6.0, Essentials - 2.0.1-b${BUILD_NUMBER}, BookShelf - 3.9, Citizens - 2.0.19-SNAPSHOT (build 1374), Shopkeepers - 1.76, EssentialsChat - Pre2.14.1.3, RecipeManager - 2.8, EssentialsSpawn - Pre2.14.1.3, Sentinel - 0.8 (build 67)
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#! List of addons: 
19.12 14:32:04 [Server] ERROR #!#! Failed to get addons hooked into Skript (NPE)!
19.12 14:32:04 [Server] ERROR #!#! 
19.12 14:32:04 [Server] ERROR #!#!

**Comment by bensku** [comment]
I did something that might fix this in last release. If not, something is wrong with parser again...

**Comment by TheBentoBox** [comment]
@Ydda Does this now seem fixed as of dev22g?

**Comment by TheBentoBox** [comment]
Closing as no response was given.
