### ISSUE TITLE
Offline UUID errors and possible crashes

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#303]
Hi

My server has been having crashing issues fairly recently, and usually along with these is an error regarding offline player UUIDs. This is probably due to the recently merged PR to add support for getting offline players via their UUID. Perhaps this is being run synchronously, causing the server to hang if there is an issue retrieving the offline player?

Note I'm not 100% sure by any means that Skript is causing the crash issue, though the severe errors should be resolved regardless.

**Spigot Version**: git-Spigot-f950f8e-0a6a5cb (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)
**Skript Version**: 2.2-dev22f

[Crash thread dump](https://www.hastebin.com/utilovunof.md)
[Error that appeared just beforehand](https://www.hastebin.com/zopasovaji.vbs)

I'm including the lines indicating the joining and leaving of the player "PhulishOne" because they seem to be what are triggering the errors. I don't think it's specifically related to them, more so that they're the one who happened to cause the issue when joining or leaving. I'm sure it could also be triggered by other players.

The code that is causing this error:

```
on packet event play_server_login:
	set {Packet::PlayerID::%uuid of player%} to int pnum 0 of event-packet

on quit:
	delete {Packet::PlayerID::%uuid of player%}
```

While the packet stuff is clearly not vanilla Skript (MundoSK), the errors seem to be related to the `uuid of player` expression (which of course *is* vanilla Skript).

Pardon if this is invalid and on my end.

**Comment by bensku** [comment]
It is possible thay fetching UUID might hang the server in some cases if done improperly for some players. I'll try to see if there is anything unusual with that player's UUID.

**Comment by TheLimeGlass** [comment]
The issue is that a UUID of a fake player is being picked up apon joining. Some plugin or object is sending a fake player to the server to handle data transfer (You're most likely running a BungeeCord server I'm guessing) so since you're using packets all the players joined catch this. I think it may be PluginMessaging that is causing this.

**Comment by TheBentoBox** [comment]
I don't use Bungee but I have JourneyMapServer which may do something like that. It gives multi-world map compatibility to clients using JourneyMap so it sends them world ID packets on world change and I'm pretty sure some sort of packet on join.

**Comment by bensku** [comment]
ProtocolLib fakes offline players, which do not perfectly mimic functionality of Spigot's OfflinePlayer. Attempting to fix, but this is*not* bug of Skript.

**Comment by TheBentoBox** [comment]
Given the new safeguard and the fact that it's not really a Skript issue anyways, I'll close.
