### ISSUE TITLE
Porblem skript2.2/paperspigot/massivecore

### ISSUE THREAD

**Issue by benbouil** [bensku/Skript#304]
Hello,

I'm using PaperSpigot on my server for more performance. I've a Faction's server and I want to use skript.
But I have a problem : 
http://pastebin.com/ykxVZVTc

I have a server with 500 players connected so If it's possible to help me faster It will be great.

Thank you,
Benbouil95

**Comment by Pyon-Pyon** [comment]
Skript never hooked into Factions AFAIK and the problem seems to be of Umbaska which hooks into Factions.

**Comment by bensku** [comment]
Umbaska Factions support is outdated or your version of Factions is outdated. Not an issue of Skript.
