### ISSUE TITLE
Issue tracker manager needed

### ISSUE THREAD

**Issue by bensku** [bensku/Skript#308]
I need someone to keep this tracker functioning. If I do it myself, it will take time away from actual development. The manager could help me with following things:

* Close old issues where I have asked for clarification, but not received that (old means more than 2-4 weeks)
* Close duplicates and tag them as such (and provide link to issue that was duplicated)
* Tag new issues correctly as bugs, enhancements etc. *or* tag them as 'dev-needed' if they are not sure if something is a bug
* Message me on Discord if something goes *horribly* wrong (e.g. any kind of security issue)
* Report any critical issues that come up in SkUnity here too
* Give me overview of most important issues when asked (in Discord, not very often)

Anyway, it shouldn't be *that* time consuming. After all, you'd not need to actually resolve any of the issues, besides closing invalid ones :)

If you're interested, please reply here. No 'application' is needed; I will consider each one who is interested based on how they have previously helped with Skript development.

**Comment by melinstagibson** [comment]
I can do that. I can also try to reproduce some errors reported but most likely not all. Especially on older versions since i always update everything on my servers asap but ill try to reproduce errors on 1.11+ versions (if the skript is provided)

**Comment by TheBentoBox** [comment]
I can do this. I keep my server up to date with new Minecraft versions (as soon as my plugins are ready, I update, and if they're not, I'm always testing on a local server) so I should be good to test with up to date versions. I've had the repo watched for a long time so I get email notifications for each issue regardless.

**Comment by Pyon-Pyon** [comment]
I can do this also, such as I have time and I regularity answers to the issues (you may saw me commenting in some issue) and because I know how the bugs should be reported I give the most information as possible.

**Comment by bensku** [comment]
@TheBentoBox has generally been very helpful and contributed a lot here, so... Thanks for everyone interested, anyway!
