### ISSUE TITLE
Move to a standalone repository.

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#309]
Currently, this repository does not appear when users [search for "Skript" here on GitHub](https://github.com/search?utf8=%E2%9C%93&q=skript). By detaching into a standalone repository, I think this fork will benefit from the extra visibility since it's the only actively developed fork of Skript.

All you have to do is contact GitHub support and request [repository detachment](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork):

> To detach the fork and turn it into a standalone repository on GitHub, contact [GitHub Support](https://github.com/contact).

**Comment by bensku** [comment]
I'll see what can be done.

**Comment by RezzedUp** [comment]
Looks like it worked 😄 

![](http://i.imgur.com/PU5CWbC.png)

**Comment by bensku** [comment]
Github support is awesome :)
