### ISSUE TITLE
Villagers not firing right click events, and called "entities.normal.name"

### ISSUE THREAD

**Issue by tuanjr** [bensku/Skript#311]
i just update to version 2.2dev22f, and "on click on a villager" won't work.
Please fix it.

**Comment by TheBentoBox** [comment]
Just tested on 2.2dev22g, can confirm. 

I was curious if this was just a result of the trading window interfering, so I tried using `spawn a nitwit` to spawn the nitwits (which don't have trades) to test on them, and I've also found that Skript-spawned nitwits actually spawn with trades. They seem to have the trades of a random profession/career combo (I've seen ones with blacksmith trades, priest trades, etc.). This is possibly a result of them being spawned, THEN having their profession set, so the trades are set before they are changed to a nitwit.

Not sure why the right click event isn't firing. A fix for the latter issue is to use the [setRecipes function](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/Merchant.html#setRecipes(java.util.List)) of the Merchant API and set it to an empty list for Nitwits in the [VillagerData.java](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/entity/VillagerData.java)'s `spawn` function. This may also just be an issue with their career not being set properly; nitwit is both a profession AND a career, like how "farmer" is a villager profession, but then farmers can specifically be farmers, shepherds, or fishermen. 

Updated title of issue report to reflect both of these issues.

**Comment by TheBentoBox** [comment]
Upon further testing when going through old similar issues about right click villager events, I've also found that villagers are even further bugged in the current build (2.2-dev22g). Using `send "%target%"` on a villager returns `entites.normal.name`. 

Ironically, this means a roundabout, not recommended, busted method for checking and cancelling villager right click events is:

```
on right click on entity:
	"%event-entity%" is "entities.normal.name"
	cancel event
	wait 1 tick
	close inventory of player
```

This will close the trading interface after a delay, but of course the root issue is what should be fixed.

**Comment by TheLimeGlass** [comment]
In Spigot 1.11 or 1.11.2 Spigot changed all Villager classes and updated them. All old villager methods shouldn't work.

**Comment by TheBentoBox** [comment]
The only recent large changes I see to [the Villager class](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/entity/Villager.java) is adding the Merchant API, which shouldn't cause the issues occurring here. I don't see any large changes made as a result of 1.11 (which makes sense, as 1.11 didn't add anything that should drastically affect villagers).

**Comment by bensku** [comment]
Okay, trades of nitwit are now set to an empty list. I hope it works.

**Comment by TheBentoBox** [comment]
I can confirm the nitwit fix did work, however the `entities.normal.name` issue still persists.

**Comment by Ayase-san** [comment]
A simple fix for this is add the following to the `entities` entry on the english.lang file:
```
normal:
	name: villager¦s
	pattern: <age> villager(|1¦s)|(4¦)[villager] (kid(|1¦s)|child(|1¦ren)) 
```
I've tested and it's working fine for me.

**Comment by melinstagibson** [comment]
Just getting this issue now on the latest version altho it actually is in the english.lang file. Ill use the workaround mentioned above but idk, this should be fixed i guess? Took me a while to dig this up

**Comment by bensku** [comment]
Right click events for villagers work. So does <code>broadcast "%entity%"</code> in such event.

**Comment by Snow-Pyon** [comment]
@bensku just to clarify, @Tuke-Nuke who fixed this problem just adding it to the language file in his PR as I stated above.

**Comment by bensku** [comment]
Yeah, I figured it out while writing release notes and gave credit correctly. Sorry that I forgot to do so here.
