### ISSUE TITLE
Remove player/victim/etc. from {example.list::*}

### ISSUE THREAD

**Issue by Thijsje** [bensku/Skript#312]
Skript don't remove the player or something from a list. Please can you fix it?
I need it very much.
(PS. Remove a targeted block or a block works)

**Comment by TheBentoBox** [comment]
Can you provide your code that is causing the issue? And what version of Skript & Spigot are you using?

**Comment by Ydda** [comment]
https://github.com/bensku/Skript/issues/302
I had this same issue. 2.2-dev22g so far seems to have fixed this. Further testing is required though for reliable confirmation.

**Comment by TheBentoBox** [comment]
@Thijsje Can you please confirm whether or not this is fixed for you on dev22g?

**Comment by FUZIK** [comment]
add {_player} to {@list}
remove {_plater} from {@list}

**Comment by TheBentoBox** [comment]
No confirmation from reporter after waiting almost a week, only word is Ydda saying it seems fixed for them, so closed.
