### ISSUE TITLE
on enter world

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#314]
Please add support for _on enter world_ event. It should probably be balanced by _on exit world_ as well, but I am more interested in the former.

**Comment by TheLimeGlass** [comment]
LargeSk and SharpSk have `[on] world change` which is called when a player changes worlds.

**Comment by SlimeDog** [comment]
I suppose _on world change_ is a generalization of _on enter world_ and _on exit world_, but I would prefer not to carry the weight of an add-on. Thus the feature request.

**Comment by Syst3ms** [comment]
*cough* *cough* addons are too big *cough* *cough*. Anyway, to say something on topic, I mean why not. Skript already has world support, so why the hell not.

**Comment by Leomixer17** [comment]
Is easy to add this event.

**Comment by Pyon-Pyon** [comment]
@Leomixer17 make a pull request then :+1:

**Comment by FUZIK** [comment]
on chunk load:
    world = "world_the_end"
    message "Hello!"
not a tested.

**Comment by Pyon-Pyon** [comment]
@FUZIK it would be better to do it with the teleport event.

**Comment by SlimeDog** [comment]
One cannot count on the timing of chunk loading. Spawn chunks are usually pre-loaded (that is the default) and may be loaded in any event from previous use.

The _on teleport_ event is much more frequent than just entering the world. It is true that

> on teleport
if former world was not _world_:
if world is _world_:

should work (it does not in 2.1.2), but
> on enter world

is much cleaner and clearer.

**Comment by Pyon-Pyon** [comment]
The addons have the `world change` event because that's the event which Spigot support:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerChangedWorldEvent.html

Obviously you can do a work around with the [entityTeleportEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityTeleportEvent.html) but it would be pointless such as Spigot already support a similar event.

**Comment by SlimeDog** [comment]
> on [first] enter _world_

would be even better. For the same reasons as

> on [first] join

**Comment by TheBentoBox** [comment]
I support the `enter world` and `exit world` events, but absolutely don't believe Skript should create its own `[first] (enter|exit) world` events. There is no Spigot-side support for detecting first-time entry into a world, so Skript itself would have to keep track of that itself to be able to fire an event like that. That's much better left to individual scripters to code and keep track of themselves via variables if they need it (which I believe a majority of people wouldn't).

**Comment by SlimeDog** [comment]
> but absolutely don't believe Skript should create its own [first] (enter|exit) world events

Makes sense to me.

**Comment by FUZIK** [comment]
on teleport:
    former world was "world"
    world will be "world_nether"

**Comment by SlimeDog** [comment]
Last time I tested, "on teleport" was broken. I will test again.

**Comment by SlimeDog** [comment]
Any chance of _on enter world_ being implemented?

**Comment by SlimeDog** [comment]
Thank you!

**Comment by SlimeDog** [comment]
What am I missing something here?

"on world changed" reports that I am in the target world, not the event-world. But anything I execute within the skript (for example, looping on inventory items or executing another skript) acts as though I am in the (previous) event-world. So I cannot really do anything related to entering the world.

**Comment by TheBentoBox** [comment]
How can you not give items when they enter a world if you can detect changing worlds and check the target (new) world?

**Comment by SlimeDog** [comment]
If I knew, I wouldn't have posted. :(

```
on player world change:
        set {_DEBUG} to true

        set {_world} to world

        if {_DEBUG} is true:
                send message "You entered world %world%" to the player
                send message "You set _world to %{_world}%" to the player

        set {_permission} to "blackdog.visited.%{_world}%"
        if the player has permission "%{_permission}%":
                if {_DEBUG} is true:
                        send message "Player has permission %{_permission}% at point A" to the player
        if the player does not have permission "%{_permission}%":
                if {_DEBUG} is true:
                        send message "Player does not have permission %{_permission}%" to the player
                execute console command "pex user %player% add %{_permission}%"
        else:
                if {_DEBUG} is true:
                        send message "Player has permission %{_permission}% at point B" to the player

# It won't work until the player is actually in the world.
# And PerWorldInventory may defeat it anyway.
#
                if {_DEBUG} is true:
                        send message "Player has gamemode %player's gamemode%" to the player
                if player's gamemode is survival:
                        if {_DEBUG} is true:
                                send message "Player is in survival mode" to the player
                        if player has permission "essentials.fly":
                                execute player command "/essentials:fly off"
                                if {_DEBUG} is true:
                                        send message "No flying!" to the player
                if {_world} is "world_luckyblock":
                        if {_DEBUG} is true:
                                send message "You are in world %{_world}%" to the player
                                send message "You are about to execute /equip-luckyblock" to the player
                        execute console command "equip-luckyblock"
```
The game mode is reported from the calling (event-) world. equip-luckyblock is a Skript that calls plugin commands that grant LuckyBlocks items. It executes if called in-game or from the console, but does not execute in this event.

**Comment by SlimeDog** [comment]
Perhaps _PerWorldInventory_ is causing interference?

**Comment by TheBentoBox** [comment]
Part of your issue is you're comparing a world to a text, you're setting `{_world}` to `event-world` then checking if it equals `"world_luckyblock"` before executing the equip-luckyblock command, which is impossible because a world isn't a text, which is at least partly why it isn't working as you'd expect. You at the very least need to do `if "%{_world}%" is "world_luckyblock"`

**Comment by SlimeDog** [comment]
Thanks.

**Comment by SlimeDog** [comment]
I grant that the types were inconsistent, but actually the test works as written. The last two _DEBUG statements in the example are printed on entry into world_luckyblock. What doesn't happen is equip-luckyblock. In addition, the other tests print the content of the event-world, not the new (target) world. And the survival-mode test also is executed based on the game mode of the event-world, not the new (target) world. The test does not succeed if I change the type to text
```
                if "{_world}" is "world_luckyblock":
 ```
As originally written, the script equip-luckyblock is executed, but does not grant the luckyblock items. I maintain that is because it believes it is not in world-luckyblock, but the other possibility is that PWI is causing interference.

**Comment by TheBentoBox** [comment]
Well that one wouldn't work because you forgot the percent signs, that'll check if your world is literally named "{_test}" when you want to check for "%{_test}%".

**Comment by TheBentoBox** [comment]
That being said if you have a perworld inventory plugin installed like you said

**Comment by SlimeDog** [comment]
The entire point of my request for _on player world change_ was to automate the process of generating this content. If we're thinking that it cannot work with a per-world inventory plugin, that is sort of a negative. I can work around the lack with explicit activators (signs or proximity sensors or whatever).
