### ISSUE TITLE
Cannot shoot fireball

### ISSUE THREAD

**Issue by c0wg0d** [bensku/Skript#315]
I'm trying to shoot a fireball and it's not working. I'm using Spigot 1.11.2 and Skript dev22g. Any ideas why? Here's my skript:

```
on right click with blaze rod:
    shoot fireball from player
```

**Comment by TheLimeGlass** [comment]
You have to put the letter `a` between the shoot and fireball
```
on right click with blaze rod:
	shoot a fireball from player

#If you want to change the speed use

on right click with blaze rod:
	shoot a fireball from player at speed 1
```

**Comment by c0wg0d** [comment]
That works, thanks.

**Comment by FloofyFloof** [comment]
can you make it so it has a cooldown?

**Comment by Potatoechip203** [comment]
Yes I also need help, I have the basic fireball shooting skript, I just don't know how to make it to where it has a cooldown, so players can maybe shoot like 5 fireballs, then after they shoot them, they need to wait say 60 seconds to shoot them, basically the "staff" needs to recharge, can anyone help?

**Comment by bluelhf** [comment]
> Yes I also need help, I have the basic fireball shooting skript, I just don't know how to make it to where it has a cooldown, so players can maybe shoot like 5 fireballs, then after they shoot them, they need to wait say 60 seconds to shoot them, basically the "staff" needs to recharge, can anyone help?

This issue tracker is for things that are broken in Skript itself, try a Skript-focused Discord server for help instead.
