### ISSUE TITLE
Skript Oldparser dev22g Event on chat not working

### ISSUE THREAD

**Issue by MKMethosPL** [bensku/Skript#316]
Such things do not work:

replace all "test" with ***
if message contains "test" or "test2":
execute console command "custom command" etc.

Chat event's not working. Even though the script has loaded the scripts properly and without errors.

**Comment by TrademarkTM** [comment]
It works perfectly for me using PaperSpigot 1.11.2.
``
on chat:
	if message contains "datboi":
		send "Your old message was &a%message%"
	replace all "datboi" with "pepe" in message
	send "However, I am bad and changed it to &a%message%"
``

Everything worked normally.
http://prntscr.com/do8gec

**Comment by TheBentoBox** [comment]
I am not having any issues with `on chat` either, using 1.11.0 on dev22g.
