### ISSUE TITLE
Console spam of this error

### ISSUE THREAD

**Issue by MinecraftAdmin** [bensku/Skript#319]
http://pastebin.com/5dc42Uhh
In addition to that error being spammed, my console is also spamming these and I'm not sure if they're connected:
http://pastebin.com/uij4qmaC

I have on region enter event skripts running as well. I do not have any on move event skripts. There is also some rubber banding going on on my server.

**Comment by MinecraftAdmin** [comment]
Ah thank for your explaination. Any ideas about the first pastebin?

**Comment by JeepSmash** [comment]
instead of doing "remove player from {joinleavedisabled::*}" replace it with "delete {joinleavedisabled::%loop-index%}'  that might be the line causing the internal error

As for the pastebins I don't have the knowledge to attempt at explaining it.
