### ISSUE TITLE
Spelling error for "exprerience orb"

### ISSUE THREAD

**Issue by JeepSmash** [bensku/Skript#320]
Using dev22g:
Whenever an experience orb entity is stringified using "%{_orb}%" or "%loop-entity%" it displays experience orbs with a mispelling of "exprerience orb"
I have also noticed that villagers will display as "entities.normal.name" using the same method which is also referenced in #311

**Comment by Pyon-Pyon** [comment]
that's not a bug, that's a feature which is explained at the Advanced Syntax section in this page:
http://njol.ch/projects/skript/doc

**Comment by JeepSmash** [comment]
on the prior version villagers displayed properly with "villager" i'm not sure if experience was spelled wrong with an extra R in it.  I noticed both these after updating to 22f and the skript stopped working properly until i adjusted for the different spelling and then after updating again it is still present in 22g

**Comment by TheBentoBox** [comment]
Yeah, I don't see how this typo would be a result of the Advanced Syntax. Regardless, it should be resolved.
