### ISSUE TITLE
Where in the world(s) am I?

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#322]
Environment: Spigot 1.11.2 latest, Skript 2.2-dev22g, Multiverse-Core 2.5.0 build 275 (latest snapshot). 

While waiting for on [first] enter world :)
I constructed the script:

> on enter region:
        set {_region} to region
        set {_world} to world
        send message "You are in region %{_region}%" to the player
        send message "You are in world %{_world}%" to the player

When I mvtp from world_lobby to world (which has region "worldspawn")

> You are in region worldspawn in world **world**
You are in world **world_lobby**

and back to world_lobby (which has region "spawn", just to have a difference)

> You are in region spawn in world **world_lobby**
You are in world **world**

(boldface added for emphasis). The Skript documentation states that _world_ is the world in which the event occurred. But the event of interest is _on enter region_, which would seem to occur in the target world rather than the former world. Other than parsing region, is there a variable that captures the world I am in?

**Comment by TheBentoBox** [comment]
This is correct and intentional, as you are not in the future world yet when the event is called. This allows you to use `cancel event` to prevent players from cross-world teleporting into a region you don't want them to enter.

In theory, syntax like `future event-world` should tell you where you're going, but if not, you can just as easily parse it out of the region name, as you said.

**Comment by SlimeDog** [comment]
Apparently, there is no event-world in on world enter/leave.

This is my first attempt at parsing. Can someone familiar with parsing correct the following?

```set {_region} to region```

returns "spawn in world world_lobby" 

```
set {var::*} to {_region} parsed as "%text% in world %text%"
if {parse error} is set:
    send message "Error: %last parse error%" to the player
if {var::*} is set:
    send message "Set: %{var::*}%" to the player
send message "You are in region %{var::1}%" to the player
send message "You are in world %{var::2}%" to the player```

returns no parse error, but var::* is not set (ie., no message) and fields are empty.

**Comment by Pyon-Pyon** [comment]
the parse error isn't a variable, also, did you set the region var like `set {_region} to "%region%"`? If not it wouldn't work.

**Comment by SlimeDog** [comment]
Excellent. Thanks.
