### ISSUE TITLE
on Preparing Craft

### ISSUE THREAD

**Issue by nshun1896** [bensku/Skript#323]
Thanks for your great update.
I have a problem and want to know about it.

The code below doesn't work.
```
on preparing craft:
	message "hey" to player
```

Error message is "There is no player  in an on prepare craft event".
I'd like to know it's bug or not. Thank you.

**Comment by bensku** [comment]
The event does not have player. However, it has inventory from which we can indirectly get player. Doing that for next release.

**Comment by TheBentoBox** [comment]
Just tested in dev23, you can now message players in `preparing craft` events.

**Comment by nshun1896** [comment]
I appreciate to your quick response!
