### ISSUE TITLE
permissions check fails

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#324]
Environment: Spigot 1.11.2 (latest), Skript 2.2-dev22g, PEX 1.23.4 (latest).

```
on enter region:
        if the player has permission "blackdog.xyzzy" :
                send message "permissions: yes" to the player
        if the player does not have permission "blackdog.xyzzy" :
                send message "permissions: no" to the player
        send message "outta here" to the player
```
returns
```
permissions: yes
outta here
```
I do not see an error in the script. It appears that _has permission_ always returns true, and _does not have permission_ always returns false, regardless of the value of the text. Needless to say, the permission _blackdog.xyzzy_ does not exist.

**Comment by TheBentoBox** [comment]
Are you opped or do you have the '*' permission? A lot of permissions will be assumed to default to ops, and if you have '*' then you have ALL permissions, even "fake ones" like this.

**Comment by SlimeDog** [comment]
Right. :( Not '', but OP. Re-testing...

**Comment by SlimeDog** [comment]
Resolved, I think. :(

plugins/PermissionsEx/permissions.yml starts
`# PermissionsEx/permissions.yml`
`# BlackDog-specific permissions are blackdog.*`
which despite parsing visually as a comment, is treated as a valid permission node
`blackdog.*`
This is most unfortunate, but fortunately easy to resolve. Yikes!
