### ISSUE TITLE
No looping of entities from a location

### ISSUE THREAD

**Issue by Rixic** [bensku/Skript#326]
Example Script with Issue:
https://hastebin.com/ekayaxaqis.coffeescript

- No console errors
- No loading errors
- No entities being broadcasted

Using Latest 22g
http://i.imgur.com/RazCaSK.png (script addons)

Tested in versions 1.11.2 and 1.10.2

Example Script with Issue without function usage:
https://hastebin.com/usutoxigim.sql

**Comment by FUZIK** [comment]
test is > loop entities in radius 10 around {_loc}:

**Comment by JeepSmash** [comment]
If you change from:

>  loop entities in radius 10 around {_loc}:

to:

>  loop entities in radius 10 around **location of** {_loc}: 

it will work just fine.  It seems that skript is not looking at the variable as a location until you specify to use its location.

**Comment by Rixic** [comment]
hmm, I feel like it should return some feedback in this situation either way

**Comment by TheBentoBox** [comment]
I've always had this issue as well. You can also do `loop entities in radius 10 around {_loc}'s location`. But yeah, there's definitely an issue with Skript not viewing the variable as a location in this context, I've had to use that workaround for a long time.

**Comment by FUZIK** [comment]
```
function loopentity(player:player,loc:location,world:world,int:integer):
	send "start." to {_player}
	loop all living entities in world {_world}:
		distance between location of loop-entity and {_loc} <= {_int}
		send "i am %loop-entity%." to {_player}
	send "stop." to {_player}
command loop-entity <integer = 10>:
	trigger:
		loopentity(player,location,world,arg-1)
```

**Comment by Pyon-Pyon** [comment]
@FUZIK that would be so laggy, just use the workaround that JeepMash said.

**Comment by Rixic** [comment]
or use skellets looping entities, kappa
