### ISSUE TITLE
Nothing is working?!

### ISSUE THREAD

**Issue by JakeBanner** [bensku/Skript#327]
Hello, 
So before I get into the issue I just wanted to say I have tried almost everything to try and fix my problem by getting newer or older versions of Skript and Skript Addons, also I have asked many people from Skunity and people I know who are very good and experienced with Skript but nobody seems to know what is causing me to have this issue/problem on my server. So to the problem i'm having. One day I updated to a newer version of Skript and reloaded my Scripts and they had so many errors or some didn't work at all. "Mainly _Events_ issues", so I thought I would just switch back to my older version of Skript which when I had that **before** I had No problems what so ever, everything worked flawlessly. But when I did switch back to that version my Scripts had errors "same as when I updated to the newer version". So then I did what I said in the beginning of this long paragraph, I asked many people and tried many other things but I can't seem to get my Skript(s) to work no longer after updating to that one newer version. Here are my errors http://imgur.com/a/SHblq and console log.   http://pastebin.com/ZbcmUJ0U  Sorry for the long post I just want to give as much information as possible, but if you have any questions please feel free to ask, and thanks for reading!!

**Comment by JakeBanner** [comment]
I have addons, and I never use the command "/reload" on my server. As I was told it can break things.

**Comment by MotoSolar** [comment]
You have same issue as me

**Comment by JakeBanner** [comment]
@MotoSolar It really sucks, because I can't get anything to work, and I can't get no support :/ at this point i honestly don't know what to do. I tried everything...

**Comment by MotoSolar** [comment]
If you're on 1.10 Try 

https://www.dropbox.com/sh/qubix8i86u216rs/AAATz1mjgYH6ySeUSr0NPYH-a?dl=0

1.11

than try 

https://github.com/grzegorzekkk/Skript/releases/tag/v2.3

**Comment by JakeBanner** [comment]
Thanks, I appreciate it. ill see if that works for me. I'll let you know :)

**Comment by JakeBanner** [comment]
@MotoSolar Problem has been finally solved... everything works fine now. Thank you for your help I appreciate it.

**Comment by MotoSolar** [comment]
@JakeBanner How do you fixed it?
