### ISSUE TITLE
Not working on 1.8?

### ISSUE THREAD

**Issue by sandor111** [bensku/Skript#328]
Hey i was trying to use this fork on my 1.8 server when i started the server it gave this error on startup:
http://pastebin.com/TYDVAk9g
After that all my skripts were not working so i tried typing /skript reload scripts then it gave me this error:
http://pastebin.com/BTYNM4AY

**Comment by Pyon-Pyon** [comment]
The 1.8 isn't supported, if you want use Skript in 1.8 use the [Mirreski's fixes](https://www.dropbox.com/s/fmglw850ioh2avo/Skript%202.2%20Fixes%20V9%20Early%20Test.jar?dl=0).

**Comment by sandor111** [comment]
@Pyon-Pyon But in that version is no support for /skript timings on and hasn't been updated in a while

**Comment by TheBentoBox** [comment]
@sandor111 That's the price you pay for staying on old versions. 1.9 was released almost a year ago and we're starting to approach 1.12 snapshots with you still on 1.8. If you spend forever on old versions you won't get new features, plain and simple. 

I'll leave this up to @bensku to see if he wants to try to fix it for you, but he'd be completely fair to say he doesn't. 1.8 is very old and unsupported by this fork.

**Comment by sandor111** [comment]
@thebentobox but i hate the 1.9 pvp feature

**Comment by TheBentoBox** [comment]
Then use SkStuff and add this code:

```
on join:
	add "{Attributes:[{Name:generic.attackSpeed, Base: 1024}]}" to nbt of player
```

And it'll make players able to spam click again.

**Comment by sandor111** [comment]
@TheBentoBox do i need to use skstuff? CuZ i want to keep the amount of addons as low as possible cuz the more addons the more ram. And if i only need to use skstuff for 1 effect :(

**Comment by TheBentoBox** [comment]
That's not true at all as most addons take essentially no RAM, most of what they do is just register effects on startup. For example, [here are my server's timings for today](https://timings.spigotmc.org/?url=tujumiduro) over the course of 14.5 hours, and you can see the most resource intensive addon I have is SkMorkaz, which is my 15th most intensive plugin taking only 0.01% of my server processing -- that's 1/10,000th of my RAM. SkStuff doesn't even show up on my timings (and I use it EXTENSIVELY) because it doesn't actively listen for any server events, once it registers it's done.

**Comment by sandor111** [comment]
@TheBentoBox I did what you said i updated to 1.9 installed skstuff and the bensku version off skript.
But when i try to use what you said:
`on join:
	add "{Attributes:[{Name:generic.attackSpeed, Base: 1024}]}" to nbt of player`
I just says:
https://gyazo.com/1ca7dcef401d84f947ef6a60d2523c75

**Comment by sandor111** [comment]
@TheBentoBox Whats your server ip and where are you hosting it?

**Comment by TheBentoBox** [comment]
That means you have the wrong version of SkStuff installed because it's not registering the syntaxes properly. What specific version of 1.9 are you on? (1.9.0, 1.9.4?)

**Comment by TheBentoBox** [comment]
And my server has 8 gigs of RAM hosted by Exodus.

**Comment by sandor111** [comment]
@TheBentoBox 1.9.4

**Comment by sandor111** [comment]
@TheBentoBox  are you paying 64.00 a month :O for a serverwith 8gb ram

**Comment by bensku** [comment]
GSON is not available on your environment, which is ridiculous. It is needed by Skript updater and actually, by Minecraft itself. Do you use some cheap host? Or are you running something that is even older than latest 1.8 release?

Anyway, I made few changes; now you should be able to just disable Skript updater and hope it works. No guarantees, and I will spend no more time on this, if it didn't get fixed.

**Comment by sandor111** [comment]
@bensku thanks
