### ISSUE TITLE
Permissions anomaly

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#335]
Environment: Spigot 1.11.2, Skript 1.22-dev23, Pex 1.23.4 and a host of other up-to-date plugins.

**command pex-test** script:
<blockquote><pre>
command /pex-test:
	trigger:
		send message "SKRIPT PEX-TEST" to the player
		set {_permission} to "blackdog.visited.xyzzy"
		send message "permission=%{_permission}%" to the player
		send message "player=%player%" to the player
		if the player has permission "%{_permission}%":
			send message "player HAS %{_permission}%" to the player
			if the player is op:
				send message "maybe because player is OP" to the player
			if the player has permission "op":
				send message "maybe because player has permission ""op""" to the player
		if the player does not have permission "%{_permission}%":
			send message "player DOES NOT HAVE %{_permission}%" to the player
</pre></blockquote>

**on enter region** script:
<blockquote><pre>
on enter region:
	send message "SKRIPT ON-ENTER-REGION" to the player
	set {_permission} to "blackdog.visited.xyzzy"
	send message "permission=%{_permission}%" to the player
	send message "player=%player%" to the player
	if the player has permission "%{_permission}%":
		send message "player HAS %{_permission}%" to the player
		if the player is op:
			send message "maybe because player is OP" to the player
		if the player has permission "op":
			send message "maybe because player has permission ""op""" to the player
	if the player does not have permission "%{_permission}%":
		send message "player DOES NOT HAVE %{_permission}%" to the player
</pre></blockquote>

With the exception of the required indentations, these have the same content. In the first case, it is executed as a command, and in the second case it is executed in response to entering a WG region. The actual permission being tested is irrelevant. The command **pex-test** case performs as expected; it correctly reports whether the player has the permission, or not, and also detects whether the player is OP or not. The **on-enter-region** case reports that the player has the permission, regardless of the facts; probably because it believes that the player is OP, regardless of the facts.

I would be happy to learn that I have made an error somehow.

**Comment by bensku** [comment]
Do you have addons installed? On Discord someone said that certain versions of some addons might mess with permissions.

**Comment by SlimeDog** [comment]
No Skript addons.

**Comment by SlimeDog** [comment]
I would be happy to provide access to my test server, if useful for isolation.

**Comment by SlimeDog** [comment]
I have isolated the conflict to ItemJoin. I will acquaint the developer with the issue, and take it from there. Unfortunately, there are no up-to-date alternative plugins available.

**Comment by SlimeDog** [comment]
Possibility: The ItemJoin items executes the command as OP. That would explain the anomaly.

**Comment by TheBentoBox** [comment]
Sounds like an ItemJoin issue, because anything that executes as OP will just bypass permissions checks, and there's not really anything Skript can do about it. Looks like a dev in your ticket on their repo has assigned themselves to your issue report, so hopefully this gets resolved for you soon.

**Comment by SlimeDog** [comment]
Agreed. Thanks.
