### ISSUE TITLE
Issue with World Guard Flags

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#336]
I am getting this error in the console on startup and on a script reload

http://pastebin.com/VkKgPVmn

I am on build dev23 running spigot 1.11.2

**Comment by Pyon-Pyon** [comment]
skRambled isn't supported and it's outdated anymore, you shouldn't use it.

**Comment by bensku** [comment]
Not Skript issue.

**Comment by whoshenry** [comment]
Can you tell me what is an alternative to skRambled? Thanks.

**Comment by Pyon-Pyon** [comment]
@whoshenry for what you use it? Also, it's preferable to talk about this on Discord, you can join to the Skript-chat if you want talk with me:
https://discord.gg/0lx4QhQvwelCZbEX
