### ISSUE TITLE
Unable to get balance of offlineplayer

### ISSUE THREAD

**Issue by JeepSmash** [bensku/Skript#339]
Not sure when this issue started but players just noticed it after i updated to dev23.  I have Vault 1.5.6 and EssentialsX 2.0.1

```
command /testbal <offlineplayer>:
	trigger:
		message "Balance: %balance of arg 1%"
```

Running this code will properly display the balance of the specified player if they are online.  But the second they log off it will return <none>.  Skript is unable to make any changes or get balances for players not online.

**Comment by Pyon-Pyon** [comment]
welp, it never was possible and I don't know how it worked before, the expression is:
```css
%player%'s (money|balance|account)
(money|balance|account) of %player%
```
not:
```css
%offlineplayer%'s (money|balance|account)
(money|balance|account) of %offlineplayer%
```
You can do this with TuSKe though:
```vbs
command testbal <offlineplayer>:
      trigger:
            if arg-1 has played before:
                  set {_data} to player data of arg-1
                  send "Balance: %money of {_data}%"
            else:
                  send "&cPlayer not found."
```

**Comment by bensku** [comment]
Uhh. Docs list expressions which were registered on my dev server. Apparently I forgot to install Vault there.

**Comment by JeepSmash** [comment]
All commands and expressions did work 100% using balances for %offlineplayer% arguments while the player was online.  But it wasn't noticed until yesterday that the balances of players were not changed when they were offline and someone sold/bought something from their shops.  Maybe a warning should be included while loading scripts that using offlineplayer arguments with balances will not work if the player is not online
