### ISSUE TITLE
Shulker bullet is not considered a projectile in on projectile hit:

### ISSUE THREAD

**Issue by xBiscuit** [bensku/Skript#343]
title

**Comment by Weefle** [comment]
Are you serious?
You could at least put what's in your console and your skript!

**Comment by TheBentoBox** [comment]
@Weefle if it's as they say, there will be nothing in console because there's no error. It's just that shulker bullets don't fire projectile hit events, which they should. 

I'll check this and mark as a bug if I can verify as soon as I get free time (tonight or tomorrow).

**Comment by xBiscuit** [comment]
What he said :p

**Comment by Weefle** [comment]
Oh, ok, sorry XBiscuit :')

**Comment by TheBentoBox** [comment]
Can confirm. They are treated as projectiles in many other cases -- they fire an `on shoot` event which works properly (registers the shulker shooter with the bullet projectile), and also properly as a projectile in a damage event, but they do not fire `on projectile hit`, regardless of if they hit an entity or a block.

**Comment by bensku** [comment]
Registered as simple event on Skript side. Assuming that this is Spigot bug with projectile hit events.
