### ISSUE TITLE
How to cancel damage on boat?

### ISSUE THREAD

**Issue by Weefle** [bensku/Skript#344]
Hey I need this to my server:
`on damage of boat:
    cancel event`
But It doesn't work.
And this script works with armor stands:
`on damage of armor stand:
    cancel event`
Please help me! :/

**Comment by xBiscuit** [comment]
On damage:
    if victim is a boat:
        cancel event
    if victim is an armor stand:
        cancel event
Try those. Also i suggest going to SkUnity forums or SkUnity discord to ask questions like these. This is the place for issues with skript, not personal issues. 🙂

**Comment by Weefle** [comment]
I've already tested this:
'on damage:'
André thé Armor stands works fine but not thé boats 😐

**Comment by Weefle** [comment]
I've already tested this:
'on damage:'
And the armor stands works fine but not thé boats 😐

**Comment by Weefle** [comment]
Ok, I've found the syntax:
`on vehicle destroy:
    cancel event`
You can close this thread! :D

**Comment by TheBentoBox** [comment]
You can close your own issue reports, for future reference. Don't have to wait for me to do it.
