### ISSUE TITLE
Suggestion: UUID support for non-players

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#347]
Personally, i use Skript together with the plugin "MythicMobs" a lot. The latter plugin is dedicated to giving you full control over the mobs on your server and adding lots of neat functionalities.

When working with these 2 plugins together, i often find myself being forced to use "hacky shit" to get them to communicate with one another. Passing data from MythicMobs to Skript is very easy, but the other way around unfortunately isn't, and that's because Skript does not have an expression for the uuid of a non-player entity.

My example being one, for how this would be useful. However, being able to address entities by UUID would also open other gates, for example towards vanilla minecraft commands, as all minecraft commands not only support players as input, but also UUIDs for entities. Example:
`console command "minecraft:execute %victim's uuid% ~ ~ ~ minecraft:playsound [...]"`

Stuff like that

Thank you for reading this

**Comment by Pyon-Pyon** [comment]
Already suggested at the issue #193
