### ISSUE TITLE
Errors on VisualEffects

### ISSUE THREAD

**Issue by DrYoshYz** [bensku/Skript#348]
I got a lot visualeffects errors on server console on version 1.11.2 of spigot , using the last dev of skript.
Already tested too with the version 1.10.2 but same errors.
This appear with ALL visual effects of minecraft (Tested)
The {_particle} is just a location setted , already try with things like at location of player/target but the same it doesn't work.
![error](https://cloud.githubusercontent.com/assets/25226865/22112364/f0df85bc-de62-11e6-99ef-a4b3de11275d.PNG)

**Comment by Pyon-Pyon** [comment]
Cannot reproduce this at 1.11.2 nor 1.10.2 using the latest release. Could you show what you've tried?

**Comment by TheBentoBox** [comment]
I also cannot reproduce this. Send the code you're using, including where the `{_particle}` variable is set.

**Comment by TheBentoBox** [comment]
No response, closing.
