### ISSUE TITLE
SQLite variables are not removed.

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#350]
I've already made a report for this, but this one is a real bug. The other one was just like a "problem". In csv, the variables get cleared upon restart. In SQLite, they just are loaded again.

How to reproduce:
- Save any variable into a SQLite database (from vanilla Skript).
- Delete/clear them. Now they won't work, but the database has the same size.
- Restart the server. All the variables are loaded again, even if you deleted them.

Version: dev23
Errors: none
Server version: 1.11.2
SQLibrary version: 7.1

**Comment by bensku** [comment]
Well, no idea how variable stuff really works, so...
