### ISSUE TITLE
villager = "entities.normal.name"

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#354]
Skript version dev23
Spigot 1.10.2

I discovered this when an event i previously used with dev20 worked fine (on right click on villager). After updating the event stopped calling, so i messed around a little and tried to broadcast "%type of clicked entity%" with "on right click on entity".

https://snag.gy/GWmlcO.jpg

The above being the result. Pretty sure that's supposed to say villager, hence why i'm reporting this.

Cheers

**Comment by jaylawl** [comment]
update: same on 1.11.2 spigot

**Comment by TheBentoBox** [comment]
This and other current villager issues are being discussed in #311
