### ISSUE TITLE
How to open a GUI and automatically put things in it. (Like a warp menu) 

### ISSUE THREAD

**Issue by garageagleMC** [bensku/Skript#358]
I couldn't find a way to automatically put things in a chest GUI.
I am using the latest dev-build, dev23.

[Here is what I have so far. ](http://pastebin.com/3Y7sVqb9)

**Comment by loadka95** [comment]
```
on rightclick holding a paper:
open chest with 1 row named "SOMETHING" to player
	format slot 5 of player with dirt named "SOMETHING" with lore "LORE" to close then run "/say hi"
```

**Comment by Pyon-Pyon** [comment]
This is a issue tracker, not a place where you ask for help, if you want help please go to the [Discord's official server](https://discord.gg/vb9dGbu) or [the forums](https://forums.skunity.com/) (the forums are down though, the best would be go to the Discord server, you'll get help ASAP).

**Comment by garageagleMC** [comment]
I had four errors, two about indention. I fixed those, but I still have two more.

![2017-01-24_09 25 20](https://cloud.githubusercontent.com/assets/17891461/22253399/132ee628-e217-11e6-88a0-6e4302d5f26d.png)

**Comment by garageagleMC** [comment]
I didn't mean to close it! :P

**Comment by sandor111** [comment]
@garageagleMC Please read what @Pyon-Pyon Said

**Comment by TheBentoBox** [comment]
Vanilla Skript does not have syntax for this. If you'd like to request some sort of `set slot` effect to be added, you may do so in a new issue and it could be labeled as enhancement, but this is not the place to ask for help with scripts or with addon syntaxes.
