### ISSUE TITLE
Suggestion: Add new effect "set slot"

### ISSUE THREAD

**Issue by garageagleMC** [bensku/Skript#359]
I think that there should be a new effect called `set slot` where you can set a item in a GUI. For example,
`set slot 5 of chest to steak called "Meat"
on click: "/say MEAT!!"`

**Comment by Pyon-Pyon** [comment]
Instead of that, there should be the `slot %int% of %inventory%` expression, then with this expression you could do:
```
set slot 5 of player's inventory to 10 of stone called "hi"
set {_slot} to slot 5 of player's inventory
remove 5 of stone from slot 5 of player's inventory
clear slot 5 of player's inventory
```

**Comment by TheMeq** [comment]
This would be awesome!

**Comment by TheBentoBox** [comment]
This has been added with Tuke's merged PR.
