### ISSUE TITLE
event-entity in an on tame event returns the player, not the wolf

### ISSUE THREAD

**Issue by githubthrowaway123** [bensku/Skript#361]
```
on tame:
	broadcast "%event-entity%"
```
is my code for testing. it broadcasts my in game name instead of "wolf" or something along those lines. if u do not fix this im telling my mom on u and ur in big trouble ty

**Comment by TheLimeGlass** [comment]
Suggestion to fix this bensku: Adding an event-value to define the entity and the player 👍
