### ISSUE TITLE
On Respawn event is not being called

### ISSUE THREAD

**Issue by JeepSmash** [bensku/Skript#365]
I'm having difficulty getting the on respawn event to work. #287 references some issues with the command but they are in relation to some code not executing.  I'm having an issue getting the event to even be called.  Multiverse normally handles the player respawn location would it be preventing the respawn event from being called?  I'm not trying to change the respawn location and still want multiverse to handle the respawn location.

Plugins: Skript dev23, vault, multiverse, essentialsx,coreprotect,griefprevention,dragontravel,groupmanager
SK Addons: SkQuery, SkDragon, SkRayfall

The following code will not generate any messages and is never called after players deaths/respawns.  

```
on respawn:
	broadcast "%player% respawned"
```

**Comment by bensku** [comment]
Minecraft/Spigot do not correctly transmit chat messages at the exact moment when player is respawning. Note that everyone else, including console, will see the broadcast. If you want the *player* to see a chat message, you must wait at least 1 tick.

I don't think this is something I'd fix on Skript side even if it would be possible.
