### ISSUE TITLE
Multiple passengers

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#368]
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprPassenger.java

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/a17b015899fd9a82d63b61c5a37a52ecbfb89b9e

Allowing for Multiple passengers. In the latest Spigot they deprecated the old getPassenger() method and replaced it with getPassengers() because in 1.11 Entities can have multiple passengers.

Should be an easy fix changing some of the getPassenger() to getPassengers()

**Comment by TheBentoBox** [comment]
Enhancement, I guess? Will sorta become a bug in the future...

Do you happen to know if `make %entity% ride %entity%` works for multiple passengers? i.e. If you make multiple entities ride the same entity through Skript, will it work? As of 1.9 entities can have multiple passengers (not 1.11 actually, as you said), so Skript should allow you to do that too. If not, that's something else that'll need to be fixed here.

**Comment by TheLimeGlass** [comment]
@TheBentoBox That too will need updating as it now uses addPassenger and removePassenger methods.

**Comment by bensku** [comment]
Do note that 1.9+ is still supported. Adding 1.11 specific features is not *that* easy.

**Comment by Tuke-Nuke** [comment]
I'm taking over this issue, to make `passenger of %entity%` works with multiple passengers and works normally for previous version, since the methods was added in `1.11.2` if I'm not wrong. I might make a PR in a few hours.

**Comment by TheLimeGlass** [comment]
@Tuke-Nuke Any luck?

**Comment by Tuke-Nuke** [comment]
@TheLimeGlass sorry to take too long, I hadn't time to test it last days. I will make a final test tonight and them make a PR.

**Comment by bensku** [comment]
Ooops, I forgot to close this even though I wrote about this in release notes and gave credit to PR.
