### ISSUE TITLE
On spawn event not working

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#369]
```
on spawn of zombie:
    broadcast "%event-entity%"
```

literally tried everything with this, including making sure entities are getting spawned by different spawn reasons like spawners, natural spawning, plugin spawning, minecraft command spawning, mob egg spawning... all to no avail

of course i also tried to specifying an entity type at all

skript dev-23
spigot 1.11.2

**Comment by TrademarkTM** [comment]
The event is working, but for some reason only if you use it out of the 'spawn' line. Example:
`
on spawn:
    event-entity is zombie
    # do something
`

**Comment by TheBentoBox** [comment]
[Cannot reproduce, using your code exactly](https://gyazo.com/c8e5396d2d2037d4b1b0e2207fa2df68). And I'm using tons of spawn events on my public server (which is 1.11.2 using dev-23) and they all work fine.

Anyone else having this issue or can give me a way to reproduce it? If not I'll close soon; this seems to be something on your end.

**Comment by JeepSmash** [comment]
I use this event pretty heavily on my server and have no issues with up to date spigot / skript.

**Comment by jaylawl** [comment]
Could my issue have anything to do with using a modified aliases.sk?

im using 2.0.5 by tim470: https://hastebin.com/rukomunusu.rb

**Comment by jaylawl** [comment]
i found the godamn issue...
turns out this would only work if one did a full reload of all scripts (/skript reload scripts), while i was using a alias to only reload the scripts in a specified folder

sorry for all the confusion, i learned something out of this ^^
