### ISSUE TITLE
Issue with Incorrect Yaw Value

### ISSUE THREAD

**Issue by JeepSmash** [bensku/Skript#384]
I have been receiving erroneous values from Mob Yaw values.  It appears that the Yaw values of entities only updates when they are walking.  Once the mob stops walking and is standing still the Yaw value does not update to match the direction the mob is facing as they can be looking all around and the yaw will not change.  This is not true for the pitch which will update when the mobs looks around the world.

Test Code:
```
command /yaw:
	trigger:
		set {_ent} to targeted entity
		set {_t} to now
		add 1 minute to {_t}
		while {_t} is greater than now:
			wait 1 tick
			set action bar of player to "Yaw: %yaw of {_ent}% Pitch: %pitch of {_ent}%"
```

At first i thought maybe the server doesn't update mobs looking around at random stuff and that was client side but i confirmed with alt accounts that the mobs are looking around all the same on different clients but that is when i discovered that the pitch IS updating so I'm not sure why the yaw would not be updating when the mob is looking around but the pitch will update.

This also seems to affect other skript expressions that would use yaw like: 
`set {_loc} to location 10 meters in front of {_entity}`
`shoot arrow from {_ent} in direction of {_ent}`

**Comment by TheBentoBox** [comment]
Wow, you're completely right. Just tested on dev23 with 1.11.2 and can confirm it won't update yaw while a mob is standing still.

**Comment by Rixic** [comment]
I believe this is a minecraft bug rather than a script bug, there are workarounds i believe, like forcefully teleporting the entity without a yaw to update its yaw

**Comment by bensku** [comment]
For some reason, Spigot is not updating Location's yaw until the mob moves. I recommend reporting this to them.
