### ISSUE TITLE
some of on rightclick event does not work when offhand tool is a shield

### ISSUE THREAD

**Issue by nshun1896** [bensku/Skript#385]
The script below works well basically, but under particular situation below, it doesn't work.
-If player's offhand tool is shield
-and player's main hand tool is seeds (of wheet, pumpkin, melon and beetloot)
-and player's target block is farmland
(It means potato and carrot works well)

I guess the cause is about offhand shield.. but I don't know how to fix.
I would appreciate if you fix the problem or tell me how to avoid this problem. Thank you.
```
aliases:
	seeds = 295, 351:3, 361, 362, 372, 391, 392, 435
*all kinds of seeds, carrot item, and potatoes and so on

on rightclick holding seeds:
	message "test"
```

**Comment by TheBentoBox** [comment]
This sounds like an issue for bensku to consider, but just as a possible solution for you, you could try using an `on place` event instead, where it detects the placement of the crop blocks instead of right clicking with them. (Though I suppose you may not be trying to detect planting).

**Comment by Syst3ms** [comment]
Or even better, `on can build check`

**Comment by bensku** [comment]
Apparently Skript treated <code>holding</code> exactly same as <code>with</code>, while they can mean different things now that we have offhand support.

This means I had not to deal with weird event-firing-twice stuff. Easy to fix.

**Comment by nshun1896** [comment]
Thanks for your commit and considerate comment.
and thanks for The Bento Box's and Syst3ms's kindful help!
