### ISSUE TITLE
error with "if" in on death event

### ISSUE THREAD

**Issue by norbi002** [bensku/Skript#386]
Error log: http://pastebin.com/geqetZj9
Script: 
on damage:
	if victim is a player:
		if {bnnyBase::god::%victim%} is true:
			cancel event

**Comment by FUZIK** [comment]
please use: on damage of %entity%

**Comment by SwiKZiiK** [comment]
Use Skript 2.2 Dev23.

**Comment by TheBentoBox** [comment]
Downgrade to dev23, there are some issues in dev24 for now that I think will just have to wait for another release. Also, as FUZIK said, you can just use `on damage of player`.
