### ISSUE TITLE
on place

### ISSUE THREAD

**Issue by epicskymi** [bensku/Skript#390]
using on place allows you to get event-item but not the item name

been told this is a sub 1.11 issue

**Comment by TheBentoBox** [comment]
You mean to say this only happens in versions before 1.11? If that's what you mean I can test on a 1.10 server to help confirm. Also if anyone here has a pre-1.11 server they can test on for me, that'd be helpful, as my public server is on 1.11.2.

**Comment by TheBentoBox** [comment]
No response, closing.
