### ISSUE TITLE
SkRayFall Scoreboard Error

### ISSUE THREAD

**Issue by A248** [bensku/Skript#395]
I recently received an error after writing a scoreboard script.

http://pastebin.com/hgN7fpdd

This is because I added a scoreboard script using SkRayFall. As soon as I did, this error occured.

Scoreboard script:

every 5 seconds:
	loop all players:
		if {sidebar.%loop-player%} is false:
			erase loop-player's sidebar
		else:
			erase loop-player's sidebar
			set score "{@Line1}" in sidebar of loop-player to 7
			set score "{@Line2}" in sidebar of loop-player to 6
			set score "{@Line3}" in sidebar of loop-player to 5
			set score "{@Line4}" in sidebar of loop-player to 4
			set score "{@Line5}" in sidebar of loop-player to 3
			set score "{@Line6}" in sidebar of loop-plauer to 2
			set score "{@Line7}" in sidebar of loop-player to 1
			set name of sidebar of loop-player to "{@Title}"

I did set a configuration option for Title and the lines. Those are working just fine.

**Comment by A248** [comment]
Scoreboard script:

every 5 seconds:
	loop all players:
		if {sidebar.%loop-player%} is false:
			erase loop-player's sidebar
		else:
			erase loop-player's sidebar
			set score "{@Line1}" in sidebar of loop-player to 7
			set score "{@Line2}" in sidebar of loop-player to 6
			set score "{@Line3}" in sidebar of loop-player to 5
			set score "{@Line4}" in sidebar of loop-player to 4
			set score "{@Line5}" in sidebar of loop-player to 3
			set score "{@Line6}" in sidebar of loop-plauer to 2
			set score "{@Line7}" in sidebar of loop-player to 1
			set name of sidebar of loop-player to "{@Title}"


I did set a configuration option for Title and the lines. Those are working just fine.

**Comment by Syst3ms** [comment]
The error is related to skRayFall not Skript itself. To close
