### ISSUE TITLE
on region enter/leave events fire twice

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#4]
**The issue:**
On Region Enter/Leave events fire twice.

**Version:**
Latest Skript (by bensku).

**Spigot version:**
This server is running CraftBukkit version git-Spigot-3104eb1-daf4514 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)

**Steps to reproduce:**
```
On Region Enter:
  broadcast " DEBUG: &a%player%&f On Region Enter (region at player: %region at location of player%)"
 
On Region Leave:
  broadcast " DEBUG: &a%player%&f On Region Leave (region at player: %region at location of player%)"

```

**Comment by bensku** [comment]
Fixed in all normal cases.
