### ISSUE TITLE
Sweeping Edge uses wrong enchantment name ("enchantments.names.sweeping")

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#401]
Hello

Attempting to enchant a tool with the 1.11.2 "Sweeping Edge" enchantment does not work as expected. The attempted fix was made in [this commit](https://github.com/bensku/Skript/commit/4ac5a0ab165fe2504dae3a40b853426d8c2f1e55), but this change wasn't sufficient, as it requires you to use "enchantments.names.sweeping" instead of the expected "sweeping edge" to reference the enchantment.

## Example Tests
![image](https://cloud.githubusercontent.com/assets/6902229/23335144/ec44f118-fb7c-11e6-90d8-54dd4b0ba86e.png)
As you can see, the final test worked fine, using enchantments.names.sweeping.
This issue is also visible when looking at the Enchantment type on the [types documentation](http://bensku.github.io/Skript/classes.html), where the enchantment is listed as enchantments.names.sweeping.

## Setups
- Skript dev24b
- [Recent](https://gyazo.com/4b14a2f026ab0a388452d934ddce3fb0) Spigot 1.11.2 build

## How To Fix
Apparently, the issue is that the lang file was updated to use `sweeping_edge` as the enchantment ID while it should be just `sweeping`. I personally haven't tested this, but Ayase/Snow-Pyon of the Skript forums has tested for me and confirmed it worked on their server by manually editing the english.lang file to say `sweeping: Sweeping Edge` instead. I'm not sure why this would be the case, as the Spigot Enchantment enum uses the wording you used originally (`SWEEPING_EDGE`), however, the vanilla enchantment name _is_ just `sweeping`, which may be causing the issue. I don't know how Skript's enchantment parsing works.

**Comment by bloggy** [comment]
For me this does not work. What is the correct name to use?
I tried everything:

`
set {_enchantment} to "Sweeping Edge"
enchant {_item} with "%{_enchantment}% 1"
`

Tried: Sweeping, Sweeping Edge, sweeping_edge

Nothing works

**Comment by bensku** [comment]
Implicit string to enchantment conversion does not exist.
