### ISSUE TITLE
Villagers are "entities.normal.name" for skript

### ISSUE THREAD

**Issue by Guarmanda** [bensku/Skript#403]
I couldn't edit villagers, and my idea was that they weren't recognized by skript. I was right.
I tried this code:
on leftclick on entity:
    message "%entity%"
It returns "entities.normal.name" for villagers. I tried to rightclick on a sheep, on a pig and some other mobs, and it returned "sheep" or "pig" for them...
Can you please fix this issue? 

I use that to recognize villagers, for now, but if someone else looks into my code, I think he wouldn't find any logic in it :D
on damage of entity:
	"%victim%" is "entities.normal.name" ...
on spawn of creature:
	"%event-entity%" is "entities.normal.name"....
command /pnj:
	trigger:
		loop all entities:
			"%loop-entity%" is "entities.normal.name"....

**Comment by JeepSmash** [comment]
This is a Duplicate as its already been reported in #311 and #292

Before reporting bugs I suggest using the search to look up your issue.  Some of these pending issues will often have work arounds posted so that we can make our scripts work while waiting for an update.
