### ISSUE TITLE
Sorted Function throwing internal errors

### ISSUE THREAD

**Issue by thejimmyj57** [bensku/Skript#405]
I am trying to use the 'sorted' function to create a /baltop command. It seems to work under only certain conditions and throws internal errors in others. From what I gathered the sorted function throws this error when one number does not have a decimal place (integer) and another number has decimal places. It seems that it does not know how to compare them? This is a code I have been trying that throws errors:
```
command /test2:
	trigger:
		add 5.02 to {_list::*}
		add 2 to {_list::*}
		add 2304 to {_list::*}
		set {_list2::*} to sorted {_list::*}
		message "%{_list2::*}%"
```

I have tried on both Skript dev23 and Skript dev24b

**Comment by TheBentoBox** [comment]
[Confirmed](https://www.hastebin.com/xuzicuqohi.vbs). It's an issue with casting doubles to longs, which sounds about in line with what you're saying.

**Comment by bensku** [comment]
Nice, you managed to find JVM bug. Arrays.sort doesn't seem to be very reliable :) I'll see if I can hack around this.
