### ISSUE TITLE
on walk on %itemtype% fall through issue

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#406]
This has been a bug for a long time and no one has fixed it. But it might have some connection to the teleport issue #286 

Basically when a player walks on any block it makes them go through the block like in this video
```
on step on glass:
    message "You stepped on glass. OW!"
```
This gets fixed if you just add a wait tick into it
```
on step on glass:
    wait a tick
    message "You stepped on glass. OW!"
```
https://www.youtube.com/watch?v=V_rUiqICfvA

**Comment by bensku** [comment]
Hmm, apparently Skript was modifying player's location on this event because someone forgot to use <code>.clone</code> and Bukkit Location behaviour had changed.
