### ISSUE TITLE
Anvil inventory doesn't let you do anything meaningful

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#41]
When you use the code below and then try to rename something on the anvil window it will seem like you get the item but when you drop it it will revert back to what it was before.

Also sound is missing from using the anvil.

Also when you open the anvil window and try to drop items from your inventory they seem to disappear but if you relog your items are still in your inventory.
```
on right click on anvil:
  cancel event
  open anvil window to player
```

Console error:
http://pastie.org/private/7bgpoah4wrqshk5cdqm9qg

**Comment by bensku** [comment]
Spigot bug, only workaround seems to be NMS code... Or Sponge port of Skript.

**Comment by Pilvinen** [comment]
Fix it in Spigot and make a pull request? :-)

**Comment by bensku** [comment]
Uhh, this is still open? Anyway, nothing I can do in Skript side. Closing.
