### ISSUE TITLE
Tab and space (code).

### ISSUE THREAD

**Issue by SwenCake** [bensku/Skript#410]
Hello,

I have one issue with tab and space in my code but i don't no if it's .jar or my pc...

I must use tab with "if" condition and "trigger" on command event but I can use space on any other event, effect ...

My code : http://pastebin.com/BKUZhuC0

If you want pics or other, tell me.

Goog day/night.

**Comment by bensku** [comment]
* Don't mix tabs and spaces
* Don't mix different indentation lengths (2 vs. 4 spaces)
* Use editor with UTF-8 support if you don't already.
