### ISSUE TITLE
Skript reload error

### ISSUE THREAD

**Issue by ThePraZ** [bensku/Skript#416]
I get this error when I reload my skript
http://pastebin.com/5rL8icfp

Please help me

**Comment by bensku** [comment]
Did you use /reload at some point before.

**Comment by ThePraZ** [comment]
I think no

**Comment by TheBentoBox** [comment]
I am not having this issue on either my private server or public server, both running 2.2-dev25 (with the public one running nearly 100 scripts). The only difference is that my servers (public and test) are on 1.11.2 as opposed to 1.9.4.

**Comment by ThePraZ** [comment]
Are you using any addon? I need addons for my skript

**Comment by TheBentoBox** [comment]
I'm using plenty of addons, but I'm not using Umbaska or WildSkript. Both of them are known to have issues with either 1.9 or this fork. I'd ask around on the skUnity forums and Discord to make sure you're using the right version of all three of those addons (and also check your startup log to see if the three of them are enabling properly).

**Comment by ThePraZ** [comment]
@TheBentoBox  My error is that if I put an skript and reload it it reload with no errors but the skript doesn't work, like if it is empty

**Comment by TheLimeGlass** [comment]
This error most likely comes from an addon. Can you test reload a script with no addons on your server. If so this isn't a skript issue but an addon issue.

**Comment by ThePraZ** [comment]
@TheBentoBox but, what can I do? I need addons for my skript

**Comment by TheLimeGlass** [comment]
@ThePraZ What event is
```
Current node: set {varita.%player%} to 0 (mgcobra.sk, line 264)
```
Line 264 in. The player is what I'm looking for.

**Comment by Snow-Pyon** [comment]
No response and doesn't seem like it's happening anymore, comment if that isn't the case and it'll be reopened.
