### ISSUE TITLE
Entity names broken

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#417]
So, entity names are kind of broken. As an example, code like this outputs "<none>"

on death of cow:
	broadcast "%entity%"

Same thing with event-location with the same code.

I am usin the newest build (dev25)

**Comment by TheBentoBox** [comment]
Wrong expression, use `attacker` or `victim` to refer to the relevant entities in a death event.

**Comment by AsDsDD** [comment]
Yeah, thank you.
