### ISSUE TITLE
on damage event not working

### ISSUE THREAD

**Issue by thejimmyj57** [bensku/Skript#419]
Trying to use on damage event for a /god command. Seems to not work what so ever

Here is the code I am using for the command

```
on damage:
	if {god.%UUID of victim%} = true:
		cancel event
		if attacker is a player:
			if damage is caused by fall:
				stop
			set {_god-msg-to-attacker} to {ue.msg.god.msg-to-attacker}
			replace all "{victim}" in {_god-msg-to-attacker} with "%victim%"
			message "%{ue.msg.important.prefix}% %{_god-msg-to-attacker}%" to attacker
```

**Comment by TheLimeGlass** [comment]
Can you send your console log or any errors you may possibly get in the console. I'm currently having some issues with damage cause that might be relevant.
