### ISSUE TITLE
console error on startup: ch.njol.skript.SkriptAPIException: No class info found for animation

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#422]
Today I have updated to the latest Skript version:  Skript: 2.2-dev25
My server is running on Paper Spigot 1.10.2

And lots of errors appear on startup:
https://www.hastebin.com/pocajewoti.vbs

Previous version I had was: Loading Skript v2.2-dev20
And no errors there.

**Comment by TheLimeGlass** [comment]
Pretty sure this is a RandomSk error

**Comment by bensku** [comment]
Addon issue. Closing...

**Comment by bloggy** [comment]
I removed RandomSK and it seems to work now. Since using Skellett I no longer need RandomSK, right?

**Comment by TheBentoBox** [comment]
@bloggy Yeah, Skellett has basically everything from RandomSK now.
