### ISSUE TITLE
Chunks issues

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#423]
If i use the syntax 

Reset chunk at (location|player)

It restores the chunk but somehow if i do that in a chunk that contains a cavespider, silverfish or blaze spawner it removes them. Zombie, skeleton and spider spawners seem to work tho aswell as mansions and strongholds (besides the silverfish spawner) is there any way to fix this?

I use dev25

I also discovered an issue with loop all blocks in chunk at player. It wont loop spawners, soul sand, nether bricks and most likely many other materials.

**Comment by TheLimeGlass** [comment]
Pretty sure this is a Mojang/Spigot issue

**Comment by bensku** [comment]
Not Skript issue, sorry.
