### ISSUE TITLE
On teleport broken in dev25

### ISSUE THREAD

**Issue by skripttpbug2** [bensku/Skript#428]
possibly related to the fixing of #406 
```
on teleport:
    broadcast "hi"
````
does not broadcast anything. bizarrely it worked the first restart after upgrading to dev25 but after any more restarts it stopped working

**Comment by JeepSmash** [comment]
I'm running dev25 on 1.11.2 and the On teleport event is firing for me.  Do you have any errors in console when you reboot?  I'm assuming this happens after the entire server restarts not just a /reload command which is known to make bad things happen

**Comment by bensku** [comment]
I have got multiple error reports like this, but they do not help, at all unless you tell us how to *reproduce* the issue. And no, I don't think this is related to fixing #406.

**Comment by skripttpbug2** [comment]
wish i knew how to reproduce it. the only thing i could tell you is the above code worked until i restarted my server for the first time after installing dev25. It now does nothing, no errors in console or anything

**Comment by Snow-Pyon** [comment]
Still happening? I'll close otherwise.
