### ISSUE TITLE
PlayerInteractEntityEvent not being cancelled

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#429]
```
on right click on item frame:
	broadcast "hi"
	cancel event
```
Event is called but isn't actually cancelled

I have noticed this aswell with other entities such as villagers not being cancelled. I don't know if this wasn't possible back in the day when Skript was made or if this is a glitch. But when clicking on entities the event is called but it can't be cancelled?

Just wondering on this. Thanks.

**Comment by JeepSmash** [comment]
#290 Specifically reports this issue.  it started with 1.11  I had several scripts that worked prior to 1.11 and then were unable to cancel the events after updating to 1.11

**Comment by bensku** [comment]
If the event is called, there is no reason why you couldn't cancel it. Unless, of course, Spigot ignores the request to cancel the event.

**Comment by TheBentoBox** [comment]
Closing since this dupes #290.
