### ISSUE TITLE
NEW FEATURE Suggestion: Alphabetically ordering of a list

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#43]
I need a function to alphabetically order a list like this:

{test::1} = "Anton"
{test::2} = "Berthold"
{test::3} = "Zafer"

Can you implement something like this? Would be awesome!

**Comment by bensku** [comment]
It is possible, and might be pretty easy actually... However, it will be *very* slow no matter how I implement it. I can either
1. Organize list each time a new value is added, which makes adding values slow
2. Loop through list each time a value is needed and _maybe_ cache results, which is either slow or very complicated

Soo... Not high priority, sorry.

**Comment by xXAndrew28Xx** [comment]
I'll try to add it right now. I just got the project working in my IDE.

**Comment by xXAndrew28Xx** [comment]
Ignore ff8f77f

**Comment by bensku** [comment]
Done!

**Comment by bloggy** [comment]
May I know the code for this? How would I use it? Example please :)
