### ISSUE TITLE
Particle don't working

### ISSUE THREAD

**Issue by cisiluma02** [bensku/Skript#432]
http://imageshack.com/a/img922/8418/V6vaB3.png
http://imageshack.com/a/img924/2646/r58zyn.png

```
on damage:
    projectile is snowball
    if attacker is holding stick of unbreaking 1 named "&cAsa" with lore "&2Eklenti: &4Yak":
        if {yak.%attacker%} is 1:
            ignite the victim for 5 seconds
            show 5 "flame" particles at location of victim for victim offset by 0.4, 0.7, 1
```

>show 5 "flame" particles at location of victim for victim offset by 0.4, 0.7, 1
skRayFall v1.9.7

**Comment by Snow-Pyon** [comment]
This issue isn't related to Skript, it's an effect of skRayFall, an issue of skRayFall, contact to the author of it if you want support from his addon.

**Comment by TheBentoBox** [comment]
@Snow-Pyon is correct (as always!). Contact eyesniper! Closing.
