### ISSUE TITLE
Dev 25 still registering to server as Dev 23

### ISSUE THREAD

**Issue by Zaphara94** [bensku/Skript#437]
Just installed Dev 25 to the server, restarted it, and I keep getting a skript notification that Dev 25 is now released and that I am running Dev 23 still.

**Comment by Snow-Pyon** [comment]
Did you install it correctly? If you're using FTP, you might check if you saved the changes too.

**Comment by Zaphara94** [comment]
Yeah, that was my bad! Sorry XD I guess I disabled the wrong Skript.jar! (would help if they were labeled skript-25.jar etc)
