### ISSUE TITLE
Safe explosion not working as expected

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#44]
"Starting with Bukkit 1.4.5 and Skript 2.0 you can also create "safe explosions" which will damage entities but won't destroy any blocks."

But this does not do any damage to entities nearby:

on death:
	if victim is a zombie:
		create a safe explosion of force 10 at the victim

Can you fix it?

**Comment by bensku** [comment]
It seems to work now (with no changes to Skript), maybe this was Spigot bug?

**Comment by bloggy** [comment]
Which spigot version?
