### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by donut42915** [bensku/Skript#447]
I get this error when starting my server:
https://justpaste.it/14wp9

Also get a bunch of errors when enabling the skripts:
https://justpaste.it/14wsp
(just one of many)

Some of the example scripts that it comes with work and some of them do not work.

**Comment by Tuke-Nuke** [comment]
What's your Skript and server version?

**Comment by Syst3ms** [comment]
```
#!#! at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:626)
```
1.10.2 server version

**Comment by donut42915** [comment]
I'm using the latest skript  version (dev25?) and my server is 1.11.2.

**Comment by Snow-Pyon** [comment]
If you have used a plugin like PlugMan or the `/reload` command to load Skript then that's the issue, try completely restarting your server.

**Comment by donut42915** [comment]
Restarting the server didn't help. Skript just doesn't seem to understand any of the events.

**Comment by TheBentoBox** [comment]
Does this happen without any addons installed?

**Comment by bensku** [comment]
Are you possibly running CraftBukkit instead of Spigot? It is not supported, and might cause stuff like this.

**Comment by donut42915** [comment]
Oh yeah I was using craftbukkit thanks.
