### ISSUE TITLE
Clicking on Storage Minecarts can not be canceled!

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#448]
Until updating to Paper Spigot 1.11.2 this worked for me:

**on rightclick on storage minecart:
	send "&cZugriff verweigert - Storage Minecarts können nur abgebaut werden!" to the player
	cancel event**

But stopped working as of now. The message is shown to the player but he can also access the inventory of the storage minecart.

**Comment by TheLimeGlass** [comment]
Duplicate #290
