### ISSUE TITLE
Skript won't load with latest Umbaska (conflict?!)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#45]
When I have umbaska installed, skript fails to load.

This is the error from my startup log:
http://hastebin.com/fobetudozu.avrasm5

Versions:
Umbaska v2.0 Beta 5.5
Skript (latest dev build from you, bensku)
Spigot 1.9.2

**Comment by bensku** [comment]
Umbaska has some error with Metrics it seems, and somehow Skript doesn't like that either... Interesting.

**Comment by bensku** [comment]
No new information and closed source addon used -> closing.
