### ISSUE TITLE
difference between not working with variables

### ISSUE THREAD

**Issue by gitscrubsk** [bensku/Skript#450]
```
command /works:
	trigger:
		send "%difference between 1 and 2%"
command /broken:
	trigger:
		set {_1} to 1
		set {_2} to 2
		send "%difference between {_1} and {_2}%"
```
`

**Comment by Tuke-Nuke** [comment]
Already known issue and I think I know how to fix it, I will see it later if possible.

**Comment by bensku** [comment]
Still an issue @gitscrubsk ?

**Comment by TheBentoBox** [comment]
@bensku Still an issue in dev27, this is using the code provided then running `/works` followed by `/broken`:

![image](https://cloud.githubusercontent.com/assets/6902229/25968316/0400a762-365f-11e7-93e9-b458561ff33c.png)

**Comment by Syst3ms** [comment]
The problem obviously lies (here)[https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/expressions/ExprDifference.java#L75-L78]

**Comment by Syst3ms** [comment]
Yup, there is no such thing as a date/timespan to double converter. Plus, one can't just calculate a difference with numbers and convert it back to timespans OR numbers like that

**Comment by bensku** [comment]
Wait what... Yeah, this is definitely the cause for this. Wasn't the parser bug after all...

**Comment by StealWonders** [comment]
Still really isnt fixed.
Using the following code:

`set {_diff} to difference between {game.start} and now	
set {_diff} to difference between {map.%map%.maptime} and {_diff}
send "&eNext map starts in: %{_diff}%"`

**Comment by StealWonders** [comment]
@bensku @Syst3ms @Tuke-Nuke

**Comment by Syst3ms** [comment]
Could you demonstrate that with dummy data ? I don't see the problem atm

**Comment by StealWonders** [comment]
The error I get with skript can be seen here:
https://www.dropbox.com/s/nncpztkg3nlea3h/Screenshot%202018-01-04%2020.56.33.png?dl=0

Dummy test:
step 1.: difference between 18:30 and 18:45 (now)
step 2.: difference between 50 [minutes] and 15 [minutes] (step 1)

**Comment by bensku** [comment]
Looks like an user error to me. Specially, invalid uae of variable inside another one's name. It should be %{map}%, not {map}.

**Comment by StealWonders** [comment]
Sorry for wasting your time @bensku Works like a charm!

**Comment by LifeLesS2147** [comment]
31
