### ISSUE TITLE
Canceling rightclick event & remove tool from player's hand causes FATAL ERROR + buggy skull

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#451]
As md5 mentioned in this issue thread they changed something regarding how empty itemstacks are handled: https://hub.spigotmc.org/jira/browse/SPIGOT-2977

And I have this issue on my server when canceling the placing of a mob head and remove 1 of tool from tool. Here is my skript:

```
on rightclick with mob head:
	if player is sneaking:
   	  cancel event

```
```
on rightclick with player head:
	if name of event-item contains "Coolbox":
 	   remove 1 of tool from tool

```

The item in my hand is 397:3 (SKULL_ITEM). While sneaking and right-clicking I get this spigot error in console:
https://www.hastebin.com/upuxajinuq.vbs

This way players are able to place bugged skull items anywhere in the world.
Hope you can reproduce and fix asap!

**Comment by Snow-Pyon** [comment]
Cannot reproduce any of the above issues in my 1.11.2 test server (with a fresh build from BuildTools) and the dev25 with the code provided above.

**Comment by bensku** [comment]
This is likely a Spigot bug, as md5's warning was mostly meant for NMS developers. Anyone else can reproduce on something that is not 1.11.2?

**Comment by bensku** [comment]
No other reports, so I assume this is a bug with certain Spigot versions.
