### ISSUE TITLE
Bug when trying to delete a uuid variable

### ISSUE THREAD

**Issue by MarvelDC** [bensku/Skript#455]
`[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! [Skript] Severe Error:[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.[21:47:07] [Server thread/ERROR]: #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/[21:47:07] [Server thread/ERROR]: #!#! and check whether this error has already been reported.[21:47:07] [Server thread/ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),[21:47:07] [Server thread/ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error.[21:47:07] [Server thread/ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well.[21:47:07] [Server thread/ERROR]: #!#! By following this guide fixing the error should be easy and done fast.[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! Stack trace:[21:47:07] [Server thread/ERROR]: #!#! java.lang.NullPointerException[21:47:07] [Server thread/ERROR]: #!#! at uk.co.umbaska.UUID.ExprUUIDOfEntity.get(ExprUUIDOfEntity.java:45)[21:47:07] [Server thread/ERROR]: #!#! at uk.co.umbaska.UUID.ExprUUIDOfEntity.get(ExprUUIDOfEntity.java:16)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.VariableString.toString(VariableString.java:371)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Variable.set(Variable.java:370)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Variable.change(Variable.java:393)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.effects.EffChange.execute(EffChange.java:273)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:54)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:222)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:184)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:270)[21:47:07] [Server thread/ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:165)[21:47:07] [Server thread/ERROR]: #!#! at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)[21:47:07] [Server thread/ERROR]: #!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[21:47:07] [Server thread/ERROR]: #!#! at java.lang.reflect.Method.invoke(Method.java:498)[21:47:07] [Server thread/ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)[21:47:07] [Server thread/ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)[21:47:07] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)[21:47:07] [Server thread/ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1154)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)[21:47:07] [Server thread/ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[21:47:07] [Server thread/ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)[21:47:07] [Server thread/ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)[21:47:07] [Server thread/ERROR]: #!#! at java.lang.Thread.run(Thread.java:745)[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! Version Information:[21:47:07] [Server thread/ERROR]: #!#! Skript: 2.2-dev23[21:47:07] [Server thread/ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT[21:47:07] [Server thread/ERROR]: #!#! Minecraft: 1.8.8[21:47:07] [Server thread/ERROR]: #!#! Java: 1.8.0_112 (Java HotSpot(TM) 64-Bit Server VM 25.112-b15)[21:47:07] [Server thread/ERROR]: #!#! OS: Linux amd64 3.14.32-xxxx-std-ipv6-64-hz1000[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! Running CraftBukkit: false[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! Current node: null[21:47:07] [Server thread/ERROR]: #!#! Current item: delete/clear {banned.msg.%return uuids of entity%}(as java.lang.Object)[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! Thread: Server thread[21:47:07] [Server thread/ERROR]: #!#![21:47:07] [Server thread/ERROR]: #!#! End of Error.[21:47:07] [Server thread/ERROR]: #!#!`

There is the error I get.
Spigot 1.8.8 snapshot r0.1
Skript 2.2-dev23

My code that produces the error:
`command /test <offline player>:
	trigger:
		delete {banned.msg.%uuid of arg-1%}
`

**Comment by TheBentoBox** [comment]
1. This fork does not officially support Minecraft versions below 1.9. If you want proper support here, you should update.
2. If you read that error properly, you'll see it says the cause is Umbaska:

`at uk.co.umbaska.UUID.ExprUUIDOfEntity.get(ExprUUIDOfEntity.java:45)`

I'd suggest trying to change the syntax to `%arg-1's uuid%`, as the `uuid of %entity%` syntax is what's triggering Umbaska's code to try to run. Hopefully that fixes it for you, but regardless, this isn't the place to come for Umbaska issues nor issues on pre-1.9 Minecraft versions.
