### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by kiritss** [bensku/Skript#456]
Suggestion: adding region for break/mine events. I'm trying to check a line on a sign to check if it's a player that is a member of a region but I'm getting an error that says "no region in an on break / mine event"

**Comment by TheBentoBox** [comment]
You can just use `region at event-location` to get the regions at the block.

Please note if you have any other questions or if that doesn't work for you, if not I will close this.

**Comment by kiritss** [comment]
Okay, that worked for bypassing the mine/break event but now it says can't compare a text with 'member of the region at event-location' now

**Comment by TheBentoBox** [comment]
Are you doing `"%player%"` instead of just `player`? You can't put the player in a text then check if they're a member, because then the object is no longer a player, but a text.

If that's not your problem, I'll need to see your code to help you further.

**Comment by kiritss** [comment]
Basically, I'm checking a lockette sign number to see if it's a member in the region, if not, remove it.

**Comment by TheBentoBox** [comment]
You'll have to parse the line as a player (if they're going to always be online when the code runs) or offline player.

**Comment by kiritss** [comment]
so would I do something like

set {lockette} to line 2 parsed as offline player

**Comment by TheBentoBox** [comment]
Yes, if that doesn't work you may need to do `"%line 2%`. However, I'm not even positive if you can check if an offline player is a member of a region, but hopefully it will work.

**Comment by kiritss** [comment]
It doesn't seem to check for offline players

**Comment by kiritss** [comment]
this is what i have
`on break of sign:
	if player is owner of the region at event-location:
		if line 1 is "[Private]":
			set {lockette} to line 2 parsed as offline player
			if {lockette} is not member of the region at event-location:
				cancel event
				set event-block to air
				delete {lockette}
on break of wall sign:
	if player is owner of the region at event-location:
		if line 1 is "[Private]":
			set {lockette} to line 2 parsed as offline player
			if {lockette} is not member of the region at event-location:
				cancel event
				set event-block to air
				delete {lockette}`

**Comment by TheBentoBox** [comment]
If it won't work for offline players then there's not much that can be done I don't think.

Also, just so you know, if you start a variable's name with an underscore, it will be a temporary variable that automatically gets removed after the event code ends. You can change `{lockette}` to `{_lockette}`, then get rid of the `delete {lockette}` lines. You can also just merge those two event listeners by changing it to `on break of sign or wall sign`, then it will run for both of them instead of you needing a duplicate of the code.

**Comment by kiritss** [comment]
alright, well thanks for the help anyways
