### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by krakenicek** [bensku/Skript#458]
Hi. Today, i edited some code of my Skript. Everything was running without errors, so i stopped server hosted on my PC. Few hours later, I started server and get this error » https://pastebin.com/pZFE5Qzd

Part of Skript that is mentioned in the error » https://pastebin.com/dA6DAWgR

Thanks for replies.

**Comment by Tuke-Nuke** [comment]
This error does not came from Skript since particles is not supported.
Try it only with Skript to see if the error still persists, if it doesn't, you should check your addons and report it to the addon that has particles support.

**Comment by krakenicek** [comment]
I have probably 7 addons to my Skript and yesterday, it was running without errors. I don't know what happened..

**Comment by bensku** [comment]
This is very likely due to addons not using Skript API correctly. SkriptAPIException, that it is.

**Comment by bensku** [comment]
Cannot reproduce the issue without (or probably even with) addons.
