### ISSUE TITLE
Skript Mysql Errors

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#462]
Spigot 1.8.8 Java 8
Skript:
Pastebin: https://pastebin.com/uah7xeeU
Hastebin: https://hastebin.com/nupolewaru.sql
Pasted.Co: http://pasted.co/f83c9929

Errors
Pastebin: https://pastebin.com/qKBQDbzf
Hastebin: https://hastebin.com/ecugubuyuh.vbs
Pasted.Co: http://pasted.co/782b3f8a

**Comment by Syst3ms** [comment]
1. This fork doesn't support versions below 1.9
2. This is a Skellett error, not a Skript error
To close.

**Comment by TheBentoBox** [comment]
Barely beat me @Syst3ms!

Just as has been said, this is not an issue to report here. Ask Lime.
