### ISSUE TITLE
every minecraft minute

### ISSUE THREAD

**Issue by Remixful** [bensku/Skript#464]
This event is not functioning properly:
```
every minecraft minute:
    broadcast "hello world"
```

This should be broadcasting hello world every ~16 ticks.

Edit:
I believe `minecraft minute` is being converted to `1 hour and 12 minutes` for some weird reason.
It's probably turning
`every minecraft minute` to `every 1 hour and 12 minutes`
This is just my assumption since setting a variable to a minecraft minute and printing it will show `1 hour and 12 minutes`

I'm also trying to understand how to add minecraft time to variable set to a minecraft time.
`    set {_a} to time in "main"
    broadcast "%{_a}%"
    add 10 minecraft seconds to {_a}
    broadcast "%{_a}%"`
Does not add anything.

**Comment by whoshenry** [comment]
Perhaps linked to my error and issue with minecraft time?

**Comment by Nicofisi** [comment]
`every minecraft minute` -> irl `1 hour and 12 minutes`
`every minecraft second` -> irl `1 minute and 12 seconds`
`every minecraft tick` -> irl every tick, properly
`every minecraft hour` -> irl `3 days`
`every minecraft day` -> irl ` 72 days`
Skript seems to like the number 72, and it isn't for no reason
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/util/Timespan.java#L119

**Comment by Nicofisi** [comment]
I did some maths and the 72 number seems to be right, because an irl day has `60 * 60 * 24 * 20` = `1728000` ticks, and a Minecraft day has `24000` ticks and when you divide that you get 72.

The issue is that the code is `amount *= 72f;`, and it should be divided instead of multiplying?

**Comment by nfell2009** [comment]
It appears to be converting real time to Minecraft time which is 1 hour and 12 minutes. Minecraft time to real time would mean that 1 Minecraft minute is ~0.83 seconds which is ~16 ticks.

![image](https://user-images.githubusercontent.com/4953800/36540837-c630a660-17d3-11e8-9074-007f8f7a1eea.png)
