### ISSUE TITLE
JSON chat variables

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#467]
![jsonvariablebug](https://cloud.githubusercontent.com/assets/19997813/24803081/c43d2130-1bb2-11e7-839f-feb83ac10f3e.png)

So hovering over that text stored in that testvariable variable won't show anything.
Nothing in console.
I'm of corse using newest skript and spigot.

**Comment by bensku** [comment]
Hmm, I guess I didn't consider that you'd have tooltip only for variable. If you add some text between %{testvariable}% and tooltip tag, it might work.

**Comment by bensku** [comment]
This is should be fixed now.

**Comment by HonestlyDex** [comment]
??
