### ISSUE TITLE
Not parsing Color Codes

### ISSUE THREAD

**Issue by RepublicMC** [bensku/Skript#476]
**_Issue: Not parsing Color Codes_**
I've disabled all of my Skripts to find the issue, I've also set up a /test command to send a message with colored formatting to the command sender. However, I've noticed that this is an issue with Skript 2.2, not my code.

`command /test:
	trigger:
		send "&cHello there!"`

When the console executes /test:
http://prntscr.com/etx7xf

When a player executes /test:
http://prntscr.com/etx83h

I'd like to have this fixed as soon as possible, this is affecting my server on a huge scale and I do not wish to consider using an older version of Skript and let go of features like JSON just to have this one issue

**Comment by TheBentoBox** [comment]
Duplicates #465. Please search before submitting an issue to ensure it isn't already reported. 

Also, JSON support was _just_ added, so I'm sure you can deal with downgrading to dev25 until this is fixed. If you already integrated the JSON into a ton of places before testing the release thoroughly, that's on you. It's marked as a pre-release, and you should always be testing new releases on a test server before dropping them on a live server assuming they'll work perfectly.
