### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by kiritss** [bensku/Skript#477]
I've tried adding a new command and did /sk reload (skript) and it doesn't seem to refresh the skript. Command doesn't work after reload

**Comment by TheBentoBox** [comment]
I've never had this issue nor heard of anyone else having this issue. More information is needed. 

1. Server version
2. Skript version
3. Any console errors?
4. What's the code that's having this issue?

**Comment by HYPExMon5ter** [comment]
Has happened to a few people in the last few days from what I've seen. Are you running bukkit by chance? Skript doesn't seem to work on bukkit, switch to Spigot.

**Comment by Syst3ms** [comment]
This issue has happened to me quite a few times. I didnt make the link at first, but it became obvious that /reload was causing it. Don't use /reload. Although, it doesn't cause anything to some people, but it fucked Skript pretty badly for me.

**Comment by bensku** [comment]
I might need to make Skript disable itself on /reload... Seriously, it prints warning in chat!

**Comment by TheBentoBox** [comment]
Well, this person never replied again, so...
