### ISSUE TITLE
Severe Error: Not loading - Current Node

### ISSUE THREAD

**Issue by Classic36MC** [bensku/Skript#478]
Came across this error in dev26 so I updated to dev26b but the isuse is still there. I'm running 1 version behind the latest Spigot release.

Error: https://pastebin.com/i6yUswjz

Script: https://www.spigotmc.org/resources/ezmemes.36654/

**Comment by ChimpGamer** [comment]
I have exactly the same problem with dev26. I downgraded to dev25 and everything was normal again.

**Comment by bensku** [comment]
Ah, this kinda makes sense. Not much, but still starting point for debugging...

**Comment by bensku** [comment]
This is likely fixed, assuming it was caused by {@prefix} containing invalid tag.
