### ISSUE TITLE
Permission Eror 

### ISSUE THREAD

**Issue by Shilder26** [bensku/Skript#479]
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#! End of Error.
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#! Thread: Server thread
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#! Current item: format
09.04 14:02:32 [Server] ERROR #!#! Current node: null
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#! Running CraftBukkit: false
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#!   OS: Linux amd64 3.14.32-xxxx-grs-ipv6-64
09.04 14:02:32 [Server] ERROR #!#!   Java: 1.8.0_102 (OpenJDK 64-Bit Server VM 25.102-b14)
09.04 14:02:32 [Server] ERROR #!#!   Minecraft: 1.11.2
09.04 14:02:32 [Server] ERROR #!#!   Bukkit: 1.11.2-R0.1-SNAPSHOT
09.04 14:02:32 [Server] ERROR #!#!   Skript: 2.2-dev25
09.04 14:02:32 [Server] ERROR #!#! Version Information:
09.04 14:02:32 [Server] ERROR #!#! 
09.04 14:02:32 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:745)
09.04 14:02:32 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
09.04 14:02:32 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
09.04 14:02:32 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
09.04 14:02:32 [Server] ERROR #!#!     at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738)
09.04 14:02:32 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
09.04 14:02:32 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.effects.Delay$1.run(Delay.java:84)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:93)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:65)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:54)
09.04 14:02:32 [Server] ERROR #!#!     at com.w00tmast3r.skquery.elements.effects.EffAddFormatSlot.execute(EffAddFormatSlot.java:62)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getSingle(ConvertedExpression.java:151)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:63)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
09.04 14:02:32 [Server] ERROR #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:1)
09.04 14:02:32 [Server] ERROR #!#!     at com.w00tmast3r.skquery.elements.expressions.ExprLoredItemStack.get(ExprLoredItemStack.java:23)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.getSingle(VariableString.java:483)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.VariableString.toString(VariableString.java:383)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:105)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:76)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.SimplePropertyExpression.get(SimplePropertyExpression.java:57)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(PropertyExpression.java:105)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.registrations.Converters.convertUnsafe(Converters.java:296)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.registrations.Converters.convert(Converters.java:305)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.hooks.chat.expressions.ExprPrefixSuffix.convert(ExprPrefixSuffix.java:1)
09.04 14:02:32 [Server] ERROR #!#!     at ch.njol.skript.hooks.chat.expressions.ExprPrefixSuffix.convert(ExprPrefixSuffix.java:64)
09.04 14:02:32 [Server] ERROR #!#!     at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:91)
09.04 14:02:32 [Server] ERROR #!#!     at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getPlayerPrefix(Chat_PermissionsEx.java:291)
09.04 14:02:32 [Server] ERROR #!#!     at net.milkbowl.vault.chat.plugins.Chat_PermissionsEx.getUser(Chat_PermissionsEx.java:107)
09.04 14:02:32 [Server] ERROR #!#!     at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405)
09.04 14:02:32 [Server] ERROR #!#! ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?

**Comment by bensku** [comment]
SkQuery issue. Do not ask support for addons here.
