### ISSUE TITLE
Error passing PlayerPortalEvent when returning from secondary Nether/End worlds

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#48]
I hope the title makes it sort of clear, it's hard to briefly describe the situation in which this is occurring.

Basically, if you're in a Nether or End world that isn't the main one (which are named "world_nether" and 'world_the_end"), and you stand in a portal, you get this error spamming console. e.g. On my server we have a resource world which is reset monthly for fresh resources, and it has its own attached Nether and End. If someone tries to enter a Nether portal while in world "resource_nether", I get the error. Same while trying to enter the End portal in "resource_the_end".

[Stack trace of error](http://pastebin.com/pmWd2ML3).

**Comment by bensku** [comment]
Uh, this was probably fixed. Forgot to close.

**Comment by TheBentoBox** [comment]
Haha alright, thanks Bensku.
