### ISSUE TITLE
java.lang.NullPointerException in console when executing command

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#480]
https://hastebin.com/colatosada.md

Here is the code

`                    arg-1 has permission "tab.exotic"
                    send "hi1" to arg-1
                    set score "lol" in sidebar of arg-1 to 1`

"set score "lol" in sidebar of arg-1 to 1" breaks the plugin.

**Comment by Snow-Pyon** [comment]
This isn't an issue of Skript, report it to the author of skRayFall.

**Comment by Adrihun** [comment]
ok thanks

**Comment by Adrihun** [comment]
What should i do now?
The dev isn't that active, it may take months for the dev to update the plugin 👎

**Comment by TheBentoBox** [comment]
Don't know, but nothing we can do for you here, sorry.
