### ISSUE TITLE
Formatting codes not applying to correct sections of text

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#482]
Hello

In dev26c, ampersand color codes are once again functioning, and we are getting closer to it working properly. However, ALL formatting codes are behaving strangely; this includes JSON tags, and formatting codes using the angled bracket notation (e.g. `<green>` as opposed to `&2`).

## Example Test
[I recorded a video here](https://gyazo.com/ecc262c4cc97ae6b5687de38093f47af). This is the code that is being run:

`send "Part One <green> Part Two <tooltip:test> Part Three <reset> Part Four &2 Part Five <strikethrough> Part Six <yellow> Part Seven" to the player`

Here, we can see a couple of issues. All formatting codes (this applies to the `<green>`, the `<tooltip>`, and the `&2`) format the messages inappropriately; as far as I can tell, they not only apply forwards in the text until they find another color code or a reset, but backwards as well. There are no color codes in the message until _after_ the "Part One" text, yet it is receiving the green color from the `<green>` tag, which it shouldn't. The tooltip, which is surrounding "Part 3", is also appearing when "Part 2" is hovered over, yet not for "Part 1" (likely because the `<green>` code is creating a new chat message section, which breaks it off there). [This is how it should look](https://gyazo.com/e9334dc10e354639b5300912fbe69f42).

Additionally, the default Bukkit behavior of color codes resetting style codes [no longer works](https://gyazo.com/fa33afbf7bacf7f98a04a0bdea3d8a73) (by style codes I refer to underline, bold, obfuscation, and italics). This is not how it has always worked; previously, the underline would have stopped at the `&6` in that message, yet now it continues through. The behavior still works as intended elsewhere in Skript (such as item names), but [is now inconsistent throughout the plugin](https://gyazo.com/b264196b496530f531315d6564eee603) since it works differently for chat messages (you can see the appropriate version appearing over my hotbar for the renamed item).

## Setup
- Spigot-d276ab1-1f6c04c for 1.11.2 (1 version behind latest)
- Skript dev26c
- No addons, no scripts loaded
- [Setup screenshot](https://gyazo.com/52919bbad1cdbd740801b31179a81360)

**Comment by bensku** [comment]
Formatting codes now apply to correct sections. However, I have decided that color codes will, in future, not reset other formatting. I will try to make it consistent so it works this way everywhere, but sadly not in this release - out of scope for bugfix.
