### ISSUE TITLE
Sending a variable in chat without text before it causes an internal error

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#483]
Hello

I presume this is due to the fix for variables being allowed in JSON tooltips and such. That DOES work appropriately, but we now have this issue.

## Example Test
Here's a simple screenshot of the issue

![image](https://cloud.githubusercontent.com/assets/6902229/24879953/8167088e-1e06-11e7-870a-4d6e3cf471f0.png)

Adding text beforehand fixes it completely, but naturally this means you can't even run simple effect commands like `send "%{example}%"` to get a variable value. 

[Here's the console error](https://pastebin.com/Qd03CGvQ).

## Setup
- Spigot-d276ab1-1f6c04c for 1.11.2 (1 version behind latest)
- Skript dev26c
- No addons, no scripts loaded
- [Setup screenshot](https://gyazo.com/52919bbad1cdbd740801b31179a81360)

**Comment by bensku** [comment]
This has been fixed now.
