### ISSUE TITLE
Expressions with embedded quotes no longer parse

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#485]
Hello

Sorry if the title isn't worded amazingly, I'm not sure how best to put it. 

## Example Test
Here's an example of me trying to get Skript to send me my stringified player object in dev26 (this should print out my name):

![image](https://cloud.githubusercontent.com/assets/6902229/24879518/2ce437e2-1e05-11e7-8577-78d6e13d7ff0.png)

For the sake of showing how it should work, here's a test run in dev25 immediately afterwards (stopped server, replaced the jar with dev25, started again, no other changes):

![image](https://cloud.githubusercontent.com/assets/6902229/24879578/5b8721e0-1e05-11e7-8b7b-a66ada6b882d.png)

Unlike the other issues I've reported, this is **not** just an issue within chat messages. Even if I run, for example, `set player's tool's name to "%""Mr_Simba"" parsed as player%"`, it will give the same error. This is not the case in dev25 or below, where it will work as expected based on the second screenshot.

Also, I know this example seems poor, but it's the first thing I thought of on the spot to demonstrate the issue. Especially when using addons, needing to stringify expressions with text within them is pretty common. One common example for my server is when using SkStuff, which has the expression `tag %text% of NBT of %entity%`. If I want to compare the returned NBT tag to a string (which I do a lot), I could run `if "%tag ""Example"" of NBT of player%" is "1"`. This no longer parses in dev26, which results in dozens of errors when loading all of my scripts (which work fine and parse correctly on dev25). In the case of that SkStuff expression, Skript fails at parsing it and says that the tag is not a world.

## Setup
- Spigot-d276ab1-1f6c04c for 1.11.2 (1 version behind latest)
- Skript dev26c
- No addons, no scripts loaded
- [Setup screenshot](https://gyazo.com/52919bbad1cdbd740801b31179a81360)

**Comment by bensku** [comment]
Fixed with next release. There was actually *two* bugs with quotes, one specific to JSON chat and one that appeared everywhere (both fixed).
