### ISSUE TITLE
Particle Effects

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#49]
Hi there,
can you add particle effects into Skript? 

Something like:
display 200 of particle heart at player 

This would be awesome :-)

**Comment by bensku** [comment]
... I added that in last update. You can use old play/show syntax found in Skript's documentation.

But multiple particles same time? Hmm, I'll look at that.

**Comment by Pilvinen** [comment]
Would be kind of useless to add multiple particles at the same time as they would only occupy the same space where you spawn them all without support for spreading the particles - which it would seem Spigot API doesn't support.

Unless of course if bensku makes his own logic for that. Since you can already spawn particles at location xyz where is no reason why you couldn't add vanilla /particle command like randomness to it from Skript's side even if Spigot API doesn't support it atm.

**Comment by bloggy** [comment]
True. You should slightly change the coords of the spawned particles if you spawn more than 1 particles. But that shouldn't be too difficult. Can you tell me where I can find a complete list of particles I am able to spawn? And are these particles shown to all players nearby?

**Comment by bensku** [comment]
Ooops. It seems Github didn't publish the draft which had the feature.

**Comment by bloggy** [comment]
I think I found a bug with the particles effect:

**# does not work (does not show any particles)
set {_loc} to location of targeted block
show heart at {_loc}

**# does work
show heart at targeted block

**Comment by bensku** [comment]
Features added, so retagging for that bug which still exists.

**Comment by bloggy** [comment]
There are even more bugs now.

My script code:
```
command /inlove:
	trigger:
		play 100 heart at targeted block
```

The error when reloading this script:

http://pastebin.com/wLca3DN3

Also there is no effect when I execute the "inlove" command.

**Comment by Pilvinen** [comment]
I'm also getting these. And the crash stops the skript from running so I had to comment out all the effect to keep in business...

**Comment by bloggy** [comment]
And now I have another problem with this release:
https://github.com/bensku/Skript/releases/tag/dev12c

When I do:
play 100 (dust of oak wood with speed 0) above clicked block

then I get:
the clicked block is not an entity

But I want the particles to be shown a location too, not only on entities?!

**Comment by TheBentoBox** [comment]
Try "1 meter above clicked block", bloggy. I can't test right now but I don't know if you can just do "above x".

**Comment by bloggy** [comment]
Thanks. This works for me:
play 20 (heart with speed 0) at targeted block

But the particles are spread in a very huge radius. Could you add additionale parameters to limit the spread of the particles to a smaller radius @bensku ?

**Comment by TheBentoBox** [comment]
@bloggy, the spread is the offset, which the release notes say can be added to any effect command with the syntax `[with [offset of %number%, %number%(,| and) %number%][[and ]speed %number%]]`. Try doing `play 20 (heart with offset of 0.25, 0.25, 0.25 and speed 0) at targeted block`

**Comment by bloggy** [comment]
Ok will try this. But if you don't add any offset value the spread is way to much / wide. The default spread should be way less.

**Comment by bensku** [comment]
Closed, and opening another issue
