### ISSUE TITLE
Loop stop working after some time

### ISSUE THREAD

**Issue by aescraftbr** [bensku/Skript#490]
This is the code I am using:

```
on join:
  while player is online:
    wait 1 minute
    if {sono.%player%.bypass} is not set:
      if {sono.%player%} is not set:
        set {sono.%player%} to 80
      remove 1 from {sono.%player%}
```

It stops working after running for some time. It should not stop.

**Comment by TheBentoBox** [comment]
Fixed your post, you need to use three ticks ` on either side for multi-line code blocks.

Cannot reproduce. I have plenty of long-term loops like this running on my server and have never experienced it. Are you sure that it's stopping, as opposed to some conditions not being met or something?

**Comment by aescraftbr** [comment]
Well, this is the full code if you want to check it:

'''every minute in world "world":
    loop all players:
        {sono.%loop-player%} is not set:
            set {sono.%loop-player%} to 80
        else:
            {sono.%loop-player%.bypasss} is not set:
                remove 1 from {sono.%loop-player%}
                send action bar from "&o&c§l-1 §7[§a-§7] §6%{sono.%loop-player%}%/240" to loop-player
                if {sono.%loop-player%} > 210:
                    remove speed from the loop-player
                    apply speed 1 to the loop-player for 70 seconds
                    remove night vision from the loop-player
                    apply night vision 1 to the loop-player for 70 seconds  
                if {sono.%loop-player%} < 1:
                    set {sono.%loop-player%} to 1
                if {sono.%loop-player%} < 30:
                    apply slowness 1 to the loop-player for 60 seconds
                if {sono.%loop-player%} < 5:
                    remove blindness from the loop-player
                    apply blindness 2 to the loop-player for 70 seconds
                    stop
                if {sono.%loop-player%} < 10:
                    remove blindness from the loop-player
                    apply blindness 1 to the loop-player for 70 seconds
                    stop
            else:
                stop loop

command /sono:
  trigger: 
    if {sono.%player%.bypasss} = true:
      message "§7[§aSono§7]§cVocê está utilizando o /sonobypass true. Digite /sonobypass false para ativar a mecânica de sono novamente"
      stop
    send action bar from "&6%{sono.%player%}%/240" to player
    if {sono.%player%} < 30:
      message "§7[§aSono§7]§cVocê está cansado. Procure uma cama para deitar."

command /showsono:
  trigger: 
    if {sono.%player%.bypasss} = true:
      stop
    wait 3 seconds
    loop 56 times:
      send action bar from "&6%{sono.%player%}%/240" to player
      wait 1 second

on bed enter:
  if {sono.%player%.bypass} = true:
    stop
  else:
    if {sono.%player%} < 120:
      set {sono.%player%} to a random integer between 180 and 240
      remove blindness from the player
      remove slowness from the player
      wait 1 second
      message "§7[§aSono§7]§c Você dormiu! Energia: %{sono.%player%}%/240"
      if {sono.%player%} > 210:
        remove speed from the player
        apply speed 1 to the player for 70 seconds
        remove night vision from the player
        apply night vision 1 to the player for 70 seconds  
      wait 5 seconds
      make player execute "/sono"
    if {sono.%player%} > 120:
      message "§7[§aSono§7]§c Você tentou dormir mas não está cansado o suficiente."
      message "§7[§aSono§7]§c Deite quando o seu nível de cansaço estiver abaixo de 120."     
      make player execute "/sono"

on consume of cookie:
  if {sono.%player%.bypass} = true:
    stop
  else:
    if {sono.%player%} < 50:
      add 5 to {sono.%player%}
      send action bar from "&a+5 por consumir Cookie! §7[§a-§7]§6 %{sono.%player%}%/240" to player
    if {sono.%player%} < 80:
      add 4 to {sono.%player%}
      send action bar from "&a+4 por consumir Cookie! §7[§a-§7]§6 %{sono.%player%}%/240" to player
    if {sono.%player%} < 100:
      add 3 to {sono.%player%}
      send action bar from "&a+3 por consumir Cookie! §7[§a-§7]§6 %{sono.%player%}%/240" to player
    if {sono.%player%} < 120:
      add 2 to {sono.%player%}
      send action bar from "&a+2 por consumir Cookie! §7[§a-§7]§6 %{sono.%player%}%/240" to player
    if {sono.%player%} < 140:
      add 1 to {sono.%player%}
      send action bar from "&a+1 por consumir Cookie! §7[§a-§7]§6 %{sono.%player%}%/240" to player

on death:
  set {sono.%player%} to a random integer between 180 and 200

command /sonobypass:
  trigger:
    if {sono.%player%.bypasss} = true:
      message "§7[§aSono§7]<red> Você já desativou a mecânica de sono permanentemente."
    message "§7[§aSono§7]<red> Você tem certeza que quer desativar a mecânica de sono?"
    message "§7[§aSono§7]<red> Essa escolha é permanente."
    message "§7[§aSono§7]<red> Digite /bypass true para remover, /bypass cancel para cancelar"
    set {sono.%player%.waitingbypasss} to true

command /bypass <text>:
  trigger:
    if {sono.%player%.waitingbypasss} = true:
      if arg 1 is "true":
        set {sono.%player%.bypasss} to true
        message "§7[§aSono§7]<green> Você desativou a mecânica de sono. Enjoe."
      if arg 1 is "cancel":
        clear {sono.%player%.waitingbypasss}
        message "§7[§aSono§7]<green> Você cancelou o bypass! Enjoe os benefícios da mecânica de sono."
    else:
      message "§7[§aSono§7]<red> Utilize o comando /sonobypass primeiro!"

command /checksono <player>:
  permission: skript.checksono
  trigger:
    message "§7[§aSono§7] %arg 1% tem %{sono.%arg 1%}%/240 de energia"

command /checksonobypass <player>:
  permission: skript.checksono
  trigger:
    message "§7[§aSono§7] %arg 1% bypass = %{sono.%arg 1%.bypasss}%"

command /clearsonobypass <player>:
  permission: skript.checksono
  trigger:
    clear {sono.%arg 1%.bypasss}
    message "§7[§aSono§7] %arg 1% bypass = %{sono.%arg 1%.bypasss}%"'''

I really don't think that there's nothing stopping the loop.
I just added a the {sono.%player%.bypass} that allow players to not use this system which is a basic sleep and fatigue system.

Maybe is something with the addons?
the addon list:

- sharpsk
- skellet
- skquery
- skrayfall
- skutilities

I'm using skript 2.2-dev24b (I'll try to update to 26c)

**Comment by TheBentoBox** [comment]
One issue with your code is this part in your `every minute` event:

```
            else:
                stop loop
```

This means that it will stop running the loop as soon as it hits any player with their `.bypass}` variable set. It will stop the loop early instead of continuing on and affecting other players without the bypass variable set. Just remove that code entirely and it will help.
