### ISSUE TITLE
chat json 

### ISSUE THREAD

**Issue by xbxymax** [bensku/Skript#493]
Can do a does not contain json send effect 
There are two kinds of sending effect 
Such as 

With json: 
Send "XXX" to palyer 

No json: 
Sendnoj "XXX" to the player 

Because 26 c this version is a problem with the sending information 
When I use the following code 
Error will be prompted to plug-ins 
	set {_home4::*} to {_home3} split at "="
	send "%{_home4::*}%" to console
	send "%{_home4::1}%%nl%%{_home4::2}%%nl%%{_home4::3}%%nl%%{_home4::4}%%nl%%{_home4::5}%"

**Comment by xbxymax** [comment]
Because of this mistake 
I have to use 2.2 - dev25 
My server is paper 1.11.2

**Comment by Classic36MC** [comment]
JSON support is only in the dev26 releases. Try using dev26b and dev26d if you haven't already.

**Comment by bensku** [comment]
Not enough information to solve the issue. Are there errors in console?

**Comment by bensku** [comment]
Closing. This is probably fixed, no matter what it was.
