### ISSUE TITLE
grow %tree type% above %location% doesn't work with trees other than oak and spruce :V

### ISSUE THREAD

**Issue by PoweredDragon** [bensku/Skript#494]
Hi. Got a problem with this script:
```
on sneak toggle:
	chance of 10%:
		loop blocks in radius 5 of player:
			set {_l} to location of loop-block
			loop-block is sapling:0:
				set loop-block to air
				grow oak above {_l}
			loop-block is sapling:1:
				set loop-block to air
				grow spruce above {_l}
			loop-block is sapling:2:
				set loop-block to air
				grow birch above {_l}
			loop-block is sapling:3:
				set loop-block to air
				grow jungle above {_l}
			loop-block is sapling:4:
				set loop-block to air
				grow acacia above {_l}
			loop-block is sapling:5:
				set loop-block to air
				grow dark oak above {_l}
```
Well; everything is ok with oak and spruce, but with birch, etc. it seems to fall apart:

```
[19:37:33 ERROR]: [Skript] Can't understand this condition/effect: grow birch above {_l} (tree.sk, line 13: grow birch above {_l}')
[19:37:33 ERROR]: [Skript] Can't understand this condition/effect: grow jungle above {_l} (tree.sk, line 16: grow jungle above {_l}')
[19:37:33 ERROR]: [Skript] Can't understand this condition/effect: grow acacia above {_l} (tree.sk, line 19: grow acacia above {_l}')
[19:37:33 ERROR]: [Skript] Can't understand this condition/effect: grow dark oak above {_l} (tree.sk, line 22: grow dark oak above {_l}')
```

It all seems to doesn't work on the newest Sk version :v

**Comment by Snow-Pyon** [comment]
Because birch, jungle, acacia​ and dark oak aren't a tree type, try with the following:
```
[any ] tree[s]

[any ](regular tree|normal tree|oak)[s]

small (regular tree|normal tree|oak)[s]

(big|large) (regular tree|normal tree|oak)[s]

[any ](fir|pine|spruce|redwood)[s]

small (fir|pine|spruce|redwood)[s]

(big|tall) (fir|pine|spruce|redwood)[s]

[any ]jungle tree[s]

small jungle tree[s]

(big|tall|huge|giant|large) jungle tree[s]

[jungle ]bush[es]

swamp tree[s]

[any ](huge|giant|large|big) mushroom[s]

(huge|giant|large|big) red mushroom[s]

(huge|giant|large|big) brown mushroom[s]
```
From the English.lang file, although I don't see the 1.8 trees nor the birch tree there, you might add them @bensku

**Comment by PoweredDragon** [comment]
My aliases file:

>  	{tree type}:
> 		{default} = :0-15
> 		(normal|regular|oak) = :0, :4, :8, :12
> 		(pine|redwood|fir|spruce) = :1, :5, :9, :13
> 		birch = :2, :6, :10, :14
> 		jungle = :3, :7, :11, :15
> 	{tree type 2}:
> 		{default} = :0-15
> 		acacia = :0, :4, :8, :12, :2, :6, :10, :14
> 		dark oak = :1, :5, :9, :13, :3, :7, :11, :15
> 	{wood type}:
> 		{default} = :0-5
> 		<any> = :0-5
> 		(oak|regular|normal) = :0
> 		(spruce|fir|redwood|pine) = :1
> 		birch = :2
> 		jungle = :3
> 		acacia = :4
> 		dark oak = :5

Neither "small jungle tree" works (i tried it too)

**Comment by Snow-Pyon** [comment]
@PoweredDragon the aliases file is only for the item aliases, not the tree types. The aliases of the tree types and other types are in the English.lang file which is in the lang folder (not accessible via the Skript folder yet but you can found it into the Skript.jar)

**Comment by bensku** [comment]
That was actually quite easy to do.
