### ISSUE TITLE
Loop error from documents (txt, ...)

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#496]
Hi,

I'm not sure, if this is an issue made by Skript, but we're currently switching from an 1.10.2 server to an 1.11.2 server. We are upgrading to the newest Skript build, too.

But when we use our "old" scripts with an external text document in UTF-8 format, the new lines aren't recognized. There is only an "CR"-Logo in a square and the loop does not split it, so there is only one loop-value.

`on load:
    wait 2 seconds
    $ thread 
    set {tipps::*} to file contents of "plugins/GMiner/GMiner-Tipps.txt"`

Skript Version: Dev26c

Any idea how to fix it or is it a bug?
![2017-04-13_02 44 22](https://cloud.githubusercontent.com/assets/23314425/24985239/42c44558-1ff3-11e7-9fdb-b3cb67b7cc9d.png)

**Comment by GermanMinerDE** [comment]
(I know, that this is a feature from SkUtilities, but I tried older versions and newer versions of that plugin and it does not work with the new Skript versions)

**Comment by Tuke-Nuke** [comment]
Have you had the same issue when using `dev25`?

**Comment by GermanMinerDE** [comment]
Yes, it's the same with dev25.

**Comment by bensku** [comment]
Very likely not Skript issue. More like 1.11 client interpreting new line characters differently or perhaps change in your server's charset (shouldn't affect anything, but...).
