### ISSUE TITLE
[dev26d] Links in plain chat no longer clickable

### ISSUE THREAD

**Issue by RoyCurtis** [bensku/Skript#501]
In dev25 and older, links that were printed out in chat with the `message` effect were clickable. In dev26d, it appears such links are no longer clickable.

# Testing

* Tested, **not reproducible** with Skript **dev25**
* Tested and reproducible on a local testing PaperSpigot (`git-Paper-1081 (MC: 1.11.2) `) server with 1 plugin
  * Skript **dev26d**

## Setup

* Skript's [`config.sk`](https://gist.github.com/RoyCurtis/1c9a006f9128272e8045f132b5cec4d1)

## Test skript

```
command /links:
    description: Shows a list of useful server websites
    aliases: /www
    executable by: players and console
    trigger:
        message "&B&LServer &flinks:"
        message "&f• &3google.com &f- Google"
        message "&f• &3reddit.com &f- Reddit"
        message "&f• http://zombo.com &f- Zombocom"
```

# Reproduction

1. Save above snippet into `plugins/Skript/scripts/test.sk`
1. `/sk reload all` - Reloads Skripts
1. `/www` - Executes above skript
1. Try clicking any of the links in chat
    * In **dev25** and older, the links will open
    * In **dev26d**, the links do nothing

# Workaround

Use the new JSON chat system to create links, e.g.

`message "&f• <link:http://reddit.com>&3reddit.com<reset> &f- Reddit"`

# Notes

I realize we can use the new JSON system for links. However, I think this is an issue as:

- It breaks backwards-compatibility with older scripts
- It is subjectively simpler and cleaner to just use raw links in messages
- In normal CraftBukkit chat, links in players' chat messages are automatically made clickable. This creates an expectation that links in any messages will be automatically clickable.

**Comment by bensku** [comment]
This is simply because with JSON chat the client doesn't interpret anything as link if it is not marked to be so. Note that Bukkit, by default, does *not* use JSON chat!

**Comment by bensku** [comment]
I guess I can add config option to try to auto-parse https:// as link declaration. Will come in some of next releases.

**Comment by bensku** [comment]
Done.

**Comment by RoyCurtis** [comment]
Thank you very much for this!
