### ISSUE TITLE
%% doesn't work

### ISSUE THREAD

**Issue by PanKlipcio** [bensku/Skript#502]
Sorry for my bad english.

Command:
`command /test:
trigger:
send "%number of players%"`

There is 1 player on the server
After writing the command "/test", 1 - logical is displayed
After writing "/test" again is displayed 22

**Comment by TheBentoBox** [comment]
Cannot reproduce with your exact code, it sends 1 every time. Anyone else having this issue?

**Comment by PanKlipcio** [comment]
This code which I sent also does not work, sure it is only on my server

**Comment by bensku** [comment]
Cannot reproduce.
