### ISSUE TITLE
New line character error

### ISSUE THREAD

**Issue by GermanMinerDE** [bensku/Skript#507]
Hi again,

I already talked about issues with new line characters in #496 but you closed it.
I'm not sure, if it is not an Skript or Skript related error.

So, when setting the motd on server ping the new line character appears.

```
on server ping:
    set {_t} to random number between 1 and 5
    set motd to "&8German&cMiner&eDE &7» &7Wirtschaftsserver (DE) &81.11.2 %nl%&aInfo » &r&c&k||&r &a%colored {ListMotd}% &r&c&k||"
```

Something weird is happening with the %nl%-variable. It makes a new line, but the "CR"-symbol is shown too. If it is not caused by Skript directly... any idea, what could be the error?

**Comment by GermanMinerDE** [comment]
Screenshot of MC-server-list: https://www.dropbox.com/s/79ou5k5fuokmgwb/Screenshot%202017-04-14%2023.36.56.png?dl=0

**Comment by TheBentoBox** [comment]
The newline character is an expression from SkQuery, not Skript. I'm not sure what's causing it, unfortunately, but it's not an issue to be reported here. You could try \n instead of %nl%, but otherwise I'm not sure.

**Comment by GermanMinerDE** [comment]
Hi. Thank you for your quick answer and the suggestion.
\n or \r does not work, but I'll try to contact the developer of SkQuery.
