### ISSUE TITLE
All colour codes need &r before them - dev26e

### ISSUE THREAD

**Issue by Classic36MC** [bensku/Skript#509]
It appears that all colour codes need &r before them in dev26e to work correctly. Due to this, old skripts with messages break.

Is this intentional behaviour?

**Comment by bensku** [comment]
Could you clarify a bit? Do you mean:

1) Color code doesn't reset formatting codes
2) Applying new color is not possible without resetting styles first

Case 2 would definitely be a bug. Case 1 is something I will make configurable (I personally would like it, but not everyone agrees)

**Comment by Classic36MC** [comment]
Case 1, I believe.

**Comment by bensku** [comment]
Very well.

**Comment by Classic36MC** [comment]
Okay, thank you.

**Comment by Classic36MC** [comment]
Turns out the issue I was having was fixed in dev26f.
