### ISSUE TITLE
[Enhancement]Lightning Strike event

### ISSUE THREAD

**Issue by PoweredDragon** [bensku/Skript#510]
I found Lightning Strike Event very useless due to lack of any supported types which we can refer to. I propose that this event should include location of block which got stroke or even lit by it (stroke block and lit block separetely?).
@bensku the best dev ever who already added tree types <3

**Comment by TheBentoBox** [comment]
Getting the event-location should be possible by getting the location of the lightning entity, which can be retrieved with the function's getLightning method.

**Comment by PoweredDragon** [comment]
What if there's no entity? ✌️

**Comment by PoweredDragon** [comment]
Got outta problem with my friends help (what was weird, it probably all gone about returning the value of function; as it works now and error doesn't show as it used to. You can close it now.

**Comment by TheBentoBox** [comment]
You can close it yourself, too, yknow? :v)

**Comment by PoweredDragon** [comment]
Well. I don't know how xD Can you grab it back to issues? I still can't get location without an entity. This post was about my functions bug problem ✌️ Sorry for the mess :/
