### ISSUE TITLE
Log Effect Doesn't Work in Functions

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#511]
## Code
```vb
function log(text: text):
    log {_text} to "test"
```
## Versions
**Paper version:** git-Paper-1079 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
**Skript version:** 2.2-dev25
## Description
No errors when reloading or when the function is run. Nothing happens.

**Comment by Snow-Pyon** [comment]
Cannot reproduce this in my 1.11.2 Spigot server with the latest release.

**Comment by TheBentoBox** [comment]
Also cannot reproduce, and no response, so closing.
