### ISSUE TITLE
Functions in functions

### ISSUE THREAD

**Issue by PoweredDragon** [bensku/Skript#513]
Dunno why it's impossible, but...
When I use function inside a function I get a message "function cannot be used here". Why is that? Shouldn't that be possible to make function which can call other function sometimes? It seriously broke my whole idea :c

**Comment by xNorbig** [comment]
Can you show the code? It works on my server

**Comment by TheBentoBox** [comment]
This error often shows when you mess up something in the function call. While it's sort of an inaccurate and unhelpful, the issue definitely isn't calling a function within a function, as that's 100% possible. 

I will be closing this so it isn't mistaken for an actual bug, but feel free to reply more with your actual code so you can be told what's wrong with it.
