### ISSUE TITLE
Color Code Errors in dev26

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#515]
https://hastebin.com/upopegejic.pl
https://hastebin.com/ideguveram.pl
https://hastebin.com/asowabavik.pl

**Comment by Classic36MC** [comment]
I think these were fixed in dev26c

**Comment by bloggy** [comment]
I have also some kind of color errors after upgrading to the latest skript version:
http://i.imgur.com/ppuLNNX.png
All I am doing is using color codes in messages like this:
message "&4My Test Message &0Another Color"

**Comment by bensku** [comment]
Apparently messages that contain pnly & or $ do not parse correctly.

**Comment by googleoblivion** [comment]
[With Latest](https://i.gyazo.com/f97b26e8d66ed13040575a1174af60ef.png)
[Without Latest](https://i.gyazo.com/643fb478335ebcf4fb4dbad97b1f832f.png)

**Comment by gundamMC** [comment]
Yep, same problem. Apparently the two characters after a color code would disappear. For example, "&aHey" would give you only "y"

**Comment by bensku** [comment]
I think I just fixed these issues. Coming with next release...
