### ISSUE TITLE
An Error About Functions in dev26

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#516]
https://hastebin.com/ipodidumul.pl

**Comment by bloggy** [comment]
Same issue here. Started to happen when I reloaded some of my scripts:

https://hastebin.com/siligiyeve.vbs

**Comment by bensku** [comment]
Pleade provide exact code which can be used to reproduce this. Function clearing should not fail with NPE in any case .. However, function data has invalid functions, and I want to know ehat causes them to appear.

**Comment by Blueyescat** [comment]
The my Skript i reloaded hasn't got create function codes. But has got call functions:

> function privateMessage(from: player, to: player, message: text):
^ This is from another Skript file

`privateMessage(player, arg 1, arg 2)`
-  player, **offlineplayer**, text
^ Maybe the problem is here, but **this code can't work if arg-1 is offline.** Anyway this error when reloading, Not when running.

`privateMessage(player, {_lastMessaging} parsed as player, arg 1)`
- player,

 player, text

**Comment by bensku** [comment]
Strange... I have no idea why this would happen, then.

**Comment by TheLimeGlass** [comment]
@bensku In the last update you said you fixed the issue where Functions would return null in some reason cases also you fixed this
```
Fixed a bug with zero-argument functions
```
Which may be where the issue is?
