### ISSUE TITLE
Projectile Issues

### ISSUE THREAD

**Issue by Andalmere** [bensku/Skript#517]
Hello bensku, i saw some bugs and i would like you to squash it.

- "On Projectile Hit" will lagg up the server and crashes when the projectile is an enderpearl. (I am only the one in my test server)
- And also the bold formatting code is not working properly if you are about to send a message to a shooter. (Egsend "&8&lMyPlugin &fYou've shoot the enderpearl." to shooter. And it will show this message to the shooter ""&8&lMyPlugin &f**&l**You've shoot the enderpearl. Everything is bolded even tho its not bolded")

Please fix it as soon as possible.

**Comment by Snow-Pyon** [comment]
1. This isn't a problem of Skript.
2. That's an intended behavior.
