### ISSUE TITLE
New feature: drop item without velocity

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#52]
```
on damage:
  victim is item frame
  cancel event
  delete victim
  drop item frame at location of victim without velocity
```

When you drop stuff with the drop expression it gives them vanilla velocities for dropped items which makes them fly here and there and they often get trapped behind a wall or what not. The only way around this has been using vanilla summon but that's rather cumbersome as you have to define all the attributes for the item manually.

But if drop expression supported "**without velocity**" argument it would be wonderful.

**Comment by bensku** [comment]
Added, this was easy one :)
