### ISSUE TITLE
[Skript] How to hide the "Can't compare"

### ISSUE THREAD

**Issue by short509** [bensku/Skript#521]
[Skript] Can't compare 'uncolored name of click item' with a text (npc.sk, line4: if uncolored name of click item is "Quest":")
[Skript] Can't compare 'uncolored name of click item' with a text (option.sk, line5: if uncolored name of click item is "Quest":")
[Skript] Can't compare 'uncolored name of click item' with a text (option.sk, line6: if uncolored name of click item is "Quest":")

source code is Works fine

**Comment by Snow-Pyon** [comment]
No, it doesn't you should read what the error is saying, not an issue of Skript anyways. To close.

**Comment by bensku** [comment]
One does not simply hide the errors.
