### ISSUE TITLE
config.sk format

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#522]
The updated config.sk does not match the (raw) content of https://raw.githubusercontent.com/bensku/Skript/master/src/main/resources/config.sk

In particular, spacing before in-line comments is elided:
> type: disabled# change to line below to enable this database
compared with
> type: disabled # change to line below to enable this database

The (raw) source, with preceding spaces, is more readable.

**Comment by bensku** [comment]
I guess this could be improved...

**Comment by Snow-Pyon** [comment]
I don't really get what's the issue here, nor if this is still happening. Some input would be appreciated.

**Comment by SlimeDog** [comment]
File matches documentation exactly in Skript 2.2-dev32d.

**Comment by SlimeDog** [comment]
Actually a VERY VERY minor correction:
lines 235-236 and 272-273 have spaces instead of tabs, so do not line up with the surrounding lines. If you want to fix that, the **diff** will be perfect.
