### ISSUE TITLE
Implementation of clear/remove drops to more events

### ISSUE THREAD

**Issue by kiritss** [bensku/Skript#524]
Implementation of clear/remove drops to more events such as on break/mine

**Comment by Snow-Pyon** [comment]
The BlockBreakEvent doesn't have a getDrops method for it, so you can't implement it to other events unless you do it in a hacky way.

**Comment by bensku** [comment]
It would be hacky, but then again a lot of Skript'sfeatures are built in hacky ways to make it easier for scripters.

**Comment by TheLimeGlass** [comment]
This issue should be closed as https://github.com/bensku/Skript/issues/659 defines and clears this issue better.
