### ISSUE TITLE
Colors with ProtocolSupport are very bugged

### ISSUE THREAD

**Issue by piter909** [bensku/Skript#525]
Effect:
Send %string% to %object%

When we use any color, like &btest, version 1.7 see it like "est" colored on light blue.
Also, if there is symbol that gives format or color after disapeared character, the format/color of text is incorrect (example: "&btusk" - it will be blue without first character with &u format).
Hope it will be fixed :)

https://github.com/ProtocolSupport/ProtocolSupport/issues/466

Edit1:
there is something wrong with using only colour without format, like "&btest". When I do "&b&lTEST" everything is ok..

**Comment by bensku** [comment]
1.7 is no way supported by Skript, and that includes 1.7's chat protocol. I'm pretty sure that there have been changes from 1.7 to 1.9, even though most of it is same.

Waiting to hear from that ProtocolSupport issue... This might be easy to fix... or not.

**Comment by piter909** [comment]
I have added fixed send effect to my addon until this problem will not be solved.

**Comment by TheLimeGlass** [comment]
You can use `<red>` or `<light blue>` to do chat colours aswell.

**Comment by bensku** [comment]
I have decided that it is not Skript's goal to work around this.
