### ISSUE TITLE
# registrered as "

### ISSUE THREAD

**Issue by Sckaletz** [bensku/Skript#526]
Example:

format slot 1 of player with 1 stone sword named "&4&lHacks" to run [skellettcord execute bungeecord console command "ban %arg-1% #hack @hack"]

In this case skripts throws and error:

Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: "". (ban.sk, line 6: format slot 1 of player with 1 stone sword named "&4&lHacks" to run [skellettcord execute bungeecord console command "ban %arg-1% #hack @hack"]')

This is due to the #.

Is there a way to fix this?

**Comment by Snow-Pyon** [comment]
You just have to put it twice (##) as quotes and other stuff in Skript. Please don't use the issue tracker for stuff like this.
