### ISSUE TITLE
1.7.10 spigot fails loading

### ISSUE THREAD

**Issue by Portanna** [bensku/Skript#527]
Error: https://pastebin.com/49HPQMUW
Versions tested: 1.7.10 Spigot and PaperSpigot (both throw same error)
Java: java version "1.8.0_60" Java(TM) SE Runtime Environment (build 1.8.0_60-b27)

tl;dr -> Bensku's Skript does not work on 1.7.10, I also tried some of the older releases (v25,v26) and they throw different errors (https://pastebin.com/mKuQ7djR) but still don't load.

**Comment by Snow-Pyon** [comment]
This fork doesn't support any version lower than the 1.9.

**Comment by bensku** [comment]
1.7.10 is not supported.
