### ISSUE TITLE
Color reset after a variable

### ISSUE THREAD

**Issue by marcellmit2l** [bensku/Skript#528]
Hello,
The color after a variable is always white, please fix that.

Code:
`send "&6%arg 1% hat &a%{_kekse}% Kekse &6und &a%{_krumel}% Kekskrümel&6.""`
Pic:
[https://cdn.discordapp.com/attachments/138027100593455104/305887058331828234/kekse.png](url)

**Comment by TheBentoBox** [comment]
Your picture isn't loading. You can just copy a picture to your clipboard then paste it directly into your post.

**Comment by marcellmit2l** [comment]
![image](https://cloud.githubusercontent.com/assets/25343627/25364556/823cd19a-2963-11e7-8e21-7768d1fe716b.png)

**Comment by TheLimeGlass** [comment]
What is in the variables {_kekse} and {_krumel}

Also this error is so minimal xD

You can just re-add your colour after the variable.

I have never had this issue, but you could do something like
```
send "&6%arg 1% hat &a%{_kekse}% &aKekse &6und &a%{_krumel}% &aKekskrümel&6.""
```

**Comment by marcellmit2l** [comment]
The color is resettet after each variable.

I know it is not bad, but now I have to put the color after a variable in all my skripts because it is otherwise white, or I make a skript downgrade. ._.

**Comment by bensku** [comment]
Yeah, this should not happen.

**Comment by bertek41** [comment]
Same problem for me color turned to white after variable:
```
command /hey:
	trigger:
		send "&6hey %player% hey"
```

**Comment by TheBentoBox** [comment]
Confirm this is still happening to me in dev27 @bensku.
