### ISSUE TITLE
Command for plots doesn't work!

### ISSUE THREAD

**Issue by sriskels** [bensku/Skript#529]
I click enter by mistake -_-

Commands for plots doesn't work!

I have code: https://pastebin.com/rW2dhmfQ but for player without op this don't work

**Comment by sriskels** [comment]
there is mistake (add worldguard.* and remove worldguard.define) but not it.

**Comment by TheBentoBox** [comment]
So what exactly isn't working? What do you mean by "commands for plots"?

**Comment by sriskels** [comment]
Em, everything, any of command is not executed.

(sory for my english, I'm from Poland)

**Comment by TheBentoBox** [comment]
Can we see the rest of the code? And what's your server/Skript version?

**Comment by sriskels** [comment]
Yes, but I write in for polish server, because you can understand a lot of messages.

I want make plots for VIP's and normal players.
https://pastebin.com/Yu5TknA4

**Comment by sriskels** [comment]
I'm using the newest version of Skript and spigot-1.11.2-R0.1-SNAPSHOT

**Comment by TheLimeGlass** [comment]
Do you have WorldGuard or any of the supported region plugins installed? Skript's regions does not include plotsquared or plotme. You will have to use SharpSk or SkAction if you would like to use PlotSquared syntax.

**Comment by bensku** [comment]
And Residence! But still, that is only a few plugins supported.

**Comment by sriskels** [comment]
Yes, I have World Guard.

**Comment by bensku** [comment]
Are your plots also WorldGuard regions?

**Comment by sriskels** [comment]
You see code >.<
execute player command "rg define %player%-%{dzialki::ilosc::%player%}% %player%"

**Comment by bensku** [comment]
Oops. Anyway, what does *not* work? Are regions not created at all?

**Comment by sriskels** [comment]
Everything, when i write /dzialka stworz (command for create plot) the chat is like that: 
 send "&8[&6Działki&8] &2Działka została utworzona pomyślnie!"  (the plot has been created successfully, but not!) ONLY!, and worldguard region doesn't exists.

**Comment by bensku** [comment]
Does the executor of WG commands (player) have necessary permissions?

**Comment by sriskels** [comment]
Nope, it's not it, i think it caused by the amount of commands with delay only 1-2 tick, but i don't want the creating plot taking large time.
This working:
`if arg 1 is not "info" or "stworz" or "dodaj" or "usun" or "flagi" or "flaga" or "wyrzuc":
make player execute "dzialka"`
But the creating plot doesn't work, only message that should be message of create plot with success

**Comment by bensku** [comment]
You have a race condition with permissions. They are probably not yet added before you start executing commands as player. In any case, granting player temporary permissions for WE/WG this is a security issue. Don't do it.

Closing, not Skript problem.
