### ISSUE TITLE
Vehicles + armor stands

### ISSUE THREAD

**Issue by minemidnight** [bensku/Skript#53]
On vehicle dismount will not trigger if the player is riding anything besides horses and pigs (for me atleast) and I cannot teleport a entity if it is being ridden? Example; I can't teleport a armor stand if a player is riding it. Also, I'm not able to teleport armor stands normally

**Comment by bensku** [comment]
This is due to vehicle events only recognizing minecarts, boats, horses and pigs. Will try to fix using Spigot new events.

**Comment by bensku** [comment]
Still issues with this when using (dis)mount events? Vehicle events do not and will not (on Spigot platform, at least) support entities not vehicles.

**Comment by bensku** [comment]
Very well, they do work, then? Closing.
