### ISSUE TITLE
Conditions in 'on death' event

### ISSUE THREAD

**Issue by PoweredDragon** [bensku/Skript#530]
Well. Conditions in 'on death' event seem to be kinda broken. I wanted to make a simple ELO script, but

```
on death:
	attacker is player:
		victim is player:
			set {elo::%attacker%} to floor(1.1*{elo::%attacker%})
			set {elo::%victim%} to floor(0.9*{elo::%victim%})
```
Doesn't seem to work. I tried other way:
```
on death:
	{elo::%attacker%} is set:
		{ello::%victim%} is set:
			set {elo::%attacker%} to floor(1.1*{elo::%attacker%})
			set {elo::%victim%} to floor(0.9*{elo::%victim%})
```
Neither it worked (I want it to work on players only). My friend said 'use types'. And so I did...
```
on death:
	type of attacker is player:
		type of victim is player:
			set {elo::%attacker%} to floor(1.1*{elo::%attacker%})
			set {elo::%victim%} to floor(0.9*{elo::%victim%})
```
no errors, but didn't work as well. Tried without conditions:
```
on death:
	set {elo::%attacker%} to floor(1.1*{elo::%attacker%})
	set {elo::%victim%} to floor(0.9*{elo::%victim%})
```
Well. It worked. But it makes a lot of crappy variables for zombies, skeletons and all entities... I don't want it! :V

So I came up with this:
```
on death:
	"%type of attacker%" is "player":
		"%type of victim%" is "player":
			set {elo::%attacker%} to floor(1.1*{elo::%attacker%})
			set {elo::%victim%} to floor(0.9*{elo::%victim%})
```
And it finally worked!
It has never happened to me before. 'Before' means before I installed newest Skript and addons. Can any1 check it?

**Comment by Snow-Pyon** [comment]
Could you tell us what version of Skript are you running exactly? And your server?

**Comment by TheBentoBox** [comment]
Cannot reproduce, I use the same exact conditions as your first example on my server in multiple places and it works fine. Need your versions as Pyon said.

**Comment by TheLimeGlass** [comment]
Uninstall Umbaska.

**Comment by PoweredDragon** [comment]
@UP
It is example I showed and which doesn't work. Ok then, so Umbaska bugs it. Good to know.
@UP and @2UP as I said i have just the newest version of skript ;V
