### ISSUE TITLE
Permissions doesn't work (?)

### ISSUE THREAD

**Issue by sriskels** [bensku/Skript#531]
I going to make plots for vip, but i give to vip permission "dzialka.vip" (from my language) and to script if player doesn't have permissions "dzialka.vip":
#code for player
else:
#code for vip

and it's always work, but now isn't :(

And it:

on command "pl" or "plugins" or "?" or "help" or "ehelp" or "essentials:help" or "essentials:ehelp" or "bukkit:pl" or "bukkit:plugins" or "bukkit:?" or "minecraft:pl" or "minecraft:plugins" or "minecraft:?":
	if player doesn't have permissions "pluginy.sprawdz":
		send "&cOur plugins are a mystery =)" (i've translated it :V)
		cancel event
this too, it doesn't work!
i'm using the newest version of skript at this momment and spigot 1.11.2 r0.1 snapshot, i can't install other spigot because my hosting doesn't offer own "engine". (i don't know the engine is the craftbukkit, spigot, sponge, bungeecord, etc.)

**Comment by bensku** [comment]
Can anyone reproduce?

**Comment by TheBentoBox** [comment]
I cannot reproduce this, I have no problems checking permissions properly on Spigot 1.11.2 (currently using dev25).

**Comment by Snow-Pyon** [comment]
I also cannot reproduce this in the latest Spigot with the latest release.
