### ISSUE TITLE
Unable to set baby villager's name

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#537]
```
command /testmob:
    trigger:
        spawn 1 baby villager at player's location
        set name of last spawned entity to "123"
```

The name won't get set!

For more information see: https://forums.skunity.com/threads/unable-to-set-name-of-villager.3499

**Comment by TheBentoBox** [comment]
I think the weirdest code from that thread is this:

```
spawn 1 zombie
set {_last} to last spawned entity
broadcast "%{_last}%"

# RESULT: zombie

spawn 1 villager baby
set {_last} to last spawned entity
broadcast "%{_last}%"

# RESULT: <none>
```

It sounds to me like spawning a baby villager doesn't store it in the `last spawned entity` expression, for some reason.

**Comment by Syst3ms** [comment]
@TheBentoBox What's the result of sending `"%last spawned entity%"` in the last example ?

**Comment by TheBentoBox** [comment]
I actually finally have a chance now to sit down and test all of this stuff, and I cannot reproduce this:

![image](https://cloud.githubusercontent.com/assets/6902229/25865065/a6fb191c-34bf-11e7-8663-81839625b9b9.png)

If anyone else is able to reproduce we can reopen, but neither the code you provided nor the code I linked above from the thread has any issues for me (save for the incorrect syntax of `villager baby` when it needs to be `baby villager`).
