### ISSUE TITLE
weather is buggy

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#54]
This has been around for quite some time. Sometimes Skript thinks that the weather is "rain" or "thunder" (?) when in fact it is clear in the world.

```
on every 10 seconds:
  if weather in world "world" is clear:
    broadcast " DEBUG: it is clear"
  else if weather in world "word" is rain:
    broadcast " DEBUG: it is raining"
  else if weather in world "word" is thunder:
    broadcast " DEBUG: it is thundering"
```

Then you just wait for it to bug out ...

**Comment by supertassu** [comment]
@Pilvinen Try to change `else if weather in world "word" is thunder: ` to `else if weather in world "world" is thunder:`

**Comment by Pilvinen** [comment]
That's just a typo in the example, I don't actually use that code.

**Comment by Pilvinen** [comment]
[http://snag.gy/oHdIA.jpg](img)

**Comment by Pilvinen** [comment]
It would seem so far that the buggy weather is always "storm", never "rain" so far (while in reality the weather is clear).

**Comment by xXAndrew28Xx** [comment]
Can not reproduce in Spigot 1.9.4 (latest). 
![image](https://cloud.githubusercontent.com/assets/9660418/16844753/e8c1f8fc-49ab-11e6-98e4-ed9b78901df0.png)

**Comment by Pilvinen** [comment]
You cannot reproduce the bug by changing the weather, you have to actually wait which makes it hard to debug ...

**Comment by TheBentoBox** [comment]
Seems resolved now, I let it run for a good 20 or 30 minutes, the weather naturally changed from thunder to raining to clear, all broadcasted correctly.
