### ISSUE TITLE
# inside of quotes

### ISSUE THREAD

**Issue by AsDsDD** [bensku/Skript#540]
So I basically tried to send # (hashtag) inside of quotes in message and it doesn't work, just gives quotes usage error. I didn't find anywhere how to fix this issue.

**Comment by TheBentoBox** [comment]
You have to put two #'s to put them inside of quotes just like you have to do two " to put double quotes inside of a quote. 

Also, in the future, you should ask on the forums first for something like this where you're not sure if it's a bug or if there's already a way to do it. The issues section here isn't really for informative Q&A.
