### ISSUE TITLE
issue with some expressions.

### ISSUE THREAD

**Issue by DevFarid** [bensku/Skript#546]
Latest version: dev26f

Expressions "%executor% and %complete command%" do not work properly. 

Thanks.

**Comment by Snow-Pyon** [comment]
What do you mean by that? Does them throw an error when used? Does them return incorrect info? You need be more specific or @bensku wouldn't be able to fix it. You should also provide the version of the server where you're having this issue and the code to reproduce it.

**Comment by DevFarid** [comment]
Never expressions no longer work in chat.

**Comment by TheBentoBox** [comment]
This is a separate issue with expressions not being parsed properly in dev26. There's already a few issues that mention this problem, so I'll be closing this one, but someone (maybe me) should probably make a more centralized issue which shows all of the problems with the current chat parsing as of 26f.
