### ISSUE TITLE
Can't compare error

### ISSUE THREAD

**Issue by cengiz77** [bensku/Skript#547]
on tool change:
	if event-player has permission "vip.pickaxe":
		if tool of event-player is diamond pickaxe named "&eFast Breaker":
			while event-player is holding diamond pickaxe named "&eFast Breaker":
				apply haste 4 to the player for 5 seconds

when i write and type sk reload digerozellikler, i get this error:
[21:59:02 ERROR]: Can't compare a player with 'holding diamond pickaxe named "&e
Fast Breaker"' (digerozellikler.sk, line 16: while event-player is holding diamo
nd pickaxe named "&eFast Breaker":')

what is my fault? this problem occurs in 2.2dev version but in the old version doesn't

**Comment by TheLimeGlass** [comment]
I don't get this issue. Also that while loop will crash your server unless you add a delay in it.

Which dev 2.2 version are you using? There are atleast 30+ different 2.2 versions.

I'm using dev-25 in case anyone is wondering.

**Comment by cengiz77** [comment]
I'm using 2.2-dev26f version, the experission was working in njolbrim's last version but when i updated the last dev version most "while" expressions started breaking.

**Comment by skripttpbug2** [comment]
can confirm this, the workaround is to compare player's tool with whatever you want

**Comment by bensku** [comment]
Try without any addons, if you didn't do that already.

**Comment by TheBentoBox** [comment]
Cannot reproduce either, on 1.11.2 dev26d with no addons.
