### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Snow-Pyon** [bensku/Skript#548]
Hey there, today, I'm asking for the addition of the stuff that I'll explain because I feel like these stuff should be a part of vanilla Skript. Said that, I'll start:

* So, the first​ thing that I think should have been added a long time ago is the following stuff for the piston related events:
```
[the] (moved|pushed) blocks
```
should be for both (the piston retract and extend event), will get the pushed blocks. It should be the possible using the following methods:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockPistonExtendEvent.html#getBlocks()
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockPistonRetractEvent.html#getBlocks()

* Other thing that I would like on those events is the direction event value which can be achieved with the following method:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/block/BlockPistonEvent.html#getDirection()

* I think this is the only expression of the chat stuff of Skript that's missing:
```
[the] (message|chat) format[ting]
```
It should return the current format of the chat and should be settable, it's possible with the following methods:
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html#getFormat()
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/AsyncPlayerChatEvent.html#setFormat(java.lang.String)

* Register new types for the following enums:
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/AsyncPlayerPreLoginEvent.Result.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/BlockIgniteEvent.IgniteCause.html
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityRegainHealthEvent.RegainReason.html
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerTeleportEvent.TeleportCause.html

**Comment by HYPExMon5ter** [comment]
Yes, please add the chat format!!

**Comment by FUZIK** [comment]
"[the] (message|chat) format[ting]" - i like.

**Comment by Snow-Pyon** [comment]
There are some suggestions that haven't been added yet so I would like to keep this open till it's fully done, or at least when these enums are added as new types/classinfos.

**Comment by bensku** [comment]
Why would you want to get them added? Just adding a bunch of types is useless if there are no syntaxes which use them.
