### ISSUE TITLE
Drop items without velocity?

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#55]
How can I drop item without velocity?

This does not work for me:
drop 1 of {_planks} without velocity at event-block

does not work either:
drop 1 of {_planks} at event-block without velocity

**Comment by bensku** [comment]
<code>drop %itemtypes/experience% [%directions% %locations%] without velocity</code>
Syntax is correct, however...

You're dropping items <code>at</code> block, i.e. inside that block. Item is dropped without velocity, but immediately after that Minecraft's physics engine sees that the item is not allowed to be there and moves it. You should find nearest air block, maybe <code>drop 1 of {_planks} without velocity above event-block</code> would work?
