### ISSUE TITLE
Help with skript reload and addon versions

### ISSUE THREAD

**Issue by ThePraZ** [bensku/Skript#553]
I need the version of skquery, wildskript and umbaska that works perfectly on 1.9/1.10 for my skript please tell me the version or give me the link.

Thanks

**Comment by ThePraZ** [comment]
I get this error on console when I reload my skript on 1.10 without any addon https://pastebin.com/KnAAX5uF (it show the version of skript and spigot)

**Comment by bensku** [comment]
Post the script that causes this error.

**Comment by ThePraZ** [comment]
@bensku what do you mean?

**Comment by bensku** [comment]
Create a test case which triggers this error and post it here. If it is a small script, shouldn't be hard to do that. If it is a large script, I will no way read through hundreds of lines of your code just to find one script bug - you need to be able to point out which code exactly causes this.

**Comment by ThePraZ** [comment]
Pff is very very large https://pastebin.com/q0rBKmMX

**Comment by TheBentoBox** [comment]
@ThePraZ Bensku specifically **just** said that he wasn't going to look through a huge script to find the error -- what's the point of posting that? Either give specific steps on how to reproduce this or provide a small sample script that reproduces the error. An oversized script like that does no good.

**Comment by ThePraZ** [comment]
@TheBentoBox I don't know the error

**Comment by TheBentoBox** [comment]
What version of Skript are you using?

**Comment by ThePraZ** [comment]
@TheBentoBox 2.2-dev26f

**Comment by TheBentoBox** [comment]
Well we can't do anything for you until you find a way to reproduce the error.

**Comment by Snow-Pyon** [comment]
No response, closing.
