### ISSUE TITLE
Many issues parsing expressions in dev26f

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#556]
This actually relates to #533, which I think was sort of incorrectly closed given that it pointed out a lot of issues that weren't a duplicate of #528. The current chat issues don't just include color resetting with variables and such, but there are many chat and expression parsing issues when using angled brackets in messages.

## Testing
This has to be tested entirely with `send` commands, since naturally this can't be tested with broadcasts or anything as it relies on issues with the JSON tag parsing (which is why I'm looping players and sending to them individually instead of broadcasting). Here's the example code I tested with some various random combinations of words and expressions:

```
on script load:
	loop players:
		send "Test Test2 %loop-player% a <" to loop-player
		send "Test Test2 %loop-player% a >" to loop-player
		send "Test Test2 %loop-player% a > %loop-player%" to loop-player
		send "<%loop-player%> Hello" to loop-player
		send "<%loop-player%> Hello <%loop-player's balance%" to loop-player
		send "<%loop-player%> Hello <%loop-player's balance%>" to loop-player
		send "%loop-player% Hello %loop-player's balance%" to loop-player
		send "%loop-player% > Hello %loop-player's balance%" to loop-player
```

And here's the result:
![image](https://cloud.githubusercontent.com/assets/6902229/25867639/319f62d2-34c8-11e7-8efb-717a6bc621fc.png)

As you can see, this is essentially an absolute mess. I'm not even sure how best to describe the problems, but just for a list of observations:

1. Adding a `>` in a message messes up expression parsing with essentially everything beforehand.
2. Any expressions that the parser believes to be inside of angled bracket JSON tags will not parse. This means you can't do something as simple as `send "<%player%>"`. This coupled with the fact that it's not even parsing tags properly anyways means that messages with angled brackets turn out very messed up.
3. Often it will cut parts of the message out entirely, which leads me to believe that it's parsing some of them as if they're a JSON tag, then removing them. This is very apparent in the last test, where running `send "%player% > Hello %player's balance%` returns ONLY their balance. Both the `%player%` and `Hello` are blatantly cut out by the `>`, somehow. This is also apparent in some of the other tests.

## Setup
- Spigot-d276ab1-1f6c04c for 1.11.2
- Skript dev26f
- No addons, no scripts loaded
- [Setup screenshot](https://gyazo.com/724b6717dd2113cbbb37b7277637266b)

## Possible (Easier) Fix
Just a suggestion, but if this continues being so problematic, it might be better to move the JSON parsing into its own effect, something like `send json %text%`, and reverting the normal `send` effect to how it was pre-dev26. I could see why you wouldn't want to take that route, but I just wanted to suggest it as an alternate option, as the `send` effect is so core to essentially every script, so issues with it will manifest more visibly than almost anything else.

**Comment by bensku** [comment]
I have removed the code that causes this. I'm not sure why I added it there in first place - current JSON chat doesn't need it for *anything*.
