### ISSUE TITLE
Unable to build/compile from repository

### ISSUE THREAD

**Issue by RoyCurtis** [bensku/Skript#56]
# Summary

I would like to contribute bug fixes and features to this Skript fork. Before I can do so, I need to be able to build Skript as-is from the latest commit. I seem to be unable to do so, as there are numerous compilation errors and the Maven file is confusing. I was unable to find building instructions.

# Environments

* [Command-line Maven 3.2.1](https://gist.github.com/RoyCurtis/aa64495dbab1169a05705c0bd20bbf82) and JDK 1.8u45
  * Attempted to build using `mvn clean package`
  * [Build success, but resulted in numerous repository warnings and a dud jar file with no built classes](http://vanderprot.gamealition.com/img/5e725.png)
  * [Build log](https://gist.github.com/RoyCurtis/c14d4647ee1ac25546df9c7ed871cb86)
* [IntelliJ IDEA 14.1.6 with repository imported as a Maven project](http://vanderprot.gamealition.com/img/2e716.png)
  * Tested with both JDK 1.7u79 and JDK 1.8u45

# Reproduction
This is how I attempted to build Skript from github using IntelliJ IDEA 14

1. [Cloned the repository using](http://vanderprot.gamealition.com/img/2698e.png) `git clone --depth 1 --branch master https://github.com/bensku/Skript.git`
  * _Cloning only a single commit was necessary for me, as otherwise the repository was too big to download_
2. [Imported the pom.xml file as a project in IntelliJ](http://vanderprot.gamealition.com/img/304d5.png)
  * [Import settings used](http://vanderprot.gamealition.com/img/d4ef9.png), with ["build" profile selected](http://vanderprot.gamealition.com/img/166b8.png)
  * [Using JDK8](http://vanderprot.gamealition.com/img/c8379.png)
  * Overwrote the existing IDEA project
3. [Confirmed that the project was successfully imported by checking dependencies and Maven tab](http://vanderprot.gamealition.com/img/63e60.png)
4. Attempted to make the project (CTRL+F9), [resulting in errors](http://vanderprot.gamealition.com/img/477dd.png)

# Issues

## Fixable

* [WorldEdit classes not found](http://vanderprot.gamealition.com/img/4a9c7.png)
  * [Fixed by adding WorldEdit to the POM file](https://gist.github.com/RoyCurtis/0449f7963fd8e4e9535b62f1988ca792)
* [Use of strings in switch not supported in Java 6 language level](http://vanderprot.gamealition.com/img/e0785.png)
  * [Fixed by changing the POM file to use 1.7](https://gist.github.com/RoyCurtis/82fec57d2c9a6e2a4048129279e6d406)
* [Use of base class' private field](http://vanderprot.gamealition.com/img/acc3e.png)
  * [Fixed by making the field `protected` instead](http://vanderprot.gamealition.com/img/a57e4.png)

## Help needed

* `ch\njol\skript\lang\SkriptParser.java L320, C50: Incompatible types: ch.njol.skript.lang.SyntaxElement cannot be converted to ch.njol.skript.lang.Expression<?>` ([screenshot](http://vanderprot.gamealition.com/img/5ebf5.png))
* `ch\njol\skript\variables\Variables.java L86, C114: Incompatible types: ch.njol.skript.classes.ClassInfo<java.lang.Object> cannot be converted to ch.njol.skript.classes.ClassInfo<? extends org.bukkit.configuration.serialization.ConfigurationSerializable>` ([screenshot](http://vanderprot.gamealition.com/img/c3262.png))
* `mvn clean package` doesn't build a usable jar (it doesn't appear to actually compile anything)

# Suggestions

* To make it easier for future contributors, the `.idea`, `.settings` and `Skript.iml` folders/files should be removed. These are IDE dependent and automatically generated. They should not be committed to version control, as the saved settings may conflict with different setups.
* Instead of bundling WorldEdit and WorldGuard jars, [they should be referred to in the POM using sk89q's repository](http://docs.enginehub.org/manual/worldguard/latest/developer/dependency/)

# Notes

* I also had the two compile errors under "Help needed" when attempting to build Skript from njol's original repository, many months ago. So I do not think these errors are introduced by this or Mirreski's fork

**Comment by bensku** [comment]
Huh, this is bad. Lot's of things to fix...

The reason why I have jars for several dependencies is simple: I got internal server error from Maven repositories. Maybe they're back up, haven't checked.

About empty jar file, I think I might know what is causing it. Njol has made Skript kinda reliant on Eclipse's compiler, i.e. "mvn compile" compiles nothing. I imagined that fix I merged here from @Gatt would have been worked, but it seems that it didn't.

**Comment by RoyCurtis** [comment]
Curious; how are you able to build Skript, yourself? Using Eclipse? Knowing that, I may be able to attempt to get building to work via Maven. I can also attempt the repository dependencies; I think some Maven servers unhelpfully report 500 (Internal Server Error) when it should be 404.

Thank you for the response

**Comment by bensku** [comment]
Eclipse automatically builds everything when you import Maven project or "Update Maven project". After that it compiles changed files when you save them. I don't really understand it well, but it is probably meant to be used for debugging in IDE.

If you could fix Maven compiler, it would be awesome. I'll try to help, but I have mostly used Gradle, this is my first project with Maven so...

**Comment by RoyCurtis** [comment]
Cool; I am the same. I started with Gradle (Forge modding) and was only introduced to Maven later.

Some questions that may help me here:

- What version of Eclipse are you using?
- What JDK are you using? (e.g. JDK6, 7, 8)

**Comment by bensku** [comment]
I use JDK 8 with Eclipse Mars.2. Note, though, that Eclipse compiler is not really dependant on JVM in any way.

**Comment by RoyCurtis** [comment]
Thank you; I didn't actually know [Eclipse had its own compiler](http://blog.deepakazad.com/2010/05/ecj-eclipse-java-compiler.html) so I was confused by that. I've learnt a lot in the last few hours.

With what I have found:

- I was able to compile the project fine in Eclipse Mars 2, myself
- IntelliJ can be made to use Eclipse instead of Javac; it builds fine, [but still marks this line as an error anyway](http://vanderprot.gamealition.com/img/c0b24.png)
- [Making Maven use the Eclipse](http://stackoverflow.com/questions/33164976/using-eclipse-java-compiler-ecj-in-maven-builds) compiler [doesn't appear to work](https://gist.github.com/RoyCurtis/3deb09945d4fc67292963a62981c6c0c)
- [I was able to fix one of the compile errors by inserting an explicit cast](http://vanderprot.gamealition.com/img/88f04.png) (untested)
- [The difference in compile errors appears to be down to how Eclipse and Javac differ in handling generics](http://stackoverflow.com/a/3063001/3354920)

I could try to fix the remaining compile error, or just leave it so Maven is not used as building and instead write instructions for each IDE on how to build a JAR.

It'd probably be easier just to leave it as-is. But for the future of Skript, I feel it'd be better to decouple it entirely from Eclipse and make it Maven buildable, so it can be built in Jenkins and developed in other IDEs without complicated instructions.

I'll keep trying, but would be curious to hear your thoughts on this.

**Comment by bensku** [comment]
For future, at least when I start planning Sponge support, I think I'm going to start using Gradle. Usually, if Maven can't do something, Gradle can :)

For now, if you can, I recommend using Eclipse, unless you're fine with those errors in editor. It would be great to have you helping me with Skript, I really can't do everything alone.

**Comment by Zbob750** [comment]
I usually hate "Bump" style comments on tickets, but I have found they can help shed some light on how the issue affects other people and the type of attention it needs. So here goes:

An issue was opened recently, (PaperMC/Paper#256, linked just above), with regards to Paper's handling of commands registered by Skript. After a bit of digging, I eventually found this was because of how Skript [registers commands](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/command/ScriptCommand.java#L271). The specific issue aside, this issue with Skript's workflow being non-trivial and my time being so limited, I ended up just dropping the notion to PR a fix entirely.

I don't claim to be the busiest person on Earth, but extra time is hard to come by for me, so any hurdle in building Skript beyond the non-trivial makes me drop any such notion immediately. So here I am "bumping" this issue, hoping that if nothing else it can help it get more attention from those with more time on their hands than I.

If I do happen across more free time I'd also be willing to assist in any way possible.
Thanks

**Comment by RoyCurtis** [comment]
Sorry for taking a while; I was finally able to figure out how to solve the build issues ([albeit in ugly ways](https://github.com/bensku/Skript/pull/69/commits/697f90852b073743f74892860f438690d023fac4)) and ended up making a large pull request, with a lot of changes.

Thoughts?

**Comment by Nicofisi** [comment]
Great job :+1:

**Comment by bensku** [comment]
See the pull request, this would be hard task.

**Comment by bensku** [comment]
... and in case someone stumbles here, this was fixed in fall 2016. Currently it is very, very easy to build Skript :)
