### ISSUE TITLE
problem with mobs in the on damage event

### ISSUE THREAD

**Issue by FightingPlay** [bensku/Skript#561]
Hey,
Version: 2.2-dev27
Server: PaperSpigot 1.11.2 Build 1095

I noticed that in the on damage event if you hit the creatures in the list under this text you will only get
creature as victim/attacker.
Mobs there a shown as creature:
Donkey
Elder Guardian
Skeleton
Wither Skeleton
LLama
Evoker
Guardian
Horse
Evoker
Mule
Polar bear
Shulker
Skeleton Horse
Stray
Vax
Vindicater
Zombie Horse

**Comment by Syst3ms** [comment]
Could you detail your issue please ?

**Comment by FightingPlay** [comment]
Sure
We are currently working on a skyblock skript and other players should be able to mobs on the island from others.
So we do a check for every mob.
But some mobs are giving out creature and not the real name of it.

**Comment by Snow-Pyon** [comment]
does `type of victim` returns the same?

**Comment by FightingPlay** [comment]
Yes

**Comment by Guarmanda** [comment]
You can handle that in your code but pay attention to the issue I postes 2 days ago: slimes, magma cubes, ghasts, and bats aren't creatures fort skript, so that you will have to do something for them.

**Comment by TheBentoBox** [comment]
Cannot reproduce at all in dev27

![image](https://cloud.githubusercontent.com/assets/6902229/25967832/64889b32-365d-11e7-8d9e-063bacdbea66.png)

Using the following code:
```
on damage:
	broadcast "%attacker% attacked %victim%"
```

To close unless anyone else can say how to reproduce.

**Comment by bensku** [comment]
They are not creatures for Bukkit, which is stupid. I might be able to hack around this, though - if this issue was caused by that.

**Comment by FightingPlay** [comment]
I used similar code to your code @TheBentoBox.
But on all that mobs I listed above I get creature and my friend too.Does this belong to our spigot version?

**Comment by TheBentoBox** [comment]
Doubt it, but what version are you on? I'm on 1.11.2, so this may be an issue on pre-1.11 versions due to the changes Bensku made to support the entity changes in 1.11, when entity variants were split off into their own versions. However, you said you tested with evokers, vindicators, vexes, and llamas, so I assume you're on 1.11 as well.

**Comment by FightingPlay** [comment]
Yes I'm using the newest paper spigot build for 1.11.2

**Comment by FightingPlay** [comment]
Thanks for the help
After removing every addon 1 times and testing again showed us that that error comes from a old addon ee are using.

**Comment by TheBentoBox** [comment]
Nice. Out of curiosity, was it the old 1.8 API version of SkQuery? That caused trouble for me in the past.

**Comment by FightingPlay** [comment]
Yes that addon was it.
