### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#562]
How can i send json to player with latest bensku's edit skript? I tried these but i couldn't (I also tried json.sk but it didn't work with latest version of skript.): 
```
<link:url>visible link text<reset>
<command:command>clickable text<reset>
<suggest command:command>clickable text<reset>
<tooltip:tooltip text>visible text with tooltip<reset>
```

**Comment by bensku** [comment]
What didn't work? Were there console errors? Were there parse errors?

**Comment by bertek41** [comment]
Can you send me example of this "<command:command>clickable text<reset>"

**Comment by TheBentoBox** [comment]
Can't reproduce on dev27, I used the following code:

```
command /test:
	trigger:
		send "<link:https://github.com/>visible link text<reset>"
		send "<command:command>clickable text<reset>"
		send "<suggest command:command>clickable text<reset>"
		send "<tooltip:tooltip text>visible text with tooltip<reset>"
```

[All four worked as expected](https://gyazo.com/3e97717785732db44933c20e43facd69). Hopefully that example helps you, because I believe you're just using them incorrectly.
