### ISSUE TITLE
Color Turned to White After Variable

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#563]
Color turned to white after variable here is my code I was using 2.2-dev20 version and today i updated to latest version then i found that bug:
```
command /hey:
	trigger:
		send "&6hey %player% hey"
```

**Comment by TheBentoBox** [comment]
Why did you first comment on the other issue, then delete it and make your own issue...? Seriously, keep discussion about the same problem to the same issue.

Duplicates #528.
