### ISSUE TITLE
Lenient Link Parsing Bug - dev27

### ISSUE THREAD

**Issue by Classic36MC** [bensku/Skript#564]
With the lenient link parsing enabled in the config, chat appears [like so](http://i.imgur.com/zozm8js.png). The links can't be clicked.

But when set to strict or false/disabled, it appears like [this](http://i.imgur.com/cZVT2rm.png), how it's supposed to be. These links can't be clicked either.

Skript: https://www.spigotmc.org/resources/ezmemes.36654/

**Comment by bensku** [comment]
Lenient parsing is apparently a bit too lenient... Anyway, will take a look soon.

By the way, can someone reproduce this issue with other scripts?

**Comment by Classic36MC** [comment]
@bensku, could we expect a hotfix update release within a few days?

**Comment by Snow-Pyon** [comment]
It's fixed in the next version, just wait for the dev28.

**Comment by Classic36MC** [comment]
Alrighty then.
