### ISSUE TITLE
Command's Aliases Don't Work

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#565]
Latest Benku's Skript:

`
command /sandık:
    aliases: sandik, chest, echest, esandık, esandik
    trigger:
`

"sandik" command don't work i tried change the order but nothing changed. (Other aliases work just sandik don't work)

**Comment by Syst3ms** [comment]
It's
```
command /sandik:
    aliases: chest, echest, esandık, esandik
    trigger:
```
Keep in mind Skript needs newlines

**Comment by bertek41** [comment]
I already did like that i just couldn't paste skript :D

**Comment by Snow-Pyon** [comment]
is it still happening?
