### ISSUE TITLE
Annoying character when I put "%nl%" for a new line in a message. (picture)

### ISSUE THREAD

**Issue by ZeTioZ** [bensku/Skript#566]
Hello, I've noticed an annoying thing with the %nl% variable to make a newline. Each time that I put this I have a strange character (look at the picture) so how could I fix it ? Thanks in advance.

Picture: [Picture of the character](http://i.imgur.com/AkN177y.png)

EDIT: I found the problem, it was Umbaska that made this annoying character...

**Comment by bensku** [comment]
Someone has been using CRLF instead of LF. It doesn't end well unless you're targeting Windows-only applications :)
