### ISSUE TITLE
Needed: Correct List of Particles

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#567]
I found most of the particle names are not working. Can you please provide a working list of particle names that we can use in skript?

e.g. "lava pop" works!

example code:

play 100 (lava pop with speed 0) at victim

**Comment by Pikachu920** [comment]
https://github.com/bensku/Skript/blob/4e677006968b23adad81560f8e83863b5b181969/src/main/resources/lang/english.lang#L964-L1099

**Comment by TheBentoBox** [comment]
These are already listed as [visual effects](http://bensku.github.io/Skript/classes.html#visualeffect), check the docs next time!

**Comment by bloggy** [comment]
Thanks for the info but I know this list and it is not correct or up to date.

Example:
play 30 (fire with speed 0) at victim

This gives an error. (cant understand this condition) in version v2.2-dev25 of Skript.

**Comment by TheBentoBox** [comment]
First of all, `fire` isn't the correct particle name. Kinda ironic that you say you know of that list already, because if you check the visual effect type I linked to, you'd see that it's called `flame`, not `fire` (this is also the case for vanilla).

Second of all, I [cannot reproduce your second error](https://gyazo.com/93d679e10064f1c08f9ec6d6f6a0602b). If you can find a way to faithfully reproduce it, I'll reopen this.

**Comment by Snow-Pyon** [comment]
@TheBentoBox seems that the void fog particle effects needs of EffectLib which you may have.

**Comment by TheBentoBox** [comment]
I do not have EffectLib installed @Snow-Pyon.

**Comment by bloggy** [comment]
`flame` does not work either

**Comment by bloggy** [comment]
Is Skript updated with new particle effects? I think there are some effects missing

**Comment by bloggy** [comment]
Is there any updated list? many of the effects do not work anymore (e.g. flame)

**Comment by johnpaulbin** [comment]
Found the list in the wayback machine:
`ender signal, mobspawner flames, potion break, smoke, hurt, sheep eating, wolf hearts, wolf shaking, wolf smoke, firework's spark, critical hit, magical critical hit, potion swirl, transparent potion swirl, spell, spell, witch spell, note, portal, flying glyph, flame, lava pop, footstep, water splash, smoke particle, huge explosion, large explosion, explosion, void fog, small smoke, cloud, coloured dust, snowball break, water drip, lava drip, snow shovel, slime, heart, angry villager, happy villager, large smoke, item crack, block break, block dust, totem, spit`
