### ISSUE TITLE
Disappearing quotes in text.

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#569]
The following command should display two quote characters, but only one gets displayed.
```vb
command /quotes:
    trigger:
        send """"" there should be two quotes."
```
![](http://i.imgur.com/mlh4wPX.png)

Using:
* Skript version 2.2-dev27
* CraftBukkit version git-Spigot-d276ab1-1f6c04c (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by bensku** [comment]
Could you try what happens with broadcast?

**Comment by RezzedUp** [comment]
```vb
command /quotes:
    trigger:
        broadcast """"" there should be two quotes."
```
![](http://i.imgur.com/Dawzy5j.png)

**Comment by bensku** [comment]
Ok, so not specific to JSON chat... Hmm, very interesting.

**Comment by bensku** [comment]
Oops, this actually miggt not be fixed. Planning to fo hotfix tomorrow.

**Comment by TheBentoBox** [comment]
@bensku Note the issues in #614 too, don't know if they're separate or not or if your hotfix tomorrow will address the problem listed there as well (I imagine it's all interrelated).
