### ISSUE TITLE
Expressions in JSON Chat Tags Isn't Works

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#572]
![image](https://cloud.githubusercontent.com/assets/19474570/26206669/be0ffd0c-3be5-11e7-981e-e3ef8a4f1d63.png)

not just a variable

**Comment by Syst3ms** [comment]
Either @bensku fixes it, or you can use evaluate from skQuery.

**Comment by Blueyescat** [comment]
@Syst3ms It is sends blank message. Also i'm using evaluate from TuSKe :P (ofc i'm tried skq)

**Comment by aescraftbr** [comment]
@Syst3ms How to use evaluate? Can you give me an example? The docs doesn't helped me...
