### ISSUE TITLE
Translation via "replace  all".

### ISSUE THREAD

**Issue by glowgrew** [bensku/Skript#577]
Hello. I have an issue with _replace all_. I have to translate a _loop_. [My code.](https://hastebin.com/iqisajopuv.vbs) The last _and_ doesn't translating! [2017-05-20_12-06-14](https://cloud.githubusercontent.com/assets/24549913/26273911/f64fed74-3d54-11e7-8b82-09e9fafddb76.png) Or, do u k **another** way to translate _time spans_ and _loops_?

**Comment by Snow-Pyon** [comment]
It's because what you're trying to replace isn't a string. The following:
```
send "{@p} Available points: {@v}%{_hm::*} join by "" ""%&f."
```

**Comment by glowgrew** [comment]
Error... :/

**Comment by Syst3ms** [comment]
Correction
```
send "{@p} Available points: {@v}%join {_hm::*} with "" ""%&f."
```

**Comment by glowgrew** [comment]
Thanks! <3
