### ISSUE TITLE
"is empty" condition does not work

### ISSUE THREAD

**Issue by nshun1896** [bensku/Skript#579]
the code below always say "something is in", though after commanding "/clear".
I suppose the condition "is empty" is something wrong.

```
on leftclick:
	cancel the event
	if player's inventories is empty:
		send "empty"
	else:
		send "something is in"
```

**Comment by nshun1896** [comment]
and

`player's inventory is empty`

also not work.

**Comment by TheLimeGlass** [comment]
Been a bug for a long time. This is bugged too
```
if {_list::*} is empty:
    message "rip"
```
A workaround is testing if it's set.
```
if {_list::*} is set:

or

if player's inventory contains anything:

or 

If items in player's inventory is set:
```

**Comment by nshun1896** [comment]
@TheLimeGlass Great ideas! I'll try it on later. Thank you!

**Comment by bensku** [comment]
The thing is, empty "list" is usually a list that has never been created. That means it is *not* a list, has no size and so cannot be empty.

Checking if an inventory is empty should work, however.
