### ISSUE TITLE
[Skript] Task #5 for Skript v2.2-Fixes-V10 generated an exception

### ISSUE THREAD

**Issue by BlomsterPolle** [bensku/Skript#58]
Hello,
im getting the following error, while loading my localhost server.
**Server version:** Spigot 1.9.2 ( http://prntscr.com/at4wmb ) 
**Java version:** Java 8.
**Running following plugins:** http://prntscr.com/at4xnk
**Error:** http://prnt.sc/at4u9p

**Comment by Nicofisi** [comment]
Couldn't you just post it all here?
And the screenshot doesn't show versions of plugins,
I can guess it's Umbaska problem again.
Try downgrading

**Comment by BlomsterPolle** [comment]
Thanks @Nicofisi :+1: 
**FIX:**
Downgraded Umbaska to the version that got released, 1st april, and that fixed the problem. :)
