### ISSUE TITLE
delete variable doesn't work on Mysql database

### ISSUE THREAD

**Issue by aaa8881** [bensku/Skript#584]
So there is a database in MySQL to store skript variables ( set up via config ) ,regex is global.* 

say A,B are servers. 
```
set {global.test} to 5 
```
in server A
will change {global.test} to 5
and I can see the change in server B as well.

If I set {global.test} to 10 , i can see change in both server.
However
If I 
```
delete {global.test} 
```
 it either doesn't change the variable, or only deleted in that server, but no change in other server. 
Using dev25.

**Comment by aaa8881** [comment]
all monitor change interval and setting are identical.

**Comment by aaa8881** [comment]
```
function delVar(p1:text, p2:text, p:player):
	delete {global.%{_p1}%.%{_p2}%::*}
	message "deleted %{_p1}%.%{_p2}% variable" to {_p}

function getVar(p1:text, p2:text, ap:text, p:player):
	message " %{_ap}% , %{global.%{_p1}%.%{_p2}%::%{_ap}%}% " to {_p}

function changeVar(p1:text, p2:text, ap:text, n:number, p:player):
	set {global.%{_p1}%.%{_p2}%::%{_ap}%} to {_n}
	message " %{_ap}% , %{global.%{_p1}%.%{_p2}%::%{_ap}%}% " to {_p}

command /changeVar [<text>] [<text>] [<text>] [<number>]:
	permission: admin.admin
	trigger:
		changeVar(arg-1,arg-2,arg-3,arg-4,player)
		
command /getVar [<text>] [<text>] [<text>]:
	permission: admin.admin
	trigger:
		getVar(arg-1,arg-2,arg-3,player)

command /delVar [<text>] [<text>]:
	permission: admin.admin
	trigger:
		delVar(arg-1,arg-2,player)
```
Here are commands and function for debugging purpose for you in case you don't feel like writing any skript. reason for these having 2 parameters are just because my variables look like that. 

{global.parameter1.parameter2:playerName} is the format

so 
```
/changeVar foo bar username1 100 
```
will change {global.foo.bar::username1} to 100

you can get this by
```
/getVar foo bar username1
```
```
/delvar foo bar 
```
will delete {global.foo.bar::*}

**Comment by bensku** [comment]
I suggest you forget MySQL variable DB for now. It needs a rewrite sooner or later, and currently it seems sooner.

**Comment by aaa8881** [comment]
kk. At least it seems to work except delete variable, so I'll wait. Hope it can be done soon. closing ticket
