### ISSUE TITLE
owner(s)/member(s) of region

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#588]
If you use the residence plugin skript cant determine the owner or member of a region, it will always return none. Region enter and leaving and stuff like that work and if you try it with a worldguard region it can also tell you the owner/members
could you please clean this up? Its a really popular claiming plugin :)

**Comment by melinstagibson** [comment]
here are the jars to download if you need them to fix it
http://ltcraft.lt/Residence/

**Comment by bensku** [comment]
Residence does not have list of regions' members. I have made it possible to get owner.
