### ISSUE TITLE
http:// (link parse) and colour error

### ISSUE THREAD

**Issue by nutella25** [bensku/Skript#595]
Before i update Skript to dev27, i can do this without any problem:
`message "&b http://minecraft-mp.com/server/112549/vote/username?=%name of player%"`

after i updated. whn you click the link, it'll just catch the `http://minecraft-mp.com/server/112549/vote/username?=` part. not with the %name of player%

I think its a bug. Please check it. Also the `&b` color resets when `%name of player%` called.
Thanks!

**Comment by bensku** [comment]
The issue with variablea resetting formatting has already been reported. I'll take a look at potential link parsing issue.

**Comment by bensku** [comment]
Should be fixed with next build.
