### ISSUE TITLE
JSON error, unterminated array

### ISSUE THREAD

**Issue by weberlepecheur** [bensku/Skript#596]
Hi

I execute this on the dev25 version but from dev26 to last, dev27, I encounter this error and impossible for me to find out where the error comes from.

```php
execute console command "tellraw %arg 1% ["""",{""text"":""╔════════════════════════════════════╗"",""bold"":true,""color"":""blue""},{""text"":""\n    ""},{""text"":""%player%"",""color"":""gold""},{""text"":"" ""},{""text"":""vous a provoqué en duel, votre réponse"",""color"":""dark_aqua""},{""text"":"" ""},{""text"":"":"",""color"":""gray""},{""text"":""\n          ""},{""text"":""(Cliquer sur les réponses ci-dessous)"",""italic"":true,""color"":""light_purple""},{""text"":""\n\n                 ""},{""text"":""ᐅ"",""color"":""dark_green""},{""text"":""  ""},{""text"":""Accepter"",""underlined"":true,""color"":""dark_green"",""clickEvent"":{""action"":""run_command"",""value"":""{@commande} %player% accepte""},""hoverEvent"":{""action"":""show_text"",""value"":""&3Cliquer ici pour &2accepter &3le duel de &6%player%""}},{""text"":""\n                 ""},{""text"":""ᐅ"",""color"":""red""},{""text"":""  ""},{""text"":""Refuser"",""underlined"":true,""color"":""red"",""clickEvent"":{""action"":""run_command"",""value"":""{@commande} %player% refuse""},""hoverEvent"":{""action"":""show_text"",""value"":""&3Cliquer ici pour &crefuser &3le duel de `&6%player%""}},{""text"":""\n\n""},{""text"":""╚════════════════════════════════════╝"",""bold"":true,""color"":""blue""}]"
```

**Screenshot with :**

_git-spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
Skript 2.2-dev25_
http://nsa37.casimages.com/img/2017/05/25/170525062943192047.png

_git-spigot-3fb9445-2b6c9f4 (MC: 1.11.2)
Skript 2.2-dev27_
http://nsa37.casimages.com/img/2017/05/25/17052506294827219.png

Yes I know, you develop a json format for skript, but minecraft is far more complete for me at the present time.

**Comment by Adrihun** [comment]
I had a simmilar problem. I was using "json.sk" from Skunity and I made a custom script that will make it so if you type in chat you can hover over the prefix and it will say something (like mineplex), I updated Skript and it gave a simmilar error in Console (and nothing happened in chat), I went back to dev 25 and it worked!

**Comment by weberlepecheur** [comment]
Fixed with dev28c
