### ISSUE TITLE
Removing a potion effect from a player deletes their cursor item (only in creative gui)

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#598]
[Gif](https://gfycat.com/UnpleasantOccasionalHarrierhawk)

```
command /test:
  trigger:
    wait 3 seconds
    broadcast "add"
    apply speed to player
    wait 3 seconds
    remove speed from player
    broadcast "remove"
```
Was apparently fixed in https://github.com/bensku/Skript/pull/187 but seems to have broken again
https://i.imgur.com/09cDFQY.png (dev25)

**Comment by bensku** [comment]
What Minecraft version you use?

**Comment by Snow-Pyon** [comment]
He uses 1.8.8 (I'm sure because I've talked with him before and he said it many times on the Skript-chat discord).

**Comment by Pikachu920** [comment]
Yeah, I am on 1.8.

**Comment by TheLimeGlass** [comment]
Is this a Skript issue or a Spigot/Mojang issue? Try it with the /effect vanila command.

**Comment by TheBentoBox** [comment]
This hasn't been addressed in a long time and was apparently only a bug before 1.9 -- AKA, it only affects versions we that this fork is no longer compatible with anyways. Closing.
