### ISSUE TITLE
Mojang is removing data-values, vanilla Skript needs NBT support

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#6]
We have long known this day was coming and now with 1.9 it is starting to really happen. Mojang is removing data-values and transfering them to NBT. This is a serious problem because vanilla Skript doesn't support NBT data at the moment.

**Example:**
potion of:8196 doesn't exist anymore. There is now only potion (373:0) with NBT tag {Potion:"minecraft:long_poison"}.

Same thing has happened with spawn eggs, etc.

At the very least vanilla Skript needs to have a rudimentary way of reading and modifying NBT data in entities, items and blocks - perhaps leaving it to the user's discretion whether or not the data is actually correct.

This would give some basic support to a feature that is going to be more and more important in the future. And if done without checks on whether or not the NBT can actually be given, etc, this would save considerable time implementing it - meaning we could have full NBT support right now and never worry about updating it with new tags as they come along - the users would do that in their own code.

I don't know whether Spigot supports this or not but if it doesn't yet have a proper API for it - it would be prudent to make one and make a pull request for Spigot. That way we would avoid having to use addons with NMS for what is becoming a basically essential feature.

**Comment by bensku** [comment]
Spigot or Bukkit won't accept direct NBT features, they have said it multiple times. I'll see what I can do, though.

**Comment by TheBentoBox** [comment]
They're getting rid of data tags, but they're not replacing them with NBT tags, they're replacing them with [block states](http://minecraft.gamepedia.com/Block_states). Those are what you'll want to look into.

**Comment by Pilvinen** [comment]
Well, I was talking about items there but yes with blocks we have now block states, it's true.

**Comment by bensku** [comment]
Potion data support coming soon, there is actually good API for it.
