### ISSUE TITLE
Percent signs not being "converted" when escaped in a string

### ISSUE THREAD

**Issue by Snow-Pyon** [bensku/Skript#600]
Hey there, I've noticed the following issue in the latest version:
```
command test:
    trigger:
        set {test::percentSign} to "%%"
        send {test::percentSign}
```
that small script should send `%` but it's sending `%%` whereas it should be `%` as it's correctly escaped.

Now, I've tried this with the dev25 and I don't have this behavior. Didn't see anyone reporting this so I did it myself, I apologize if someone already have reported this.

**Comment by TheLimeGlass** [comment]
This is very critical. Most people aren't upgrading due to this bug.
