### ISSUE TITLE
On leftclick / break of minecart not working

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#606]
Im trying to detect the breaking of a chest minecart but if i use on leftclick, click or break just nothing happens. i can detect rightclick events but not leftclick or breaking.
`on click on chest or chest minecart:
        broadcast "%chunk at event-location% %type of clicked entity% %clicked entity%"`

**Comment by TheBentoBox** [comment]
Chest minecarts are entities, not blocks, you'll have to use a damage event instead of left click.

**Comment by melinstagibson** [comment]
that doesnt solve the breaking or leftclick issue... did you even read the report? :T
