### ISSUE TITLE
Could not pass event PlayerPortalEvent to Skript 

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#607]
![image](https://cloud.githubusercontent.com/assets/19474570/26635630/b17cfa56-461a-11e7-9ca9-00f41bc89cef.png)

My Skript Timings is disabled and **i'm not using on portal event.**
Spams console for many times.. **But not every time.** I don't know when.

Paper 1104 (MC 1.11.2) (latest)
GriefPrevention 16.7.1 (latest)

Also WorldGuard 6.1.3-SNAPSHOT (if i remember correctly, 6.2 isn't compatilble with SkStuff addon.)

**Comment by Blueyescat** [comment]
The error isn't long like this everytime.

Usually:
![image](https://cloud.githubusercontent.com/assets/19474570/26637024/a3645460-461e-11e7-9b0b-16e9a2652f02.png)

**Comment by bensku** [comment]
It seems GriefPreventation or Skript hook for it is not working correctly. I guess it is the latter.

**Comment by Wasabules** [comment]
Same error, i use PaperSpigot and GriefPrevention with same version.

**Comment by bensku** [comment]
Still happens?

**Comment by Snow-Pyon** [comment]
No response, closing.
