### ISSUE TITLE
Enhancement - Disabling and Enabling scripts.

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#608]
Here is how my .sk file looks: **Test.sk**
When I disable the script: **-test.sk**
When I enable it again: **test.sk**

It would be good if it would keep the capital letter

**Comment by bensku** [comment]
What OS are you using?

**Comment by Adrihun** [comment]
I'm using Windows 8.1 Pro Currently, but I also had a server on Windows 10, and the same thing happened.

**Comment by bensku** [comment]
Windows/Java issue. If you want case-sensitive file names, use a file system that actually supports them, not NTFS :)
