### ISSUE TITLE
Skript not loading skins on player heads

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#609]
I got a simple stat script that will show Information about %arg-1% in a GUI, whenever I open the GUI, It takes 5-8 seconds for the skin to load on the %arg-1% player head.

Is there any way to load the Skin instantly?

Thanks.

**Comment by TheBentoBox** [comment]
This isn't really a Skript issue, it's just based on your server's connection/download speed. Not really the place to report this, if you need help optimizing scripts or are just wondering something like this you should ask on the forums first.

**Comment by nutella25** [comment]
If you wan't to ask more about Skript. Please do not make this kind of issue. You can join [SkUnity Discord](http://discord.gg/q7UM6vJ) . Skript expert will give the answer shortly. Remember that this thread is for Bug / Issue tracker, NOT for optimizing Skript's script.

**Comment by Syst3ms** [comment]
"Skript expert" lol

**Comment by nutella25** [comment]
Sorry if it sounds silly. But because he has made more than 1 issue, so I have to tell him. :smile: @Syst3ms

**Comment by Adrihun** [comment]
@nutella25 Yeah, Skript errors/issues.
This is the only "script problem" post
