### ISSUE TITLE
raw foods are not handled properly

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#61]
Raw foods are not being recognized with "if loop-item is raw beef" etc.
Only stacks of cooked foods become rotten with test code below.

```
on every 1 seconds:
  loop players:
    loop items in inventory of loop-player:

      if loop-item is raw beef or raw chicken or raw fish or raw salmon:
        remove 1 of loop-item from inventory of loop-player
        give 1 of rotten flesh to loop-player

      if loop-item is cooked beef or cooked chicken or cooked fish or cooked salmon:
        remove 1 of loop-item from inventory of loop-player
        give 1 of rotten flesh to loop-player

```

**Comment by Pilvinen** [comment]
No. Wait. My mistake. It was a problem in how Skript handles:

```
        name of loop-item doesn't contain "§1§f" or "§2§f" or "§3§f"
```

At some point the behaviour has changed and now you have to use:
```
        "%name of loop-item%" doesn't contain "§1§f" or "§2§f" or "§3§f"
```

Ie. if the loop-item doesn't have a name the example 1 fails to work (it used to work in some past version of Skript) but now it seems you have to compare as text to get the "none" output.

**Comment by bensku** [comment]
I'll see if I can get old way working easily. If not, you'll just have to use the new way.

**Comment by TheBentoBox** [comment]
@bensku Would you still like to address this? I've also experienced this issue occasionally (where text needs to be parsed as such to be compared properly), but it has seemed better in recent times and this is now a very old issue.

**Comment by TheBentoBox** [comment]
Never addressed or further responded to, and this issue seems to have improved in my experience.
