### ISSUE TITLE
[Suggestion] Adding function name to the FunctionEvent

### ISSUE THREAD

**Issue by TheLimeGlass** [bensku/Skript#610]
As the title suggests. Adding a way to grab the name or Function instance of a function being called in a function event.
https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/lang/function/FunctionEvent.java

This would be useful for me because I want to make an event that is called when a function is called. This is mostly useful for cross sharing scripts (When you use a function from another script). That way you don't have to call another function that tells that the one function has been ran. If you get what I mean?

Adding a method to grab the name or Function instance of the function being called in the event would be helpful. I know the FunctionEvent wasn't ment to be tapped into, but just grabbing the name of the function opens lots of API possibilities.

**Comment by Syst3ms** [comment]
A function isn't like a subroutine, its name can't vary. You can just have the function name as a constant in your code there.

**Comment by bensku** [comment]
I'm kinda surprised that function event doesn't already include reference to function.

**Comment by xXAndrew28Xx** [comment]
PR is done.
