### ISSUE TITLE
Chat and some other stuff

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#612]
Info:
- Skript version: dev28
- Minecraft version: Spigot 1.11.2
- Addons: Skellett, SkQuery, SkRayFall, TuSKe, SkUtilities, and Vixio

Okay so I was messing around with the new update, dev28, and came across this.

Strict link parsing:
It works how it's supposed to and colors are correct.
![image](https://cloud.githubusercontent.com/assets/12315186/26698932/e8690e3a-46e5-11e7-9e8f-2d7943bcaac8.png)

Lenient link parsing:
Colors are messed up and link does not work at all.
![image](https://cloud.githubusercontent.com/assets/12315186/26698948/f4d6ef16-46e5-11e7-80b5-2e8f23909566.png)

Also, json does not seem to work correctly anymore:
It was working fine on dev25
![image](https://cloud.githubusercontent.com/assets/12315186/26699016/3056854c-46e6-11e7-861a-76378024d107.png)

Player's ip no longer works,
`01.06 14:42:14 [Server] ERROR [Skript] {playersIP.%the player%} can only be set to one object, not more (UE_Pro_[1.9-1.11].sk, line 1574: set {playersIP.%player%} to player's ip')
01.06 14:42:14 [Server] ERROR [Skript] {playersIP.%the player%} can only be set to one object, not more (UE_Pro_[1.9-1.11].sk, line 1571: set {playersIP.%player%} to player's ip')`

**Comment by bensku** [comment]
Try the ip thing without any addons.

**Comment by HYPExMon5ter** [comment]
Nope, still the same error

**Comment by bensku** [comment]
Need more information on colors breaking with lenient link parsing. In the mean time, you might want to use at least strict link parser.

**Comment by HYPExMon5ter** [comment]
What info do you need? I'd be happy to provide any info you may need.

**Comment by bensku** [comment]
What messages, exactly, are you trying to send? Post sample code to reproduce the issue.

**Comment by HYPExMon5ter** [comment]
`if text from "http://pastebin.com/raw/eAzWp3iR" is not "2.7":
		wait 5 seconds
		if player has permission "ue.admin":
			wait 1 second
			send "&3&lUE&8&l» &9An update is out for &7UltimateEssentials Pro&9, check it out.%nl%%nl%&7https://www.spigotmc.org/resources/ultimate-essentials-pro.23669/"`

**Comment by bensku** [comment]
Ok, I'll check that later...

Btw shame on you for doing paid script. REALLY? Seriously, I don't think *plugins* should cost money.

**Comment by bensku** [comment]
Please try again now @HYPExMon5ter, this was probably fixed a few releases ago.

**Comment by HYPExMon5ter** [comment]
oh damn, sorry for not replying lol, it is indeed fixed now, this can be closed.
