### ISSUE TITLE
Double quotes ("") isn't usable in dev28

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#614]
I can't use double quotes
```vb
send "join {_llist::*} with "", """

with lore "&b%colored join {_list::*} with ""||""%"

"&c(&f%function({_variable}, ""text"")%"

List is missing 'and' or 'or', defaulting to 'and': join {_adminCommands::*} with "",""

**Comment by TheBentoBox** [comment]
The current issues with double quotes are discussed in #569. Based on bensku's comment there, he's aware with issues parsing them and it'll be fixed tomorrow, but I'll reference this issue there too. Regardless, closing this to keep the double quote parsing discussion in one issue.

Closed #614.
