### ISSUE TITLE
No aliases warn

### ISSUE THREAD

**Issue by waiching514** [bensku/Skript#616]
how to fix it
`[07:37:26 WARN]: [Skript] There are no aliases defined for the following ids: 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 438, 441, 449, 450, 452`

**Comment by Pikachu920** [comment]
Not an issue, you can fix it by defining aliases for those IDs or safely ignore it

**Comment by TheBentoBox** [comment]
Yeah, just update your aliases file. Not on issue on our end.
