### ISSUE TITLE
Links in direct messages to player

### ISSUE THREAD

**Issue by WolfezzKyne** [bensku/Skript#618]
I tried using this code, but it doesn't work. After a while of testing I've seen, that it works with the broadcast effect, but not with send/message

Tested on latest v, 27 and v. 28, on 1.11.2 Spigot and 1.12-pre6 Spigot 

> command google:
	trigger:
		message " http://google.com/ " to player
		send " http://google.com/ "
		broadcast " http://google.com/ "

**Comment by bensku** [comment]
See "parse links in chat messages" config option.
