### ISSUE TITLE
Looping through player inside timed loop gives wrong players

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#62]
Sometimes when you loop through players through inside a timed loop with other nested loops it gives you wrong player as the source of the other loops, ie:

The exit loop may have some bearing on making this bug happen. Sometimes the loops work and sometimes when new people log in / log out, suddenly you get the debug message for people that are not standing near fire. In other words you get wrong player as the source of wrong location or the other way around.

1) Pilvinen is standing in a forest with no fire.
2) Jeb_ logs in and is inside a house warming himself by a fire.
3) ---> " DEBUG: Pilvinen is standing by fire"
4) Jeb_ feels cold and sad.

This bug has existed in Skript for a very long time AFAIK and it's super annoying since you can't reliably do nested loops with exit loops / exit sections and instead have to resort to evil wizardry and lame tricks.

```
on every 5 seconds:
  loop players:
    loop blocks in radius 3 of location of loop-player:
      if loop-block is fire:
        send " DEBUG: %loop-player% is standing by %loop-block%" 
        exit loop
```

**Comment by bensku** [comment]
Figured out what is wrong. Bukkit/Spigot online player collection acquired by Skript is **not** thread safe, meaning if players die/leave/join, and you have a loop, something bad happens.

**Comment by Pilvinen** [comment]
I hope it's fixable. It's been around from times immemorial and fucks up some things severely causing random strangeness and most of the time it's not that obvious that you'd even know it's happening.

**Comment by bensku** [comment]
Next build might fix this.
