### ISSUE TITLE
Links & JSON Chat Bug

### ISSUE THREAD

**Issue by Classic36MC** [bensku/Skript#620]
I don't know how to explain this...

```
#Links:
	Meme: <link:goo.gl/X6Nok5>Click here
#Messages:
        MemeMessage: for the meme.
#Chat:
       send "{@Prefix} {@Meme} &f{@MemeMessage}
```

Clicking the "here" in the chat doesn't actually take the user to the link but to https://here with lenient link parsing. (dev28c & dev29)

**Comment by bensku** [comment]
Do you have lenient link parsing enabled... ? You might want to toggle it off until I manage to fix it.

**Comment by Classic36MC** [comment]
Yeah, I have it enabled. Thanks :)

**Comment by Legoman99573** [comment]
Mojang changed how chat works, so yeah, chat plugins will break.

**Comment by Classic36MC** [comment]
I assume that they changed it due to the Narrator?

**Comment by bensku** [comment]
Umm no. Chat protocol did not change significantly with 1.12. Mostly localization related stuff.

**Comment by DoreK333** [comment]
When will the error be fixed?
Players complain that clicking on a link does not open the page.

**Comment by Classic36MC** [comment]
Yeah... That seems to be a result of this bug. Hopefully, it will be fixed soon.

**Comment by DoreK333** [comment]
I have a solution to this problem!
Set it up in a configuration and it will work!

parse links in chat messages: strict
# Controls how Skript will try to parse links in chat messages.
# If 'disabled' or 'false', no links will be automatically parsed.
# When 'strict', everything starting with http(s):// will be parsed as link.
# When 'lenient', everything that contains a dot will be interpreted as a link.

**Comment by Classic36MC** [comment]
Lenient link parsing is the problem here, which is what most people tend to use iirc

**Comment by bensku** [comment]
Lenient link parser did not correctly verify validity of a link, so everything that had a dot would be parsed as a link. Fixed this for next release.
