### ISSUE TITLE
Server is crashing because of Skript's newest version.

### ISSUE THREAD

**Issue by berkanbasaran** [bensku/Skript#626]
I was using dev25 version without any problems, now i installed dev28c. My server is crashing while loading my scripts.

Here's error log: https://hastebin.com/ilonikamam.md

**Comment by bensku** [comment]
I need to see script(s) which cause this. Anyway, it crashes because reload is too slow for Spigot's watcher thread. I can try to resolve the issue, but need testing material.

**Comment by berkanbasaran** [comment]
I text you on Discord.

**Comment by berkanbasaran** [comment]
I sent a message to you on Discord.

**Comment by Syst3ms** [comment]
@berkanbasaran Come on, nobody is going to steal your scripts if you post them here

**Comment by Legoman99573** [comment]
@berkanbasaran plus even if they are public, anyone can see it. Just run a dummy one and post it here. Without it, we cant help you if we cant resolve it

**Comment by bensku** [comment]
See #636 for discussion about this.
