### ISSUE TITLE
Error by loading Skript 2.2-dev28c

### ISSUE THREAD

**Issue by Drumber** [bensku/Skript#628]
The version dev27 ran withot problems for me. But when I installed the version dev28b/c, there were some errors.
By enabling Skript:
https://hastebin.com/mifupiwovi.bash

By reload a skript:
https://hastebin.com/tobubezuho.vbs

Server version: Spigot 1.8.8

Sorry for my not so perfect english :D

**Comment by bensku** [comment]
1.8 does not work anymore. As it was never supported, it is unlikely that this will be fixed.
