### ISSUE TITLE
Signature of Function is null.

### ISSUE THREAD

**Issue by berkanbasaran** [bensku/Skript#629]
My script doesn't load on starting of server with this error: https://hastebin.com/hiwupasopu.md
But when I reload it manually after server started, it works.

**Comment by nshun1896** [comment]
If the function is loaded after scripts which used the function, those kind of errors occur.
How about naming files as 1.functions.sk and 02.main_script.

I'm just a skript user, and if i'm wrong I'm sorry.

**Comment by TheBentoBox** [comment]
What script is the getWeekDay function defined in?

**Comment by berkanbasaran** [comment]
Okay fixed, thanks.
