### ISSUE TITLE
`on form` event not working

### ISSUE THREAD

**Issue by LuckyBowers** [bensku/Skript#63]
the `on form` event is simply does not work.  No console errors, just does not detect.  I am using it as: `on form of cobblestone:` to create custom cobblestone generators, but it does not detect. PLEASE fix

**Comment by LuckyBowers** [comment]
apparently `on block physics:` works, so I shall try it when I am home

**Comment by bensku** [comment]
Soo, does it work? And what you actually tried to do, could you post the script (using pastebin etc.)?

**Comment by bensku** [comment]
Closing an extremely old issue. I assume block physics event worked but no one actually bothered to respond here.

**Comment by GoodmanSIG** [comment]
Today, I tried to write the script "if lava and water create a cobblestone"
The error does not say it but nothing happens.
Is it going to fix it?

**Comment by supertassu** [comment]
@GoodmanSIG Pleade create a new issue instead of commenting of really old one.

**Comment by LuckyBowers** [comment]
haha, hello old thread 😜
