### ISSUE TITLE
Can't get name of written book

### ISSUE THREAD

**Issue by loadka95** [bensku/Skript#633]
What im tyring to do is remove an item from the player's inventory with a specific name, but it doesnt's work,
It doesn't even get the name of the items.. it's always says <none>
I don't know it's a bug or im just doing it wrong but its not wroking...
```
command /dut:
    trigger:
        loop items in player's inventory:
            wait 1 second
            message "%name of loop-item%" to player
            if name of loop-item is "hi":
                remove loop-item from player's inventory
                stop
command /other:
	trigger:
		remove 1 written book named "hi" from player's inventory
```

**Comment by Snow-Pyon** [comment]
If you're trying to get their raw name, not a custom one, then you should use `loop-item's type` rather than `loop-item's name`. You should ask in the forums before post an issue here.

**Comment by loadka95** [comment]
That's the problem I want to get the custom name, but it's doesn't work...

**Comment by bensku** [comment]
I think written book's name is implemented a bit differently than other nameable items. After all, they were added before general-purpose named items.

Why Spigot doesn't handle it for me... Well, I can only wonder :)

**Comment by WheezyGold7931** [comment]
I'm looking into a fix for this

**Comment by Snow-Pyon** [comment]
Fixed in dev32 (use the [book title](http://bensku.github.io/Skript/expressions.html#ExprBookTitle) expression).
