### ISSUE TITLE
Skript 1.8 request

### ISSUE THREAD

**Issue by Aralwen** [bensku/Skript#635]
Version 1.8 is a much used version, would it be possible to maintain updates of Skript on this release also ? :|

**Comment by TheBentoBox** [comment]
No. Bensku has taken his stance. It's your fault for using a version that's four major updates behind and that was released almost three years ago. There's literally no reason to be on 1.8 over any of the newer reasons (especially if you use Skript given you can revert all of the 1.9 combat changes through addons). If you want to stay on an ancient version forever, this is eventually what you'll have to deal with. There are plenty of Skript versions available to 1.8 users, but you're lucky it even worked for as long as it did.
