### ISSUE TITLE
Spigot particle support is buggy

### ISSUE THREAD

**Issue by bensku** [bensku/Skript#64]
I'll need to create some workaround and/or write my own NMS library. Current Spigot API can't set force flag in particle packet (i.e. it lacks features that /particle command has)

**Comment by Sashie** [comment]
There's nothing wrong with this library (https://github.com/DarkBlade12/ParticleEffect) A lot of people as well as myself use it for our particle effects. 
The one in EffectLib is also upgraded to 1.9 (https://github.com/Slikey/EffectLib/blob/master/src/main/java/de/slikey/effectlib/util/ParticleEffect.java)

Honestly the spigot particle api sucks!

**Comment by bensku** [comment]
Hmm, EffectLib dependency might be good idea. I'll think about it bit more.

**Comment by bensku** [comment]
Partially fixed in next release with EffectLib support. Of course, that doesn't fix everything, since EffectLib has some bugs too.
