### ISSUE TITLE
Amount of players

### ISSUE THREAD

**Issue by Feerko** [bensku/Skript#641]
Hello, 'amount of players in world "xyz"' returns location ;o

**Comment by Snow-Pyon** [comment]
Can confirm this behavior. Tested on my Spigot 1.11.2 server and seems that it only happens with the dev28 (tested with the dev25 and dev27, it doesn't happen with them). Might be something related  to the new vector stuff?

**Comment by bensku** [comment]
Is the location location of some of the players?

**Comment by Snow-Pyon** [comment]
It's just the amount of players as x, y and z axis. For example I have two players then it'll display:
```
x: 2, y: 2, z: 2
```
Here an example:
![image](https://user-images.githubusercontent.com/23110519/26860489-9293cfbc-4b14-11e7-9aeb-259527d62c4e.png)

**Comment by Syst3ms** [comment]
Definitely vectors. For some reason it has used the number > vector > location route.

**Comment by bensku** [comment]
Hmm, I might have to disable number to vector right-chaining for converters. It will break stuff, but less than this. Plus, if I finally fixed vector math it would not be needed. :)

**Comment by bensku** [comment]
When next release is out, could someone test this again?

**Comment by Snow-Pyon** [comment]
I'll test it, sure.

**Comment by bensku** [comment]
Ok, new release is out. Not closing until testing has been done though.

**Comment by Snow-Pyon** [comment]
Tested and it seems to work fine now. Can be closed now, I think? Haha.
