### ISSUE TITLE
Make the "<none>" null value display configurable

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#646]
In Config, there should be an option to change the 

"< none >" to something like "Nothing here!", so when there isn't anything in the variable in my script, it won't say "< none >"

**Comment by Pikachu920** [comment]
I guess this would be an ok config option to have, but its easy to implement this yourself with skquery's default values like so:
```
{_var} ? "Nothing here!"
```

**Comment by Adrihun** [comment]
default is not a boolean

**Comment by Pikachu920** [comment]
What?

**Comment by bensku** [comment]
This is about the same as asking Java to make null's name configurable. But fine, I guess for localization reasons this would be useful.
