### ISSUE TITLE
ch.njol.skript.SkriptAPIException: No class info found for player'

### ISSUE THREAD

**Issue by Tristag** [bensku/Skript#648]
I feel terrible for putting more bugs in the issues section without actually being able to help much :(

However, this glitch has been causing me quite a bit of trouble these past few days... 

It randomly happens and the only way I know how to fix it is to copy all my plugin files to a brand new server and copy them back.

It happened most recently when I upgraded to 28c from 25.  However, going back to 25 the issue still persists.

Here is a complete Error Log:
https://pastebin.com/NaeJSttF

Thanks for all the hard work! Will continue fixing it the only way I know how

**Comment by Pikachu920** [comment]
This probably isn't a skript issue but rather an issue with an addon. This bug tracker is for skript itself, not addons.

**Comment by bensku** [comment]
Sounds like an addon issue. Make sure you update them as well.
