### ISSUE TITLE
Targeted Block

### ISSUE THREAD

**Issue by bertek41** [bensku/Skript#651]
Targeted block is not target the crosshair.

```
command /hey:
	trigger:
		set line 1 of player's targeted block to "Test"
		stop
```

![2017-06-11_02 27 43](https://user-images.githubusercontent.com/20637793/27007044-b6de1b0c-4e4d-11e7-8eaa-161f3b3dee52.png)
![2017-06-11_02 27 49](https://user-images.githubusercontent.com/20637793/27007045-b6e11230-4e4d-11e7-8ef7-d369fd321709.png)

**Comment by TheBentoBox** [comment]
This isn't really a bug, it gets the first block in a straight line from your crosshairs that's not air. You'll have to petition Spigot if you want a way around that.

**Comment by bertek41** [comment]
Is there anyway to detect where is the player looking?

**Comment by FUZIK** [comment]
I am using:
```
command /hey:
	trigger:
		set line 1 of clicked block to "Test"
		stop
```

**Comment by bertek41** [comment]
How can you use clicked block in command it is can only be used in on click event
