### ISSUE TITLE
Aliases missing for new 1.12 objects

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#653]
In preparation for 1.12 support:
> [18:38:08] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 438, 441, 453

The aliases for ids 438 and 441 were never resolved for 1.11.2. See #275.

**Comment by Syst3ms** [comment]
There is an updated version of the aliases on the forums

**Comment by bensku** [comment]
Updating aliases for next release from @tim740, as I have done with every significant Minecraft update before.

**Comment by SlimeDog** [comment]
Apologies. I didn't scan the forum for it. I looked at https://raw.githubusercontent.com/bensku/Skript/master/src/main/resources/aliases-english.sk, as instructed in #275. Thanks for the update.

**Comment by SlimeDog** [comment]
Spigot 1.12
Skript 2.2-dev28c
aliases-english.sk 2.0.6

Aliases now resolve, except for the two unresolved previously:
> [06:17:40] [Server thread/WARN]: [Skript] There are no aliases defined for the following ids: 438, 441

As in aliases_english.sk 2.0.5, the file contains
```
        splash(_| )potion¦s = 438
        spectral(_| )arrow¦s = 439
        tipped(_| )arrow¦s = 440
        lingering(_| )potion¦s = 441
```

**Comment by HYPExMon5ter** [comment]
That's a bug iirc

**Comment by bensku** [comment]
Old bug, already reported! And not even 1.12 specific.

**Comment by SlimeDog** [comment]
Yes, it was reported for the 2.0.5 file. The point of this report is that it still exists in 2.0.6 file. :(
