### ISSUE TITLE
Console Error while reloading skript

### ISSUE THREAD

**Issue by Cheikotesu** [bensku/Skript#654]
Hi, why all of my Skript doesn't work while change skript jar to version 2.2-dev28c ? My server using Spigot 1.8.8 with Java 8. After i try to reload one of my skript, the Console contain error like this:

11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! End of Error. 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! Thread: Server thread 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! Current item: null 
11.06 16:59:31 [Server] ERROR #!#! Current node: Command /CustomButtonCommand [<Text>] [<Number>] [<Text>] [<Text>]: (CBC.sk, line 4) 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! Running CraftBukkit: false 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.6.2.el6.x86_64 
11.06 16:59:31 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14) 11.06 16:59:31 [Server] ERROR #!#!   Minecraft: 1.8.8 
11.06 16:59:31 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT 
11.06 16:59:31 [Server] ERROR #!#!   Skript: 2.2-dev28c 
11.06 16:59:31 [Server] ERROR #!#! Version Information: 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) 
11.06 16:59:31 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source) 
11.06 16:59:31 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) 
11.06 16:59:31 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) 
11.06 16:59:31 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) 
11.06 16:59:31 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
11.06 16:59:31 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:187) 
11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:267) 11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243) 11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409) 11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:370) 
11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:335) 
11.06 16:59:31 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240) 
11.06 16:59:31 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over 
11.06 16:59:31 [Server] ERROR #!#! Stack trace: 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast. 11.06 16:59:31 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
11.06 16:59:31 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error. 
11.06 16:59:31 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service), 
11.06 16:59:31 [Server] ERROR #!#! and check whether this error has already been reported. 
11.06 16:59:31 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/ 
11.06 16:59:31 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
11.06 16:59:31 [Server] ERROR #!#! 
11.06 16:59:31 [Server] ERROR #!#! Could not load CBC.sk 
11.06 16:59:31 [Server] ERROR #!#! [Skript] Severe Error: 
11.06 16:59:31 [Server] ERROR #!#!

**Comment by TheBentoBox** [comment]
This fork is no longer compatible with versions of Minecraft older than 1.9 as of dev28. Either downgrade your Skript version or (finally) upgrade your server.

**Comment by Cheikotesu** [comment]
owh, thx k :)
