### ISSUE TITLE
Console Error While Event on death of Player

### ISSUE THREAD

**Issue by Cheikotesu** [bensku/Skript#655]
Console Contain error while suicide, this is happend when i'm add Force Respawn on Skript like this:

on death of player:
	wait 1 tick
	force victim to respawn

11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! End of Error. 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! Thread: Server thread 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! Current item: the attacked entity is not equal to (the last dropped dropped item, the fireball or [[entitydata:armor stand]])[class java.lang.Object] (comparator: null) 
11.06 21:35:44 [Server] ERROR #!#! Current node: null 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! Running CraftBukkit: false 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.6.2.el6.x86_64 
11.06 21:35:44 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14) 11.06 21:35:44 [Server] ERROR #!#!   Minecraft: 1.8.8 
11.06 21:35:44 [Server] ERROR #!#!   Bukkit: 1.8.8-R0.1-SNAPSHOT 
11.06 21:35:44 [Server] ERROR #!#!   Skript: 2.2-dev27 
11.06 21:35:44 [Server] ERROR #!#! Version Information: 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) 
11.06 21:35:44 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source) 
11.06 21:35:44 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) 
11.06 21:35:44 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) 
11.06 21:35:44 [Server] ERROR #!#!     at com.earth2me.essentials.Essentials.onCommand(Essentials.java:402) 
11.06 21:35:44 [Server] ERROR #!#!     at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:527) 
11.06 21:35:44 [Server] ERROR #!#!     at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:180) 
11.06 21:35:44 [Server] ERROR #!#!     at com.earth2me.essentials.commands.Commandsuicide.run(Commandsuicide.java:20) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) 
11.06 21:35:44 [Server] ERROR #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare.check(CondCompare.java:258) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:157) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:174) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.conditions.CondCompare$1.check(CondCompare.java:261) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.ExpressionList.check(ExpressionList.java:170) 11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.ExpressionList.check(ExpressionList.java:176) 11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:157) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpression.java:162) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:113) 11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:91) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:105) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1) 11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:193) 
11.06 21:35:44 [Server] ERROR #!#!     at ch.njol.skript.classes.data.BukkitEventValues$32.get(BukkitEventValues.java:1) 
11.06 21:35:44 [Server] ERROR #!#! java.lang.ClassCastException: org.bukkit.event.entity.EntityDamageEvent cannot be cast to org.bukkit.event.entity.EntityDamageByEntityEvent 
11.06 21:35:44 [Server] ERROR #!#! Stack trace: 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast. 11.06 21:35:44 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
11.06 21:35:44 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error. 
11.06 21:35:44 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service), 
11.06 21:35:44 [Server] ERROR #!#! and check whether this error has already been reported. 
11.06 21:35:44 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/ 
11.06 21:35:44 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
11.06 21:35:44 [Server] ERROR #!#! 
11.06 21:35:44 [Server] ERROR #!#! [Skript] Severe Error: 
11.06 21:35:44 [Server] ERROR #!#!

**Comment by bensku** [comment]
Are you absolutely sure that this is related to force respawn? Looks like more generic death eveng bug to me...

**Comment by Cheikotesu** [comment]
Sorry,  You are right. This happen because event on death of player

**Comment by TheBentoBox** [comment]
I'll say fixing this is sort of awkward since you're using an older Skript version (dev27 when we're on dev29) and you can't even update to test if this works in newer versions since you're on 1.8 and new versions don't work on 1.8 anymore. I'm not really sure what the policy should be in regards to fixing bugs on older versions, but obviously that's up to bensku, not me.

**Comment by bensku** [comment]
This might be an issue on 1.9+ too. Just haven't checked it yet. And I do know that this has not been fixed unless it was a Spigot bug in 1.8.

**Comment by bensku** [comment]
Actually, cannot reproduce this with newer Minecraft versions.

**Comment by Bastiaan1200** [comment]
having this to

**Comment by Bastiaan1200** [comment]
> [18:31:47 ERROR]: #!#! Stack trace:
> [18:31:47 ERROR]: #!#! java.lang.ClassCastException: org.bukkit.event.entity.EntityDamageEvent cannot be cast to org.bukkit.event.entity.EntityDamageByEntityEvent
> [18:31:47 ERROR]: #!#! at ch.njol.skript.classes.data.BukkitEventValues$32.get(BukkitEventValues.java:1)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:193)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.registrations.EventValues$2.get(EventValues.java:1)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.expressions.base.EventValueExpression.getValue(EventValueExpression.java:105)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.expressions.base.EventValueExpression.get(EventValueExpression.java:91)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:113)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.expressions.ExprEntity.get(ExprEntity.java:1)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpression.java:77)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:75)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.conditions.CondIsSet.check(CondIsSet.java:81)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.Condition.run(Condition.java:56)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:151)
> [18:31:47 ERROR]: #!#! at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:109)
> [18:31:47 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [18:31:47 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
> [18:31:47 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
> [18:31:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:92)
> [18:31:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:577)
> [18:31:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:563)
> [18:31:47 ERROR]: #!#! at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:609)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1309)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:855)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityBat.damageEntity(SourceFile:203)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.Entity.burn(Entity.java:1028)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.Entity.move(Entity.java:893)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityLiving.g(EntityLiving.java:1762)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2064)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:501)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1893)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:244)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.EntityBat.A_(SourceFile:112)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1631)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.World.h(World.java:1606)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1432)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
> [18:31:47 ERROR]: #!#! at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
> [18:31:47 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)

**Comment by bensku** [comment]
That is... not the same issue. Probably.

**Comment by Bastiaan1200** [comment]
It has something to do with the on death
