### ISSUE TITLE
Wipe scoreboard bug

### ISSUE THREAD

**Issue by lucasboss45** [bensku/Skript#656]
{\rtf1\ansi\ansicpg1252\deff0\deflang1036{\fonttbl{\f0\fnil\fcharset0 Arial;}}
{\colortbl ;\red0\green0\blue255;\red255\green0\blue0;}
\viewkind4\uc1\pard\cf1\fs24 11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:53 [SEVERE] #!#! Version Information:\par
11/06/2017 16:02:53 [SEVERE] #!#!   Skript: 2.2-dev28c\par
11/06/2017 16:02:53 [SEVERE] #!#!   Bukkit: 1.9.4-R0.1-SNAPSHOT\par
11/06/2017 16:02:53 [SEVERE] #!#!   Minecraft: 1.9.4\par
11/06/2017 16:02:53 [SEVERE] #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)\par
11/06/2017 16:02:53 [SEVERE] #!#!   OS: Windows 10 amd64 10.0\par
11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:53 [SEVERE] #!#! Running CraftBukkit: false\par
11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:53 [SEVERE] #!#! Current node: null\par
11/06/2017 16:02:53 [SEVERE] #!#! Current item: null\par
11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:53 [SEVERE] #!#! Thread: Server thread\par
11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:53 [SEVERE] #!#! End of Error.\par
11/06/2017 16:02:53 [SEVERE] #!#!\par
11/06/2017 16:02:57 [SEVERE] #!#!\par
11/06/2017 16:02:57 [SEVERE] #!#! [Skript] Severe Error:\par
11/06/2017 16:02:57 [SEVERE] #!#!\par
11/06/2017 16:02:57 [SEVERE] #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.\par
11/06/2017 16:02:57 [SEVERE] #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/\par
11/06/2017 16:02:57 [SEVERE] #!#! and check whether this error has already been reported.\par
11/06/2017 16:02:57 [SEVERE] #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),\par
11/06/2017 16:02:57 [SEVERE] #!#! and describe what you did before it happened and/or what you think caused the error.\par
11/06/2017 16:02:57 [SEVERE] #!#! If you think that it's a trigger that's causing the error please post the trigger as well.\par
11/06/2017 16:02:57 [SEVERE] #!#! By following this guide fixing the error should be easy and done fast.\par
11/06/2017 16:02:57 [SEVERE] #!#!\par
11/06/2017 16:02:57 [SEVERE] #!#! Stack trace:\par
\cf2 11/06/2017 16:02:57 [SEVERE] #!#! java.lang.NullPointerException\par
11/06/2017 16:02:57 [SEVERE] #!#!     at net.rayfall.eyesniper2.skRayFall.Scoreboard.EffSetScore.execute(EffSetScore.java:42)\par
11/06/2017 16:02:57 [SEVERE] #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564)\par
11/06/2017 16:02:58 [SEVERE] #!#!     at java.lang.Thread.run(Unknown Source)\par
\cf1 11/06/2017 16:02:58 [SEVERE] #!#!\par
11/06/2017 16:02:58 [SEVERE] #!#! Version Information:\par
11/06/2017 16:02:58 [SEVERE] #!#!   Skript: 2.2-dev28c\par
11/06/2017 16:02:58 [SEVERE] #!#!   Bukkit: 1.9.4-R0.1-SNAPSHOT\par
11/06/2017 16:02:58 [SEVERE] #!#!   Minecraft: 1.9.4\par
11/06/2017 16:02:58 [SEVERE] #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)\par
11/06/2017 16:02:58 [SEVERE] #!#!   OS: Windows 10 amd64 10.0\par
11/06/2017 16:02:58 [SEVERE] #!#!\par
11/06/2017 16:02:58 [SEVERE] #!#! Running CraftBukkit: false\par
11/06/2017 16:02:58 [SEVERE] #!#!\par
11/06/2017 16:02:58 [SEVERE] #!#! Current node: null\par
11/06/2017 16:02:58 [SEVERE] #!#! Current item: null\par
11/06/2017 16:02:58 [SEVERE] #!#!\par
11/06/2017 16:02:58 [SEVERE] #!#! Thread: Server thread\par
11/06/2017 16:02:58 [SEVERE] #!#!\par
11/06/2017 16:02:58 [SEVERE] #!#! End of Error.\par
11/06/2017 16:02:58 [SEVERE] #!#!\par
}

The problem arrived when i tried to add:
wipe {variable}'s sidebar
And the portion of code started repeating and this was the error i saw on the console

Here is the skript file in case it is needed
[Skript.zip](https://github.com/bensku/Skript/files/1066478/Skript.zip)

Here are my addons used in case they are needed:
- SharpSK
- Skellet
- SkQuery
- SkUtilities
- TySKe
- Umbaska
- WildSkript
- WolvSK
- SkRayFall
- RandomSK

**Comment by TheBentoBox** [comment]
Not a Skript issue, this is an skRayFall effect, report it to eyesniper.

Closed #656.
