### ISSUE TITLE
Unable to properly cancel dual right click events

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#66]
Sorry if the title is a little weird, the issue is a bit specific and hard to describe shortly.

I think the issue here lies with the fact that Spigot (I believe) always throws right click events for both hands, but Skript only fires one right click event - you manually check if the mainhand item is usable, and if it is, you fire the mainhand click event. Otherwise, if the offhand is usable, you fire the click event from the offhand tool (I believe that's how you're doing it).

Anyways, my situation is that we have an item called the "Portable Hole" - it's an eye of ender that lets you right click with it to open a temporary tunnel in front of you. We detect right click events, and perform the necessary checks on both your mainhand and your offhand items to see if you're holding it in either one. Of course, since it's an eye of ender, we then cancel the right click event, otherwise you'd just throw it on use. This works perfectly fine and as expected when it's in the mainhand. If it's in the offhand, however, it only properly cancels the event if there's nothing in the mainhand. Otherwise, it cancels the mainhand item's click event instead, then performs the Portable Hole action, and then also throws the pearl - because it DOES properly detect the item in the offhand, but the offhand item's event  isn't fired by Skript, so my `cancel event` isn't cancelling it.

I'm not sure the best solution, all of this 1.9 dual wielding stuff is cool but it's made a bit of a Skript mess. Maybe just make it so cancelling a right click event cancels it for both hands if possible?

**Comment by TheBentoBox** [comment]
Along with this, I tried fixing it by detecting `on shoot` for eyes of ender, and it doesn't fire for them.

**Comment by TheBentoBox** [comment]
Ok, so part of the problem is that `EYE_OF_ENDER` isn't in the big switch statement in the checkUseOffHand function in [EvtClick.java](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/events/EvtClick.java), so Skript isn't counting it as a usable item.

**Comment by bensku** [comment]
Whoa, thanks! I have gotten some reports for click events bugging, but this is first time someone has given me solutions for this particular problem.

Now I can actually start fixing this :)

**Comment by bensku** [comment]
Ok, I have probably fixed this. Please try again with next build :)

In general, this is complex system to work with. First I tried to cancel both events; the problem was that when getting click event I can never know if another will come after a while. That was called "feature" many times, but in the end it broke our project and I had to fix it somehow.

**Comment by bensku** [comment]
Yes, but not usable item for off hand. For some reason, in main hand it has priority over e.g. blocks, in off hand it does not.
