### ISSUE TITLE
minecraft

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#660]
I know this isnt the place to post this but...

You all hard the news right? Console & all other versions will be cross compatible but not PC, pc will be left out and All of the big servers will go over to console, they will get more players etc...

What will happen to skript? 
What will happen to Spigot?
What will happen to..... Bungeecord???

I'm scared ._.

**Comment by aescraftbr** [comment]
?

**Comment by Adrihun** [comment]
https://www.youtube.com/watch?v=Nq_Q77bJ3H0

**Comment by TheBentoBox** [comment]
If you know this isn't the place to post this, then don't post it. Seriously, this isn't a forum. I'm tired of having to close issue reports from you.

**Comment by Adrihun** [comment]
What do you mean you only had to close like 3 issues.

and i dont post every day

**Comment by TheBentoBox** [comment]
Most people don't report as many invalid issues as you in as short of a period of time :) This isn't open for discussion regardless, I'm not here to argue with you. Just don't report something you know you shouldn't be reporting again. Random discussions, questions, and addon issues don't belong here.
