### ISSUE TITLE
On Consume of potion - RESOLVED

### ISSUE THREAD

**Issue by PheonBest** [bensku/Skript#663]
Hi !
I get an error when I use on consume event :/
Hope you would be able to fix it !

**Comment by Snow-Pyon** [comment]
You have to be more specific, which errors? How it occurs exactly? Are you sure it happened just because the event and not your code? Which version of Skript are you running? which Minecraft version?

**Comment by PheonBest** [comment]
Skript can't understand this event so that's only cause of it. I run the latest Skript.jar provided by Benksu (you make a great job <3) and I use the latest Spigot version.

**Comment by Syst3ms** [comment]
1. "latest" can mean a lot of things, please say the exact versions (Spigot and Skript)
2. Could you provide the code ?

**Comment by PheonBest** [comment]
Hi Syst3ms x) The latest means the latest ! I use the dev29 version of Skript and spigot-1.12-R0.1-SNAPSHOT-b1316 version of Spigot.
```
On Consume of potion:
	wait 1 tick
	set {_bottle} to tool of player
	remove 1 of {_bottle} from player's inventory

```
Here is it but i've already said it: Skript can't understand this event, simply.

**Comment by TheBentoBox** [comment]
Potion is an expression now, as potions are stored as NBT on bottles of watter. Have you tried `on consume of bottle of water` instead?

**Comment by PheonBest** [comment]
You're right I'm sorry.
Thank you so much :)

**Comment by Sam1370** [comment]
someone close this issue
