### ISSUE TITLE
Regarding slow script loads

### ISSUE THREAD

**Issue by Sashie** [bensku/Skript#665]
Just thought i'd leave this everywhere for people to see. It will most likely make 0 sense. What i did was make some timings to see how Skripts parser works and came up with this mess....
https://hastebin.com/ulanorowuv.vbs
the .sk file i used only has...
```
command /initvector:
	trigger:
		set {vector} to new vector 0, 2, 0

command /example01:
	trigger:
		spawn 5 directional blockdust particle made of redstone block at location of player with direction {vector} and speed .2
```

**Comment by Syst3ms** [comment]
Seen that when debugging the Scope API

**Comment by TheBentoBox** [comment]
What is it like if you take out the particle part? These even slower script loading times started in dev28, perhaps it's due to the changes to the particle system to support colored particles and stuff?

**Comment by Sashie** [comment]
That would be a fancy theory however I'm using my own particle syntax

**Comment by Sashie** [comment]
these lines in that log might point to an issue, see the time go up drastically..
```
1:27:10 PM [INFO] [Skript] [TIMER]                  - FOR LOOP 1 START (0.196513606s)
1:27:10 PM [INFO] [Skript] [TIMER]                  - SkriptParser.parse(source) calling SkriptParser.parse_i() START: spawn %entitytypes% [%directions% %locations%] (0.196544861s)
1:28:54 PM [INFO] [Skript] [TIMER]                  - SkriptParser.parse(source) calling SkriptParser.parse_i() END: null (105.650361999s)
1:28:54 PM [INFO] [Skript] [TIMER]                  - LOOP 1 check 1 (105.650584292s)
```

**Comment by Sashie** [comment]
Here are some more  timings once it gets into parse_i(). It gets extremely spammy so I only copied over the first chunk to show some recursion. (the log file the server created got up to 25mb before my server crashed due to low memory(i only have 4gb ;p))

this time the test skript was this..
```
command /example01:
	trigger:
		set {_v} to new vector 0, 2, 0
		spawn 5 directional blockdust particle made of redstone block at location of player with direction {_v} and speed .2
```
The first chunk of mess..
https://hastebin.com/adakawivap.vbs

This next section is where it starts looking at `spawn %entitytypes% [%directions% %locations%]`
https://hastebin.com/hasakiqigu.sql

I also seem to get this error(i dont remember seeing it before)
`[01:52:23] [Server thread/ERROR]: [Skript] Variables cannot be used here. (ztest.sk, line 11: spawn 5 directional blockdust particle made of redstone block at location of player with direction {_v} and speed .2')`

it also seems to take some time in that ParseResult class before the timer continues
```
[01:52:11] [Server thread/INFO]: [Skript] [TIMER]                    - SkriptParser.parser_i() END return new ParseResult(this, pattern) [116 - 46] (86.237944279s) 
[01:52:23] [Server thread/ERROR]: [Skript] Variables cannot be used here. (ztest.sk, line 11: spawn 5 directional blockdust particle made of redstone block at location of player with direction {_v} and speed .2')
[01:52:23] [Server thread/INFO]: [Skript] [TIMER]                    - [8 - 21] calling parse_i() (98.006372183s) 
```
By adding timings to parse_i() it seems to have slowed the parser down considerably not to mention the recursion spam

**Comment by bloggy** [comment]
for me your hastebin links won't show anything

**Comment by Sashie** [comment]
A couple of them are fairly large, perhaps they take too long to load? (they still work for me)

On as side note @bensku I ran this same .sk file on dev25 and using bi0s vector addon instead...
The load times are way faster on the older version....
`12:00:16 PM [INFO] [Skript] Loaded 1 script with a total of 0 triggers and 2 commands in 20.4 seconds`

**Comment by Sashie** [comment]
[vectors-addon-dev25.zip](https://github.com/bensku/Skript/files/1098078/vectors-addon-dev25.zip)
A copy of the modified version version of bi0s vectors addon that works with dev25 of Skript

**Comment by bensku** [comment]
I would like to see the code that loads this slowly with dev28+. Yes, even if it uses addons.

**Comment by Sashie** [comment]
I'll send the syntax in question to your discord
