### ISSUE TITLE
Changing table name in SQL database

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#666]
Title says it

i want to change the name of the table in the SQL database.
 i dont like the name: "variables21"

**Comment by Syst3ms** [comment]
You can't.

**Comment by Adrihun** [comment]
well make it a config option then

**Comment by Pikachu920** [comment]
i think you forgot the magic word

**Comment by Adrihun** [comment]
plzz

**Comment by xXAndrew28Xx** [comment]
One does not simply "make it a config option". It takes work.

**Comment by Adrihun** [comment]
yes but it would be a really good option

**Comment by Pikachu920** [comment]
Why don't we just add a config option to enable the config option? That would be the perfect solution.

**Comment by Adrihun** [comment]
lmao

**Comment by xXAndrew28Xx** [comment]
I'll probably do a PR adding it.

**Comment by xXAndrew28Xx** [comment]
PR is done 👍
