### ISSUE TITLE
Incorrect script load order

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#667]
Load order is very important when dealing with Skript because functions may only be used once they've been declared, otherwise nasty exceptions are thrown. In the last few Skript releases, this delicate order has essentially reversed.

With the following scripts, '**should-be-first.sk**', as its name suggests, *should* load first because its directory ('**__load**') is alphabetically before '**second.sk**'. This has been the standard Skript behavior for years.
* **plugins/Skript/scripts/__load/should-be-first.sk** 
```
on script load:
    broadcast "LOADED: '/__load/should-be-first.sk'"
```
* **plugins/Skript/scripts/second.sk**
```
on script load:
    broadcast "LOADED: '/second.sk'"
```

## Comparing load orders with previous releases

Using **Skript version 2.2-dev25** (__correct__ ✅):
```
[Skript] Loading variables...
[Skript] Loaded 0 variables in 0.0 seconds
LOADED: '/__load/should-be-first.sk'
LOADED: '/second.sk'
[Skript] All scripts loaded without errors.
[Skript] Loaded 2 scripts with a total of 2 triggers and 0 commands in 0.14 seconds
[Skript] Finished loading.
```

Using **Skript version 2.2-dev29** (__incorrect__ 🚫):
```
[Skript] Loading variables...
[Skript] Loaded 0 variables in 0.0 seconds
LOADED: '/second.sk'
LOADED: '/__load/should-be-first.sk'
[Skript] All scripts loaded without errors.
[Skript] Loaded 2 scripts with a total of 2 triggers and 0 commands in 0.1 seconds
[Skript] Finished loading.
```

**Comment by Pikachu920** [comment]
I think this should be fixed, but Bensku has said otherwise in #466

**Comment by RezzedUp** [comment]
This is a huge issue for me because my scripts directory structure is basically this:
```
. scripts/
|--. __lib/
|  |--. __framework/
|  |  |--. __util/
|  |  |  |--- contains.sk
|  |  |  |--- strings.sk
|  |  |  `--- typeof.sk
|  |  |--- events.sk
|  |  `--- region-maps.sk   
|  `--. json/
|     `--- json.sk
|--- chat.sk
`--- welcome.sk
```
All reusable scripts/libraries/functions/etc are put into the **__lib/** directory so that they reliably load first. Now, they're loaded dead last (breaking everything).

**Comment by bensku** [comment]
To be clear, I did not change load order intentionally. As you can see, #466 is still open and waiting for me to do something with it.

**Comment by RezzedUp** [comment]
> Besides, functions should work even before rhey are declared.

I don't think that's *ever* been the case in Skript.

If I update my example scripts above to use a function instead of the broadcast effect directly, this is what happens:

* **plugins/Skript/scripts/__load/should-be-first.sk**
```
function broadcast(message: text):
    broadcast {_message}
on script load:
    broadcast("LOADED: '/__load/should-be-first.sk'")
```
* **plugins/Skript/scripts/second.sk**
```
on script load:
    broadcast("LOADED: '/second.sk'")
```
### Results:
```
[Skript] Loading variables...
[Skript] Loaded 0 variables in 0.0 seconds
#!#!
#!#! [Skript] Severe Error:
#!#!
#!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
#!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
#!#! and check whether this error has already been reported.
#!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
#!#! and describe what you did before it happened and/or what you think caused the error.
#!#! If you think that it's a trigger that's causing the error please post the trigger as well.
#!#! By following this guide fixing the error should be easy and done fast.
#!#!
#!#! Stack trace:
#!#! java.lang.NullPointerException
#!#!     at ch.njol.skript.lang.function.FunctionReference.execute(FunctionReference.java:189)
#!#!     at ch.njol.skript.lang.function.EffFunctionCall.execute(EffFunctionCall.java:53)
#!#!     at ch.njol.skript.lang.Effect.run(Effect.java:52)
#!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
#!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
#!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
#!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:61)
#!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:458)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
#!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)
#!#!     at ch.njol.skript.Skript$2.run(Skript.java:405)
#!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
#!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
#!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
#!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
#!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
#!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
#!#!     at java.lang.Thread.run(Unknown Source)
#!#!
#!#! Version Information:
#!#!   Skript: 2.2-dev29
#!#!   Bukkit: 1.12-R0.1-SNAPSHOT
#!#!   Minecraft: 1.12
#!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
#!#!   OS: Windows 10 amd64 10.0
#!#!
#!#! Running CraftBukkit: false
#!#!
#!#! Current node: on script load: (second.sk, line 1)
#!#! Current item: broadcast("LOADED: '/second.sk'")
#!#!
#!#! Thread: Server thread
#!#!
#!#! End of Error.
#!#!
LOADED: '/__load/should-be-first.sk'
[Skript] All scripts loaded without errors.
[Skript] Loaded 2 scripts with a total of 2 triggers and 0 commands in 0.16 seconds
[Skript] Finished loading.
```

**Comment by TheBentoBox** [comment]
Bensku at one point added pre-loading of functions to this fork so that the declaration order wouldn't matter, which is why he says this shouldn't be an issue (even though it clearly is since something with it must have broken).

**Comment by bensku** [comment]
Well, I kinda see the issue. You're calling functions when the script is loaded... Had you called it from any other event (for example on click etc.) it would probably have worked.

I guess I need to change how on load events work or disallow functions in them.

**Comment by RezzedUp** [comment]
> Well, I kinda see the issue. You're calling functions when the script is loaded... Had you called it from any other event (for example on click etc.) it would probably have worked.

I use functions in `on script load` all the time. Actually, it's probably the event where I use them most.

> I guess I need to change how on load events work

They could be fired after all scripts are initially loaded (on server start) and kept the same when loaded individually (from /sk reload, for example).

>  or disallow functions in them.

... don't do that. 😦

Honestly, just fixing load orders would fix most of my current problems.

**Comment by bensku** [comment]
The thing is, if I make on load events to be called once ALL scripts are loaded - and thus, functions work - it might silently break old scripts. Disallowing functions would break scripts, but not silently.

I guess best idea would to have better error message here, and some kind of post-load event. And probably also fix this.

**Comment by bensku** [comment]
Found it and fixed. Was surprisingly easy to fix after all.

**Comment by Syst3ms** [comment]
Talking about derpage 😂. The simplest of mistakes always cause the biggest of issues.
