### ISSUE TITLE
Regions 1.12

### ISSUE THREAD

**Issue by Feerko** [bensku/Skript#669]
Hellooo

command /test:
<tab>trigger:
<tab><tab>set {_r} to "house" parsed as region
<tab><tab>loop all blocks in {_r}:
<tab><tab><tab>broadcast "%loop-block%"

it's doesn't work anymore. I'm using the newest WG and Skript version.

**Comment by Feerko** [comment]
loop all blocks in the region "house":

it's works but 

set {_house} to "house"
loop all blocks in the region "{_region}"

doesn't works

**Comment by TheBentoBox** [comment]
Do you realize you used two different variables in that second example? One is `{_house}` and the other `{_region}`. That's probably what caused that issue if you made that mistake in the actual code.

**Comment by Feerko** [comment]
@TheBentoBox I simplified the script to explain the error and made a typo. The error still occurs.

**Comment by bensku** [comment]
Is this 1.12 specific issue?

**Comment by bensku** [comment]
Cannot reproduce and no response. Closing.
