### ISSUE TITLE
New Feature: expression to get block face from block interact event

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#67]
The [PlayerInteractEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerInteractEvent.html) on Spigot has a method called [getBlockFace()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerInteractEvent.html#getBlockFace%28%29) which returns a [BlockFace](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/BlockFace.html) representing the side of the block that was clicked. It would be cool if, within the block left/right events in Skript, we could use %clicked block face% and %clicked block opposite face% to get the face that was clicked and the face opposite the one that was clicked as strings. You get the string of block face from the interact event (`e` being interact event) with `e.getBlockFace().toString()` and the opposite with `e.getBlockFace().getOppositeFace().toString()`.

**Comment by TheBentoBox** [comment]
Not one to do a -bump- normally, but any chance on getting this feature in one of the next releases when you get a chance? Would be very useful for doing directional things related to blocks, and should be fairly straightforward given the methods within the API for interact events (described in the first post).

**Comment by bensku** [comment]
Adding new data types is always major testing task, but I'll take look at that when I next have chance to add new features.

Intentory clicks, for example, vere bugged for few months until I in dev20 finally managed to fix last of those bugs.

**Comment by TheBentoBox** [comment]
I understand. Whenever you do get a chance, I'll be open to do a lot of testing with it for you and tell you how it seems to work. I imagine the most useful implementation would be the clicked block face representing a Skript direction. That way you could so stuff like `5 meters (clicked block face) of clicked block`. So if you clicked the "north" block face, it'd be `5 meters north`.

**Comment by Ayase-san** [comment]
Just bumping this to see when this will be a thing, I know you don't have the time to do it and it might be a bigger task then I thought, I'm bumping this just if you forgot about it and see if you think on add this on a non-far future.

**Comment by TheLimeGlass** [comment]
I will decompile Skript and add this type right now. Then do some testing to see how it goes.

**Comment by Syst3ms** [comment]
You know, Github (and Github desktop) is a thing
