### ISSUE TITLE
Skript (re)load times is becoming a real issue

### ISSUE THREAD

**Issue by Sam1370** [bensku/Skript#672]
Skript load times are getting to be a real problem for me.
I'm using the latest skript version and spigot 1.11.
I have a ~520 line Skript and when I load it (server load) it takes approx ~1 min. When I reload it Spigot crashes the server, saying that the server has become unresponsive.
EDIT: Let me elaborate:
I have Skript addons TuSKe, SkQuery-Lime, and Skellett.
Halfway through the skript reloading process my player disconnects.
Awhile later (~30 secs) the server crashes, here is the console.
https://pastebin.com/M12VtrP9
Here is my skript code. I'm using a Mac to host the server and join the server on the same computer, if that helps?
https://pastebin.com/jA0x426i
I'm also using json.sk (look it up on SkUnity.)

**Comment by TheBentoBox** [comment]
Duplicates #636 .
