### ISSUE TITLE
cancel event on anvil is not working with specific direction

### ISSUE THREAD

**Issue by setrymagent** [bensku/Skript#675]
issue: title
plz fix

**Comment by Syst3ms** [comment]
Okay lots of things to be said : 
- The title isn't very clear, you need to detail
- No detailing whatsoever
- You don't give enough info. We need your code as well as spigot and Skript versions
- "plz fix" won't help your case. It can even make people reluctant to help you. Also, we're not bugfix-o-matics.

**Comment by setrymagent** [comment]
sorry , i am english is not good.
i cant explain well. it mean specific direction cant cancel when anvil degree specific direction (like south north)

and skript is 2.2 dev28c minecraft is 1.11.2
when i wrote 

on rightclick on anvil:
cancel event
it will be cancelled but specific direction's degree anvil is not cancelled
it mean cancel event not working on rightlicking anvil
but it often works 
i dont know why it wont work.
i guess chunk is relation can you test

**Comment by Syst3ms** [comment]
I see the problem. So, depending on the orientation of the anvil a `cancel event` in an `on rightclick on anvil` event doesn't work ? What country are you from by the way ?

**Comment by Syst3ms** [comment]
Try with the dev29 and tell us if the problem persists

**Comment by TheBentoBox** [comment]
This sounds like it's just an aliases issue to me. Your aliases are probably set up in such a way that `anvil` only ends up referring to anvils in a specific orientation.

Will close if no further response is given.
