### ISSUE TITLE
New feature suggestion: Basic String Functions!

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#68]
Hi there,
I am in need of simple string functions which I have been missing in Skript since forever.

Mainly I am looking for such functions:

- Lowercase/Uppercase of first letter of a string
- Lowercase/Uppercase a complete string

**Comment by bensku** [comment]
In next release! And not as function, but as expression :)

**Comment by bensku** [comment]
... next release was later than I expected. Well, it is here now.

**Comment by bloggy** [comment]
Am I wrong or is it only possible to upperase ALL letters of a word?
If so, could you add a feature to uppercase only the first letter of a word?

Example:
"test" => "Test"

**Comment by TheBentoBox** [comment]
True. This is so old that I'll report it as a new enhancement but you're right that as far as I know there's no easy way to do this. Technically you can do it with `"%first character of %text% in upper case%%last (length of %text% - 1) characters of %text% in lower case%"` but that's really ugly.

**Comment by bloggy** [comment]
Has this ever been implemented? If so, what is the syntax?

**Comment by TPGamesNL** [comment]
> Has this ever been implemented? If so, what is the syntax?

It has: https://skriptlang.github.io/Skript/expressions.html#ExprStringCase (it's the proper/title case one)

**Comment by bloggy** [comment]
Does this work for you? 
"hellO i'm steve!" in proper case # HellO I'm Steve!

**Comment by TPGamesNL** [comment]
> Does this work for you?
> "hellO i'm steve!" in proper case # HellO I'm Steve!

I haven't tested it, but if it doesn't work, open an issue for it.
