### ISSUE TITLE
Doesn't work with Spigot 1.8.8

### ISSUE THREAD

**Issue by HaNiTLG** [bensku/Skript#680]
Hello!
I just want to report that the newest Spigot version doesn't work with the Spigot 1.8.8 version.
Best regards,
HaNiTLG :)

**Comment by Syst3ms** [comment]
How. many. of. these. issues. will. we. get ? Skript doesn't support 1.8 anymore, it never did anyway. It just magically worked before. If you still want to stick to 1.8 (which is going to be very unconvenient eventually), you should use dev25.

**Comment by TheBentoBox** [comment]
Yep, as Syst3ms said this is known and it's not going to be fixed. Downgrade to dev25 or (for the love of god) update your server.
