### ISSUE TITLE
Add new Entity types to spawn eggs

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#681]
If I use "{entity type} spawn egg" with {entity type} different from below, like llamas, parrots (from 1.11 mobs I think)(using their numerical id, of course)... it won't work.

	{entity type}:
		experience orb = :2
		xp orb = :2
		TNT = :20
		minecart = :40
		boat = :41
		creeper = :50
		skeleton = :51
		spider = :52
		giant = :53
		zombie = :54
		slime = :55
		ghast = :56
		zombie pigman = :57
		pig[ ]zombie = :57
		enderman = :58
		cave spider = :59
		silverfish = :60
		blaze = :61
		magma cube = :62
		ender dragon = :63
		wither = :64
		witch = :66
		bat = :65
		pig = :90
		sheep = :91
		cow = :92
		chicken = :93
		squid = :94
		wolf = :95
		mooshroom = :96
		snow golem = :97
		ocelot = :98
		iron golem = :99
		villager = :120
		ender crystal = :200

	{entity type} spawn egg¦s = 383

**Comment by TheBentoBox** [comment]
Spawn eggs were completely changed a while back to store their entity type in NBT as opposed to data value which is why this no longer works. I'm not sure if Spigot has an API for spawn eggs but if so it would be possible to fix (maybe someone could make a pull request).

**Comment by YellowZaki** [comment]
But right now all spawn eggs work till 1.10.
Can't you add the new mobs?

**Comment by Snow-Pyon** [comment]
This belongs to aliases rework so I'm closing this.
