### ISSUE TITLE
Particle names still wrong (latest 1.11.2 version of Skript)

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#685]
The particle names in the documentation seem still to be wrong. Example:

http://bensku.github.io/Skript/classes.html
'totem'

I have this:
**play 20 (totem with speed 0) at player**

And it results in an error (can't understand the effect/condition)

Can you fix them?

**Comment by Snow-Pyon** [comment]
Try without the speed.

**Comment by bensku** [comment]
Entity effects like totem do not support speed. I should clarify that in docs, though.

**Comment by bensku** [comment]
Works for me. Are you using addons?

**Comment by TheBentoBox** [comment]
No reply, closing.
