### ISSUE TITLE
On consume event gets fired twice

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#686]
I have this bug that the "on consume" event is triggered twice sometimes (not always) when drinking a water bottle.

on consume:
	if "%event-item%" contains "water_bottle":
        broadcast "test"

result:
test
test

Skript version:
Skript v2.2-dev25

**Comment by bensku** [comment]
Cannot reproduce with 1.12 and dev29. What Minecraft version? Do you have addons (try without if so)?

**Comment by TheBentoBox** [comment]
Cannot reproduce either, and no response, so closing.
