### ISSUE TITLE
Condition "is in world" isn't working

### ISSUE THREAD

**Issue by xMarkbom** [bensku/Skript#687]
I keep on getting this error and I don't think the plugin is reading my script correctly. the line is this:

command /arenaleave:
	aliases: /aleave
	trigger:
		if player is in world "{@World}":
			send "{@Pre}&8 Leaving the PvP Arena!"
			wait 1 ticks
			heal the player
			make console execute command "/spawn %player%"
			make console execute command "/ci %player%"
			make console execute command "/scoreboard players reset %player%"
			stop

But whenever I reload the script, I get this error message:

 "Cant compare a player with 'in world "Arena"'

This happens three other times in the script

I am using dev27 and spigot 1.8.8(I can't update my server to another version of minecraft)

**Comment by Pikachu920** [comment]
Version info?

**Comment by xMarkbom** [comment]
I am using dev27 and spigot 1.8.8(I can't update my server to another version of minecraft)

**Comment by Pikachu920** [comment]
Probably not related to the fact you're on 1.8, but you should know 1.8 isn't supported on this fork and in fact doesn't even work with the newest versions

**Comment by melinstagibson** [comment]
try
player is in "world"
that worked for me

**Comment by Pikachu920** [comment]
Yeah, that's what is on the njol docs but its weird there isn't an option "world" in that syntax to match `player is not in world`... maybe it should be added

**Comment by melinstagibson** [comment]
Yeah well.. the docs.... :/

**Comment by bensku** [comment]
It would be useless to fix 1.8 issues as latest version doesn't work with 1.8 anyway.
