### ISSUE TITLE
Table names in sql

### ISSUE THREAD

**Issue by Adrihun** [bensku/Skript#688]
@bensku Could you please add the feature to change the name of the table in SQL or send me a 
2.2 dev 25 version that has the table name changed to just **variables** ?

**Comment by Snow-Pyon** [comment]
Stop asking for this. And I really doubt he will do a version just for you, less if you're using an old version.

**Comment by Adrihun** [comment]
**Nevermind!** 

I successfully edited the class files in the variables folder inside Skript.jar, and I have renamed "variables21" to "variables" with dirtyJoe.

**Comment by TheBentoBox** [comment]
Seriously, don't open an issue for something you already have an issue for.

**Comment by bensku** [comment]
@Adrihun What you are doing is extremely dangerous and could destroy your data if I change variable storage implementation. You have been warned...

**Comment by Adrihun** [comment]
Bensku, It's fine if you change it 

I have multiple backups of my servers & databases, so if something happens, i can easily restore the data

**Comment by Adrihun** [comment]
update: after i changed the classes it kinda broke, it sometimes wont generate a new table, sometimes say "old variable" at startup, etc.

**Comment by Snow-Pyon** [comment]
That's what you get for touch something you don't know, bensku warned you about it.

**Comment by TheBentoBox** [comment]
Love how you were warned, replied that it was ok to the plugin developer, then within 5 hours replied again with issues.

**Comment by Pikachu920** [comment]
Adrihun:
>Bensku, It's fine if you change it
Also Adrihun:
>after i changed the classes it kinda broke

**Comment by Adrihun** [comment]
He might be able to do it better than be because he actually has the SRC and can change it with Eclipse, While i'm here using random programs to edit .class files inside of the .jar, I don't think i even changed **all** of the **variables21** inside the jar

**Comment by Pikachu920** [comment]
You also actually have the source, it's on here.

**Comment by Snow-Pyon** [comment]
he can't do that, it would break other people's databases. As you said it could be done with a config option and `variables21` would be the default value but as said that will not be easy and I doubt it'll happen anytime soon.
