### ISSUE TITLE
Saturation can be applied but not removed

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#692]
![](https://i.imgur.com/NGXJFjl.png)

(tested without addons)

**Comment by aescraftbr** [comment]
Can confirm. Happens in 1.12 too.

**Comment by bensku** [comment]
Saturation has two different meanings with Minecraft. Yeah, it is a potion effect, *but* also an attribute of player. Skript treats saturation as the latter, so I'm quite surprised that even applying it (potion effect) worked.

**Comment by silencercomes** [comment]
I found a workaround on that: if you add an additional alias for saturation in /src/main/resources/lang/english.lang, e.g. 
`saturation: saturation, saturationeffect`
Skript can correctly understand the condition and works as expected:
I tested that in 1.12 with the following code:
`apply saturation to player for 10 minutes`
`wait 10 seconds`
`remove saturationeffect from player`

hope that helps :)

**Comment by TheLimeGlass** [comment]
@Snow-Pyon Close?
