### ISSUE TITLE
Error loading inventory

### ISSUE THREAD

**Issue by theLMGN** [bensku/Skript#695]
Code: `restore inventory of player from {kits::%arg 1%::kit}`

Variable.csv http://www.thelmgn.xyz/2017/06/2017-06-28_21-04-15.txt

Error java.lang.IllegalArgumentException: Chests must have a size that is a multiple of 9!
Full Trace http://www.thelmgn.xyz/2017/06/2017-06-28_21-04-37.txt

**Comment by Pikachu920** [comment]
This is not a skript issue

**Comment by TheBentoBox** [comment]
This is an issue with SkQuery, not Skript.
