### ISSUE TITLE
Onload Error! [Please Help]

### ISSUE THREAD

**Issue by CollierPlaysMC** [bensku/Skript#699]
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! End of Error.
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! Thread: Server thread
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! Current item: null
30.06 13:38:40 [Server] ERROR #!#! Current node: {killaura.%player%}: 0 (Tesla.sk, line 233)
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! Running CraftBukkit: false
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.13.1.el6.x86_64
30.06 13:38:40 [Server] ERROR #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
30.06 13:38:40 [Server] ERROR #!#!   Minecraft: 1.8
30.06 13:38:40 [Server] ERROR #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
30.06 13:38:40 [Server] ERROR #!#!   Skript: 2.2-dev23
30.06 13:38:40 [Server] ERROR #!#! Version Information:
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656)
30.06 13:38:40 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
30.06 13:38:40 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919)
30.06 13:38:40 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058)
30.06 13:38:40 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625)
30.06 13:38:40 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
30.06 13:38:40 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:167)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:271)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:407)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:68)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:85)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:1)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:415)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:337)
30.06 13:38:40 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
30.06 13:38:40 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
30.06 13:38:40 [Server] ERROR #!#! Stack trace:
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
30.06 13:38:40 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
30.06 13:38:40 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
30.06 13:38:40 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
30.06 13:38:40 [Server] ERROR #!#! and check whether this error has already been reported.
30.06 13:38:40 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
30.06 13:38:40 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:40 [Server] ERROR #!#! Could not load Tesla.sk
30.06 13:38:40 [Server] ERROR #!#! [Skript] Severe Error:
30.06 13:38:40 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! End of Error.
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! Thread: Server thread
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! Current item: null
30.06 13:38:14 [Server] ERROR #!#! Current node: {killaura.%player%}: 0 (Tesla.sk, line 233)
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! Running CraftBukkit: false
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.13.1.el6.x86_64
30.06 13:38:14 [Server] ERROR #!#!   Java: 1.8.0_121 (Java HotSpot(TM) 64-Bit Server VM 25.121-b13)
30.06 13:38:14 [Server] ERROR #!#!   Minecraft: 1.8
30.06 13:38:14 [Server] ERROR #!#!   Bukkit: 1.8-R0.1-SNAPSHOT
30.06 13:38:14 [Server] ERROR #!#!   Skript: 2.2-dev23
30.06 13:38:14 [Server] ERROR #!#! Version Information:
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656)
30.06 13:38:14 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
30.06 13:38:14 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919)
30.06 13:38:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058)
30.06 13:38:14 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625)
30.06 13:38:14 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
30.06 13:38:14 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:145)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.Skript.reloadScripts(Skript.java:694)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:201)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:247)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:407)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:68)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.util.StringUtils.replaceAll(StringUtils.java:85)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:1)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader$2.run(ScriptLoader.java:415)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:337)
30.06 13:38:14 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:242)
30.06 13:38:14 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
30.06 13:38:14 [Server] ERROR #!#! Stack trace:
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
30.06 13:38:14 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
30.06 13:38:14 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
30.06 13:38:14 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
30.06 13:38:14 [Server] ERROR #!#! and check whether this error has already been reported.
30.06 13:38:14 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
30.06 13:38:14 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
30.06 13:38:14 [Server] ERROR #!#! 
30.06 13:38:14 [Server] ERROR #!#! Could not load Tesla.sk
30.06 13:38:14 [Server] ERROR #!#! [Skript] Severe Error:
30.06 13:38:14 [Server] ERROR #!#!

**Comment by CollierPlaysMC** [comment]
i am a server admin ... not the dev.

**Comment by TheBentoBox** [comment]
You're using an old version of Skript, and newer versions aren't compatible with 1.8 or below anymore. We can't provide support for people on old versions and you won't be unable to update to the newest version because your server version is so old, so your best bet is to update to dev25 (the newest most stable version that works on 1.8). Past that we can't help you.
