### ISSUE TITLE
Skript needs support for new mobs

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#7]
Skript needs support for the new mobs. For example zombie and skeletal horses.

If you spawn a skeletal horse:
/summon EntityHorse ~ ~ ~ {Type:4}

```
on spawn:
  broadcast " DEBUG: %event-entity%"
```

Will give you "horse" for all the different subtypes. So if for example you wish to stop skeletal horses from spawning you cannot do it without preventing all the horses from spawning as well.

Also I'm not sure but it would seem Skript is not showing "donkey" or "mule" either when they spawn.

**Comment by bensku** [comment]
Yeah - new "simple" mobs (shulkers) are added, but horse types are not supported and I have no idea how Skript handles this sort of things (if it handles them at all...).

**Comment by bensku** [comment]
Partial horse support added, better support would require way too many changes to entity system.

**Comment by bensku** [comment]
And so much later, 1.11 has at least somehow solved *this* issue.
