### ISSUE TITLE
Very annoying villager trade issue

### ISSUE THREAD

**Issue by UltraFaceguy** [bensku/Skript#70]
The below code fails when the player had any item in their offhand slot:

on right click on entity:
__entity is not a villager:
____exit
__remove swiftness from the player
__remove haste from the player
__apply swiftness 1 to the player for 3 minutes
__apply haste 2 to the player for 3 minutes
__cancel event

This is super annoying for using villagers as NPCs and for disabling trades. Because it straight up doesn't work for the half of players who have something in the offhand.

**Comment by TheBentoBox** [comment]
I've recently noticed this issue with other things as well - I have Skript powered buy signs in my server shop, and they just don't work at all if the player's mainhand is empty and offhand is holding something, the click event just doesn't fire.

**Comment by bensku** [comment]
Hmm, I'll look at this. Not sure if will be fixed in next release, though...

For me, clicking entities - regardless what I have in my hand - works. Maybe just villagers?

**Comment by bensku** [comment]
I think I have fixed the bug with signs - however, it is quite possible that 1.9.4 broke something else.

With villagers, I still have no idea what is wrong.
