### ISSUE TITLE
Error reloading a skript

### ISSUE THREAD

**Issue by ThePraZ** [bensku/Skript#702]
When I reload a specific skript or start my server, it stops. The skript take too much time to reload

Before I add like 20 lines to the skript, it tooks like 30 seconds to reload, but after add the 20 lines, it makes the server stops, please, help me.

Im using skript 2.1.2 and spigot 1.8

The skript have 4616 lines (There are a lot of lines disabled)

**Comment by melinstagibson** [comment]
Gold Luck.... :/

**Comment by Syst3ms** [comment]
1.8 is not supported anymore.

**Comment by TheBentoBox** [comment]
Make your script shorter or split it up over multiple scripts.
