### ISSUE TITLE
New expression: is sheared

### ISSUE THREAD

**Issue by YellowZaki** [bensku/Skript#704]
Could you add a new expression for sheeps so we can now if the sheep is sheared?

**Comment by Snow-Pyon** [comment]
Just check `if entity is sheared sheep`.

**Comment by YellowZaki** [comment]
It doesn't work.

**Comment by YellowZaki** [comment]
Ok, now works with unsheared sheep.

**Comment by Snow-Pyon** [comment]
What? That's a bug, `unsheared sheep` should be a normal sheep with wool @bensku.

**Comment by YellowZaki** [comment]
Noo, it works fine.
