### ISSUE TITLE
%yaw of player% and %pitch of player% is not working! Don't change every value is 0.

### ISSUE THREAD

**Issue by Pledix** [bensku/Skript#707]
%yaw of player% and %pitch of player% is not working! Don't change every value is 0.
I don't get error the console. Just value is every 0. Don't change.

**Comment by TheBentoBox** [comment]
Duplicates #384, this is an issue with Spigot, not Skript: it doesn't update yaw/pitch until the mob moves. If that's not what you're talking about, then I cannot reproduce this otherwise, and you've provided no helpful information like server/Skript version, so...

**Comment by Pledix** [comment]
My Skript version is latest version!
2.2-dev29
