### ISSUE TITLE
Vault 1.5.6 is not working with Skript (2.2. dev29 latest version)

### ISSUE THREAD

**Issue by Pledix** [bensku/Skript#709]
Vault 1.5.6 is not working with Skript (2.2. dev29 latest version)

I get this error in console.
http://imgur.com/Fv8TxiO

**Comment by TheBentoBox** [comment]
Can't confirm on my end. What version is your server?

**Comment by Pledix** [comment]
Spigot 1.12

**Comment by bensku** [comment]
Cannot reproduce, works for me too.
