### ISSUE TITLE
Won't run at all?

### ISSUE THREAD

**Issue by minemidnight** [bensku/Skript#71]
`03.05 16:01:49 [Server] INFO minemidnight issued server command: /sk reload essentials.sk
03.05 16:01:49 [Server] ERROR null
03.05 16:01:49 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'sk' in plugin Skript v2.2-dev13d
03.05 16:01:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
03.05 16:01:49 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
03.05 16:01:49 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class ch.njol.skript.SkriptConfig
03.05 16:01:49 [Server] INFO at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:349) ~[?:?]
03.05 16:01:49 [Server] INFO at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:272) ~[?:?]
03.05 16:01:49 [Server] INFO at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:155) ~[?:?]
03.05 16:01:49 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
03.05 16:01:49 [Server] INFO ... 15`

**Comment by minemidnight** [comment]
Bump

**Comment by bensku** [comment]
What version are you using? Latest?

Anyway, please update your Spigot and make sure that you DO NOT use /reload. And please use Java 8 if you don't already, too.

**Comment by minemidnight** [comment]
I restarted, minecraft 1.8, any spigot version reccomended and I do use Java 8.

**Comment by minemidnight** [comment]
bump, this is pretty urgent @bensku

**Comment by bensku** [comment]
Hmm, in SkUnity forums it is clearly mentioned that 1.8 is not supported. I'll add that here, too.

About the bug, well, I'll see if I can fix it. Not high priority since it is 1.8, though.

**Comment by minemidnight** [comment]
Sorry, also last time I asked it was said it was 1.8 supported with something like "I don't see why not" said

**Comment by bensku** [comment]
Hmm, I was saying "yeah it should work". And it really should, but if it does not, I don't have time to fix it very fast.

Please try latest version (and redownload the jar), and latest Spigot, too. Maybe it'll help...

**Comment by bensku** [comment]
Still an issue? Skript command handling was changed a bit in last release.
