### ISSUE TITLE
Problem with Elemental Monsters spigot plugin 

### ISSUE THREAD

**Issue by Grippy19** [bensku/Skript#711]
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! End of Error.
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! Thread: Server thread
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! Current item: null
07.07 15:55:43 [Server] ERROR #!#! Current node: function spawn_demon(loc: location): (emobs.sk, line 73)
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! Running CraftBukkit: false
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#!   OS: Linux amd64 2.6.32-642.6.2.el6.x86_64
07.07 15:55:43 [Server] ERROR #!#!   Java: 1.8.0_111 (Java HotSpot(TM) 64-Bit Server VM 25.111-b14)
07.07 15:55:43 [Server] ERROR #!#!   Minecraft: 1.12
07.07 15:55:43 [Server] ERROR #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
07.07 15:55:43 [Server] ERROR #!#!   Skript: 2.2-dev29
07.07 15:55:43 [Server] ERROR #!#! Version Information:
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#!     at java.lang.Thread.run(Unknown Source)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:366)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:695)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
07.07 15:55:43 [Server] ERROR #!#!     at java.util.concurrent.FutureTask.run(Unknown Source)
07.07 15:55:43 [Server] ERROR #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:9)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(SourceFile:37)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1186)
07.07 15:55:43 [Server] ERROR #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1326)
07.07 15:55:43 [Server] ERROR #!#!     at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:622)
07.07 15:55:43 [Server] ERROR #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
07.07 15:55:43 [Server] ERROR #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:161)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.Skript.reload(Skript.java:722)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadStructures(ScriptLoader.java:517)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadStructure(ScriptLoader.java:555)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.lang.function.Functions.loadSignature(Functions.java:172)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfoFromUserInput(Classes.java:335)
07.07 15:55:43 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
07.07 15:55:43 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
07.07 15:55:43 [Server] ERROR #!#! Stack trace:
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
07.07 15:55:43 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
07.07 15:55:43 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
07.07 15:55:43 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy &amp; paste this whole error into it (or use paste service),
07.07 15:55:43 [Server] ERROR #!#! and check whether this error has already been reported.
07.07 15:55:43 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
07.07 15:55:43 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
07.07 15:55:43 [Server] ERROR #!#! 
07.07 15:55:43 [Server] ERROR #!#! Could not load emobs.sk
07.07 15:55:43 [Server] ERROR #!#! [Skript] Severe Error:
07.07 15:55:43 [Server] ERROR #!#! 

PLEASE HELP

**Comment by TheBentoBox** [comment]
What are the contents of that function?

**Comment by TheBentoBox** [comment]
No response, closing for now unless you can provide more info or tell us how to reproduce this.
