### ISSUE TITLE
Could not hook into Vault. This can happen if Skript doesn't support the installed version of Vault

### ISSUE THREAD

**Issue by Pledix** [bensku/Skript#715]
I get error:
`[Server thread/ERROR]: [Skript] Could not hook into Vault. This can happen if Skript doesn't support the installed version of Vault`

Server version:
`This server is running Paper version git-Paper-1142 (MC: 1.12)`

Skript version:
`Latest version (2.2 dev29)`

Vault version:
`Latest version (1.6.1)`

**Comment by bensku** [comment]
Vault needs an economy/chat plugin installed to work. I updated to latest Vault, it worked perfectly once I added an economy plugin.
