### ISSUE TITLE
Item Number Glitch

### ISSUE THREAD

**Issue by caldersprinkle** [bensku/Skript#717]
Using this code, two items disappear from the hopper in some situations.

```
On piston extend:
	block 1 meter above is hopper
	loop all items in block above:
		block above contains concrete:0
		remove 1 concrete:0 from block above
		cancel event
		data value of block is 5:
			set block 1 meter east to concrete:0
		data value of block is 4:
			set block 1 meter west to concrete:0
		data value of block is 3:
			set block 1 meter south to concrete:0
		data value of block is 2:
			set block 1 meter north to concrete:0
```

When a piston is activated, 2 concrete are taken from the hopper. If you break the concrete while the piston is still powered, it takes two more and places another concrete, BUT if you deactivate and reactivate the piston without breaking the concrete and leaving it there, only one item is taken. Can this be fixed? Is this a plugin error or my bad scripting?

**Comment by TheBentoBox** [comment]
It's your bad scripting, you're removing 1 concrete for every stack of concrete in the hopper. There's no reason to be doing `loop all items` at all, just remove that line and un-indent the rest and it should improve it.

Also, if you're not sure if something's a bug or your own code in the future, you'd do better to ask on skUnity first. This isn't a help forum. Additionally, take a look at the source of your post by clicking the edit button on it; you hadn't formatted your code correctly, so I fixed it (you need three ` tick marks on the lines above and below your code block, it's on the same key as ~).

A better finalized script would probably look more like:
```
on piston extend:
	block 1 meter above is hopper
	block above contains concrete:0
	remove 1 concrete:0 from block above
	cancel event
	set block 1 meter in front event-block to concrete:0
```

**Comment by caldersprinkle** [comment]
This did absolutely nothing to fix the problem, it only condensed some of my lines of code. This code you suggested was the code I used before I realized that the hopper lost 2 items instead of one when the block was placed.

On Jul 10, 2017, at 6:30 PM, Jake Ben-Tovim <notifications@github.com> wrote:

It's your bad scripting, you're removing 1 concrete for every stack of concrete in the hopper. There's no reason to be doing loop all items at all, just remove that line and un-indent the rest and it should improve it.

Also, if you're not sure if something's a bug or your own code in the future, you'd do better to ask on skUnity first. This isn't a help forum. Additionally, take a look at the source of your post by clicking the edit button on it; you hadn't formatted your code correctly, so I fixed it (you need three ` tick marks on the lines above and below your code block, it's on the same key as ~).

A better finalized script would probably look more like:

on piston extend:
	block 1 meter above is hopper
	block above contains concrete:0
	remove 1 concrete:0 from block above
	cancel event
	set block 1 meter in front event-block to concrete:0

**Comment by TheBentoBox** [comment]
You should do some debug then, because I can't reproduce this. There's a fair possibility something is causing the event to fire twice, e.g. it's receiving power from multiple places or something due to the intricacies of how Spigot (and therefore Skript) handles and fires the event. Try adding a broadcast to see if it's firing multiple times or something of that nature, and if so that may give a way to see what the underlying issue is (whether it's Skript's fault or not).

**Comment by caldersprinkle** [comment]
It is firing twice.

Proof: I added a drop 1 TNT to the code and it dropped two, where as I added a code so that right clicking on grass would drop a stick, and it only dropped one. Exact same numbers, two different results.

**Comment by bensku** [comment]
Unlikely that it is a Skript issue.
