### ISSUE TITLE
can't use any script even default

### ISSUE THREAD

**Issue by yong24k** [bensku/Skript#720]
on 1.12

when i try to test default skript,

it doesnt understand event such as 'on chat'

what do i do?

**Comment by TheBentoBox** [comment]
Well, we need more information since clearly this issue isn't affecting everyone. What version of Skript are you running? And what specific Spigot version? You can see these with `/ver Skript` and `/ver` respectively. It would also be useful to know what addons you have.

**Comment by Pikachu920** [comment]
More than likely you're running Craftbukkit. If you are, you should know Skript doesn't support Craftbukkit and you should be using Spigot.

**Comment by TheBentoBox** [comment]
No response, hopefully what @Pikachu920 said resolved your issue.
