### ISSUE TITLE
Error trying to broadcast "&d#..."

### ISSUE THREAD

**Issue by MinecraftSBC** [bensku/Skript#724]
`broadcast "&d# # # # # # # # # # # # # # # # # # # # # # # # #"`
throws an exception:
`Invalid use of quotes ("). If you want to use quotes in "quoted text", double them: '"`

However, this effect statement works in effect commands.

**Comment by Snow-Pyon** [comment]
Yes, as you can't put comments on effect commands. Just put it twice, it should look like this:
```
broadcast "&d## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ##"
```

**Comment by MinecraftSBC** [comment]
@Snow-Pyon That worked. Thanks.
