### ISSUE TITLE
Loop All Players Error

### ISSUE THREAD

**Issue by xErtern** [bensku/Skript#726]
So on my server when I try to loop all players in a skript it gives me this error. I'm running dev29 on a 1.12 spigot server.

12.07 15:56:51 [Server] WARN [Skript] Task #62 for Skript v2.2-dev29 generated an exception
12.07 15:56:51 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
12.07 15:56:51 [Server] INFO at ch.njol.skript.entity.EntityData.getAll(EntityData.java:455) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:146) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.expressions.ExprEntities.get(ExprEntities.java:1) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:103) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.lang.util.SimpleExpression.iterator(SimpleExpression.java:306) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.expressions.ExprEntities.iterator(ExprEntities.java:211) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.lang.Loop.walk(Loop.java:79) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.lang.Trigger.execute(Trigger.java:55) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.events.EvtPeriodical.execute(EvtPeriodical.java:90) ~[?:?]
12.07 15:56:51 [Server] INFO at ch.njol.skript.events.EvtPeriodical$1.run(EvtPeriodical.java:104) ~[?:?]
12.07 15:56:51 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.jar:git-Spigot-7228328-af1c013]

**Comment by Snow-Pyon** [comment]
Are you sure it's a Spigot server and not a Craftbukkit one? Do `/about` and tell us the output.

**Comment by bensku** [comment]
Can anyone reproduce?

**Comment by xErtern** [comment]
Here's my /about output and all the plugins I have on my server.
https://gyazo.com/344362119e99d13dd0096496f22e33cf

**Comment by xErtern** [comment]
I just deleted WildSkript and updated my SkQuery and it works now. Thanks though.
