### ISSUE TITLE
On right click on dropped item

### ISSUE THREAD

**Issue by PheonBest** [bensku/Skript#727]
Hi ! Isn't it possible to make the followed event: on right click on dropped item
The entity type of an item is dropped item but when i click on it (and not WITH it) the event doesn't work :/
I hope it will be possible in the next Skript's version <3

**Comment by TheBentoBox** [comment]
Dropped items don't even throw click events because they have no collision box; it's not a limitation of Skript, it's just how the game works. Just use a generic `on right click` event instead and then check if the `player's target` is a dropped item. It'll essentially work the same.
