### ISSUE TITLE
SkQuery 1.12

### ISSUE THREAD

**Issue by Fargus5** [bensku/Skript#728]
Hi, I have this error:= when I add SkQuery 1.7-1.12 version...
Maybe you have an update of skquery? or did you know what is the problem?

`11:18:28 CONSOLE: ERROR]: Parameters:
11:18:28 CONSOLE: a=0
11:18:28 CONSOLE: b=[1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 1xtile.air@0, 10xtile.dropper@0, 1xtile.air@0, 5xtile.woodSlab@0, 1xtile.stairsStoneBrickSmooth@0, 1xtile.torch@0, 1xitem.record@0, 1xtile.stone@0, 1xtile.air@0, 1xitem.hatchetWood@0, 1xtile.air@0]`

**Comment by Syst3ms** [comment]
This is only about Skript itself, not addons. Go to skUnity or its discord for add-on help.

**Comment by Fargus5** [comment]
I tried but the skunity forum doesn't work.

A lot of download are broken... for example if I go here: https://www.skunity.com/SkQuery the download doesn't work.

**Comment by Syst3ms** [comment]
try using http instead of https for he forum. Also, downloads on skUnity are outdated.

**Comment by Syst3ms** [comment]
Also, how does it "doesn't work" ?

**Comment by Fargus5** [comment]
try your self... XD

and I have not to change https in http it's automaticcaly this...
try your self to download something and you will see... anyway for everyone it's a very disaster to find on the web update for any resources of skunity... this becouse downloas are broken, as u can see for skquery... howewer about the thread do you know what it could be?
to write in the skunity forum u have to register, i don't want to make the 4100th registration only to write a simple report .

**Comment by Syst3ms** [comment]
Works perfectly for me : http://imgur.com/a/HMHic. And the version on skunity.com/skQuery is outdated, it is not the latest.

**Comment by Fargus5** [comment]
so you confirm what I told...

that https://www.skunity.com/SkQuery doesn't work...
I found this https://forums.skunity.com/resources/unofficial-skquery-fork-1-6-1-12.68/ 

but is unofficial...

skunity need a big big fix and update. becouse a lot of people from spigot has a lot of difficulty to finds updates for avery addon on skript... also for skript it's difficult... many people doesn't know your github name... and if you try to find skript on google you are not directly redirect here

**Comment by Syst3ms** [comment]
There is no officially updated version because the original dev calls his add-on dipshit now. Also, why does it being "unofficial" matter ?

**Comment by Syst3ms** [comment]
This discussion should have never existed to close.

**Comment by Fargus5** [comment]
it has started about the issue

**Comment by Syst3ms** [comment]
The discussion should have never existed because this is not about addons, only vanilla Skript, and even less about skUnity. Dot.
