### ISSUE TITLE
Errors in biomes

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#73]
I went through and tested **all** the biomes with //setbiome and then tested what Skript shows as the biome:

```
command /biometest:
  trigger:
    send " Biome: %biome at location of player%" to player
```

I found some errors:

In the Spigot javadocs in biomes enum the code shows having both "jungle_hills" and "mutated_jungle".

//setbiome mutated_jungle ---> results in Skript showing the biome as jungle hills.
//setbiome jungle_hills ---> results in Skript showing the biome as nothing.

//setbiome mutated_mesa -> results in Skript showing the biome as “Hoodoos” I have never read of it or heard of it. Is this correct? Shouldn't it be "Mesa (Bryce)"?

//setbiome mutated_mesa_clear_rock ---> result in Skript showing the biome as nothing.
//setbiome mutated_mesa_rock ---> result in Skript showing the biome as nothing.

//setbiome roofed_forest_hills ---> result in Skript showing the biome as "biomes.roofed_forest_hills" (missing support).

//setbiome redwood_taiga_hills ---> result in Skript showing the biome as "biomes.META_taiga_hills", ie. missing support/spelling error (meta instead of mega).

//setbiome void ---> result in Skript showing the biome as "void biome", which I'm not sure if it's intentional or not.

AFAIK all the rest of the biomes were working properly unless I missed something.

**Comment by bensku** [comment]
Mutated mesa is due to Skript having wrong order in lang file entry. Should have checked that earlier...

**Comment by bensku** [comment]
Fixed in next release.
