### ISSUE TITLE
Contains require literals

### ISSUE THREAD

**Issue by MinecraftSBC** [bensku/Skript#731]
`%text% contains %text%` does not work with text variables, such as
`if loop-value contains {StringVar}:`
however, it does work with string literals, such as
`if "%loop-value%" contains "%{StringVar}%"`

**Comment by Syst3ms** [comment]
What version of Skript and Minecraft are you using ?

**Comment by MinecraftSBC** [comment]
Minecraft 1.11.2, Skript version dev29c.

**Comment by bensku** [comment]
Hm, this is probably due to type of variable not being known, while string literal is always a string.

**Comment by Pikachu920** [comment]
This wasn't always the case, I think this should be marked bug. if my memory serves right, loop-value was treated like variables (assumed to be right)

**Comment by Syst3ms** [comment]
No. A loop-value is an expression like another.

**Comment by MinecraftSBC** [comment]
I think it doesn't work on normal strif variables too. Mind reproducing?

**Comment by bensku** [comment]
Got hit by unexpected amount of spaghetti code while trying to fix this. I got it fixed, but the fix could break other things...

**Comment by bensku** [comment]
Fixed. I hope I didn't break literally everything else along the way. Initial tests with @Snow-Pyon have been promising - worst issues were not even related to this change.
