### ISSUE TITLE
An internal error occurred while attempting to perform this command.

### ISSUE THREAD

**Issue by SchmiddyTV** [bensku/Skript#736]
Hello, I've got an error, when i want to start with json skript's.

When i send the command i will get this message:
An internal error occurred while attempting to perform this command.
https://pastebin.com/zFwDp0gj

**Comment by Syst3ms** [comment]
Addon issue.

**Comment by SchmiddyTV** [comment]
Which one?

**Comment by Syst3ms** [comment]
skQuery. Don't ask me how to fix it. To close.
