### ISSUE TITLE
Cannot get lore of items

### ISSUE THREAD

**Issue by Gamebuster19901** [bensku/Skript#738]
In Skript v2.2-dev29; lore of ITEM returns none even if the lore of the item is set

```
on right click:
	message "lore: ""%lore of event-item%""" to player
```

**Comment by Gamebuster19901** [comment]
It appears that you can use "Line x of ITEM's lore" as a workaround.

**Comment by Snow-Pyon** [comment]
And that's how it should be? Plus, you might be confusing Skript's lore expression (which never worked well) with skQuery's one.

**Comment by Gamebuster19901** [comment]
No, it should return the items full lore with newline characters if it has multiple lines. This was tested on a clean install without any addons, and it still compiles. If it is not intended to work, it should throw an error.

**Comment by bensku** [comment]
In my opinion it should return list of lore lines instead of one text, but none is definitely not correct.

**Comment by Gamebuster19901** [comment]
Yes, currently, if you use "if ITEM's lore is set" it will always return false.

**Comment by melinstagibson** [comment]
shouldnt this be closed by now? i have no issues with lore of event-item in dev30d, not even with the exact same code posted.

**Comment by bensku** [comment]
Oh, that is interesting. Maybe it was a parser bug which got fixed. Anyway, I'll need to test this too.

**Comment by Gamebuster19901** [comment]
Appears to be fixed in dev30d
