### ISSUE TITLE
Skript flat out doesn't work

### ISSUE THREAD

**Issue by LandonPlayz2** [bensku/Skript#742]
I am running Spigot 1.8.8 R0.1 SNAPSHOT.

When I reload a skript, it says a bunch of errors like:

cant understand this event: "on right click:"

and basic things like that.

Console Errors:
`22.07 18:14:35 [Server] ERROR #!#! 
22.07 18:14:35 [Server] ERROR #!#! [Skript] Severe Error:
22.07 18:14:35 [Server] ERROR #!#! Could not load ItemShop.sk
22.07 18:14:35 [Server] ERROR #!#! 
22.07 18:14:35 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
22.07 18:14:35 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
22.07 18:14:35 [Server] ERROR #!#! and check whether this error has already been reported.
22.07 18:14:35 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
22.07 18:14:35 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
22.07 18:14:35 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
22.07 18:14:35 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
22.07 18:14:35 [Server] ERROR #!#! 
22.07 18:14:35 [Server] ERROR #!#! Stack trace:
22.07 18:14:35 [Server] ERROR #!#! java.lang.IllegalStateException: Cannot use classinfos until registration is over
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.checkAllowClassInfoInteraction(Classes.java:240)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.getClassInfos(Classes.java:245)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:414)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.registrations.Classes.parse(Classes.java:449)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:385)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:445)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1159)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:219)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:174)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.lang.Statement.parse(Statement.java:59)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:659)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.command.Commands.loadCommand(Commands.java:465)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:409)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:243)
22.07 18:14:35 [Server] ERROR #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:200)`

**Comment by TheBentoBox** [comment]
This fork doesn't support 1.8.

**Comment by LandonPlayz2** [comment]
Is there a skript version that works for 1.8?

**Comment by TheBentoBox** [comment]
You can try downgrading to version dev25 of this fork, or searching for Skript 2.2 v8b.
