### ISSUE TITLE
"The loader method"

### ISSUE THREAD

**Issue by rplcnn** [bensku/Skript#744]
dear bensku, 

> ScriptLoader.loadScripts(file);

 method was working well in dev23+, but i tried that in dev29 it didn't work. can you add the method again? thanks. it is important because im loading language files with that.

**Comment by Snow-Pyon** [comment]
It's still a method but it doesn't use a File object anymore but a Config one.

**Comment by bensku** [comment]
It takes config because parsing config file twice is stupid. Might be good idea to add helper method for compatibility, though.

**Comment by rplcnn** [comment]
`    protected void execute(Event event) {
        String d = this.dir.getSingle(event);
        if (d == null) {
            return;
        }

        d = d.replaceAll("/", Matcher.quoteReplacement(File.separator));
        File file = new File(d);
        if (!file.isFile()) {
            ScriptLoader.loadScripts(file);
        }`

**Comment by rplcnn** [comment]
`    protected void execute(Event event) {
        String d = this.dir.getSingle(event);
        if (d == null) {
            return;
        }

        d = d.replaceAll("/", Matcher.quoteReplacement(File.separator));
        File file = new File(d);
        if (!file.isFile()) {
            ScriptLoader.loadScripts(file);
        }`

**Comment by Snow-Pyon** [comment]
Just use the ScriptLoader#loadStructure method like this:
```
ScriptLoader.loadScripts(ScriptLoader.loadStructure(file));
```

**Comment by rplcnn** [comment]
Didn't work

**Comment by rplcnn** [comment]
@bensku

**Comment by bensku** [comment]
You're doing something wrong. The error doesn't even mention loadScripts method, it mentions loadScript one.

That being said, feel free to submit a pull request to fix this. I do wonder, though... Why would you load script files using Skript addon?

**Comment by rplcnn** [comment]
I fixed. Thanks @bensku
