### ISSUE TITLE
Proposal: Convert all variables to lists: make periods an alias for two colons in variables names.

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#745]
There are so many benefits to using lists variables (iteration, easy to delete, etc) and new Skript users notoriously never use them. They do, however, use periods to separate variable name components, so why not make `.` and alias for `::`?

It's good practice to use list variables everywhere, but unfortunately many Skript users are reluctant to convert their variables manually.

**Comment by Snow-Pyon** [comment]
Wouldn't it break stuff as:
```
add 1 to {single.var}
```

**Comment by RezzedUp** [comment]
Nope. Unless they named their variable `{single.*}` for some reason.

**Comment by Snow-Pyon** [comment]
It's fine then but I'm actually liking the idea. The main issue is that pretty much every Skript documentation uses the dot instead of a double colons and that makes people do it too. I would get a better documentation instead of doing this to be fair.

**Comment by TheBentoBox** [comment]
I guess this is an enhancement? We'll see what bensku has to say.

**Comment by bensku** [comment]
Good idea. The single biggest issue here is that bariable backend would need complete rewrite. Currently Skript has one big flat map for all variables... And bunch of maps which duplicate that data to allow looping variables.

This change would certainly break a lot of scripts and even more addons... But I do like it. Time will tell of I *implement* it though.

**Comment by bi0qaw** [comment]
Just stumbled over this. Don't implement this. It will break everything. Variable names rely heavily on points. Every time you use a `%object%` in your variable it is very likely that it will add some points to the variable name. All floating point numbers have points in them. Here some examples of how these variables can look like in the database:
``` 
"var::vector:1.2,3.5,5.5::key", string, 800576616C7565
var::ch.njol.skript.command.effectcommandevent@11474099, string, 80056576656E74
```

**Comment by RezzedUp** [comment]
This was a bad idea. 😅
