### ISSUE TITLE
Proposal or Don'tKnowHowToDoIt: Multiple CSV Files

### ISSUE THREAD

**Issue by PheonBest** [bensku/Skript#748]
Hi !
Is there a way to have multiple CSV Files please ? I would have one per server and one at the root:
**default** variables.csv in each server's folder and another database **bungee** bungeevariables.csv at the root.

I made that but variables aren't saved at all:
`	bungee:
		# The default "database" is a simple text file, with each variable on a separate line and the variable's name, type, and value separated by commas.
		# This is the last database in this list to catch all variables that have not been saved anywhere else.
		# You can modify this database freely, but make sure to know what you're doing if you don't want to loose any variables.
		
		type: CSV
		
		pattern: bungee.*
		
		file: ../bungeevariables.csv
		
		backup interval: 2 hours
		
		# PS: If you don't want some variables to be saved in any database (e.g. variables that contain an %entity% which usually despawn when the server is shut down)
		# you can modify the last database's pattern to not match all variables, e.g. use '(?!x_).*' to match all variables that don't start with 'x_'.
		# Be very cautious when doing this however as unsaved variables cannot be recovered after the server has been stopped.
		# I recommend to use a single character to denote unsaved variables (similar to local variables' '_'), e.g. '-', in which case the last database's pattern should be '(?!-).*'.
		
		# ==== Settings that should not be changed ====

	default:
		# The default "database" is a simple text file, with each variable on a separate line and the variable's name, type, and value separated by commas.
		# This is the last database in this list to catch all variables that have not been saved anywhere else.
		# You can modify this database freely, but make sure to know what you're doing if you don't want to loose any variables.
		
		type: CSV
		
		pattern: .*
		
		file: ./plugins/Skript/variables.csv
		
		backup interval: 2 hours
		
		# PS: If you don't want some variables to be saved in any database (e.g. variables that contain an %entity% which usually despawn when the server is shut down)
		# you can modify the last database's pattern to not match all variables, e.g. use '(?!x_).*' to match all variables that don't start with 'x_'.
		# Be very cautious when doing this however as unsaved variables cannot be recovered after the server has been stopped.
		# I recommend to use a single character to denote unsaved variables (similar to local variables' '_'), e.g. '-', in which case the last database's pattern should be '(?!-).*'.`

**Comment by bensku** [comment]
When you have this, does it cause bungee.* variables not get saved, variables not starting with it to not get saved or ALL variables not get saved?

**Comment by PheonBest** [comment]
bungee.* variables are saved in default variables.csv
Now it works with this pattern (for default database): (?!bungee).*
But i get strange things when i set some variables:
`# === Skript's variable storage ===
# Please do not modify this file manually!
#
# version: 2.2-dev29

bungee.age.pheonbest, string, 80096C656D617576616973

bungee.age.pheonbest, string, 800B767261696D656E74626F6E
bungee.age.pheonbest, string, 8006706173626F6E
`

**Comment by PheonBest** [comment]
Hi ! I made this but i cant't modify a file that is not in server's file (set line {_line} in file "../bungeevariables.csv" to ""):
`function Bungee(toCheck: String, variable: String, toSet: String):
	set {_split::*} to {_toCheck} split by ""
	broadcast "&b&l%{_toCheck}%"
	set {_letters} to size of {_split::*}
	broadcast "&b&l%{_letters}%"
	set {_letters} to {_letters} parsed as number
	reduce {_letters} by 2
	broadcast "&b&l%{_letters}%"
	set {_letters} to {_letters} parsed as number
	set {_file::*} to file contents of "../bungeevariables.csv"
	set {_line} to 0
	loop {_file::*}:
		broadcast "&a&l---------"
		broadcast "%loop-value%"
		set {_Compare} to decouper("%loop-value%", {_letters}, "")
		broadcast "%{_Compare}%"
		broadcast "%{_toCheck}%"
		broadcast "&a&l---------"
		if {_Compare} is equal to {_toCheck}:
			broadcast "&a&lA"
			set line {_line} in file "../bungeevariables.csv" to ""
			add 1 to {_line}
			exit loop
	set {%{_variable}%} to "%{_toSet}%"
	broadcast "%{_variable}%"
	broadcast "%{%{_variable}%}%"

command /text [<text>] [<text>]:
	trigger:
		if arg-1 is "set":
			Bungee("bungee.text.", "bungee.text.%player%", "%arg-2%")
			#set {bungee.age.%player%} to "%arg-2%"
			message "Bungee.Text set to %arg-2%"
		else if arg-1 is "see":
			message "%{bungee.text.%player%}%"
		else if arg-1 is "delete":
			delete {bungee.text.%player%}
command /textlist [<text>] [<text>]:
	trigger:
		if arg-1 is "add":
			add "%arg-2%" to {bungee.list.%player%::*}
			message "%arg-2% added to Bungee.Text.list"
		else if arg-1 is "see":
			message "%{bungee.text.list.%player%::*}%"
		else if arg-1 is "remove":
			remove "%arg-2%" from {bungee.text.list.%player%::*}
		else if arg-1 is "delete":
			delete {bungee.text.list.%player%::*}`

**Comment by bensku** [comment]
Ah yeah. CSV doesn't work well with multiple servers at same time.

**Comment by PheonBest** [comment]
Do you think it will be working in dev30 ? And if i was able to delete a variable from bungeevariables.csv by setting the variable's line to nothing (if i make "delete {bungee.variable}", the server where i deleted the variable can't use it but the second server can use it - AND the variable is not deleted from bungeevariables.csv -), will it work ?

Do you know if there is a way to have "bungee" variables (cross-servers) ?

-And I would so much know when will dev30 be released, if you're okay to tell it -

Thanks you for all you've already made for Skript's community and Skript itself <3

**Comment by bensku** [comment]
CSV will NOT work with multiple servers at same time. Other bugs, maybe.

Currently there is no reliable way to have cross-server variables. MySQL variable backend would do that, but it is not exactly reliable...

**Comment by melinstagibson** [comment]
Use MySQL just as a bridge and load its content in each servers local variables. 
Just avoid realtime calls from the DB
Even tho I never had problems doing that with a local DB. Its fast.

**Comment by bensku** [comment]
Thar's not the issue with MySQL+Skript. The issue is that variables are not deleted in MySQL storage, too large databases can freeze the server, and probably some more.

**Comment by PheonBest** [comment]
So what's the best idea to ave cross-variables (money, kills, games played, etc ...) ? MySQL can't be used currently and, if it's fix, it can freeze the server if the database is too large.
Wouldn't it be a nice idea to have csv for multiple servers ? Think about it please because it looks really cool :)
The best, if it's done, would to send bungee variables to mysql by a little plugin, and all will be quite easy.

Thanks you anyway.

**Comment by PheonBest** [comment]
Final: I'm sorry, you said no and i shall not continue to post. I'll make an addon request.
Bye !

**Comment by bensku** [comment]
You could use MySQL and hope it works. Or perhaps an addon to synchronize variables between multiple servers... Not trivial thing to do. Good luck with addon search.

If someone else reads this later, checn if variable storage on DB has been reworked since this post. It is on my TODO list.
