### ISSUE TITLE
Fishing rod in off-hand

### ISSUE THREAD

**Issue by WolfezzKyne** [bensku/Skript#75]
Using a fishing rod in off-hand-slot won't work with skript

**Comment by bensku** [comment]
Interact events do not work, or vanilla fishing doesn't work? And are you running latest Spigot?

**Comment by WolfezzKyne** [comment]
Only vanilla fishing rod, latest spigot, latest skript

**Comment by WolfezzKyne** [comment]
https://youtu.be/iU2eWQ9nsz8 - video of it to show you the issue

**Comment by bensku** [comment]
Ok, thanks for information. Will try to fix this soon.

**Comment by bensku** [comment]
This happens without Skript, so it has to be Spigot or Vanilla bug. Please report it to Spigot's bug tracker (if that has not been done yet).
