### ISSUE TITLE
2.1.2 open inventory to the player

### ISSUE THREAD

**Issue by Vibezz** [bensku/Skript#750]
#!#! at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:36)
#!#! at com.w00tmast3r.skquery.elements.expressions.ExprBlankInventories.get(ExprBlankInventories.java:14)
#!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:101)
#!#! at ch.njol.skript.lang.util.SimpleExpression.getSingle(SimpleExpression.java:61)
#!#! at ch.njol.skript.effects.EffOpenInventory.execute(EffOpenInventory.java:78)
#!#! at ch.njol.skript.lang.Effect.run(Effect.java:50)
#!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:63)
#!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:91)
#!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:53)
#!#! at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:220)
#!#! at ch.njol.skript.command.ScriptCommand$1.call(ScriptCommand.java:1)
#!#! at ch.njol.skript.util.Task.callSync(Task.java:139)
#!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:193)
#!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:260)
#!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:155)
#!#! at sun.reflect.GeneratedMethodAccessor179.invoke(Unknown Source)
#!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#!#! at java.lang.reflect.Method.invoke(Unknown Source)
#!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
#!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
#!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
#!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
#!#! at ch.njol.skript.Skript.dispatchCommand(Skript.java:935)
#!#! at ch.njol.skript.effects.EffCommand.execute(EffCommand.java:86)
#!#! at ch.njol.skript.lang.Effect.run(Effect.java:50)
#!#! at com.w00tmast3r.skquery.skript.LambdaEffect.walk(LambdaEffect.java:35)
#!#! at com.w00tmast3r.skquery.util.custom.menus.v2_.SlotRule.run(SlotRule.java:30)
#!#! at com.w00tmast3r.skquery.util.custom.menus.v2_.FormattedSlotManager.onClick(FormattedSlotManager.java:66)
#!#! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#!#! at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
#!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
#!#! at java.lang.reflect.Method.invoke(Unknown Source)
#!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
#!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
#!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
#!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
#!#! at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1630)
#!#! at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
#!#! at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
#!#! at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
#!#! at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
#!#! at java.util.concurrent.FutureTask.run(Unknown Source)
#!#! at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
#!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
#!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
#!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
#!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
#!#! at java.lang.Thread.run(Unknown Source)
#!#!
#!#! Version Information:
#!#! Skript: 2.1.2
#!#! Bukkit: 1.8.8-R0.1-SNAPSHOT
#!#! Minecraft: 1.8.8
#!#! Java: 1.8.0_45
#!#!
#!#! Running CraftBukkit: false
#!#!
#!#! Current node: null
#!#! Current item: open inventory to the player
#!#!
#!#! Thread: Server thread
#!#!
#!#! End of Error.

**Comment by TheBentoBox** [comment]
This is an SkQuery issue, and you're not even running our version of Skript (and you couldn't even if you wanted to since you're on 1.8). Go ask on the skUnity forums for help, this isn't the place.
