### ISSUE TITLE
Skript error

### ISSUE THREAD

**Issue by X3n0s** [bensku/Skript#752]
`27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! [Skript] Severe Error:

27.07 20:31:16 [Server] ERROR #!#! An error happened when trying to enably resolving offline players, so the feature has been turned off. Please report this at https://github.com/bensku/Skript/issues/237

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.

27.07 20:31:16 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/

27.07 20:31:16 [Server] ERROR #!#! and check whether this error has already been reported.

27.07 20:31:16 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),

27.07 20:31:16 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.

27.07 20:31:16 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.

27.07 20:31:16 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! Stack trace:

27.07 20:31:16 [Server] ERROR #!#! java.lang.NullPointerException: null offline player resolve queue

27.07 20:31:16 [Server] ERROR #!#! at ch.njol.skript.bukkitutil.UnresolvedOfflinePlayer$1.run(UnresolvedOfflinePlayer.java:59)

27.07 20:31:16 [Server] ERROR #!#!     at java.lang.Thread.run(Thread.java:748)

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! Version Information:

27.07 20:31:16 [Server] ERROR #!#!   Skript: 2.2-dev29

27.07 20:31:16 [Server] ERROR #!#!   Bukkit: 1.12-R0.1-SNAPSHOT

27.07 20:31:16 [Server] ERROR #!#!   Minecraft: 1.12

27.07 20:31:16 [Server] ERROR #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)

27.07 20:31:16 [Server] ERROR #!#!   OS: Linux amd64 3.10.0-514.21.2.el7.x86_64

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! Running CraftBukkit: false

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! Current node: null

27.07 20:31:16 [Server] ERROR #!#! Current item: null

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! Thread: Skript offline player resolver thread (fetches UUIDs from the minecraft servers)

27.07 20:31:16 [Server] ERROR #!#! 

27.07 20:31:16 [Server] ERROR #!#! End of Error.

27.07 20:31:16 [Server] ERROR #!#! `

**Comment by TheBentoBox** [comment]
Duplicates #237
