### ISSUE TITLE
Add the unix time expression

### ISSUE THREAD

**Issue by TrademarkTM** [bensku/Skript#753]
Hello people.
I'm suggesting this because it'd be way easier to use, and even easier to implement.

**Why?**
- It's a number, so you can do whatever you can do any sort of math with it.
- You wouldn't need to parse as date or anything like that.
- For cooldowns it would work a lot better, just a simple subtraction and it is done.
- If you want only minutes for example all you gotta do is divide by 60, without all the `1 hour, 3 minutes and 5 seconds`.
- Easier to store and manage.

It'd take a couple lines `long unix = Instant.now().getEpochSecond();` and will make date more versatile.
Made [this](https://gist.github.com/TrademarkTM/6375bb76e7e9c3ab177c705a8455d7ea) but it's not worth the 1 ms.

Hope you implement this!
Thanks!

**Comment by Snow-Pyon** [comment]
Please look at the docs before asking something like this, he already added it a while ago:
http://bensku.github.io/Skript/expressions.html#ExprUnixTime

**Comment by TrademarkTM** [comment]
Alright, sorry, I searched only in skUnity. Bug it seems not to work:

```
command /something:
	trigger:
		broadcast "%unix time of now%"

[08:19:57 INFO]: [Skript] # /something
[08:19:57 INFO]: 2017-07-28 08:19:57 BRT
[08:19:57 INFO]: [Skript] # something took 0.363203 milliseconds
```

Parsing as number:
```
[08:24:23 INFO]: [Skript] # /something
[08:24:23 INFO]: <none>
[08:24:23 INFO]: [Skript] # something took 0.519808 milliseconds
```

Also, it does not work in math correctly (I could use my unix function normally):
```
unix time of now - {cooldown} < 300

[08:21:35 ERROR]: Can't compare 'unix time of now - {cooldown}' with an integer (RuneEssentials.sk, line 31: unix time of now - {cooldown} < 300')
```

I know I can parse it, but as it's seconds since 1970, shouldn't it be a number?

Hope it can be fixed soon.
Thanks once again and sorry for the thread.

**Comment by bensku** [comment]
The existing expression is not seconds since epoch. Actually I don't recall why I named it so...

**Comment by TrademarkTM** [comment]
So.. could you add it in the next update?
Don't think it'll take more than 30 seconds to create this expression.

Thanks.

**Comment by bensku** [comment]
Next feature release, probably. But I try to avoid adding anything new to hotfixes to not introduce new bugs.
