### ISSUE TITLE
Herochat + Skript error in console

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#76]
http://hastebin.com/

I don't know what could be the problem!?

**Comment by bensku** [comment]
Umm, that paste is missing last part of ULR...

**Comment by bloggy** [comment]
Sorry!
Here the correct URL:
http://hastebin.com/kavedoyali.vbs

**Comment by bensku** [comment]
This might have been fixed by recent PR from @RoyCurtis. I merged it already, but next release was delayed by some parser changes.

**Comment by bensku** [comment]
So, was this fixed?

**Comment by bensku** [comment]
Assuming it is.
