### ISSUE TITLE
Disabling disable conflict warnings in addon.

### ISSUE THREAD

**Issue by rplcnn** [bensku/Skript#762]
Is there a method for disabling skript's conflict warnings from addon.

like Skript.getConfig().disableConflictWarnings

**Comment by bensku** [comment]
Could you elaborate? What conflict warnings?

**Comment by rplcnn** [comment]
[23:08:53] [Server thread/WARN]: [Skript] Possible name conflict of variables {now::%loop-value%} and {now::Minute} (there might be more conflicts). (SUPERGUILDS_main.sk, line 137: {_now::%loop-value%} contains "*0":')

**Comment by TheBentoBox** [comment]
That's already a setting:
```
disable variable conflict warnings: true
# Disables warnings of potential variable name conflicts if set to true.
```

**Comment by rplcnn** [comment]
@TheBentoBox Wtf I already know that. Im asking for Java code to do that.

**Comment by TheBentoBox** [comment]
Guess it's up to bensku if he wants to even discuss this but what good reason is there for an API to allow an addon to disable conflict warnings? Seems like it's asking for trouble, you're recommended to not even toggle that config setting.

**Comment by rplcnn** [comment]
@bensku

**Comment by TheBentoBox** [comment]
You don't need to tag people that are clearly going to check the issue reports, especially ones that have already replied to the specific issue. It's annoying.

**Comment by bensku** [comment]
You can change settings using Java code, but you should not do that. It might anger some users.

And no, there is no way to disable this warning for certain SkriptParser instance, nor it looks likely that it will be possible in near future. The warning is usually a sign of bad code style in scripts, if not actual variable name conflict.

**Comment by rplcnn** [comment]
I hate that warning... Im using variables like (SG::Messages::U_Cmd) for set messages. So i have to do that.
Can I use variables in java code like

onEnable() ->
   String variable == Skript.getVariable("SG::Version");
   getLogger("version: " + variable);

**Comment by Syst3ms** [comment]
Yes you can, but the appropriate method is sitting in the `Variables` class.

**Comment by rplcnn** [comment]
@Syst3ms can you give me an example?
