### ISSUE TITLE
Problem : Console Error 

### ISSUE THREAD

**Issue by Daxxas** [bensku/Skript#763]
I'm not a addon dev, I have no idea why this error happen.
The part of skript that is broken worked fine before, I've only added new event.

It happen when event of line 93, 72, 34 are triggered as far as I know :(

The error : https://hastebin.com/akeratulol.vbs

The skript : https://hastebin.com/ebigoraqaf.vbs

**Comment by Daxxas** [comment]
I found why there is an error : 
`on right click on a gravel:
	if player is not sneaking:
#		play "BLOCK_STONE_HIT" at event-block at volume 0.4 and pitch 1
		chance of 10%:
			drop a flint with custom nbt "{CanDestroy:[""minecraft:tallgrass""]}" named "&fPetite pierre"
		chance of 10%:
			drop a cobblestone with nbt "{CanDestroy:[""minecraft:log""]}" named "&fGrosse pierre"
		chance of 10%:
			set event-block to air
			play "BLOCK_STONE_BREAK" at event-block at volume 0.4 and pitch 1`
the line with # is making everything crash (without the # obviously).
The same happen for the event at the lines 93, 72, 34 !

**Comment by Snow-Pyon** [comment]
This isn't a Skript issue, go ask Skellett's developer for support as this doesn't belong here.

**Comment by TheBentoBox** [comment]
Addon issue.
