### ISSUE TITLE
Doubling "%%" doesn't work

### ISSUE THREAD

**Issue by cengiz77** [bensku/Skript#765]
Hi i wrote a skript with strings contains "%%" but the percent symbols seems double in game. Could you fix this issue?

![adsiz](https://user-images.githubusercontent.com/26792423/28904215-ee7f52ae-7811-11e7-9b5c-b037fbca5a87.png)

**Comment by Snow-Pyon** [comment]
Which version of Skript are you using?

**Comment by cengiz77** [comment]
Dev26c

**Comment by TheBentoBox** [comment]
Are you sure? This was an issue with the JSON chat stuff added in dev26-27 and as far as I recall all of the obvious issues like this have been fixed since then.

**Comment by cengiz77** [comment]
Ok. I downloaded the dev25 version and fixed! Sorry for occupation :)
