### ISSUE TITLE
Implement Multi-dimensional lists

### ISSUE THREAD

**Issue by MinecraftSBC** [bensku/Skript#766]
Skript lacks support for multi-dimensional lists. It would be nice to have them like this:
`{Two_Dimensions::a::b}`

**Comment by bensku** [comment]
The exact code you provided works perfectly.

**Comment by TheBentoBox** [comment]
Can confirm, use these all the time and they work exactly as you describe and would expect. Did you even try?

**Comment by MinecraftSBC** [comment]
Adding a list to a list and looping a two dimensional list doesn't work.

**Comment by Snow-Pyon** [comment]
MundoSK has the following expression:
```
tree of %objects%

#And the following expression is the loop-index
branch
```
which is a fix to this issue.

**Comment by bensku** [comment]
@MinecraftSBC Ah, I see. Not what the original post stated, though.

It is not exactly easy to implement true variable nesting, but I'd still like to do it at some point. When, though, is another question.
