### ISSUE TITLE
Error on 1.12.1

### ISSUE THREAD

**Issue by MinecraftAdmin** [bensku/Skript#768]
https://pastebin.com/raw/JHDeupE9

Running Dev29 on PaperSpigot 1.12.1 #1170
I don't know if the Essentials error is related.

**Comment by MinecraftAdmin** [comment]
https://pastebin.com/raw/QUsRLM68

Getting similar error when running Spigot 1.12.1 #1378

**Comment by Snow-Pyon** [comment]
This isn't related to the addon. More like of Skript not supporting the latest version.

**Comment by JeepSmash** [comment]
I am getting the same error.  I do not run essentials so its unrelated to essentials.  It occurs whenever a [ targeted block ] expression is executed rendering that expression broken.  It is however the only issue i have come across so far with 1.12.1

**Comment by bensku** [comment]
Fixed in next release.
