### ISSUE TITLE
Skript does not always load skripts

### ISSUE THREAD

**Issue by higoogle1234** [bensku/Skript#769]
Recently I've been having issues with Skript where once I stop the server and start it back up, none of my skript's work and there's many errors in the console. If I close the server back down and wait a little bit sometimes it goes back to normal, i've tried replacing the jar file a few times when its happened and that seemed to fix it but I don't know whether that was the reason it fixes or not.

I am using Skript 2.1.2
I am also currently using spigot 1.8.8.

Here is a few images of the errors:

![image](https://user-images.githubusercontent.com/20887226/28981590-3cb7e538-794a-11e7-8342-c90bdf8bb21e.png)
![image](https://user-images.githubusercontent.com/20887226/28981799-36edaeca-794b-11e7-8040-57f33bf7dd6f.png)

**Comment by TheBentoBox** [comment]
You're not even using this fork of Skript, and this fork isn't compatible with 1.8 any longer. Your best bet is to use [dev25](https://github.com/bensku/Skript/releases/tag/dev25), but past that we can't provide any more support.

**Comment by higoogle1234** [comment]
Okay, thank you for your advice.
