### ISSUE TITLE
dev30 Issues (clicked item's name expression, functions, potions, lists, loop-index, name of victim and others)

### ISSUE THREAD

**Issue by PheonBest** [bensku/Skript#776]
Hi !
(Errors about delays smaller than 1 tick aren't important)
I get some issues with dev30:
https://pastebin.com/tacfRA4v

Thanks for help :)

**Comment by bensku** [comment]
Please follow the instructions in those exceptions. I will take look at other parse errors, though.

**Comment by bensku** [comment]
Parse errors probably fixed.
