### ISSUE TITLE
[1.12.1] Command block selectors do not expand for custom commands

### ISSUE THREAD

**Issue by rjlan** [bensku/Skript#777]
It appears that command block selectors (e.g. `@p`) are not working with custom commands from Skripts. Instead of being expanded to a match (e.g. `rjlan`), the raw selector itself (e.g. `@p`) is passed to the command
# Testing
* Was not an issue on 1.11.2 running Paper version git-Paper-1104 (MC: 1.11.2), using Skript version dev25
* Became an issue when upgrading to 1.12.1
   * `/version` = `This server is running Paper version git-Paper-1173 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)`
   * `/plugins` = `Plugins (31): Chairs, CleanroomGenerator, CraftBook, DiscordSRV, dynmap, Dynmap-Essentials, Essentials, GTicketMaster, HappyPet, LWC, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, NoCheatPlus, PerWorldInventory, Prism, ProtocolLib, SignShop, SignShopExport, Skript, SQLibrary, Stables, Titanic, VanishNoPacket, Vault, WoodCutter, WorldBorder, WorldEdit, WorldGuard, zPermissions`
* Tested and reproducible on a local testing PaperSpigot (`git-Paper-1173 (MC: 1.12.1)`) server with 2 plugins
   * Skript dev30b, SQLibrary
* Is an issue on both old version (dev25) and new version
* Other plugins do not have this issue (e.g. Multiverse's `/mvtp @p world`)

# Test skript
```
command /debug <text>:
    trigger:
        broadcast arg 1
```

# Reproduction
1. Save above snippet into `plugins/Skript/scripts/debug.sk`
2. `/sk reload all` - Reload Skripts
3. Place command block and enter `/debug @p`
4. Activate command block, observe that it echos `@p` instead of your player name

# Notes

Here is the script that bug was discovered https://github.com/Gamealition/Survival-Skripts/blob/master/approval.sk#L155

**Comment by melinstagibson** [comment]
Do /skript:Debugger @p

Am 06.08.2017 16:44 schrieb "rjlan" <notifications@github.com>:

**Comment by rjlan** [comment]
Did you mean `/skript:debug @p` ? That works as a work-around for the bug, thanks!

**Comment by bensku** [comment]
Will check this once more severe bugs are fixed. Sounds like potential Spigot issue.

**Comment by xXAndrew28Xx** [comment]
Can reproduce in 1.12.1. Will try to fix.

**Comment by weberlepecheur** [comment]
Any news for this issue ?

**Comment by tim740** [comment]
Doesn't looks like anything yet, @bensku

**Comment by daverau** [comment]
This showed up in `1.12.2` — and broke my in-game command block triggers for Skript commands like `/wildwarp @p`, `/rules @p`, etc.

Has anyone found a workaround?

**Comment by supertassu** [comment]
@daverau If it come up only in 1.12.2, it's a Spigot issue.

**Comment by melinstagibson** [comment]
try /skript:rules @p

**Comment by daverau** [comment]
@melinstagibson, @supertassu using `/skript:command` silently does nothing, do I need to enable using `/skript:zzz` somehow?

**Comment by bensku** [comment]
Nice.
