### ISSUE TITLE
Proposal: Ability to change potion color

### ISSUE THREAD

**Issue by DatArnoGuy** [bensku/Skript#780]
Since 1.11 there have been ability to give potion any hex-color. Would be great if there was expression for that in Skript.

**Example usage:**
_on drink:
 ...... cancel event
 ...... tool of player is potion
 ...... set color of tool of player to "#FF0000"_

**Comment by bensku** [comment]
This is already [supported](http://bensku.github.io/Skript/effects.html#EffColorArmor).
