### ISSUE TITLE
Question - Using Skript variables in java plugin

### ISSUE THREAD

**Issue by rplcnn** [bensku/Skript#781]
Could you give me an example?

**Comment by Snow-Pyon** [comment]
You just use the Variables#getVariable method. Example:
```
Object variable = Variables.getVariable("variable::name", null, false);
```
The event can be null if the variable isn't local.

And for set you'd do:
```
Variables.setVariable("variable::name", "value", null, false);
```

**Comment by bensku** [comment]
Question has been answered.
