### ISSUE TITLE
Another dev30b error

### ISSUE THREAD

**Issue by Sashie** [bensku/Skript#782]
`[ERROR] [Skript] event-projectile is not a world (test.sk, line 2: broadcast "%type of event-projectile%"')`

Using..
```
on projectile hit:
	broadcast "%type of event-projectile%"
```

**Comment by Snow-Pyon** [comment]
Duplicate of #779.

**Comment by Sashie** [comment]
I didn't see this error specifically mentioned in there

**Comment by Snow-Pyon** [comment]
This is an issue related to the type of expression being broken which was reported in that issue.

**Comment by bensku** [comment]
Bug fixed.
