### ISSUE TITLE
Kill entity does not working on pigs

### ISSUE THREAD

**Issue by Nevvy** [bensku/Skript#783]
My skript code:
```
on right click on entity:
	kill clicked entity
	send "&c&lEntity&f >> %clicked entity%" to player
```
Kill clicked entity does not working on pigs. They dissapear

**Comment by Syst3ms** [comment]
We need your Skript, Spigot and Minecraft versions. You will get no help if you're in 1.8.x, as it is not supported by Skript in the latest version.

**Comment by Snow-Pyon** [comment]
>1.8.x, as it is not supported by Skript in the latest version.

1.8 has never been supported by this fork, just to clarify.

**Comment by Nevvy** [comment]
[15:09:08 INFO]: This server is running Paper version git-Paper-1168 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[15:09:08 INFO]: Checking version, please wait...
Skript v29 and Skript v30

**Comment by Snow-Pyon** [comment]
Couldn't reproduce running dev30b and Spigot 1.12 with the exact same code.

**Comment by bensku** [comment]
Can anyone reproduce?

**Comment by Nevvy** [comment]
@bensku 
I tried use this skript code on server with only skript
It doesn't work for me
[20:25:39 INFO]: Plugins (1): Skript
[20:27:12 INFO]: This server is running Paper version git-Paper-1168 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
[20:27:12 INFO]: Checking version, please wait...
[20:27:12 INFO]: You are 11 version(s) behind

**Comment by TheBentoBox** [comment]
I'm only on dev25 but I can confirm the pigs do just disappear as opposed to actually dying. It's the same for all rideable mobs. This is likely due to your first a while back for allowing the `kill` effect to be used on armor stands and such; it seems like a number of living entities are being "killed" via `entity.remove();`

**Comment by xXAndrew28Xx** [comment]
This is because the kill effect uses .remove() on Vehicles, I'll make a PR fixing this.

**Comment by xXAndrew28Xx** [comment]
I found another bug while reproducing this, it attempts to cast an Ender Dragon to a LivingEntity and fails.
