### ISSUE TITLE
residence support

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#784]
it seems like the "%player% can build at %location%" syntax isnt working for residence anymore.

whenever i try to use it in a residence even when i am owner it wont pass.
i have to set the build flag to true for everyone for it to work

```
command /canbuild:
        permission: *
        trigger:
                if player can build at location at player:
                        send "ok"
                else if player can't build at location of player:
                        send "not ok"
```

nothing bad so no need to hurry, also im still on dev29 due to bugs but i guess its the same in dev30

**Comment by bensku** [comment]
Are you using absolutely latest Residence which also supports your MC version officially?

**Comment by bensku** [comment]
I need that information to even begin debugging, going to close this if no answer comes.

**Comment by melinstagibson** [comment]
sorry, yes, im using the latest for everything. dev30d, latest residence (http://ltcraft.lt/Residence/download.php?file=Residence4.7.1.2.jar) and currently paperspigot build 1190 (1.12.1)

**Comment by melinstagibson** [comment]
this seems to have fixed itself, just tried it again
