### ISSUE TITLE
Exception with latest skript version

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#79]
Latest version of skript causes a crash / exception on server startup:
http://hastebin.com/cisahitiyi.vbs
Guess it has something to do with functions?!

**Comment by bensku** [comment]
Yeah, functions are bugged it seems... Hotfixing

**Comment by bloggy** [comment]
But you will fix it in next version?

**Comment by bensku** [comment]
Of course, but since I'm rewriting some parts of the parser, it will take few days.

**Comment by bloggy** [comment]
No problem. 1.9.4 is out, too.

**Comment by bensku** [comment]
Fixed yesterday.
