### ISSUE TITLE
Proposal: Condition 'script [%text%] is loaded'

### ISSUE THREAD

**Issue by TheBentoBox** [bensku/Skript#797]
The syntax would be something like `script [%text%] is loaded`. The text can be provided optionally to give the name of a specific script to check its load state, but it will otherwise default to the script the condition is in. This allows for scripts to easily do stuff conditionally based on if another script is currently active, or to do loaded-based loops, e.g.

```
on script load:
    while script is loaded:
        <code>
```

Currently, a while loop like this would continue uncontrollably even after unloading unless you use a variable of some variety to track the script's load status (which, granted, is not at all hard, but this looks nicer).

**Comment by v3Monsta** [comment]
I know it's not how it's done in an actual programming language, but for Skript couldn't you just have the script dependencies in the same file? So if you need to depend on a function for the main script to function, you have it in the same file so that it's always available.

**Comment by Snow-Pyon** [comment]
Of course you can have all your scripts in one big file, but shall I wait 16 minutes for that script to load? Split scripts into different files makes them faster at parse-time.

**Comment by v3Monsta** [comment]
Okay, well I figured it was a better solution if you just needed to depend on a couple functions, but if you need to depend on an entire script file then yes this would be very nice to have. I never suggested you put _everything_ into 1 file.

**Comment by bensku** [comment]
I just fixed the bug that caused function calls before function definitions not to work.

Anyways, good idea.

**Comment by Pikachu920** [comment]
Wouldn't it be easier to have the syntax
```
[script] %text% is loaded
```
as that still allows you to do
```
script is loaded
```

Wouldn't it be easier to have the syntax
```
[script] %text% is loaded
```
as that still allows you to do
```
script is loaded
```
because of the script expression, and then Bensku doesn't have to fuck

**Comment by xXAndrew28Xx** [comment]
PR is done, it uses these syntaxes:
`script[s] [%-strings%] (is|are) loaded`, `script[s] [%-strings%] (isn't|is not|aren't|are not) loaded`
