### ISSUE TITLE
Tab completer.

### ISSUE THREAD

**Issue by PanKlipcio** [bensku/Skript#799]
Code:
```
command /abcd [<text>]:
	trigger:
		if "%arg 1%" is "yes":
			send "YES !"
		else if "%arg 1%" is "no":
			send "NO !"
		else:
			send "UNSET !"
on tab completer for "abcd":
	if argument at 2 is not set:
		add "yes" to completions
		add "no" to completions
		add "back" to completions
```
Error:
![obraz](https://user-images.githubusercontent.com/21959209/29430445-b15c7b2a-8394-11e7-93d2-3562c9dbb5f8.png)

**Comment by TheBentoBox** [comment]
This is an SkQuery event, not vanilla Skript. Ask for help on the forums, issues caused by addons don't belong here.

**Comment by melinstagibson** [comment]
Did you try 
On Tab completer for "/abcd" 
?

**Comment by Battledash-2** [comment]
r
