### ISSUE TITLE
How to set the second hand of player ?

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#80]
Hi there,

skript contains effects like:
set the player's helmet to iron helmet

and with 1.9 there is the second hand where player can have a shield etc. how would I make use of it??

**Comment by bensku** [comment]
<code>"[the] (off[(-| )]tool|off[(-| )][held ]item|off[(-| )]weapon) [of %livingentities%]", "%livingentities%'[s] (off[(-| )]tool|off[(-| )][held ]item|off[(-| )]weapon)",
"[the] (off[ ]hand tool|off[ ] hand item|shield[ item]) [of %livingentities%]", "%livingentities%'[s] (off[ ]hand tool|off[ ] hand item|shield[ item])"</code>

All possible patterns, separated with commas. You can use <code>set</code> to change them.
