### ISSUE TITLE
Command already exists warning not being very helpful

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#802]
Hey, this is just a minor thing since i dont think anyone would forget what he was just working on but if i make a script with a command that already exists i get things like this:

[10:06:58 ERROR]: A command with the name /ch.njol.skript.command.ScriptCommand@274d4f4a is already defined in fun.sk

tried with other skripts, it wont show the actual command anymore.

Im not sure if this is related to that aswell but for example i cant figure out which command caused this crash http://www.paste.org/85571
but i guess the one thing has nothing to do with the other so just ignore that if im being retarded ^^

**Comment by bensku** [comment]
Hm, sounds like a bug.

**Comment by xXAndrew28Xx** [comment]
Fixed in a PR, accidently messed up #806.
