### ISSUE TITLE
Skript  relaod all > GUI issues

### ISSUE THREAD

**Issue by epicskymi** [bensku/Skript#804]
After reloading all any custom menu when opened is screwed stealing is possible and commands don't run when clicking.

I tested both SKquery menu's and Tuske menu's and both behave this way after reload all.

no errors on console after the reload.
I tested this on both v29 and v30 and it was the same results

http://i.imgur.com/z66M1ma.gifv
heres a gif of the issue

**Comment by melinstagibson** [comment]
can confirm

**Comment by epicskymi** [comment]
reload all is useful when multiple scripts use a function

**Comment by TheBentoBox** [comment]
This isn't a vanilla Skript issue though is it? This sounds more like a problem with TuSKe or SkQuery's GUI effects not handling reloads correctly, which is a problem on their end. Correct me if I'm wrong but otherwise this doesn't belong here so I'll close it.

**Comment by epicskymi** [comment]
this isn't an issue on v25 so something changed in skript to break it

**Comment by TheBentoBox** [comment]
Might have something to do with the changes to the parser to support async parsing.

**Comment by epicskymi** [comment]
Considering it gives no errors how are addon dev's supposed to know what's breaking it? This seems more of a skript issue

**Comment by bensku** [comment]
Considering that, how would I fix this? To put it simply, I'll take this up with addon devs in question later. Cannot help you with this right now.

That being said, @Tuke-Nuke couldn't replicate with latest version of Skript (see the link above). I'm curious, but for now going to close this. Will be back after talking to addon devs if this is Skript issue.

**Comment by epicskymi** [comment]
I don't think the issues are the same this is 1.12 and it give no errors as hid did
