### ISSUE TITLE
Setting lore of a variable fails to work

### ISSUE THREAD

**Issue by Pilvinen** [bensku/Skript#81]
```
on left click on chest or trapped chest:
  set {_item} to paper
  set line 1 of lore of {_item} to "Line 1 of lore"
  set line 2 of lore of {_item} to "Line 2 of lore"
  add {_item} to inventory of event-block
```

Results in a paper inside the chest with no lore.

**Comment by TheBentoBox** [comment]
Why not just do `set {_item} to paper with lore "Line 1 of lore||Line 2 of lore"`?

**Comment by Pilvinen** [comment]
I suppose I could try that but it doesn't make the above any less of a bug, so...

**Comment by bensku** [comment]
Your code (copied, without changing anything) works for me. Maybe Spigot 1.9.4 update fixed something, or I "accidentally" fixed it.

If it still doesn't work, then we'll need to do some debugging together.
