### ISSUE TITLE
event block not working with on break/mine/block damage

### ISSUE THREAD

**Issue by aycgit** [bensku/Skript#812]
it seems like the event block is set to nothing on dev30d spigot 1.9.4

**Comment by bensku** [comment]
Did it happen before? In which event this happens, if not always?

**Comment by bensku** [comment]
Need more information @aycgit...

**Comment by aycgit** [comment]
oops, i must have missed your first message, that was the first time i tried, it happens with on break/on mine and seems to always happen, if you can not reproduce it it may have been my setup since i just started doing skript things

**Comment by bensku** [comment]
I'll try to reproduce, now that I know where to look. Sounds like MC version specific issue, but that's my problem as 1.9 is still supported by Skript.

**Comment by aycgit** [comment]
or the issue fixed itself or it was my setup but everything seems to work fine now, i will close this issue to reopen it later if the issue comes back. Thanks for putting your time in this awesome project.
