### ISSUE TITLE
Latency and crash with citizen expression

### ISSUE THREAD

**Issue by DevilishDante** [bensku/Skript#818]
Hi i have a problem, in deed when i use citizen expression in a skript reload my server crash
and i start my server my skript take 3-6 minutes with citizen expression

- Condition "if citizen is named "test":"
- my citizens is update at the last release and skript too

i don't have any error in the console, just a big latency
It's an issues? i don't know
Thanks :)

**Comment by Snow-Pyon** [comment]
This isn't related to Skript but an addon (which is probably Skellett or skRayFall). Don't report addon issues here.

**Comment by DevilishDante** [comment]
Oow ,sorry my bad >< i don't remind hmm "rappeler", i'm sorry in deed is not a skript issues
