### ISSUE TITLE
License Violations

### ISSUE THREAD

**Issue by CDAGaming** [bensku/Skript#819]
* What went wrong:
Execution failed for task ':licenseMain'.
> License violations were found: E:\Forked Repos\Minecraft Repos\CoreFiles\Skript\src\main\java\ch\njol\skript\expressions\ExprBookRecipes.java}

**Comment by bensku** [comment]
Something I started to add but didn't finish. Do gradle licenseFormat to fix this for now, or wait a few hours for me to resolve this issue.

**Comment by CDAGaming** [comment]
Thanks.
