### ISSUE TITLE
Issues with particles

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#82]
I am unable to get this to work:

play 100 (potion_swirl with speed 0) at player

or

play 100 (witch magic with speed 0) at player

results in:
"Cant understand this condition" - error

**Comment by bensku** [comment]
You are probably using wrong names (see https://gist.github.com/bensku/834e7bf666eb995e53d456c21ecc1e0e). If it still bugs, reply here.

Also, particle support is generally very buggy (issue #64 ). I'm considering EffectLib as dependency at some point.

**Comment by bensku** [comment]
Fixed in next release, at least if you use EffectLib.
