### ISSUE TITLE
Error Skript

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#824]
29.08 11:26:14 [Server] ERROR #!#! 
29.08 11:26:14 [Server] ERROR #!#! [Skript] Severe Error:
29.08 11:26:14 [Server] ERROR #!#! 
29.08 11:26:14 [Server] ERROR #!#! If you're developing an add-on for Skript this likely means that you have done something wrong.
29.08 11:26:14 [Server] ERROR #!#! If you're a server admin however please go to https://github.com/bensku/Skript/issues/
29.08 11:26:14 [Server] ERROR #!#! and check whether this error has already been reported.
29.08 11:26:14 [Server] ERROR #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it (or use paste service),
29.08 11:26:14 [Server] ERROR #!#! and describe what you did before it happened and/or what you think caused the error.
29.08 11:26:14 [Server] ERROR #!#! If you think that it's a trigger that's causing the error please post the trigger as well.
29.08 11:26:14 [Server] ERROR #!#! By following this guide fixing the error should be easy and done fast.
29.08 11:26:14 [Server] ERROR #!#! 
29.08 11:26:14 [Server] ERROR #!#! Stack trace:
29.08 11:26:14 [Server] ERROR #!#! java.util.ConcurrentModificationException
29.08 11:26:14 [Server] ERROR #!#!     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
29.08 11:26:14 [Server] ERROR #!#!     at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
29.08 11:26:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.EntityTracker.track(EntityTracker.java:32)
29.08 11:26:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.WorldManager.a(WorldManager.java:18)
29.08 11:26:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.World.a(World.java:1066)
29.08 11:26:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.WorldServer.a(WorldServer.java:970)
29.08 11:26:14 [Server] ERROR #!#!     at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1059)

**Comment by TheBentoBox** [comment]
Systems is correct that you'd need to post the full error and it's something you should make note of for future bug reports (on any repository). However, this fork isn't compatible with 1.8 anymore and we cannot provide support for old versions. If you're on 1.8 you should be using build dev25, but we cannot provide any support for you past that advice.
