### ISSUE TITLE
Names Section in Docs

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#825]
I'm not sure about name of the section, but a section that contains these should be great/useful!:

`entities`, `enchantments`, `potions`, `weather`, `biomes`, `tree types`, `colors`, `damage causes`, `visual effects`, `inventory actions` and `click actions`.

Also maybe `gamemodes`, `times`, `directions `and `chat styles`. Why not?

**Note:** All of them are from [english.lang](https://github.com/bensku/Skript/blob/99ba30fe2380531ab7264884bc76f4021c4ade63/src/main/resources/lang/english.lang) :wink:

**Comment by TheBentoBox** [comment]
All of the ones that make sense are listed in the [types section](http://bensku.github.io/Skript/classes.html) already. Is that what you're looking for?

**Comment by Blueyescat** [comment]
No, these aren't in types section. You should look at [english.lang](https://github.com/bensku/Skript/blob/99ba30fe2380531ab7264884bc76f4021c4ade63/src/main/resources/lang/english.lang).

**Comment by TheBentoBox** [comment]
I'm not really sure what you're talking about, most of the types you've listed are already in the types section I linked, including all of the enchantments, potion effect types, (most) trees, colors, damage causes, visual effects, inventory actions, and click actions. The only ones really missing are entities and biomes. Also, listing times and directions doesn't really make sense, as there's essentially an infinite/arbitrarily large number of them (since e.g. `3 meters north and 2 meters below` is also a direction).

**Comment by Blueyescat** [comment]
Enchantments and colorsok, there is no aliases of potion types, damage causes, click actions and inventory actions.
There are only 2-3 tree types, visual effects aren't good really, you will see something like "block dust of %itemtype%" if you can check [english.lang](https://github.com/bensku/Skript/blob/99ba30fe2380531ab7264884bc76f4021c4ade63/src/main/resources/lang/english.lang) also there is a offset expression, Already entities list is important, also there is advanced types like "enderman holding stone". Biomes list is important too. So just check the language file.

**Comment by TheBentoBox** [comment]
Not sure if you're blind or we're just talking about different things but potion effect types, damage causes, click actions, and inventory actions ARE all listed there, e.g. [here's the potion effect type section](https://gyazo.com/b0aba01a1a5397bcd1711dfbbeba611d) that lists all the potions. There's one for all of those and I'm not sure how you're missing it, to be honest.

It sounds more like what you want is more examples of advanced syntax (like with `enderman holding` and `block dust of %itemtype%`), which I agree with. Stuff like that should be in the docs. Most of what you're saying is already there though, you're just not looking carefully enough.

**Comment by Blueyescat** [comment]
I already said aliases of these aren't in docs.. A names section should be fine for that.
