### ISSUE TITLE
[SUGGESTION] Residence plugin in "Can Build" condition ?

### ISSUE THREAD

**Issue by MachisCZ** [bensku/Skript#83]
Hello, is possible to add Residence plugin http://dev.bukkit.org/bukkit-plugins/residence/
To Can Build ? Thanks

**Comment by bensku** [comment]
It might be possible, but whole region system is still somewhat buggy regardless of plugin used.

**Comment by itismejoey** [comment]
Why add this into the full Skript plugin when half (see 99%) won't use it. I suggest asking a developer to add it to one of their add-ons.
