### ISSUE TITLE
Can hold / has enough space

### ISSUE THREAD

**Issue by Barbarx** [bensku/Skript#830]
`> [21:45:25 ERROR]: #!#! Stack trace:
> [21:45:25 ERROR]: #!#! java.lang.UnsupportedOperationException
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getSingle(ExpressionList.jav
a:87)
> [21:45:25 ERROR]: #!#!     at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.jav
a:46)
> [21:45:25 ERROR]: #!#!     at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.jav
a:15)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getAll(SimpleExpressi
on.java:78)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.getAll(ConvertedEx
pression.java:163)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.getAll(Prope
rtyExpression.java:79)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getAll(ExpressionList.java:1
16)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.ExpressionList.getArray(ExpressionList.java
:99)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(Property
Expression.java:74)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpres
sion.java:104)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.expressions.base.PropertyExpression.get(Property
Expression.java:74)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpressio
n.java:163)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.conditions.CondCanHold$1.check(CondCanHold.java:
93)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.conditions.CondCanHold$1.check(CondCanHold.java:
1)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression$1.check(ConvertedE
xpression.java:180)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpressio
n.java:175)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpressio
n.java:163)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.check(SimpleExpressio
n.java:158)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.util.ConvertedExpression.check(ConvertedExp
ression.java:173)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.conditions.CondCanHold.check(CondCanHold.java:81
)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.Condition.run(Condition.java:56)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.Conditional.walk(Conditional.java:51)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java
:151)
> [21:45:25 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.
java:109)
> [21:45:25 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListen
er.java:62)
> [21:45:25 ERROR]: #!#!     at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegist
eredListener.java:36)
> [21:45:25 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginMan
ager.java:499)
> [21:45:25 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginMan
ager.java:484)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnecti
on.java:1877)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceF
ile:33)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceF
ile:10)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(Sourc
eFile:13)
> [21:45:25 ERROR]: #!#!     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.j
ava:511)
> [21:45:25 ERROR]: #!#!     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer
.java:747)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer
.java:405)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer
.java:678)
> [21:45:25 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServ
er.java:576)
> [21:45:25 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! Version Information:
> [21:45:25 ERROR]: #!#!   Skript: 2.2-dev30d (latest)
> [21:45:25 ERROR]: #!#!   Bukkit: 1.12-R0.1-SNAPSHOT
> [21:45:25 ERROR]: #!#!   Minecraft: 1.12
> [21:45:25 ERROR]: #!#!   Java: 1.8.0_131 (Java HotSpot(TM) 64-Bit Server VM 25.131-b11)
> [21:45:25 ERROR]: #!#!   OS: Linux amd64 4.4.0-78-generic
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! Running CraftBukkit: false
> [21:45:25 ERROR]: #!#! Running Spigot (or compatible): true
> [21:45:25 ERROR]: #!#! Running Paper (or compatible): false
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! Current node: null
> [21:45:25 ERROR]: #!#! Current item: (the player >> ch.njol.skript.classes.data.DefaultConver
ters$1@a80ebcc: org.bukkit.entity.Player->org.bukkit.inventory.Inventory) can hold lore
> [21:45:25 ERROR]: #!#! Thread: Server thread
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! Language: english
> [21:45:25 ERROR]: #!#! Link parse mode: DISABLED
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! End of Error.
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! [Skript] Severe Error:
> [21:45:25 ERROR]: #!#! 
> [21:45:25 ERROR]: #!#! Something went horribly wrong with Skript.`

**Comment by TheBentoBox** [comment]
That looks like an SkStuff error to me judging by this part:

```
[21:45:25 ERROR]: #!#! at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.jav
a:46)
[21:45:25 ERROR]: #!#! at me.TheBukor.SkStuff.expressions.ExprItemNBT.get(ExprItemNBT.jav
a:15)
````

Contact the developer of the addon.
