### ISSUE TITLE
error skript 

### ISSUE THREAD

**Issue by RafsJR1** [bensku/Skript#835]
01.09 16:42:52 [Server] ERROR Error occurred while enabling Skript v2.2-dev30d (Is it up to date?)
01.09 16:42:52 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/Particle

**Comment by TheBentoBox** [comment]
Your version of Spigot is out of date as it doesn't contain the particle class. Additionally, this is the third issue report you've filed and I've told you both other times that your version was out of date. Stop filing reports here until you update your server, we **can't** help people that are on versions older than 1.9.
