### ISSUE TITLE
On region enter

### ISSUE THREAD

**Issue by GrimEpp** [bensku/Skript#838]
The event on region enter|exit exist in other Skript versions f. eks v8b but not bensku.

**Comment by Snow-Pyon** [comment]
It does exist on this fork? I have used it many times and it's still working fine for me.

**Comment by TheBentoBox** [comment]
This isn't true at all, the event still exists. If you're having issues with events not registering it's probably due to an addon or server version issue.

**Comment by Syst3ms** [comment]
More likely a region plugin issue.
