### ISSUE TITLE
Entity (Armor Stand) [right] click event - two outputs

### ISSUE THREAD

**Issue by le0-minelandeu** [bensku/Skript#839]
on right click on armor stand:
	make player execute command "/examplecommand"

or: https://pastebin.com/M7AmnSZn

the command will be used two times, not just once.

Using 1.10.2 and Skript 2.2-dev30

**Comment by bensku** [comment]
Sounds like old main/off hand bugs. Usually easy to fix but numerous.

**Comment by Snow-Pyon** [comment]
Tested, doesn't happen anymore in the latest version.

**Comment by melinstagibson** [comment]
I just tried this with the lastest version (dev35b) and it still happens to me

**Comment by Blueyescat** [comment]
Doesn't happen to me

**Comment by bensku** [comment]
What Minecraft version do you use @melinstagibson?
