### ISSUE TITLE
Loop inventory change

### ISSUE THREAD

**Issue by SlimeDog** [bensku/Skript#841]
Spigot 1.12.1 latest
Skript 2.2-dev31

Loops on the players inventory worked through Skript 2.2-dev30b, but now...
```
[11:26:00] [Server thread/ERROR]: [Skript] Can't understand this loop: 'loop all items in the player's inventory' (clear-inventory.sk, line 14: loop all items in the player's inventory:')
```

I searched documentation for changes to the loop syntax, but didn't find any pointers.

**Comment by bensku** [comment]
Probably a side effect of some unrelated change. I'll take a look at this soon.

**Comment by SlimeDog** [comment]
thanks.

**Comment by bensku** [comment]
For some reason, all items in whatever doesn't parse at all. I'll attempt to fix this, but it will likely take hours of debugging from me - which I can't in next few days.

**Comment by WolfezzKyne** [comment]
Got that issue with 	`loop items in victim's inventory:` too

**Comment by bensku** [comment]
I think it is more about 'items in' than where the inventory comes. Which is strange, indeed.

**Comment by TrademarkTM** [comment]
So when will you be able to fix it?
It's a quite important feature to manage inventories.

**Comment by bensku** [comment]
Not soon. I did attempt to figure out what is wrong, but in the end failed. I still have no clue what might cause this.

Does this happen with dev30 too, by the way?

**Comment by WolfezzKyne** [comment]
In dev30 it worked fine

**Comment by bensku** [comment]
Huh, that is interesting. There were no significant parser changes.

**Comment by SlimeDog** [comment]
It worked correctly until dev32.

**Comment by bensku** [comment]
Change to plans: it is fixed now.

**Comment by bensku** [comment]
Sorry, forgot to push release... Oops.

**Comment by SlimeDog** [comment]
An updated release that includes this basic functionality would be nice.

**Comment by bensku** [comment]
I have published that update already. My comment was just to apologize delay of six days between fix and release.

**Comment by SlimeDog** [comment]
I see only [dev31c](https://github.com/bensku/Skript/releases) on GitHub, which predates this conversation by a week. Where should I be looking?

**Comment by SlimeDog** [comment]
Sorry, I missed that there was a hotfix. If the release version doesn't change, my checker doesn't pick it up. Thanks.
