### ISSUE TITLE
[SEVERE] List variables no longer delete all elements.

### ISSUE THREAD

**Issue by RezzedUp** [bensku/Skript#843]
Skript no longer clears an entire list (**including** sub-lists) when using `delete {<variable>::*}`

## Using:
* Skript version **2.2-dev31** 
* Spigot (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

## Tested with:
```vb
command /vars:
    trigger:
        delete {vars::*}
        add "Hello, I should only send one message!" to {vars::messages::*}
        loop {vars::messages::*}:
            send "&6##%loop-index%:&f %loop-value%"
```
Results after running 4 times in a row:

![](https://i.imgur.com/kUXxPUE.png)

## Expected behavior:

The command should only send one message since it clears the list before adding an entry. This works correctly with **Skript-2.2-dev25**.

I've also noticed a difference in how list variable deletions are recorded in variables.csv: previously (in dev25), only one '`variable::*, null, `' entry would be appended. Now, every single list item gets an entry appended ('`variable::index, null, `' etc).

Please revert back to the previous list-deletion implementation.

**Comment by bensku** [comment]
Gotta find the root cause of this. Previous delete implementation was utterly broken too, just not with CSV.

**Comment by RezzedUp** [comment]
Keep in mind that a majority of Skript users use the default CSV setup (and [SQLibrary](https://dev.bukkit.org/projects/sqlibrary) hasn't been updated in 3 years). I'm sure the problems described in this issue report affect database users as well. 

In my opinion, #791 should immediately be reverted (merge #844) and a hotfix should be released to address this problem.

**Comment by bensku** [comment]
Once I get to computer later today, I'll fix this. I'll *try* to find a way to not recreate original problem, but no worries. This is higher priority.

**Comment by RezzedUp** [comment]
I don't think [ch.njol.skript.lang.Variable](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/lang/Variable.java) is the appropriate class to modify for this purpose in the first place. Updates to variable storage should happen further down the pipeline (like in [ch.njol.skript.variables.Variables](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/variables/Variables.java) - or - [ch.njol.skript.variables.VariablesMap](https://github.com/bensku/Skript/blob/master/src/main/java/ch/njol/skript/variables/VariablesMap.java)). 

The problems that #791 "fixes" only affect SQL-styled storage, so whatever updates occur should only apply when using non-CSV storage (i.e. put all that in an if statement that only fires when deleting variables from SQL).

**Comment by RezzedUp** [comment]
I still think you should consider a more elegant solution. CSV users don't need [this whole block of redundant iteration](https://github.com/bensku/Skript/blob/47e624dbd91c00def3ecd965c87a1094430c60f2/src/main/java/ch/njol/skript/lang/Variable.java#L390-L404) to delete variables.

Besides, old deletion behavior still exists for [setting lists](https://github.com/bensku/Skript/blob/47e624dbd91c00def3ecd965c87a1094430c60f2/src/main/java/ch/njol/skript/lang/Variable.java#L411).

**Comment by bensku** [comment]
Setting lists behaves differently since you're not setting final values to be nulls. At least I hope you don't do that.

Anyway, whole variable backend is full of hacks on top of other hacks. That and legacy code. Unless you prove that we have a performance problem here, I'm not going to start optimizing parts of that code.
