### ISSUE TITLE
Cancelling on damage with flaming arrows not working

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#854]
I have a script where players can attack each other during certain server time.

This works perfectly for PvP however if a player has Flame on their arrow and shoots someone when PvP time is inactive, the player still gets hurt.

Not sure if this is a bug or my lack of knowledge with scripts.

Script here:
```
# When {pvp.active} is true damage from player to player is cancelled
on damage:
	if {pvp.active} is false:
		if attacker is player:
			if victim is player:
				chance of 60%:
					message "&4&lWARNING: &cPvP is enabled between &l18:00 and 06:00 &cserver time." to attacker
					message "&4&lWARNING: &cPvP is enabled between &l18:00 and 06:00 &cserver time." to victim
				cancel event
```

**Comment by jaylawl** [comment]
this might not be a bug but rather something you have to differentiate in your code. try this:
```
on damage:
    broadacast "%attacker%"
    broadacast "%damage cause%"
```
and then work with the results and, if possible, integrate projectiles that way in your script

**Comment by Snow-Pyon** [comment]
This isn't a bug, it is just that you're checking if the attacker is a player, therefore if it's fire caused by an arrow it wouldn't be detected by the trigger.

**Comment by jaylawl** [comment]
@whoshenry try:
# When {pvp.active} is true damage from player to player is cancelled
on damage:
```
	if {pvp.active} is false:
		if attacker is player:
			if victim is player:
                                **extinguish victim**
				chance of 60%:
					message "&4&lWARNING: &cPvP is enabled between &l18:00 and 06:00 &cserver time." to attacker
					message "&4&lWARNING: &cPvP is enabled between &l18:00 and 06:00 &cserver time." to victim
				cancel event
```

**Comment by TheBentoBox** [comment]
No response and I agree with @Snow-Pyon about the cause of this, so closing.
