### ISSUE TITLE
Event 'every 30 minecraft minutes in world:' not working

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#857]
The time checking events seem to be off, especially this one:
```
every 30 minecraft minutes in "Survival5":
	broadcast "&cDebug: &fStage 1 Pass"
```
It simply doesn't broadcast it, no error in console either.

Skript dev31b and Spigot 1.12.1

**Comment by Nicofisi** [comment]
Had it worked before or did you try it for the first time before reporting?

**Comment by whoshenry** [comment]
First time trying it.

**Comment by Nicofisi** [comment]
Duplicate of #464, I discussed it in #464
