### ISSUE TITLE
At 1200 ticks in world "world": event not understood

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#858]
Can Skript understand and use ticks as a way of telling the time on the at time events?

I'm currently using at 06:00 in world... and it's really inconsistent.

**Comment by MinecraftSBC** [comment]
Tick is a timespan while 06:00 is a time... probably would regard that as a enhancement

**Comment by TheBentoBox** [comment]
I don't think `at 1200 ticks in world` should even work, that wording doesn't even make sense. I don't think we should support alternate syntaxes that only serve to allow more opportunities for people to misunderstand where different types should be used.

**Comment by bensku** [comment]
Yeah, no way we're going to support this.
