### ISSUE TITLE
Receiving Basic Command Errors

### ISSUE THREAD

**Issue by Parrothead** [bensku/Skript#86]
Hello!

I'm having major problems with using various Skript builds for 1.9.  I'm not really sure where to go from here.  The other Skript build that has been around the SkUnity forums for a while has never worked on my server so I thought I would give this one a try.  I put the error I get on a pastebin page below.  I made a very simple script to test and it was unable to compile.  Any help would be appreciated.

Thanks for taking the time to read this.

Using:
- Bukkit 1.9.4.
- The latest version of this Skript fork (May 19).
- Java 8 (build 1.8.0_92-b14)

_(ALSO) I removed all other plugins except skript and only had the script linked below loaded when I tried to execute the command in the picture._

Links:
Pastebin Error: http://pastebin.com/VRFZrKwi
Ingame/Skript Error: http://i.imgur.com/i2ci9FL.jpg (Works on 1.8 live server).
Skript Version: https://github.com/bensku/Skript/releases/download/dev15/skript.jar

**Comment by bensku** [comment]
You should really use Spigot. Bukkit is apparently missing some features.
