### ISSUE TITLE
particles

### ISSUE THREAD

**Issue by aycgit** [bensku/Skript#860]
there does not seem to be a working particle system for skript at the moment, May it be possible to add a particle system integrated into skript as all current particle supporting addons are broken.

**Comment by bensku** [comment]
Skript uses Spigot's particle API. Is that broken again?

**Comment by aycgit** [comment]
no, but is the particle api documented anywhere?

**Comment by TheBentoBox** [comment]
The visual effect syntax is [here](http://bensku.github.io/Skript/effects.html#EffVisualEffect) and the list of visual effects is [here](http://bensku.github.io/Skript/classes.html#visualeffect). Is that what you're looking for @aycgit ?

**Comment by aycgit** [comment]
yes, thanks, i don;'t know how i didnt find that
