### ISSUE TITLE
Add Support for Spigot Sounds

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#861]
Minecraft sound names are liable to change throughout versions, Spigot's are less liable to change.

**Comment by Blueyescat** [comment]
In my opinion it shouldn't support that... Spigot names aren't fit in Skript, looks ugly. Since Skript's aim is easier/more readable things, it should use a sound type like SkQuery does in language files. With this way it can still use Spigot names with the advantage you said :+1:

**Comment by TheBentoBox** [comment]
@Blueyescat What's the difference between what you're saying and the initial suggestion? Both of you are saying to support playing sounds using the Spigot sound enum names :')

**Comment by Blueyescat** [comment]
His suggestion is support for
```vb
play sound "ENTITY_ENDERDRAGON_FIREBALL_EXPLODE " at player
```
and mine is
```vb
play sound ender dragon fireball explode at player```

**Comment by bensku** [comment]
I'll roll my own sound names initially based in Vanilla ones, but without risk of them breaking in future. Spigot names are hit and miss: sometimes descriptive and useful, sometimes utterly horrible. Not to mention that they might change...

**Comment by bensku** [comment]
Merging support for Spigot sound names in. It does not *solve* this issue, but is still nice to have.

**Comment by TheLimeGlass** [comment]
Reopened?

**Comment by bensku** [comment]
I accidentally closed it.
