### ISSUE TITLE
Need help with a skript

### ISSUE THREAD

**Issue by Fimbelind** [bensku/Skript#864]
I am using the Plugin Skript with a skript called "Unlockableores" or something similar to that atleast. When I use /unlockore and buy for example the ability to mine Coal it doesn't work for me. It takes the money and says I've purchased the ability but then when I try to mine a coal ore it says I need to go buy it with /unlockore.

I don't know if this helps but this is what shows up in the console:

#1: https://pastebin.com/GVEuejAL

#2: https://pastebin.com/Hux0UrKG

**Comment by Syst3ms** [comment]
This is not for problems with scripts, this is for Skript bugs and things that need to be fixed. Ask this on skUnity's forum or Discord server.

**Comment by Fimbelind** [comment]
Yes sorry, will remove this
