### ISSUE TITLE
Checking Statistics Instead of PlayerMoveEvent

### ISSUE THREAD

**Issue by Blueyescat** [bensku/Skript#869]
Hello, as known bukkit has [PlayerStatisticIncrement ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerStatisticIncrementEvent.html)event, but it doesn't check movement statistics etc. expect jumpinh. I saw [this](https://github.com/bensku/Skript/blob/8c26dca2f0520bbac0e1817c8af58229b1a05669/src/main/java/ch/njol/skript/events/EvtMoveOn.java#L54) and it looks so bad... Why not just check jump statistic in the statistic increment even? :slightly_smiling_face: 

Anyway, what about checking increment of WALK_ONE_CM statistic _manually_ in a few ticks instead of PlayerMoveEvent for [MoveOn ](https://github.com/bensku/Skript/blob/8c26dca2f0520bbac0e1817c8af58229b1a05669/src/main/java/ch/njol/skript/events/EvtMoveOn.java)event? Since [PlayerMoveEvent ](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerMoveEvent.html)checks yaw and pitch so _**a lot of**_ checks...

By the way `(on|over) %itemtypes%` in [MoveOn ](https://github.com/bensku/Skript/blob/8c26dca2f0520bbac0e1817c8af58229b1a05669/src/main/java/ch/njol/skript/events/EvtMoveOn.java)event should be optional with this way.

**Comment by Blueyescat** [comment]
Hmm actually the MoveOn event needs `SPRINT_ONE_CM`, `SWIM_ONE_CM` etc. statistics...

**Comment by bensku** [comment]
This would be less accurate, but I guess it could be considered as an option.

**Comment by Pikachu920** [comment]
this is not possible because as incremented in the javadoc of that event, it is not called for movement related events. This can be closed @Snow-Pyon @TheBentoBox
