### ISSUE TITLE
[Suggestions] Click types, console commands and player's inventory ?)

### ISSUE THREAD

**Issue by JKGamerxD** [bensku/Skript#87]
1) Hey Bensku! You can add the click type expression to on click event ?)
This is a cool feature and the syntax can be this:

```
[event-]click [type] (is|are|is not|are not|aren't|isn't) (left|middle|right) [click]
```

2) The `on command` event can have more support to console for `cancel the event` and other things. Because you can't cancel console commands in `on command` event.

3) You can make the expression `%inventory% (can|can't) hold %itemstack%` and `%inventory% (has|have|hasn't|has not|have not|haven't|don't|doesn't|does not) [enough] space for %itemstack%` have one difference? And the difference is if you use `can hold` expression don't check the armour of player, but if you use the `have enough space` expression, this check the armour of player?

**Comment by bensku** [comment]
1) For inventory clicks? They're bugged anyway, fix in TODO list.

2) This might be Skript bug or Spigot bug/features. Will see at some point.

3. I will not (intentionally) change existing expression in a way that would break old scripts. If I could, it would be so much easier to do pretty much anything.

**Comment by JKGamerxD** [comment]
No, I say the click expression for the `on click` event, because you can't detect the click type in `on click` event, but for Inventory clicks are good. Thanks anyway.

**Comment by TheBentoBox** [comment]
As this is old and Bensku said he was tagging it for the sake of inventory clicks (which are now implemented), I'm closing.
