### ISSUE TITLE
Colour Codes Not Working

### ISSUE THREAD

**Issue by CalebIsAwesome** [bensku/Skript#872]
My color codes stooped working and this is what I see in my console.
https://pastebin.com/bw1Qkpur

**Comment by jaylawl** [comment]
Please edit your post and put that console log in a hastebin or pastebin.

**Comment by CalebIsAwesome** [comment]
Ok sorry.

**Comment by bensku** [comment]
It seems Vault doesn't like PEX or your Vault version is unnofficial and thus not compatible with Skript.
