### ISSUE TITLE
Suggestion: "entity's speed"

### ISSUE THREAD

**Issue by jaylawl** [bensku/Skript#875]
The velocity expression is already extremely valuable, kudos for that.

A further valuable addition would be a "speed expression", which would basically just return the highest value of "velocity", because that value always is the speed an entity is travelling at (measured in blocks per second).

Otherwise, as of currently, one has to do this to get that value:
```set {_speed} to max(x of entity's velocity, y of entity's velocity, z of entity's velocity)```
(This is kinda missing the number conversion to make all numbers positive, can't make that out off the top of my head now, you get the idea though)

nevermind here it is:
`set {_speed} to max(abs(x of loop-entity's velocity), abs(y of loop-entity's velocity), abs(z of loop-entity's velocity))`

**Comment by TheBentoBox** [comment]
Your math is very incorrect. An entity's speed would be the magnitude (length) of its velocity vector, not the value of its velocity's highest component. If I was going 3 m/s in both X and Z, I'm traveling faster than 3 m/s. That being the case, we already have a [vector length expression](http://bensku.github.io/Skript/expressions.html#ExprVectorLength), which you can use with `vector length of player's velocity` or `player's velocity's length`. 

If there's something about your issue this solution doesn't address please feel free to say so but if not this issue should be closed.

**Comment by jaylawl** [comment]
@TheBentoBox You learn something new every day, didn't take that into account at all and unfortunately i don't know enough about vectors in general yet, so i didn't know that the mentioned expression would do it.

Thanks so much! :)

**Comment by TheBentoBox** [comment]
Glad to help!
