### ISSUE TITLE
Sprint event

### ISSUE THREAD

**Issue by Tai1er** [bensku/Skript#88]
Hi, I have tested different version of skript (Skript 2.2, Skript-2.2-Fixes-V9b, Skript-2.2-Fixes-V9b-1.5nfell and your version) and the "on sprint toggle" and "is sprinting" doesn't work. :C 
The event work only when the player stop to sprint.
Is it possible to fix it? :D

**Comment by Pilvinen** [comment]
```
on every 10 seconds:
  loop players:
    if loop-player is sprinting:
      broadcast " DEBUG: It's working just fine on my server. Are you using broken addons?"
```

**Comment by bensku** [comment]
It probably should work, though I have never seen it working. Looping players works anyway.

I'll try to look at this, but it'll take a while. I have another plugin to update for 1.9.

**Comment by TheBentoBox** [comment]
Works fine now.
