### ISSUE TITLE
Big Issue: Loading/Reloading time of all scripts doubled

### ISSUE THREAD

**Issue by bloggy** [bensku/Skript#880]
With the old 1.11.2 version of skript I had this loading time:
Skript v2.2-dev25
**Loaded 58 scripts with a total of 129 triggers and 150 commands in 2 minutes and 19.12 seconds**

With the latest 1.12 version of skript I have this loading time:
Skript v2.2-dev31c
**Loaded 58 scripts with a total of 129 triggers and 150 commands in 6 minutes and 18.67 seconds**

What happened? Why is the parsing of scripts soooo slow now? It is freezing my server when reloading all skripts while server is running and it takes forever to restart the server :-(

I really hope you can fix or improve this.

**Comment by TheBentoBox** [comment]
Duplicates #636. Report any more findings, info, and slowly loading samples over there.
