### ISSUE TITLE
Error in function causes skripts to be un-reloadable

### ISSUE THREAD

**Issue by Pugabyte** [bensku/Skript#884]
![](https://i.imgur.com/B00nXFf.png)

```
function mute(p: player, t: text):
	set {_uuid} to "%uuid of {_p}%"
	set {mutemenu::%{_uuid}%::%{_t}%} to true

	if "%{_t}%" is "minigame":
		if player has permission "minigames.seebroadcast":
			execute console command "/pex user %{_p}% add -minigames.seebroadcast"
		else:
			execute console command "/pex user %{_p}% remove -minigames.seebroadcast"

	muteMenu_Item({_p}, "%{_t}%", {mutemenu::slots::%{_t}%}, {mutemenu::items::%{_t}%})
```

I forgot to change `if player has permission` to `if {_p} has permission`, and it broke reloading of all scripts. I now have to restart to make it work again

![](https://i.imgur.com/J7rZV6K.png)

![](https://i.imgur.com/fp8F5QB.png)

**Comment by bensku** [comment]
Looks like the function will not get registered at all when it contains errors, while signature is still parsed and loaded. Interesting.
