### ISSUE TITLE
economy plugins cause nullpointer error

### ISSUE THREAD

**Issue by aeonlamb** [bensku/Skript#885]
I'm trying to use craftconomy on my server, but despite not using any economy-related stuff in any of my scripts, they all cause NPEs upon trying to load while craftconomy is installed. I don't really get why, but it's really annoying. 

[Stack trace](https://ghostbin.com/paste/5hj7s)

Using a lot of add-ons but I've tested it in a clean environment with just skript installed and this still happens.

**Comment by bensku** [comment]
Might be Vault issue, as top of the stack trace points to Vault. Not sure, though.

**Comment by TheBentoBox** [comment]
Do you have an economy plugin installed??

**Comment by TheBentoBox** [comment]
No response, closing for now. If you can verify that you have an economy plugin installed when this error still occurs on the latest version with an economy plugin installed, feel free to reply and I can reopen.

**Comment by supertassu** [comment]
@TheBentoBox By the error, it sounds like the economy plugin doesn't provide valid singular name for the economy (`net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.currencyNameSingular`) and the economy is CraftConomy3 (looking at the error), so this isn't a Skript issue. Don't quote me on that still.

**Comment by TheBentoBox** [comment]
Ah yeah good catch, I was thinking roughly the same (that it's an economy plugin issue and not Skript).
