### ISSUE TITLE
add a on toggle event

### ISSUE THREAD

**Issue by aycgit** [bensku/Skript#888]
oops, on toggle doesnt even exist and i was reading the wrong thing, can you add something like a on toggle?

(edited)

**Comment by Blueyescat** [comment]
Do not use skunity for Skript documentation firstly: https://bensku.github.io/Skript/effects.html#EffToggle

What is **`toggle the state of lever`**:slightly_frowning_face: Just check what you are doing...
**`lever`** is not a block, it is an item and how can you toggle a non-exist lever block? There is an example usage in the link above ^^

**Comment by aycgit** [comment]
i was looking at that thing and i should have suffixed on in my issue but sadly it is  not that easy

**Comment by bensku** [comment]
Add what exactly? What are you toggling?

**Comment by Syst3ms** [comment]
I think he talks about stuff like a lever, a door or stuff like that, but all of that is covered by the rightclick event.

**Comment by TheBentoBox** [comment]
No response and I agree that you can just use right click for this.
