### ISSUE TITLE
set player's display name

### ISSUE THREAD

**Issue by sriskels** [bensku/Skript#89]
set player's display name to "&c%player%" doesn't work.

**Comment by JKGamerxD** [comment]
For me works fine, what is your error?

**Comment by sriskels** [comment]
I know, I have EssentialsX for 1.9 and it's doesn't work. I waiting for update, maybe it's will repaired

Sorry for my english I Polish :x

**Comment by bensku** [comment]
So, not Skript bug. Closing.
