### ISSUE TITLE
Error that makes no sense

### ISSUE THREAD

**Issue by Pugabyte** [bensku/Skript#895]
http://paste.bear-nation.net/luyud.md

The code has nothing to do with a HangingBreakEvent. It's checking if a variable is true using a player's uuid. I included all the code that matches the supposedly broken syntax, cause I don't know which part exactly is throwing the error.

**Comment by bensku** [comment]
@TheLimeGlass Looks like your addon has a problem. Open a new issue if you think it is a Skript bug.

**Comment by Pugabyte** [comment]
alrighty thanks
