### ISSUE TITLE
get highest block at location.

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#897]
doc: https://jd.bukkit.org/org/bukkit/World.html#getHighestBlockAt(org.bukkit.Location)

example:
```
on death:
     set chest to highest solid block at player
     message "your chest set to %location of highest solid block%"
```
thanks to all.

**Comment by FUZIK** [comment]
in MundoSk -https://github.com/MundoSK/MundoSK/blob/ad6d023757650a6edf9bf600a242b86d9498d54c/src/com/pie/tlatoani/Miscellaneous/ExprHighestSolidBlock.java

**Comment by Nicofisi** [comment]
Added, will PR Soon™

**Comment by Comthefox2486** [comment]
PLEASE add Lowest solid block as well

**Comment by TheLimeGlass** [comment]
> PLEASE add Lowest solid block as well

Make a new issue, this is complete
