### ISSUE TITLE
Size of variable

### ISSUE THREAD

**Issue by Demonkid1112** [bensku/Skript#898]
Short description: Basically whenever I attempt to get the size of a list an error is thrown up. I did attempt with "size of all players" and this seemed to work fine but even simple code such as this 
```
command /temp:
    trigger:
        set {temp::*} to 1,2,3,4,5,6 and 7
        message "%size of {temp::*}%"
        delete {temp::*}
```
throws up an error. Here is the console log, now I'm not sure if it is Skripts issue, or if it stems from one of the many plugins I currently have installed. 
but [here is the error log](https://pastebin.com/7cJ83SBy)
and here is a list of addons

> MundoSK, SharpSK, skDragon-0.14.0, Skellett, SkMorkaz, SkQuery-Lime, skRayFall v1.9.10, skUtilities v0.9.0, TuSKe, Umbaska-3.3

**Comment by TheBentoBox** [comment]
Server version? Skript version? Error being produced? Sample code? Needs more info.

**Comment by Demonkid1112** [comment]
Sorry updated now, hit enter on accident and pre-posted

**Comment by TheBentoBox** [comment]
Duplicates #876. Read Tlatoani's comment there for a way to potentially fix this.
