### ISSUE TITLE
"blocks above/under/..." changes between dev29 and dev31c?

### ISSUE THREAD

**Issue by Vrontis** [bensku/Skript#903]
Well, after updating Skript from 2.2-dev29 to dev31c I get an error with this:
`on rightclick on lapis block holding stick:
    [...]
    if block 2 blocks above clicked block is light gray shulker box:`
`[13:22:42] [Server thread/ERROR]: [Skript] the clicked block is not a world (Ritual.sk, line 4: if block 2 blocks above clicked block is light gray shulker box:')`

**Comment by bensku** [comment]
Any addons?

**Comment by Pikachu920** [comment]
try meters instead of blocks

**Comment by Vrontis** [comment]
Uhm... Before and after the update the same versions of:
Umbaska, skDragon, SharpSK, SkQuery and SkStuff

And with meters it's working again.
But still the fact, that the earlier written code with blocks doesn't work anymore.

**Comment by Pikachu920** [comment]
This is a duplicate of #828 then

**Comment by TheBentoBox** [comment]
Duplicates #828.
