### ISSUE TITLE
JSON Chat Problem

### ISSUE THREAD

**Issue by tirtbey** [bensku/Skript#904]
When i write `<suggest command:/ark ekle <oyuncu>>test` it shows `>test` instead of `test`.
My server version: PaperSpigot 1.12
![resim](https://user-images.githubusercontent.com/32433256/31054798-1b20a382-a6c3-11e7-9a13-f14b9b6f6bfa.png)

Skript version: 2.2dev31c

**Comment by Syst3ms** [comment]
@bensku Looks like the json chat parser is a bit lazy (as in a lazy regex).

**Comment by bensku** [comment]
Umm yeah my tag parsing doesn't like extra \>s.

**Comment by Blueyescat** [comment]
What about escaping >s? Like ``\>`` :thinking:

**Comment by TheBentoBox** [comment]
You could probably use a regex match to check for matching amounts of angled brackets to find where the JSON tag actually ends instead of assuming it to be at the first closing angled bracket.

**Comment by bensku** [comment]
Escape characters or regular expressions are needed. I just need to count the angle brackets :)
