### ISSUE TITLE
Next error...

### ISSUE THREAD

**Issue by Auswahluhr60042** [bensku/Skript#906]
Hello,

now i'm on the version 1.12.2... and the commands of the skript aren't loading...

Link: https://pastebin.com/7xRJjzFF

Thank you.

**Comment by Snow-Pyon** [comment]
You must use the latest version (dev31c) to report an error.

**Comment by TheBentoBox** [comment]
Please always use the VERY latest version when reporting bugs. If you're not on the absolute newest release and your issue is reporting a bug, it is almost immediately invalidated as the issue causing it could have been fixed in a more recent release.
