### ISSUE TITLE
'on explosion prime' called at explosion not when priming

### ISSUE THREAD

**Issue by JeepSmash** [bensku/Skript#908]
I would expect the 'on explosion prime' event to be called when a TNT is lit or when a creeper first starts flashing.  It is called when the entity is going to explode at the same time 'on explode' is called.  I am trying to make an TNT ignition prevention routine to prevent more than a certain amount of TNT from being lit in a given area.  But i cannot 'cancel event' for TNT from being primed since the event is called after they are primed and are about to explode.  No i have checked will trigger for TNT block turning into lit TNT entity:
on spawn
on burn
on ignition
on block damage
on physics
on fade

**Comment by Pikachu920** [comment]
Explosion prime does cover both TNT and creepers, and it is cancellable

**Comment by JeepSmash** [comment]
Yes but the problem is that it only cancels the explosion not the actual priming of the explosive.  So cancelling it does not return the TNT to a TNT block since it left block form 4 seconds prior to this event being called.

**Comment by TheBentoBox** [comment]
This is not a Skript issue, Spigot's `ExplosionPrimeEvent` is called right before the TNT explodes. Even if Spigot were to make it be called right when the TNT ignites, cancelling it wouldn't turn the entity back into a block as that would not be logical -- it would probably just remove the entity. You can read more discussion about the hurdles of detecting TNT ignition in [this Spigot feature request](https://hub.spigotmc.org/jira/browse/SPIGOT-519). 

But yeah, this isn't a bug and it's a Spigot-side issue.
