### ISSUE TITLE
Log handlers not stopping properly?

### ISSUE THREAD

**Issue by Lordcre** [bensku/Skript#914]
As of now I have not noticed any issues but it's heavily spamming my console. This occurs every reload (/sk reload <script>)

**Addons:**
- SkMorkaz - v0.21
- Skript - v2.2-dev25
- skUtilities - v0.9.0
- skript-mirror - v0.7.1
- SkQuery - v3.21.4
- WildSkript - v1.8
- ExtrasSK - v1.1
- skRayFall - v1.9.5
- RandomSK - 1.6
- Skellett - v1.9.6a
- TuSKe - v1.8.1
- SharpSK - v1.6.2
- 
`08.10 00:48:06 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1059)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

08.10 00:48:07 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1171)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

08.10 00:48:07 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:261)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

08.10 00:48:08 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1098)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

08.10 00:48:10 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.registrations.Classes.parseSimple(Classes.java:428)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]

08.10 00:48:11 [Server] ERROR [Skript] 1 log handler was not stopped properly! (at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1098)) [if you're a server admin and you see this message please file a bug report at http://dev.bukkit.org/server-mods/skript/tickets/ if there is not already one]`

**Comment by Blueyescat** [comment]
What is your Skript and server version :( I think 2.1? As you are using dead addons like SkMorkaz, WildSkript, ExtrasSK and RandomSK...

**Comment by Lordcre** [comment]
@Blueyescat Server Version: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Skript Version: v2.2-dev25

**Comment by Blueyescat** [comment]
Hmm, there is a similar issue: https://github.com/bensku/Skript/issues/293
But bensku doesn't support old versions, and dev25 doesn't support 1.8 officially. I don't know anything about the problem but why 1.8? Use 1.12 :wink:

**Comment by TheBentoBox** [comment]
We can't provide support for old versions of Skript, and as you're running 1.8 you can't even update. You're on your own unless you're able to update to the latest version and find that this is still happening. I'd start by getting rid of some of those ancient addons.
