### ISSUE TITLE
Amount Bug

### ISSUE THREAD

**Issue by Xpgrin** [bensku/Skript#918]
Hello
I'm running on spigot 1.11.2-R0.1-SNAPSHOT and skript version 2.2-dev31c (latest)

Here this is my code:
```
on skript load:
	add 10 of stone to {i::*}
command /free:
	trigger:
		open "CHEST" with 3 rows named "FREE" to player
		loop {i::*}:
			add 64 of loop-value to player's current inventory
```

And this coming out when I use this command:
https://hastebin.com/ikobuheqox.md

Someone told me to update alias but same error and get more item error from using 1.12 alias in 1.11

**Comment by TheBentoBox** [comment]
Not even sure if it's a Skript bug or something related to the inventory opened by the addon

**Comment by bensku** [comment]
Very interesting. Try if it happens when inventory is not opened by an addon.

**Comment by TheLimeGlass** [comment]
That's a strange bug. I don't know why that would be happening. Doesn't seem like a thing I could fix. Try waiting a tick before adding the items. Maybe it hasn't opened fully yet before setting the items.

**Comment by Nicofisi** [comment]
The stacktrace link is dead btw

**Comment by Snow-Pyon** [comment]
Closing since the link of the stack trace is dead and that there wasn't a lot of info about the issue. Reopen it if it is still happening.
