### ISSUE TITLE
On Command doesn't work

### ISSUE THREAD

**Issue by Bayside308** [bensku/Skript#92]
I'm experiencing an issue with "on command" not working.

Spigot ver: git-Spigot-4af49dc-c5e9a16 (MC: 1.9.4)
Skript ver: 2.2-dev15
Plugins: http://pastebin.com/dq0vviQ3
On Command Script: http://pastebin.com/esaM803z

EDIT: No issues logged to console

**Comment by TheBentoBox** [comment]
You may first want to try to do `set {_this} to "%command%"` and see if that helps; I often find I can fix some errors by parsing them as strings. If not, and I hate to ask the obvious question, but you're sure you're not opped when you're testing right?

**Comment by Bayside308** [comment]
I've tried using the %command%, I even tried doing:

`on command:
	set {_this} to "%command%"
	send "%command% -- %{_this}%"`

This outputs nothing when a command is executed, and I wasn't opped while testing :)

**Comment by Jduffygames** [comment]
http://pastebin.com/a1T8A2gt

**Comment by bensku** [comment]
This is caused by annoying parsed bug with variables.

**Comment by TheBentoBox** [comment]
@Bayside308 Are you still experiencing this? I use `on command` a fair amount on my 1.11.0 server with dev22g and have no issues.

**Comment by TheBentoBox** [comment]
Maybe. Regardless, seems ok now.
