### ISSUE TITLE
Current repo fails build on Fedora 26

### ISSUE THREAD

**Issue by MrAureliusR** [bensku/Skript#922]
gradle clean build fails with

FAILURE: Build failed with an exception.

* What went wrong:
Could not copy MANIFEST.MF to '/home/amr/workspace/Skript/build/tmp/jar/MANIFEST.MF'.
> Specify the section name using the "name" attribute of the <section> element rather than using a "Name" manifest attribute

Not sure if this is a bug in Skript or a bug with my setup. It seems that on Fedora they call gradlew just gradle. I thought it was a permissions issue but chmod -R 777 ./* doesn't fix it. Running as sudo also fails in the same manner.

**Comment by bensku** [comment]
Try using Gradle wrapper (gradlew) so that you have correct version of it. Too new or old Gradle version might break things.

**Comment by Snow-Pyon** [comment]
No response, closing.
