### ISSUE TITLE
Error when looping blocks in front of player

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#927]
Error: https://pastebin.com/XiWp8S7P

Script: https://pastebin.com/yC5EpmkX

This is on Skript 31c build and spigot 1.12.2.

**Comment by supertassu** [comment]
Would recommend reading what the error says.

**Comment by TheBentoBox** [comment]
Not sure what causes this or if it's more of a Spigot-side issue

**Comment by whoshenry** [comment]
I have EpicWorldGenerator on the world where this is occurring, would that be something to do with it?

**Comment by whoshenry** [comment]
Maybe this helps? Sometimes when this script is fired the server crashes and EpicWorldGenerator creates a crash log - https://pastebin.com/acbkMFff

**Comment by supertassu** [comment]
>Maybe this helps? Sometimes when this script is fired the server crashes and EpicWorldGenerator creates a crash log - https://pastebin.com/acbkMFff

That is really weird crash log. It seems like EWG crash but Skript (and Skelett? `com.gmail.thelimeglass.Utils.Packets.PacketListener`) has to do something with it.

Again, really weird log. I would recommed submitting it to EWG's bug tracker [here](http://support.dynamic-bytes.com/support/home).

**Comment by whoshenry** [comment]
I have done, thanks for taking a look.

**Comment by Tuke-Nuke** [comment]
The issue is that something is trying to spawn entities/remove blocks asynchronously. Probably that on packet event is called async, so it isn't a Skript issue at first sight.

**Comment by Pikachu920** [comment]
Yeah, the issue is what Tuke said.

**Comment by whoshenry** [comment]
Is it possible for me to change so the script runs synchronously?

**Comment by Pikachu920** [comment]
@TheBentoBox this should be closed because it is not a skript issue

@whoshenry yes, mundosk has a synchronous scope

**Comment by TheBentoBox** [comment]
Thanks for the tag @Pikachu920 , missed this one
