### ISSUE TITLE
Change Skript's interaction with Craftbukkit

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#933]
When Skript is loaded on craftbukkit it should print to console that Skript is not compatible with Craftbukkit then disable itself. Alternately, it should print to console that it isn't compatible with Craftbukkit and then every /sk command should print `[Skript] Skript is not compatible with Craftbukkit, please use Spigot`.

**Comment by Legoman99573** [comment]
NGL, but wouldn't it be logical to disable the plugin if its CraftBukkit, less to avoid the spam?

**Comment by Pikachu920** [comment]
Well the idea behind having /sk show it was stopping people from opening issues here saying Skript isn't starting without checking the logs. Most people will use /sk but they probably wont look at console or will glaze over the single line warning.

**Comment by Legoman99573** [comment]
I saw that, and made a pull request that will disable the plugin if they are using Craftbukkit

**Comment by Snow-Pyon** [comment]
Fixed in dev32c.
