### ISSUE TITLE
killing armor stand

### ISSUE THREAD

**Issue by NebuSensei** [bensku/Skript#934]
when I write "spawn armor stand", creating armor stand. But when I write "kill last spawned entity". It's not working.

**Comment by TheBentoBox** [comment]
What's your server & Skript version?

**Comment by NebuSensei** [comment]
1.12 and 31c

**Comment by Blueyescat** [comment]
Armor stands aren't a living entity, how can you kill them? ``delete last spawned entity``

**Comment by NebuSensei** [comment]
Oh, in old version `kill last spawned entity` is working thx blueyescat
