### ISSUE TITLE
pikachu's contains function not working properly

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#936]
```
function contains(list: objects, check: object) :: boolean:
	loop {_list::*}:
		if loop-value is {_check}:
			return true
	return false
```
this function is not working properly on dev31c
normally you could just do `contains({aListVar::*}, "hi")` but now you have to do `contains("%{aListVar}%", "hi")`

**Comment by RezzedUp** [comment]
That function works perfectly fine on Skript 2.2 dev31c.

```
command /contains:
    trigger:
        set {_list::*} to "something", 1, "stuff", 8, 3, "a thing", true, and "okay"
        
        if contains({_list::*}, "a thing") is true:
            send "List contains:&a a thing"
            
        if contains({_list::*}, true) is true:
            send "List contains:&a true"
```
![](https://i.imgur.com/FQT1yO3.png)

I'm not sure what you mean by 'now you have to do `contains("%{aListVar}%", "hi")`', because that's not how the function works at all.

**Comment by HYPExMon5ter** [comment]
Yeah can't replicate it anymore, I'll re-open if it happens again, with proof.
