### ISSUE TITLE
dropped items vanish

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#940]
So this code
```
command /coins <int> <player>:
    permission: *
    trigger:
        if arg-2 has space for arg-1 of {@mcoin}:
            give arg-1 of {@mcoin} to arg-2
        else:
            set {_loc} to location at arg-2
            drop arg-1 of dirt at {_loc}
            drop arg-1 of {@mcoin} at arg-2's head
```

spawns the items, but most of the time only for a few ticks and then they vanish. can anyone confirm this behaviour?

Its like i run the command, the item pops up where it should but then, in like 70% of the cases, it disappears again. sometimes it works as intended but thats not too helpful.

edit:
you can exchange {@mcoin} with any option you defined or just any random item, had this issue no matter which ones i tried

**Comment by melinstagibson** [comment]
this was in dev31c and paperspigot 1.12.2

**Comment by TheBentoBox** [comment]
Can anyone else verify they're having this issue on the newest versions? I've never experienced this on my live server but I haven't upgraded past dev25 yet so it may be a new issue.

Obvious question but just to be safe, you're sure it's not just instantly being picked up or merging with another nearby item, right?

**Comment by melinstagibson** [comment]
yes, i made sure of that. ill try it with the latest version again and remove all other plugins but i dont know why this would happen at all. still strikes me as something only i experience thats why i asked for confirmation

**Comment by melinstagibson** [comment]
Closing this as it only happens on one of my servers for unknown reasons while the others work
