### ISSUE TITLE
Particle issue

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#941]
I know this error is mostly due to skRayfall but I am having trouble trying to find the cause so I am putting it here to see if anyone else knows the cause.

https://pastebin.com/1RpWhbt5

**Comment by TheBentoBox** [comment]
It's probably just a version issue, I don't think skRayFall works entirely in 1.12. However, this isn't the place to post if you're just looking for help; use the skUnity forums.

**Comment by whoshenry** [comment]
Apologies. I thought pretty much the same. Thanks.

**Comment by TheBentoBox** [comment]
No worries, hope you're able to figure it out
