### ISSUE TITLE
Errors regarding guis

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#944]
https://hastebin.com/unopugohur.sql
When starting my server after upgrading from dev31c to dev32 tons of errors regarding gui's happened.
I had no errors on dev31c

**Comment by TheBentoBox** [comment]
Looks like TuSKe isn't loading correctly on the new version; ensure you have the latest version and contact Tuke if you keep having issues. Addon errors don't belong here, though.
