### ISSUE TITLE
Else bug

### ISSUE THREAD

**Issue by HYPExMon5ter** [bensku/Skript#945]
Skript version: dev31c
Spigot version: 1.12.2
```
command /test [<text>];
    trigger:
        if arg 1 is set:
            message "test"
        else:
            message "test 2"
        else:
            message "test 3"
```
this code should throw errors (because of a double else) but it completely unloads the script not giving any info, accidentally did this and it took me a while to figure out why the script wasn't loaded anymore because it gave no feedback.

**Comment by TheBentoBox** [comment]
Will label as a bug but if anyone else can verify the same behavior it'd be helpful. It should definitely throw an error for a double else.

**Comment by Blueyescat** [comment]
Gives **`'else' has to be placed just after an 'if' or 'else if' section`** error for the latest ``else`` on Skript 2.2-dev29 and PaperSpigot 1.12.

**Comment by TheBentoBox** [comment]
Thanks for the verification @Blueyescat , will close this soon unless someone (@HYPExMon5ter) can give steps to reproduce that aren't related to an add-on (which is what I imagine could cause this, if anything).

**Comment by HYPExMon5ter** [comment]
I haven’t tried without addons but I said it was a bug in dev31c, not dev29. I’ll test it when I get a chance

**Comment by iDarkyy** [comment]
On dev32b it gives an actual skript error that an else has to be placed after an if.
https://i.imgur.com/OiBVwjR.png

**Comment by xXAndrew28Xx** [comment]
Can not reproduce on dev32d, the error shows up as expected. Btw, in your example you put a `;` instead of a `:`.
