### ISSUE TITLE
Enabling error (Particle)

### ISSUE THREAD

**Issue by SwenCake** [bensku/Skript#948]
Yop,

When Skript start, this error appears 
`Error occurred while enabling Skript v2.2-dev32 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/Particle`

 and followed by 
`https://pastebin.com/raw/74daxFci`

**Comment by supertassu** [comment]
Skript only supports 1.9+. dev25 is last version that supports 1.8, but we can't help you anything more. You should upgrade to more up-to-date versions as 1.8 is 3+ years old.

**Comment by SwenCake** [comment]
Oh ok ;) but last year i've tried dev27 in 1.8 server and it's worked...

**Comment by bensku** [comment]
Dev27 is otherwise so broken that I never recommend using it.
