### ISSUE TITLE
Probably a skript parser error

### ISSUE THREAD

**Issue by nutella25** [bensku/Skript#951]
Skript version: dev32
Server version: Paper version git-Paper-1169 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

I don't know how to read the error but when I reload this simple script with command `/sk reload azn-halloween.sk` my server tps suddenly went to 0.0 and it crashed. It will crash only when I tried to reload this effect.

Here is the logs after the crash: https://pastebin.com/Ys6TDRfV

And I'm trying to reload this simple script with an skRayFall effect in it
```vbs
command /eh16t:
	permission: skript.admin
	trigger:
		show 30 drip lava particle at player's location with data of dye offset by 0.2, 2, 0.2 at speed 0
```

I've contacted the skRayFall's developer, he said that something might be wrong with skript parser.

**Comment by nutella25** [comment]
Can someone check about this issue?

Thanks.

**Comment by TheBentoBox** [comment]
Could definitely be caused by slow parsing, but I'd also recommend not using add-ons when you don't have to since this _should_ be possible with the vanilla Skript `play effect` syntax -- in theory. It's buggy at times. See if this works:

```
show 30 (lava drip with offset 0.2, 2, 0.2 and speed 0) at player
```

**Comment by TheBentoBox** [comment]
No response, closing.
