### ISSUE TITLE
[Addon] Url parser error ?

### ISSUE THREAD

**Issue by SwenCake** [bensku/Skript#953]
Hello,

I dev an addon to replace downloader of Wildskript but Skript crash :/
Without Skript code, server goes normaly.

**Error :** https://pastebin.com/0TmgcALu
**Skript code :** https://pastebin.com/rcDg8M0J
**Addon downloader code :** https://pastebin.com/vBqGS5uV

**Skript version** : latest (dev32)

**Comment by TheBentoBox** [comment]
Looks like an issue with the downloader code to me. You're not declaring a URL class. The expression should be `"download %text% to %file%"`, not `"download %url% to %file%"`.
