### ISSUE TITLE
Cannot compare name of player's offhand tool

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#954]
This Debug: Stage 2 Pass never fires in this code:
```
	if player has music disc in offhand:
		broadcast "&cDebug: &fStage 1 Pass"
		if name of player's offhand tool is "&4&lF&cire &4&lR&cesistance &4&lR&cing &e⥁":
			broadcast "&cDebug: &fStage 2 Pass"
```
Using Dev 32.

**Comment by Pikachu920** [comment]
have you tried in other versions and had it work? at this point the most likely option is the names don't match

**Comment by whoshenry** [comment]
I have tried 2 versions before and it never seemed to work, I copied and pasted the name from the item file too so they do match.

**Comment by HYPExMon5ter** [comment]
Can't replicate, what addons do you have?

**Comment by TheBentoBox** [comment]
No response and I also can't reproduce this.
