### ISSUE TITLE
add entity ride event

### ISSUE THREAD

**Issue by FUZIK** [bensku/Skript#956]
https://hub.spigotmc.org/javadocs/spigot/org/spigotmc/event/entity/EntityMountEvent.html
https://hub.spigotmc.org/javadocs/spigot/org/spigotmc/event/entity/EntityDismountEvent.html

thanks.

**Comment by TheBentoBox** [comment]
@FUZIK [This](http://bensku.github.io/Skript/events.html#entity_mount) and [this](http://bensku.github.io/Skript/events.html#entity_dismount)? They were implemented over a year and a half ago, actually.

If you have issues using those let me know though. I'll close if they work.

**Comment by FUZIK** [comment]
i am sorry. i am check this https://docs.skunity.com/syntax/search/Mount and...

**Comment by TheBentoBox** [comment]
No worries, it's an easy mistake, and thanks for closing the issue yourself as well! 

Bensku's docs are always the best place to check for the most up-to-date vanilla Skript syntax since it's generated automatically for each release. They're very useful.

**Comment by FUZIK** [comment]
but... how i get "dismounted" and "passager"?

**Comment by TheBentoBox** [comment]
Are you able to do `event-entity` and `event-entity's passenger`/`event-entity's vehicle`?
