### ISSUE TITLE
Cannot reload skript!

### ISSUE THREAD

**Issue by KrifixYT** [bensku/Skript#957]
Hi! I have error with reload skript plugin!

IMAGE: https://imgur.com/a/COSMp
Server version: 1.8.8
Script version: Latest

**Comment by HYPExMon5ter** [comment]
Well I mean, bensku’s fork of Skript doesn’t work on 1.8 so.. either downgrade to dev25 or use someone else’s fork :P

**Comment by KrifixYT** [comment]
can u give me link?

**Comment by Pikachu920** [comment]
In addition to using 1.8, you haven't supplied the actual error so this issue is essentially useless

**Comment by KrifixYT** [comment]
so, i will no have skript on this version?

**Comment by Pikachu920** [comment]
dev25 works on 1.8 aswell as many other older skript versions. If you use 1.8 with any version of skript, you will get no support here.

**Comment by TheBentoBox** [comment]
You can try downgrading to [this version](https://github.com/bensku/Skript/releases/tag/dev25) but if you get any errors you're on your own since as has been said this Skript fork doesn't support 1.8 or below.

**Comment by KrifixYT** [comment]
Thanks!
