### ISSUE TITLE
Visual Effect parsing is broken

### ISSUE THREAD

**Issue by bi0qaw** [bensku/Skript#960]
```
play 100 (dust of oak wood with offset of 1, 1, 1 and speed 1) at player
```
Gives a "Can't understand condition/effect..." error on script load.

Skript version: dev32
Spigot version: 1.12.2

**Comment by Blueyescat** [comment]
```vb
play 100 dust of oak wood at {_p} with offset of 1, 1, 1 and speed 1
```

**Comment by bi0qaw** [comment]
This doesn't work because offset and speed are part of the visual effect object. And it throws the same error as before.

**Comment by Blueyescat** [comment]
Hmm it looks like aliases bug... Try it with other items probably it will work. Also you should able to use `oak log` instead of `oak wood`. I'm going to fix [tim740's Aliases](https://github.com/tim740/skAliases) with a pull request.

**Comment by bi0qaw** [comment]
It seems that there is a problem with the particle names. It works for some particles (for example "mobspawner flames", "ender signal") but doesn't for others ("dust", "coloured dust").

**Comment by TheBentoBox** [comment]
Definitely should work with that syntax (going off of the syntax from [when they were added](https://github.com/bensku/Skript/releases/tag/dev12c)).

**Comment by Snow-Pyon** [comment]
Tested it and it seems like it was just an alias issue (oak wood not referencing to any item) so I'm closing this.
