### ISSUE TITLE
update

### ISSUE THREAD

**Issue by comonier** [bensku/Skript#965]
after i update last build of spigot on:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits (95dd0970330)

console error version msg

`09.11 21:37:44 [Server] ERROR Error occurred while enabling Skript v2.2-dev32 (Is it up to date?)
09.11 21:37:44 [Server] INFO java.lang.NoSuchFieldError: SHEEP_EAT
09.11 21:37:44 [Server] INFO at ch.njol.skript.util.VisualEffect$Type.<clinit>(VisualEffect.java:80) ~[?:?]
09.11 21:37:44 [Server] INFO at ch.njol.skript.util.VisualEffect.<clinit>(VisualEffect.java:255) ~[?:?]
09.11 21:37:44 [Server] INFO at ch.njol.skript.classes.data.SkriptClasses.<clinit>(SkriptClasses.java:889) ~[?:?]
09.11 21:37:44 [Server] INFO at ch.njol.skript.Skript.onEnable(Skript.java:282) ~[?:?]
09.11 21:37:44 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot.jar:git-Spigot-95dd097-326c2e6]
09.11 21:37:44 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

**Comment by TheBentoBox** [comment]
Duplicates #964. Please don't report an issue without seeing if it's already been reported, it's literally the newest issue report so you clearly didn't bother checking.
