### ISSUE TITLE
Error with determining size of a list variable

### ISSUE THREAD

**Issue by whoshenry** [bensku/Skript#967]
This use to work in the earlier versions of Skript, I can't remember which version it stopped working with but it definitely does not work in Dev32.

This is the code:
```
		loop all living entities in radius 20 around player:
			loop-entity's name is "&4Alpha Werewolf" or "&4Werewolf"
			add loop-entity to {_werewolves::*}
			if {pvp.active} is false:
				if loop-entity is a player:
#					broadcast "&cDebug: &fStage 1 Pass"
					remove loop-entity from {_werewolves::*}
		broadcast "&cDebug: &fAlpha Werewolf List - %{_werewolves::*}%"
		if size of {_werewolves::*} is more than or equal to 1:
			set {_blessedwolfsjager-loop-entities} to size of {_werewolves::*}
```

I get this error in the console when the code fires - https://pastebin.com/ZZSuJReV

Then the code doesn't progress it seems. The issue is with the 'size' line of code I guess because when I reload the skript I get this 
```
[Skript] Reloading test.sk...
[08:30:20 WARN]: The 'size' syntax for border diameter will be removed in a future version. Please use 'diameter' instead. (test.sk, line 77: if size of {_werewolves::*} is more than or equal to 1:')
[08:30:20 WARN]: The 'size' syntax for border diameter will be removed in a future version. Please use 'diameter' instead. (test.sk, line 78: set {_blessedwolfsjager-loop-entities} to size of {_werewolves::*}')
[08:30:20 INFO]: [Skript] Successfully reloaded test.sk.
```

**Comment by Blueyescat** [comment]
Install the latest dev version of MundoSK and disable ``border_disable_size_syntax`` option in the config (needs restart to apply).

https://goo.gl/4GmjB5

**Comment by TheBentoBox** [comment]
@Blueyescat has the correct solution, and this also duplicates #876 , so I'm closing this.

**Comment by whoshenry** [comment]
I also fixed this by changing `size` to `amount`.
