### ISSUE TITLE
Problem with Veriables.getVeriable()

### ISSUE THREAD

**Issue by 6594k** [bensku/Skript#976]
I have problem with this method. I have veriable in skript {Stoniarka.%event-block%} and its true or false. And how to  get this boolean in plugin? Can i get example? Please sorry for my english :(

**Comment by TheBentoBox** [comment]
Looks like you're just spelling it wrong, the word is `Variables`, not `Veriables`. Does that fix your problem?

**Comment by 6594k** [comment]
Oh thanks i'm forgot :(, but that no fix my problem ;/

**Comment by Snow-Pyon** [comment]
I've explained how to use it in #781

**Comment by 6594k** [comment]
Ok thank you, but how to check if variable is true or false?

**Comment by Pikachu920** [comment]
That should be obvious if you've read what #781 says. Either way, at this point its obvious this isn't an issue with Skript. Should probably be closed.
