### ISSUE TITLE
entity click error

### ISSUE THREAD

**Issue by Poseidon23** [bensku/Skript#979]
I can not speak English well..

I am using 1.10.2 server with ProtocolSuport.
If you look at test.sk,

On right click on entity:
 if entity's name is "test":
  send "&f테스트" to player

1.8 to 1.10 will work normally
However, it does not work at all in the 1.5.2 environment.
I do not know the other version, but the biggest problem is that it is 1.5.2.
Check it out and fix it.
please!

**Comment by TheBentoBox** [comment]
We don't support Minecraft versions below 1.9.
