### ISSUE TITLE
Parser has a boolean for turning off "List is missing and" warnings, but no matching config option

### ISSUE THREAD

**Issue by Pikachu920** [bensku/Skript#981]
https://github.com/bensku/Skript/blob/a189b5a95a15462a9a44c093f25f3f00a1493220/src/main/java/ch/njol/skript/lang/SkriptParser.java#L587

This is one of the most useless and annoying errors, there should be a config option for it. Hell, maybe it should be outright removed.

**Comment by TheBentoBox** [comment]
God yes please. I don't think it should necessarily be outright removed for the sake of new scripters but a config option for this would be A+.

**Comment by bensku** [comment]
Parser option is used for suppressing missing and/or warnings in certain weird parsing contexes, for example function signature (arguments are parsed as a list...). I'm not sure what toggling this variable globally would do. I guess only one way to find out; need to test it.

**Comment by Pikachu920** [comment]
If you think it may cause issues, it might be best to just add another option for it.
