### ISSUE TITLE
Unset variables handling

### ISSUE THREAD

**Issue by melinstagibson** [bensku/Skript#984]
So i keep running into the same issue and while this might not be a bug (actually i think it is handled correctly) i still think this should work... differently.

whenever i try to do check a variable that hasn't been set yet with something like:
```
on break:
    if {reinforced::%location of event-block%} is less than 5:
        add 1 to {reinforced::%location of event-block%}
    else:
        #do sthg else
```
so what happens if the variable isn't set yet is that it won't accept the less than 5 condition since the variable itself is <none>. I always have to check that the variable is set first, if its not set it to 1 or 0 and then continue with whatever.

Would it be an issue to make unset variables compared to a number default to 0? I_m still on dev31d for compatibility reasons so this might be "fixed" yet but i didnt find a bug report about this yet.

And if its intended, would you consider changing it? what are the possible downsides?

**Comment by Pikachu920** [comment]
This is intended. Things like this can't be changed at this point because of backwards compatibility, for something like this to exist it would have had to have been from the beginning. Using skquery you can do the following:
```
on break:
    if {reinforced::%location of event-block%} ? 0 is less than 5:
        add 1 to {reinforced::%location of event-block%}
    else:
        #do sthg else
```
