### ISSUE TITLE
Weird Error

### ISSUE THREAD

**Issue by Techno3600** [bensku/Skript#985]
Hello,

When reloading a skript, it says this:
25.11 01:23:04 [Server] ERROR Unexpected entry 'if argument 1 is "bomb"'. Check whether it's spelled correctly or remove it. (game.sk, line 53: if argument 1 is "bomb":')
25.11 01:23:04 [Server] ERROR Unexpected entry 'if argument 1 is not set'. Check whether it's spelled correctly or remove it. (game.sk, line 86: if argument 1 is not set:')

Why's this not spelled correctly?

Thanks
Techno

**Comment by Pikachu920** [comment]
This is a issue with a script. This issue tracker os for issues with Skript as in the plug-in. there's various other places to go for help with your own scripts.

**Comment by bensku** [comment]
That is probably the case. But might be also addon or (unlikely) Skript bug. If that is the case, I'll reopen this.
